 CREATE OR REPLACE FUNCTION public.personupdatebasicinfo(v_personid uuid, persondetails json, v_intakeserviceid uuid, v_securityuserid character varying)                                                                                                                                 
  RETURNS text                                                                                                                                                                                                                                                                            
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                        
 AS $function$   

 /*
-- 01-06-2026 - Veera Nadimpalli -- CIDM-10982 - To save Sen Criteria Identification

 */                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                        
         DECLARE                                                                                                                                                                                                                                                                        
         v_person json;                                                                                                                                                                                                                                                                 
         v_date timestamp without time zone;                                                                                                                                                                                                                                            
         dadetails json;                                                                                                                                                                                                                                                                
         modifiedlog json;                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                        
         v_isnamechanged boolean;                                                                                                                                                                                                                                                       
         BEGIN                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                        
                 v_person := persondetails;                                                                                                                                                                                                                                             
                 v_date:= now() at time zone 'utc';                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                        
                 select case when (p.lastname != v_person->>'Lastname' OR p.firstname != v_person->>'Firstname' OR p.middlename != v_person->>'Middlename') then true else null end isnamechanged into v_isnamechanged from person p where p.personid = v_personid and p.activeflag = 1;
                                                                                                                                                                                                                                                                                        
                 select json_strip_nulls(json_build_object('lastname', a.lastname, 'firstname', a.firstname                                                                                                                                                                             
                          , 'dob', a.dob                                                                                                                                                                                                                                                
                          , 'maritalstatustypekey', a.maritalstatustypekey, 'occupation', a.occupation, 'height', a.height, 'weight', a.weight, 'tattoo', a.tattoo, 'phymark', a.phymark, 'userphoto', a.userphoto)) from (                                                             
                                         select case when p.lastname != v_person->>'Lastname' then (select json_build_object('oldvalue', p.lastname, 'newvalue', v_person->>'Lastname') x) else null end lastname                                                                       
                                         , case when p.firstname != v_person->>'Firstname' then (select json_build_object('oldvalue', p.firstname, 'newvalue', v_person->>'Firstname') x) else null end firstname                                                                       
                                         , case when p.dob != (v_person->>'Dob')::timestamp then (select json_build_object('oldvalue', p.dob, 'newvalue', (v_person->>'Dob')::timestamp) x) else null end dob                                                                           
                                         , case when p.dateofdeath != (v_person->>'Dod')::timestamp then (select json_build_object('oldvalue', p.dateofdeath, 'newvalue', (v_person->>'Dod')::timestamp) x) else null end dod                                                           
                                         , case when p.maritalstatustypekey != v_person->>'maritalstatus' then (select json_build_object('oldvalue', p.maritalstatustypekey, 'newvalue', v_person->>'maritalstatus') x) else null end maritalstatustypekey                              
                                         , case when p.occupation != v_person->>'occupation' then (select json_build_object('oldvalue', p.occupation, 'newvalue', v_person->>'occupation') x) else null end occupation                                                                  
                                                                                                                                                                                                                                                                                        
                                         , case when pht.attributevalue != v_person->>'height' then (select json_build_object('oldvalue', pht.attributevalue, 'newvalue', v_person->>'height') x) else null end height                                                                  
                                         , case when pwt.attributevalue != v_person->>'weight' then (select json_build_object('oldvalue', pwt.attributevalue, 'newvalue', v_person->>'weight') x) else null end weight                                                                  
                                         , case when ptt.attributevalue != v_person->>'tattoo' then (select json_build_object('oldvalue', ptt.attributevalue, 'newvalue', v_person->>'tattoo') x) else null end tattoo                                                                  
                                         , case when ppm.attributevalue != v_person->>'PhyMark' then (select json_build_object('oldvalue', ppm.attributevalue, 'newvalue', v_person->>'PhyMark') x) else null end phymark                                                               
                                                                                                                                                                                                                                                                                        
                                         , case when p.userphoto != v_person->>'userphoto' then (select json_build_object('oldvalue', p.userphoto, 'newvalue', v_person->>'userphoto') x) else null end userphoto                                                                       
                                         from person p                                                                                                                                                                                                                                  
                                         left join personphysicalattribute pht on pht.personid = p.personid and pht.physicalattributetypekey ='Ht' and pht.activeflag = 1                                                                                                               
                                         left join personphysicalattribute pwt on pwt.personid = p.personid and pwt.physicalattributetypekey ='Wt' and pwt.activeflag = 1                                                                                                               
                                         left join personphysicalattribute ptt on ptt.personid = p.personid and ptt.physicalattributetypekey ='Tattoo' and ptt.activeflag = 1                                                                                                           
                                         left join personphysicalattribute ppm on ppm.personid = p.personid and ppm.physicalattributetypekey ='PhyMark' and ppm.activeflag = 1                                                                                                          
                                         where p.personid = v_personid and p.activeflag = 1                                                                                                                                                                                             
                                 ) a                                                                                                                                                                                                                                                    
                          INTO modifiedlog;                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                        
         -- Inserting the old name to Alias if the name changed                                                                                                                                                                                                                         
         IF v_isnamechanged = TRUE THEN                                                                                                                                                                                                                                                 
                 INSERT INTO alias (personid, firstname, lastname, middlename, insertedby, insertedon, activeflag)                                                                                                                                                                      
                 SELECT p.personid, p.firstname, p.lastname, p.middlename, v_securityuserid, now(), 1 FROM person p WHERE p.activeflag = 1 AND p.personid = v_personid;                                                                                                                 
         END IF;                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                        
                 UPDATE person                                                                                                                                                                                                                                                          
                           SET    dangertoself = (v_person ->> 'Dangerousself'):: int,                                                                                                                                                                                                  
                                          dangertoselfreason = v_person ->> 'DangerousselfReason',                                                                                                                                                                                      
                                          ethnicgrouptypekey = v_person ->> 'Ethicity',                                                                                                                                                                                                 
                                          racetypekey = v_person ->> 'Race',                                                                                                                                                                                                            
                                          firstname = v_person->>'Firstname',                                                                                                                                                                                                           
                                          lastname=v_person->>'Lastname',                                                                                                                                                                                                               
                                          middlename= v_person->>'Middlename',                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                        
                                          dob = (v_person->>'Dob')::timestamp,                                                                                                                                                                                                          
                                          --doddate = (v_person->>'Dod')::timestamp,                                                                                                                                                                                                    
                                          -- dateofdeath = (v_person->>'dateofdeath')::timestamp,                                                                                                                                                                                       
                                          dateofdeath = (v_person->>'Dod')::timestamp,                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                        
                                          isapproxdod = (v_person->>'isapproxdod')::int,                                                                                                                                                                                                
                                          religiontypekey= v_person ->> 'religiontypekey',                                                                                                                                                                                              
                                          tribalassociation= v_person ->> 'tribalassociation',                                                                                                                                                                                          
                                          physicalattributes= v_person ->> 'physicalattributes',                                                                                                                                                                                        
                                          nationalitytypekey = v_person ->> 'nationalitytypekey',                                                                                                                                                                                       
                                          gendertypekey = (v_person->>'gendertypekey'),                                                                                                                                                                                                 
                                          suffix= v_person->>'nameSuffix',                                                                                                                                                                                                              
                                          userphoto = v_person->>'userphoto',                                                                                                                                                                                                           
                                          stateid = v_person->>'stateid',                                                                                                                                                                                                               
                                          maritalstatustypekey = v_person->>'maritalstatustypekey',                                                                                                                                                                                     
                                          occupation = v_person->>'occupation',                                                                                                                                                                                                         
                                          needs = v_person->>'needs',                                                                                                                                                                                                                   
                                          strengths = v_person->>'strengths',
                                          substanceexposednewbornflag = (v_person ->> 'substanceexposednewbornflag')::INT,
                                          substanceexposednewbornsourceid = (v_person ->> 'substanceexposednewbornsourceid')::character varying,
                                          substanceexposednewbornsourcetypekey = (v_person ->> 'substanceexposednewbornsourcetypekey')::INT,
                                          substanceexposednewborntimetamp = (v_person ->> 'substanceexposednewborntimetamp')::timestamp,
                                          substanceclasses = (v_person ->> 'substanceclasses')::json,
                                          birthinghospital = (v_person ->> 'birthinghospital')::character varying,
                                          sencriteria = (v_person ->> 'sencriteria')::character varying  ,
                                          othersubstances = (v_person ->> 'othersubstances')::character varying                                                                                                                                                                                                           
                           WHERE  personid = v_personid;                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                        
                                 IF LENGTH(lower(v_person->>'SSN')) > 0 THEN                                                                                                                                                                                                            
                     update personidentifier set activeflag =0, updatedon = now(), updatedby = v_securityuserid where personid= v_personid                                                                                                                                                                                               
                     and personidentifiertypekey ='SSN';                                                                                                                                                                                                                                
                     INSERT INTO personidentifier(personid, personidentifiertypekey, personidentifiervalue,                                                                                                                                                                             
                         insertedby, insertedon, activeflag, effectivedate)                                                                                                                                                                                                             
                     VALUES (v_personid,'SSN', v_person->>'SSN',v_securityuserid,v_date,1,v_date);                                                                                                                                                                                      
                 END IF;                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                        
                IF Length(lower(v_person ->> 'dl')) > 0 then                                                                                                                                                                                                                            
                             UPDATE personidentifier SET activeflag =0, updatedon = now(), updatedby = v_securityuserid WHERE  personid= v_personid                                                                                                                                                                                      
                 AND personidentifiertypekey ='DL';                                                                                                                                                                                                                                     
                                 INSERT INTO personidentifier (personid, personidentifiertypekey, personidentifiervalue,                                                                                                                                                                
                                                 insertedby, insertedon, activeflag, effectivedate)                                                                                                                                                                                     
                                     VALUES (v_personid, 'DL', v_person ->> 'dl', v_securityuserid, v_date, 1, v_date);                                                                                                                                                                 
                          END IF;                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                        
                          IF Length(lower(v_person ->> 'height')) > 0 then                                                                                                                                                                                                              
                             UPDATE personphysicalattribute SET activeflag =0, updatedon = now(), updatedby = v_securityuserid WHERE personid= v_personid                                                                                                                                                                                
                 AND physicalattributetypekey ='Ht';                                                                                                                                                                                                                                    
                                 INSERT INTO personphysicalattribute (personid, physicalattributetypekey, attributevalue,                                                                                                                                                               
                                                 insertedby, insertedon, activeflag, effectivedate)                                                                                                                                                                                     
                                     VALUES (v_personid, 'Ht', v_person ->> 'height', v_securityuserid, v_date, 1, v_date);                                                                                                                                                             
                          END IF;                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                        
                          IF Length(lower(v_person ->> 'weight')) > 0 then                                                                                                                                                                                                              
                             UPDATE personphysicalattribute SET activeflag =0, updatedon = now(), updatedby = v_securityuserid WHERE  personid= v_personid                                                                                                                                                                               
                 AND physicalattributetypekey ='Wt';                                                                                                                                                                                                                                    
                                 INSERT INTO personphysicalattribute (personid, physicalattributetypekey, attributevalue,                                                                                                                                                               
                                                 insertedby, insertedon, activeflag, effectivedate)                                                                                                                                                                                     
                                     VALUES (v_personid, 'Wt', v_person ->> 'weight', v_securityuserid, v_date, 1, v_date);                                                                                                                                                             
                          END IF;                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                        
                          IF Length(lower(v_person ->> 'tattoo')) > 0 then                                                                                                                                                                                                              
                             UPDATE personphysicalattribute SET activeflag =0, updatedon = now(), updatedby = v_securityuserid WHERE personid= v_personid                                                                                                                                                                                
                 AND physicalattributetypekey ='Tattoo';                                                                                                                                                                                                                                
                                 INSERT INTO personphysicalattribute(personid, physicalattributetypekey, attributevalue,                                                                                                                                                                
                                                 insertedby, insertedon, activeflag, effectivedate)                                                                                                                                                                                     
                                     VALUES (v_personid, 'Tattoo', v_person ->> 'tattoo', v_securityuserid, v_date, 1, v_date);                                                                                                                                                         
                          END IF;                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                        
                          IF Length(lower(v_person ->> 'PhyMark')) > 0 then                                                                                                                                                                                                             
                             UPDATE personphysicalattribute SET activeflag =0, updatedon = now(), updatedby = v_securityuserid WHERE personid= v_personid                                                                                                                                                                                
                 AND physicalattributetypekey ='PhyMark';                                                                                                                                                                                                                               
                                 INSERT INTO personphysicalattribute(personid, physicalattributetypekey, attributevalue,                                                                                                                                                                
                                                 insertedby, insertedon, activeflag, effectivedate)                                                                                                                                                                                     
                                     VALUES (v_personid, 'PhyMark', v_person ->> 'PhyMark', v_securityuserid, v_date, 1, v_date );                                                                                                                                                      
                          END IF;                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                        
                         SELECT json_agg(e)from ( select   v_person->>'Firstname' firstname                                                                                                                                                                                             
                                 , v_person->>'Lastname' lastname                                                                                                                                                                                                                       
                                 --, v_person->>'Dob' dob                                                                                                                                                                                                                               
                                 , v_person->>'maritalstatus' maritalstatus                                                                                                                                                                                                             
                          , v_person->>'SSN' ssn, v_person->>'weight' weight, v_person->>'occupation' occupation)e INTO dadetails;                                                                                                                                                      
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                        
            INSERT INTO auditlog(                                                                                                                                                                                                                                                       
            logtypekey,description,referenceid,servicerequestnumber, isnew,isedit,isdelete,insertedon,metadata, modifieddata,insertedby)                                                                                                                                                
             VALUES('IP','Person Edited',v_personid,null,'false','true','false',v_date at time zone 'utc',dadetails::json, modifiedlog::json,v_securityuserid);                                                                                                                         
                                                                                                                                                                                                                                                                                        
     return 'Success';                                                                                                                                                                                                                                                                  
         END;                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                        
 $function$                                                                                                                                                                                                                                                                               

