 CREATE OR REPLACE FUNCTION public.placementlist(v_intakeserviceid character varying, pagenumber integer, pagesize integer)                                                                                                                                                                                                                                                            
  RETURNS TABLE(totalcount bigint, placementid uuid, providerid uuid, intakeserviceid uuid, startdatetime timestamp without time zone, remarks text, statustypekey character varying, providername character varying, providercategorytypekey character varying, actortype character varying, dob timestamp without time zone, firstname character varying, lastname character varying)
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                     
 AS $function$                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                       
 declare  v_pageoffset int;                                                                                                                                                                                                                                                                                                                                                            
         v_pagenumber int;                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                       
 begin                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                       
     v_pagenumber := pagenumber-1;                                                                                                                                                                                                                                                                                                                                                     
     v_pageoffset = v_pagenumber * pagesize;                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                       
 return query                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                       
 SELECT count(1) over() as totalcount,a.placementid,a.providerid,a.intakeserviceid,a.startdatetime,a.remarks,a.statustypekey,b.providername,b.providercategorytypekey,e.actortype,f.dob,f.firstname,f.lastname                                                                                                                                                                         
 FROM public.placement a                                                                                                                                                                                                                                                                                                                                                               
 join public.provider b on a.providerid = b.providerid                                                                                                                                                                                                                                                                                                                                 
 join public.intakeservicerequest c on a.intakeserviceid = c.intakeserviceid                                                                                                                                                                                                                                                                                                           
 join public.intakeservicerequestactor d on d.intakeserviceid = a.intakeserviceid                                                                                                                                                                                                                                                                                                      
 join public.actor e on e.actorid = d.actorid                                                                                                                                                                                                                                                                                                                                          
 join public.person f on f.personid = e.personid                                                                                                                                                                                                                                                                                                                                       
 where a.intakeserviceid=v_intakeserviceid :: uuid                                                                                                                                                                                                                                                                                                                                     
 group by a.placementid,a.providerid,a.intakeserviceid,a.startdatetime,a.remarks,a.statustypekey,b.providername,b.providercategorytypekey,e.actortype,f.dob,f.firstname,f.lastname;                                                                                                                                                                                                    
 --LIMIT pagesize OFFSET v_pageoffset;                                                                                                                                                                                                                                                                                                                                                 
 end;                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                       
 $function$                                                                                                                                                                                                                                                                                                                                                                            

