DROP FUNCTION IF EXISTS cjams.addupdateform1080c(formdata jsonb, v_userid character varying);
CREATE OR REPLACE FUNCTION cjams.addupdateform1080c(formdata jsonb, v_userid character varying)
 RETURNS TABLE(message text)
 LANGUAGE plpgsql
AS $function$
-------------------------------------------------------------------------
--  06-19-2025 - CIDM-10473 1080 Form C-Add and update the form 1080c stored procedure - Anil Kumar Dharni 
-- 07-23-2025 - Simar Singh - CIDM-10473 Support for other risk factors
-------------------------------------------------------------------------
DECLARE
    v_fullname character varying;
BEGIN
    SELECT COALESCE(firstname, '') || ' ' || COALESCE(lastname, '')
    INTO v_fullname
    FROM cjams.person
    WHERE personid = (formData ->> 'personid')::uuid;

    IF (formdata ->> 'form1080cid') IS NULL THEN

        INSERT INTO cjams.form1080c (
            form1080cid,
            objectid,
            objecttype,
            casenumber,
            doesmaltreatmentappeartohavebeenacontributingfactor,
            ifincidentoccurredinlicensedsettingindicateactiontaken,
            specify,
            legaloutcomeinthisincident,
            wasthisincidentrelatedtosleeporanunsafesleepenvironment,
            inthe72hoursbeforethefatalincidentwasthechildinjured,
            personid,
            fullname,
            physicalabuse,
            physicalabuseradio,
            sexualabuse,
            sexualabuseradio,
            neglect,
            neglectradio,
            mentalinjuryabuse,
            mentalinjuryabuseradio,
            mentalinjuryneglect,
            mentalinjuryneglectradio,
            summaryoffactsandfindingincludingtheeventdateinthecase,
            theallegedlymaltreatedchild,
            siblingsoftheallegedlymaltreatedchild,
            otherchildinhouseholdfamilyorincaseofallegedmaltreater,
            substanceusechild,
            substanceusefamily,
            substanceusecaregiver,
            mentalillnesschild,
            mentalillnessfamily,
            mentalillnesscaregiver,
            domesticviolencechild,
            domesticviolencefamily,
            domesticviolencecaregiver,
            prenatalexposurechild,
            prenatalexposurefamily,
            prenatalexposurecaregiver,
            noprenatalcarechild,
            noprenatalcarefamily,
            noprenatalcarecaregiver,
            childfatalitychild,
            childfatalityfamily,
            childfatalitycaregiver,
            medicalconditionchild,
            medicalconditionfamily,
            medicalconditioncaregiver,
            healthinsurancechild,
            healthinsurancefamily,
            healthinsurancecaregiver,
            otherchild,
            otherfamily,
            othercaregiver,
            otherriskfactors,
            describehowtheselectedriskfactorsfromchartaboveinfluencedtheinc,
            signatureofpersoncompletingthisreport,
            personcompletingthisreport,
            supervisor,
            phonenumber,
            supervisorphonenumber,
            email,
            supervisoremail,
            datecompleted,
            activeflag,
            insertedby,
            insertedon,
            submitforapproval,
            supervisorcomments,
            status,
            updatedby,
            updatedon,
            copyofform1080c
        ) VALUES (
            gen_random_uuid(),
            (formData ->> 'objectid'),
            (formData ->> 'objecttype')::character varying,
            (formData ->> 'casenumber')::character varying,
            (formData ->> 'doesmaltreatmentappeartohavebeenacontributingfactor')::character varying,
            (formData ->> 'ifincidentoccurredinlicensedsettingindicateactiontaken')::character varying,
            (formData ->> 'specify')::character varying,
            (formData ->> 'legaloutcomeinthisincident')::character varying,
            (formData ->> 'wasthisincidentrelatedtosleeporanunsafesleepenvironment')::character varying,
            (formData ->> 'inthe72hoursbeforethefatalincidentwasthechildinjured')::character varying,
            (formData ->> 'personid')::uuid,
            v_fullname::character varying,
            (formData ->> 'physicalabuse')::character varying,
            (formData ->> 'physicalabuseradio')::character varying,
            (formData ->> 'sexualabuse')::character varying,
            (formData ->> 'sexualabuseradio')::character varying,
            (formData ->> 'neglect')::character varying,
            (formData ->> 'neglectradio')::character varying,
            (formData ->> 'mentalinjuryabuse')::character varying,
            (formData ->> 'mentalinjuryabuseradio')::character varying,
            (formData ->> 'mentalinjuryneglect')::character varying,
            (formData ->> 'mentalinjuryneglectradio')::character varying,
            (formData ->> 'summaryoffactsandfindingincludingtheeventdateinthecase')::character varying,
            (formData ->> 'theallegedlymaltreatedchild')::character varying,
            (formData ->> 'siblingsoftheallegedlymaltreatedchild')::character varying,
            (formData ->> 'otherchildinhouseholdfamilyorincaseofallegedmaltreater')::character varying,
            (formData ->> 'substanceusechild')::character varying,
            (formData ->> 'substanceusefamily')::character varying,
            (formData ->> 'substanceusecaregiver')::character varying,
            (formData ->> 'mentalillnesschild')::character varying,
            (formData ->> 'mentalillnessfamily')::character varying,
            (formData ->> 'mentalillnesscaregiver')::character varying,
            (formData ->> 'domesticviolencechild')::character varying,
            (formData ->> 'domesticviolencefamily')::character varying,
            (formData ->> 'domesticviolencecaregiver')::character varying,
            (formData ->> 'prenatalexposurechild')::character varying,
            (formData ->> 'prenatalexposurefamily')::character varying,
            (formData ->> 'prenatalexposurecaregiver')::character varying,
            (formData ->> 'noprenatalcarechild')::character varying,
            (formData ->> 'noprenatalcarefamily')::character varying,
            (formData ->> 'noprenatalcarecaregiver')::character varying,
            (formData ->> 'childfatalitychild')::character varying,
            (formData ->> 'childfatalityfamily')::character varying,
            (formData ->> 'childfatalitycaregiver')::character varying,
            (formData ->> 'medicalconditionchild')::character varying,
            (formData ->> 'medicalconditionfamily')::character varying,
            (formData ->> 'medicalconditioncaregiver')::character varying,
            (formData ->> 'healthinsurancechild')::character varying,
            (formData ->> 'healthinsurancefamily')::character varying,
            (formData ->> 'healthinsurancecaregiver')::character varying,
            (formData ->> 'otherchild')::character varying,
            (formData ->> 'otherfamily')::character varying,
            (formData ->> 'othercaregiver')::character varying,
            (formData -> 'otherriskfactors')::jsonb,
            (formData ->> 'describehowtheselectedriskfactorsfromchartaboveinfluencedtheinc')::character varying,
            (formData ->> 'signatureofpersoncompletingthisreport')::character varying,
            (formData ->> 'personcompletingthisreport')::character varying,
            (formData ->> 'supervisor')::character varying,
            (formData ->> 'phonenumber')::character varying,
            (formData ->> 'supervisorphonenumber')::character varying,
            (formData ->> 'email')::character varying,
            (formData ->> 'supervisoremail')::character varying,
            (formData ->> 'datecompleted')::timestamp,
            1,
            v_userid,
            now(),
               (formData ->> 'submitforapproval')::character varying,
                  (formData ->> 'supervisorcomments')::character varying,
                     (formData ->> 'status')::character varying,
            v_userid,
            now(),
            (formData ->> 'copyofform1080c')::jsonb
        );
    ELSE
        UPDATE cjams.form1080c
        SET 
            objectid = (formData ->> 'objectid'),
            objecttype = (formData ->> 'objecttype')::character varying,
            casenumber = (formData ->> 'casenumber')::character varying,
            doesmaltreatmentappeartohavebeenacontributingfactor = (formData ->> 'doesmaltreatmentappeartohavebeenacontributingfactor')::character varying,
            ifincidentoccurredinlicensedsettingindicateactiontaken = (formData ->> 'ifincidentoccurredinlicensedsettingindicateactiontaken')::character varying,
            specify = (formData ->> 'specify')::character varying,
            legaloutcomeinthisincident = (formData ->> 'legaloutcomeinthisincident')::character varying,
            wasthisincidentrelatedtosleeporanunsafesleepenvironment = (formData ->> 'wasthisincidentrelatedtosleeporanunsafesleepenvironment')::character varying,
            inthe72hoursbeforethefatalincidentwasthechildinjured = (formData ->> 'inthe72hoursbeforethefatalincidentwasthechildinjured')::character varying,
            personid = (formData ->> 'personid')::uuid,
            fullname = v_fullname::character varying,
            physicalabuse = (formData ->> 'physicalabuse')::character varying,
            physicalabuseradio = (formData ->> 'physicalabuseradio')::character varying,
            sexualabuse = (formData ->> 'sexualabuse')::character varying,
            sexualabuseradio = (formData ->> 'sexualabuseradio')::character varying,
            neglect = (formData ->> 'neglect')::character varying,
            neglectradio = (formData ->> 'neglectradio')::character varying,
            mentalinjuryabuse = (formData ->> 'mentalinjuryabuse')::character varying,
            mentalinjuryabuseradio = (formData ->> 'mentalinjuryabuseradio')::character varying,
            mentalinjuryneglect = (formData ->> 'mentalinjuryneglect')::character varying,
            mentalinjuryneglectradio = (formData ->> 'mentalinjuryneglectradio')::character varying,
            summaryoffactsandfindingincludingtheeventdateinthecase = (formData ->> 'summaryoffactsandfindingincludingtheeventdateinthecase')::character varying,
            theallegedlymaltreatedchild = (formData ->> 'theallegedlymaltreatedchild')::character varying,
            siblingsoftheallegedlymaltreatedchild = (formData ->> 'siblingsoftheallegedlymaltreatedchild')::character varying,
            otherchildinhouseholdfamilyorincaseofallegedmaltreater = (formData ->> 'otherchildinhouseholdfamilyorincaseofallegedmaltreater')::character varying,
            substanceusechild = (formData ->> 'substanceusechild')::character varying,
            substanceusefamily = (formData ->> 'substanceusefamily')::character varying,
            substanceusecaregiver = (formData ->> 'substanceusecaregiver')::character varying,
            mentalillnesschild = (formData ->> 'mentalillnesschild')::character varying,
            mentalillnessfamily = (formData ->> 'mentalillnessfamily')::character varying,
            mentalillnesscaregiver = (formData ->> 'mentalillnesscaregiver')::character varying,
            domesticviolencechild = (formData ->> 'domesticviolencechild')::character varying,
            domesticviolencefamily = (formData ->> 'domesticviolencefamily')::character varying,
            domesticviolencecaregiver = (formData ->> 'domesticviolencecaregiver')::character varying,
            prenatalexposurechild = (formData ->> 'prenatalexposurechild')::character varying,
            prenatalexposurefamily = (formData ->> 'prenatalexposurefamily')::character varying,
            prenatalexposurecaregiver = (formData ->> 'prenatalexposurecaregiver')::character varying,
            noprenatalcarechild = (formData ->> 'noprenatalcarechild')::character varying,
            noprenatalcarefamily = (formData ->> 'noprenatalcarefamily')::character varying,
            noprenatalcarecaregiver = (formData ->> 'noprenatalcarecaregiver')::character varying,
            childfatalitychild = (formData ->> 'childfatalitychild')::character varying,
            childfatalityfamily = (formData ->> 'childfatalityfamily')::character varying,
            childfatalitycaregiver = (formData ->> 'childfatalitycaregiver')::character varying,
            medicalconditionchild = (formData ->> 'medicalconditionchild')::character varying,
            medicalconditionfamily = (formData ->> 'medicalconditionfamily')::character varying,
            medicalconditioncaregiver = (formData ->> 'medicalconditioncaregiver')::character varying,
            healthinsurancechild = (formData ->> 'healthinsurancechild')::character varying,
            healthinsurancefamily = (formData ->> 'healthinsurancefamily')::character varying,
            healthinsurancecaregiver = (formData ->> 'healthinsurancecaregiver')::character varying,
            otherchild = (formData ->> 'otherchild')::character varying,
            otherfamily = (formData ->> 'otherfamily')::character varying,
            othercaregiver = (formData ->> 'othercaregiver')::character varying,
            otherriskfactors = (formData -> 'otherriskfactors')::jsonb,
            describehowtheselectedriskfactorsfromchartaboveinfluencedtheinc = (formData ->> 'describehowtheselectedriskfactorsfromchartaboveinfluencedtheinc')::character varying,
            signatureofpersoncompletingthisreport = (formData ->> 'signatureofpersoncompletingthisreport')::character varying,
            personcompletingthisreport = (formData ->> 'personcompletingthisreport')::character varying,
            supervisor = (formData ->> 'supervisor')::character varying,
            phonenumber = (formData ->> 'phonenumber')::character varying,
            supervisorphonenumber = (formData ->> 'supervisorphonenumber')::character varying,
            email = (formData ->> 'email')::character varying,
            supervisoremail = (formData ->> 'supervisoremail')::character varying,
            datecompleted = (formData ->> 'datecompleted')::timestamp,
            updatedby = v_userid,
            updatedon = now(),
            submitforapproval = (formData ->> 'submitforapproval')::character varying,
            supervisorcomments = (formData ->> 'supervisorcomments')::character varying,
            status =  (formData ->> 'status')::character varying
        WHERE form1080cid = (formdata ->> 'form1080cid')::uuid;
    END IF;

    RETURN QUERY
    SELECT 
        CASE
            WHEN ( formdata  ->> 'copyofform1080c') IS NOT NULL THEN 'Form 1080C Copied Successfully'  
            WHEN (formdata ->> 'form1080cid') IS NULL THEN 'Form 1080C Saved Successfully' 
            ELSE 'Form 1080C Updated Successfully' 
        END;
END;
$function$;
