DROP FUNCTION cjams.getapprovalhistory(uuid);

CREATE OR REPLACE FUNCTION cjams.getapprovalhistory(v_assessmentid uuid)
 RETURNS TABLE(routingid uuid, updatedon timestamp without time zone, insertedon timestamp without time zone, fromusername character varying, tousername character varying, routingstatustypeid integer, activeflag integer, updatedby character varying)
 LANGUAGE plpgsql
AS $function$                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 BEGIN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 RETURN  query                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 select r.routingid,r.updatedon, r.insertedon , (select displayname from userprofile where securityusersid =r.fromsecurityusersid) as fromusername,
 (select displayname from userprofile where securityusersid =r.tosecurityusersid) as tousername, r.routingstatustypeid, r.activeflag ,
 (select displayname from userprofile where securityusersid =r.updatedby) as updatedby 
 from routing r 
 WHERE r.objectid = v_assessmentid::character varying;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 END;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 $function$
;
