 CREATE OR REPLACE FUNCTION public.getassessmentvalue(v_intakenumber character varying, v_intakeserviceid uuid, v_templatename character varying, v_fieldname character varying, v_fieldvalue character varying)           
  RETURNS TABLE(returndata json)                                                                                                                                                                                           
  LANGUAGE plpgsql                                                                                                                                                                                                         
 AS $function$                                                                                                                                                                                                           
                                                                                                                                                                                                                         
                                                                                                                                                                                                                         
                                                                                                                                                                                                                         
 DECLARE                                                                                                                                                                                                                 
         v_isDetention BOOLEAN;                                                                                                                                                                                          
         v_value CHARACTER VARYING;                                                                                                                                                                                      
         j_return BOOLEAN;                                                                                                                                                                                               
                                                                                                                                                                                                                         
                                                                                                                                                                                                                         
 BEGIN                                                                                                                                                                                                                   
                                                                                                                                                                                                                         
 --SELECT count(1) > 0 into v_isDetention                                                                                                                                                                                
 SELECT ats.datavalue into v_value                                                                                                                                                                                       
 FROM assessmenttemplate at                                                                                                                                                                                              
 JOIN assessment a ON a.assessmenttemplateid = at.assessmenttemplateid AND a.activeflag = 1                                                                                                                              
 JOIN assessmentsubmission ats ON ats.assessmentid = a.assessmentid AND ats.activeflag = 1                                                                                                                               
 WHERE at.activeflag = 1 AND at."name" = v_templatename                                                                                                                                                                  
 AND ats.datakey = v_fieldname                                                                                                                                                                                           
 --AND ats.datavalue = v_fieldvalue                                                                                                                                                                                      
 AND (a.intakenumber = v_intakenumber OR (a.objectid IS NULL OR a.objectid = v_intakeserviceid));                                                                                                                        
                                                                                                                                                                                                                         
 IF v_value = v_fieldvalue THEN                                                                                                                                                                                          
         v_isDetention := TRUE;                                                                                                                                                                                          
 ELSE                                                                                                                                                                                                                    
         v_isDetention := FALSE;                                                                                                                                                                                         
 END IF;                                                                                                                                                                                                                 
                                                                                                                                                                                                                         
 return query                                                                                                                                                                                                            
 select json_build_object('assessmentvalue', case when v_fieldvalue is not null then null else v_value end, 'isassessmentvaluematch', case when v_fieldvalue is not null then v_isDetention else null end) as returndata;
                                                                                                                                                                                                                         
 --RETURN v_isDetention;                                                                                                                                                                                                 
 --RETURN j_return;                                                                                                                                                                                                      
                                                                                                                                                                                                                         
 END;                                                                                                                                                                                                                    
                                                                                                                                                                                                                         
 $function$                                                                                                                                                                                                                

