 CREATE OR REPLACE FUNCTION public.getassessmentlist(intakenumber character varying, target character varying, agencycode character varying, servreqtypeid character varying, servreqsubtypeid character varying, pageno integer, pagesize integer)
  RETURNS json                                                                                                                                                                                                                                     
  LANGUAGE plpgsql                                                                                                                                                                                                                                 
 AS $function$                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                 
  DECLARE                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                 
 assessmenttemplateid uuid;                                                                                                                                                                                                                      
 v_target character varying;                                                                                                                                                                                                                     
 assessmenttemplate_data json;                                                                                                                                                                                                                   
 v_servreqtypeid character varying;                                                                                                                                                                                                              
 v_servreqsubtypeid character varying;                                                                                                                                                                                                           
 declare  v_pageoffset int;                                                                                                                                                                                                                      
         v_pagenumber int;                                                                                                                                                                                                                       
        v_intakenumber character varying;                                                                                                                                                                                                        
                                                                                                                                                                                                                                                 
  BEGIN                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                 
 v_pagenumber := pageno-1;                                                                                                                                                                                                                       
 v_pageoffset = v_pagenumber * pagesize;                                                                                                                                                                                                         
                                                                                                                                                                                                                                                 
  v_target := target;                                                                                                                                                                                                                            
 v_intakenumber:=intakenumber;                                                                                                                                                                                                                   
  v_servreqtypeid := servreqtypeid ;                                                                                                                                                                                                             
  v_servreqsubtypeid := servreqsubtypeid ;                                                                                                                                                                                                       
                                                                                                                                                                                                                                                 
  if (coalesce(servreqtypeid,'')='') then                                                                                                                                                                                                        
                                                                                                                                                                                                                                                 
         v_servreqtypeid := '00000000-0000-0000-0000-000000000000';                                                                                                                                                                              
  end if;                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                 
   if (coalesce(servreqsubtypeid ,'')='' or                                                                                                                                                                                                      
       coalesce(servreqtypeid,'')= coalesce(servreqsubtypeid ,'')) then                                                                                                                                                                          
          v_servreqsubtypeid := '00000000-0000-0000-0000-000000000000';                                                                                                                                                                          
  end if;                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                 
                 select json_agg(a) from (                                                                                                                                                                                                       
                   select count(1) over()totalcount, AST.assessmentTextPositionTypeKey,AST.assessmentscoresetupid,                                                                                                                               
           AST.assessmenttemplateid,AST.calculationmethod,AST.datamappingenabled,                                                                                                                                                                
           AST.description,AST.effectivedate,AST.enableassessmentscore,AST.expirationdate,                                                                                                                                                       
                   AST.external_templateid,AST.helptext,AST.instructions,AST.isvisible,AST.name,                                                                                                                                                 
           ATCM.old_id,  AST.scoringname,ATT.target,ATCM.timestamp,                                                                                                                                                                              
           AST.titleheadertext,AST.version,                                                                                                                                                                                                      
            (select up.firstname||' '|| up.lastname as fullname from assignedassessment aas                                                                                                                                                      
  join userprofile up on up.securityusersid = aas.securityusersid and up.activeflag=1                                                                                                                                                            
  where aas.assessmenttemplateid=AST.AssessmentTemplateId  and aas.intakenumber =v_intakenumber and aas.activeflag=1 limit 1                                                                                                                     
  ) as assignedto,                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                 
           (select * from getassessmentdetails(intakenumber,AST.assessmenttemplateid,false)) as intakassessment                                                                                                                                  
                 from assessmenttemplate AST                                                                                                                                                                                                     
                 inner join assessmenttemplatecategoryfiltermap ATCM                                                                                                                                                                             
                 On AST.assessmenttemplateid  = ATCM.assessmenttemplateid                                                                                                                                                                        
         and ATCM.activeflag =1                                                                                                                                                                                                                  
                 inner join assessmenttemplatetarget ATT                                                                                                                                                                                         
                 on ATCM.assessmenttemplatetargetid  = ATT.assessmenttemplatetargetid                                                                                                                                                            
                         where lower(ATT.target) = lower(v_target)                                                                                                                                                                               
             and ATCM.teamtypekey = agencycode                                                                                                                                                                                                   
                         and ATCM.intakeservicerequesttypeid = v_servreqtypeid::uuid                                                                                                                                                             
                         and ATCM.intakeservicerequestsubtypeid= v_servreqsubtypeid::uuid                                                                                                                                                        
                         and AST.activeflag = 1                                                                                                                                                                                                  
             LIMIT pageno OFFSET v_pageoffset                                                                                                                                                                                                    
         ) a INTO assessmenttemplate_data;                                                                                                                                                                                                       
                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                 
 RETURN assessmenttemplate_data;                                                                                                                                                                                                                 
  END                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                 
 $function$                                                                                                                                                                                                                                        

