 DROP FUNCTION if exists getcourtorder(uuid); 
 DROP FUNCTION if exists getcourtorder(uuid, character varying, integer); 
 DROP FUNCTION if exists getcourtorder(uuid, character varying, integer, integer); 
 DROP FUNCTION if exists getcourtorder(uuid, integer, integer); 
 CREATE OR REPLACE FUNCTION cjams.getcourtorder(v_intakeserviceid uuid, isExpungementSuperUser integer DEFAULT 0::integer, isexpunged integer DEFAULT 0::integer)
 RETURNS TABLE(intakeservreqcourtorderid uuid, intakeservicerequestactorid uuid, intakeservicerequestpetitionid uuid, intakeservicerequesthearingid uuid, courtorderdate timestamp without time zone, remarks character varying, removalepisode bigint, hearingoutcometypekey character varying, hearingoutcomedesc character varying, childpermanencyplankey character varying, childpermanencyplantype character varying, 
 dob timestamp without time zone,county character varying,clientname character varying,personsappeared json,courtreview character varying,childsneed character varying,childneedcantmet boolean,childpermanencyplan boolean,childmosteffplan boolean,qrtpapproval character varying,qrtpapprovaldecision character varying,judgedate timestamp without time zone,judgename character varying,judgeid character varying,otherpersonsappeared character varying , hearingoutcome json, attachments json, courtdetails json, personid uuid, isactivehearing boolean)
 LANGUAGE plpgsql
AS $function$                                                                                                                                                                                                                                                                                                                                                                         
------------------------------------------------------------------------------------------------------------
-- Revision(s)
-- 11/17/2025 Amiya Pradhan - CIDM-10890 - CJAMS Manual & Automation Expungement Enhancement - for Sexual Abuse CPS Intakes and Cases
------------------------------------------------------------------------------------------------------------
DECLARE 
v_isexpunged integer := 0;

BEGIN 

IF isExpungementSuperUser = 1 THEN
    v_isexpunged := isexpunged;
END IF;

IF v_isexpunged = 1 THEN 
-- fully expunged 
RETURN query  
SELECT                                                                                                                                                                                                                                                                                                                                                                                
         isrco.intakeservreqcourtorderid,isrco.intakeservicerequestactorid,isrco.intakeservicerequestpetitionid,isrco.intakeservicerequesthearingid , isrco.courtorderdate,isrco.remarks,isrco.removalid as removalepisode, ppt.ref_key AS hearingoutcometypekey,                                                                                                                                                                                                                                 
         ppt.description AS hearingoutcomedesc,isrco.childpermanencyplankey,rtd.description as childpermanencyplantype,
          isrco.dob, isrco.county,isrco.clientname,isrco.personsappeared,isrco.courtreview,isrco.childsneed,isrco.childneedcantmet,isrco.childpermanencyplan,isrco.childmosteffplan,isrco.qrtpapproval,isrco.qrtpapprovaldecision,isrco.judgedate, isrco.judgename,isrco.judgeid,isrco.otherpersonsappeared,                                                                                                                                                                                                                                                                
         (                                                                                                                                                                                                                                                                                                                                                                             
                                         SELECT                                                                                                                                                                                                                                                                                                                                        
                                                 json_agg(outcome) AS hearingoutcome                                                                                                                                                                                                                                                                                                   
                                         FROM                                                                                                                                                                                                                                                                                                                                          
                                         (                                                                                                                                                                                                                                                                                                                                             
                                                 SELECT                                                                                                                                                                                                                                                                                                                                
                                                         isrhoc.hearingoutcometypekey,rvs.description AS hearingoutcomedesc                                                                                                                                                                                                                                                            
                                                 FROM Intakeservreqcohearingoutcome isrhoc                                                                                                                                                                                                                                                                                             
                                                 INNER JOIN referencevalues rvs ON rvs.ref_key=isrhoc.hearingoutcometypekey AND rvs.activeflag=1                                                                                                                                                                                                                                       
                                                 WHERE isrhoc.intakeservreqcourtorderid=isrco.intakeservreqcourtorderid AND isrhoc.activeflag=1                                                                                                                                                                                                                                        
                                         ) outcome                                                                                                                                                                                                                                                                                                                                     
                                 ),                                                                                                                                                                                                                                                                                                                                                    
         (                                                                                                                                                                                                                                                                                                                                                                             
                SELECT                                                                                                                                                                                                                                                                                                                                        
                        json_agg(doc) AS attachments                                                                                                                                                                                                                                                                                                          
                FROM                                                                                                                                                                                                                                                                                                                                          
                (                                                                                                                                                                                                                                                                                                                                             
                SELECT  dp.filename, dp.title, dp.mime, dp.numberofbytes, dp.s3bucketpathname, dp.originalfilename, dp.actualdocumentdate, dp.documentpropertiesid, dp.other,                                                                                                                                                                                                                               
                        (select up.fullname as insertedby from userprofile up where up.securityusersid = dp.insertedby), dp.updatedon, dp.uploadstatus, dp.finalstatus, dp.ecmsdocumentid                                                                                                                                                                                                                              
                from documentproperties dp where dp.objectid = isrco.intakeservreqcourtorderid and dp.activeflag in (1,3,4,5)                                                                                                                                                                                                                                              
                ) doc                                                                                                                                                                                                                                                                                                                                         
        ),                                                                                                                                                                                                                                                                                                                                                    
         (                                                                                                                                                                                                                                                                                                                                                                             
                 SELECT                                                                                                                                                                                                                                                                                                                                                                
                         json_agg(e) AS courtdetails FROM                                                                                                                                                                                                                                                                                                                              
                 (                                                                                                                                                                                                                                                                                                                                                                     
                         SELECT                                                                                                                                                                                                                                                                                                                                                        
                                 isrcod.intakeservreqcourtorderdetailsid,isrcod.checklistid,isrcod.checklisttypekey,isrcod.isselected,isrcod.remarks,                                                                                                                                                                                                                                  
                                 (                                                                                                                                                                                                                                                                                                                                                     
                                         SELECT                                                                                                                                                                                                                                                                                                                                        
                                                 json_agg(x) AS courtlanguage                                                                                                                                                                                                                                                                                                          
                                         FROM                                                                                                                                                                                                                                                                                                                                          
                                         (                                                                                                                                                                                                                                                                                                                                             
                                                 SELECT                                                                                                                                                                                                                                                                                                                                
                                                         cl.checklistname,cl.description AS checklistdesc                                                                                                                                                                                                                                                                              
                                                 FROM checklist cl                                                                                                                                                                                                                                                                                                                     
                                                 INNER JOIN referencevalues rvs ON rvs.ref_key=isrcod.checklisttypekey AND rvs.activeflag=1                                                                                                                                                                                                                                            
                                                 WHERE isrcod.intakeservreqcourtorderid=isrco.intakeservreqcourtorderid AND isrcod.activeflag=1 AND rvs.ref_key='COLANG'                                                                                                                                                                                                               
                                         )  x                                                                                                                                                                                                                                                                                                                                          
                                 ),                                                                                                                                                                                                                                                                                                                                                    
                                 (                                                                                                                                                                                                                                                                                                                                                     
                                         SELECT                                                                                                                                                                                                                                                                                                                                        
                                                 json_agg(y) AS courtpermanencyplan                                                                                                                                                                                                                                                                                                    
                                         FROM                                                                                                                                                                                                                                                                                                                                          
                                         (                                                                                                                                                                                                                                                                                                                                             
                                                 SELECT                                                                                                                                                                                                                                                                                                                                
                                                         cl.checklistname,cl.description AS checklistdesc                                                                                                                                                                                                                                                                              
                                                 FROM checklist cl                                                                                                                                                                                                                                                                                                                     
                                                 INNER JOIN referencevalues rvs ON rvs.ref_key=isrcod.checklisttypekey AND rvs.activeflag=1                                                                                                                                                                                                                                            
                                                 WHERE isrcod.intakeservreqcourtorderid=isrco.intakeservreqcourtorderid AND isrcod.activeflag=1 AND rvs.ref_key='COPP'                                                                                                                                                                                                                 
                                         ) y                                                                                                                                                                                                                                                                                                                                           
                                 ),                                                                                                                                                                                                                                                                                                                                                    
                                 (                                                                                                                                                                                                                                                                                                                                                     
                                         SELECT                                                                                                                                                                                                                                                                                                                                        
                                                 json_agg(z) AS courthearingoutcome                                                                                                                                                                                                                                                                                                    
                                         FROM                                                                                                                                                                                                                                                                                                                                          
                                         (                                                                                                                                                                                                                                                                                                                                             
                                                 SELECT                                                                                                                                                                                                                                                                                                                                
                                                         cl.checklistname,cl.description AS checklistdesc                                                                                                                                                                                                                                                                              
                                                 FROM checklist cl                                                                                                                                                                                                                                                                                                                     
                                                 INNER JOIN referencevalues rvs ON rvs.ref_key=isrcod.checklisttypekey AND rvs.activeflag=1                                                                                                                                                                                                                                            
                                                 WHERE isrcod.intakeservreqcourtorderid=isrco.intakeservreqcourtorderid AND isrcod.activeflag=1 AND rvs.ref_key='COHO'                                                                                                                                                                                                                 
                                         ) z                                                                                                                                                                                                                                                                                                                                           
                                 )                                                                                                                                                                                                                                                                                                                                                     
                         FROM intakeservreqcourtorderdetails isrcod                                                                                                                                                                                                                                                                                                                    
                         WHERE isrcod.intakeservreqcourtorderid=isrco.intakeservreqcourtorderid AND isrcod.activeflag=1                                                                                                                                                                                                                                                                
                 )  e                                                                                                                                                                                                                                                                                                                                                                  
         ),
         (select ac.personid from expunge.intakeservicerequestactor_expunge isra join expunge.actor_expunge ac on ac.actorid = isra.actorid where isra.intakeservicerequestactorid = isrco.intakeservicerequestactorid),
         (select case when inch.activeflag = 1 then true else false end as isactivehearing)                                                                                                                                                                                                                                                                                                                                                                   
 FROM intakeservreqcourtorder isrco                                                                                                                                                                                                                                                                                                                                                    
 LEFT JOIN referencevalues ppt ON ppt.ref_key=isrco.hearingoutcometypekey AND ppt.activeflag=1
 left join intakeservicerequestcourthearing inch on inch.intakeservicerequestcourthearingid = isrco.intakeservicerequesthearingid                                                                                                                                                                                                                                                                                          
 left join referencevalues rtd on rtd.ref_key=isrco.childpermanencyplankey and rtd.referencetypeid=137 and rtd.activeflag=1                                                                                                                                                                                                                                                            
 WHERE isrco.activeflag=1 AND isrco.intakeserviceid=v_intakeserviceid; 
ELSEIF isExpungementSuperUser = 1 AND v_isexpunged = 2 THEN 
-- partially expunged 
RETURN query  
SELECT                                                                                                                                                                                                                                                                                                                                                                                
         isrco.intakeservreqcourtorderid,isrco.intakeservicerequestactorid,isrco.intakeservicerequestpetitionid,isrco.intakeservicerequesthearingid , isrco.courtorderdate,isrco.remarks,isrco.removalid as removalepisode, ppt.ref_key AS hearingoutcometypekey,                                                                                                                                                                                                                                 
         ppt.description AS hearingoutcomedesc,isrco.childpermanencyplankey,rtd.description as childpermanencyplantype,
          isrco.dob, isrco.county,isrco.clientname,isrco.personsappeared,isrco.courtreview,isrco.childsneed,isrco.childneedcantmet,isrco.childpermanencyplan,isrco.childmosteffplan,isrco.qrtpapproval,isrco.qrtpapprovaldecision,isrco.judgedate, isrco.judgename,isrco.judgeid,isrco.otherpersonsappeared,                                                                                                                                                                                                                                                                
         (                                                                                                                                                                                                                                                                                                                                                                             
                                         SELECT                                                                                                                                                                                                                                                                                                                                        
                                                 json_agg(outcome) AS hearingoutcome                                                                                                                                                                                                                                                                                                   
                                         FROM                                                                                                                                                                                                                                                                                                                                          
                                         (                                                                                                                                                                                                                                                                                                                                             
                                                 SELECT                                                                                                                                                                                                                                                                                                                                
                                                         isrhoc.hearingoutcometypekey,rvs.description AS hearingoutcomedesc                                                                                                                                                                                                                                                            
                                                 FROM Intakeservreqcohearingoutcome isrhoc                                                                                                                                                                                                                                                                                             
                                                 INNER JOIN referencevalues rvs ON rvs.ref_key=isrhoc.hearingoutcometypekey AND rvs.activeflag=1                                                                                                                                                                                                                                       
                                                 WHERE isrhoc.intakeservreqcourtorderid=isrco.intakeservreqcourtorderid AND isrhoc.activeflag=1                                                                                                                                                                                                                                        
                                         ) outcome                                                                                                                                                                                                                                                                                                                                     
                                 ),                                                                                                                                                                                                                                                                                                                                                    
         (                                                                                                                                                                                                                                                                                                                                                                             
                SELECT                                                                                                                                                                                                                                                                                                                                        
                        json_agg(doc) AS attachments                                                                                                                                                                                                                                                                                                          
                FROM                                                                                                                                                                                                                                                                                                                                          
                (                                                                                                                                                                                                                                                                                                                                             
                SELECT  dp.filename, dp.title, dp.mime, dp.numberofbytes, dp.s3bucketpathname, dp.originalfilename, dp.actualdocumentdate, dp.documentpropertiesid, dp.other,                                                                                                                                                                                                                               
                        (select up.fullname as insertedby from userprofile up where up.securityusersid = dp.insertedby), dp.updatedon, dp.uploadstatus, dp.finalstatus, dp.ecmsdocumentid                                                                                                                                                                                                                              
                from documentproperties dp where dp.objectid = isrco.intakeservreqcourtorderid and dp.activeflag in (1,3,4,5)                                                                                                                                                                                                                                              
                ) doc                                                                                                                                                                                                                                                                                                                                         
        ),                                                                                                                                                                                                                                                                                                                                                    
         (                                                                                                                                                                                                                                                                                                                                                                             
                 SELECT                                                                                                                                                                                                                                                                                                                                                                
                         json_agg(e) AS courtdetails FROM                                                                                                                                                                                                                                                                                                                              
                 (                                                                                                                                                                                                                                                                                                                                                                     
                         SELECT                                                                                                                                                                                                                                                                                                                                                        
                                 isrcod.intakeservreqcourtorderdetailsid,isrcod.checklistid,isrcod.checklisttypekey,isrcod.isselected,isrcod.remarks,                                                                                                                                                                                                                                  
                                 (                                                                                                                                                                                                                                                                                                                                                     
                                         SELECT                                                                                                                                                                                                                                                                                                                                        
                                                 json_agg(x) AS courtlanguage                                                                                                                                                                                                                                                                                                          
                                         FROM                                                                                                                                                                                                                                                                                                                                          
                                         (                                                                                                                                                                                                                                                                                                                                             
                                                 SELECT                                                                                                                                                                                                                                                                                                                                
                                                         cl.checklistname,cl.description AS checklistdesc                                                                                                                                                                                                                                                                              
                                                 FROM checklist cl                                                                                                                                                                                                                                                                                                                     
                                                 INNER JOIN referencevalues rvs ON rvs.ref_key=isrcod.checklisttypekey AND rvs.activeflag=1                                                                                                                                                                                                                                            
                                                 WHERE isrcod.intakeservreqcourtorderid=isrco.intakeservreqcourtorderid AND isrcod.activeflag=1 AND rvs.ref_key='COLANG'                                                                                                                                                                                                               
                                         )  x                                                                                                                                                                                                                                                                                                                                          
                                 ),                                                                                                                                                                                                                                                                                                                                                    
                                 (                                                                                                                                                                                                                                                                                                                                                     
                                         SELECT                                                                                                                                                                                                                                                                                                                                        
                                                 json_agg(y) AS courtpermanencyplan                                                                                                                                                                                                                                                                                                    
                                         FROM                                                                                                                                                                                                                                                                                                                                          
                                         (                                                                                                                                                                                                                                                                                                                                             
                                                 SELECT                                                                                                                                                                                                                                                                                                                                
                                                         cl.checklistname,cl.description AS checklistdesc                                                                                                                                                                                                                                                                              
                                                 FROM checklist cl                                                                                                                                                                                                                                                                                                                     
                                                 INNER JOIN referencevalues rvs ON rvs.ref_key=isrcod.checklisttypekey AND rvs.activeflag=1                                                                                                                                                                                                                                            
                                                 WHERE isrcod.intakeservreqcourtorderid=isrco.intakeservreqcourtorderid AND isrcod.activeflag=1 AND rvs.ref_key='COPP'                                                                                                                                                                                                                 
                                         ) y                                                                                                                                                                                                                                                                                                                                           
                                 ),                                                                                                                                                                                                                                                                                                                                                    
                                 (                                                                                                                                                                                                                                                                                                                                                     
                                         SELECT                                                                                                                                                                                                                                                                                                                                        
                                                 json_agg(z) AS courthearingoutcome                                                                                                                                                                                                                                                                                                    
                                         FROM                                                                                                                                                                                                                                                                                                                                          
                                         (                                                                                                                                                                                                                                                                                                                                             
                                                 SELECT                                                                                                                                                                                                                                                                                                                                
                                                         cl.checklistname,cl.description AS checklistdesc                                                                                                                                                                                                                                                                              
                                                 FROM checklist cl                                                                                                                                                                                                                                                                                                                     
                                                 INNER JOIN referencevalues rvs ON rvs.ref_key=isrcod.checklisttypekey AND rvs.activeflag=1                                                                                                                                                                                                                                            
                                                 WHERE isrcod.intakeservreqcourtorderid=isrco.intakeservreqcourtorderid AND isrcod.activeflag=1 AND rvs.ref_key='COHO'                                                                                                                                                                                                                 
                                         ) z                                                                                                                                                                                                                                                                                                                                           
                                 )                                                                                                                                                                                                                                                                                                                                                     
                         FROM intakeservreqcourtorderdetails isrcod                                                                                                                                                                                                                                                                                                                    
                         WHERE isrcod.intakeservreqcourtorderid=isrco.intakeservreqcourtorderid AND isrcod.activeflag=1                                                                                                                                                                                                                                                                
                 )  e                                                                                                                                                                                                                                                                                                                                                                  
         ),
        (
                SELECT ac.personid
                FROM expunge.intakeservicerequestactor_expunge isra
                JOIN expunge.actor_expunge ac ON ac.actorid = isra.actorid
                WHERE isra.intakeservicerequestactorid = isrco.intakeservicerequestactorid
                UNION ALL
                SELECT ac.personid
                FROM intakeservicerequestactor isra
                JOIN actor ac ON ac.actorid = isra.actorid
                WHERE isra.intakeservicerequestactorid = isrco.intakeservicerequestactorid
        ),
         (select case when inch.activeflag = 1 then true else false end as isactivehearing)                                                                                                                                                                                                                                                                                                                                                                   
 FROM intakeservreqcourtorder isrco                                                                                                                                                                                                                                                                                                                                                    
 LEFT JOIN referencevalues ppt ON ppt.ref_key=isrco.hearingoutcometypekey AND ppt.activeflag=1
 left join intakeservicerequestcourthearing inch on inch.intakeservicerequestcourthearingid = isrco.intakeservicerequesthearingid                                                                                                                                                                                                                                                                                          
 left join referencevalues rtd on rtd.ref_key=isrco.childpermanencyplankey and rtd.referencetypeid=137 and rtd.activeflag=1                                                                                                                                                                                                                                                            
 WHERE isrco.activeflag=1 AND isrco.intakeserviceid=v_intakeserviceid;  
ELSE 
-- original query
RETURN query  
SELECT                                                                                                                                                                                                                                                                                                                                                                                
         isrco.intakeservreqcourtorderid,isrco.intakeservicerequestactorid,isrco.intakeservicerequestpetitionid,isrco.intakeservicerequesthearingid , isrco.courtorderdate,isrco.remarks,isrco.removalid as removalepisode, ppt.ref_key AS hearingoutcometypekey,                                                                                                                                                                                                                                 
         ppt.description AS hearingoutcomedesc,isrco.childpermanencyplankey,rtd.description as childpermanencyplantype,
          isrco.dob, isrco.county,isrco.clientname,isrco.personsappeared,isrco.courtreview,isrco.childsneed,isrco.childneedcantmet,isrco.childpermanencyplan,isrco.childmosteffplan,isrco.qrtpapproval,isrco.qrtpapprovaldecision,isrco.judgedate, isrco.judgename,isrco.judgeid,isrco.otherpersonsappeared,                                                                                                                                                                                                                                                                
         (                                                                                                                                                                                                                                                                                                                                                                             
                                         SELECT                                                                                                                                                                                                                                                                                                                                        
                                                 json_agg(outcome) AS hearingoutcome                                                                                                                                                                                                                                                                                                   
                                         FROM                                                                                                                                                                                                                                                                                                                                          
                                         (                                                                                                                                                                                                                                                                                                                                             
                                                 SELECT                                                                                                                                                                                                                                                                                                                                
                                                         isrhoc.hearingoutcometypekey,rvs.description AS hearingoutcomedesc                                                                                                                                                                                                                                                            
                                                 FROM Intakeservreqcohearingoutcome isrhoc                                                                                                                                                                                                                                                                                             
                                                 INNER JOIN referencevalues rvs ON rvs.ref_key=isrhoc.hearingoutcometypekey AND rvs.activeflag=1                                                                                                                                                                                                                                       
                                                 WHERE isrhoc.intakeservreqcourtorderid=isrco.intakeservreqcourtorderid AND isrhoc.activeflag=1                                                                                                                                                                                                                                        
                                         ) outcome                                                                                                                                                                                                                                                                                                                                     
                                 ),                                                                                                                                                                                                                                                                                                                                                    
         (                                                                                                                                                                                                                                                                                                                                                                             
                SELECT                                                                                                                                                                                                                                                                                                                                        
                        json_agg(doc) AS attachments                                                                                                                                                                                                                                                                                                          
                FROM                                                                                                                                                                                                                                                                                                                                          
                (                                                                                                                                                                                                                                                                                                                                             
                SELECT  dp.filename, dp.title, dp.mime, dp.numberofbytes, dp.s3bucketpathname, dp.originalfilename, dp.actualdocumentdate, dp.documentpropertiesid, dp.other,                                                                                                                                                                                                                               
                        (select up.fullname as insertedby from userprofile up where up.securityusersid = dp.insertedby), dp.updatedon, dp.uploadstatus, dp.finalstatus, dp.ecmsdocumentid                                                                                                                                                                                                                              
                from documentproperties dp where dp.objectid = isrco.intakeservreqcourtorderid and dp.activeflag in (1,3,4,5)                                                                                                                                                                                                                                              
                ) doc                                                                                                                                                                                                                                                                                                                                         
        ),                                                                                                                                                                                                                                                                                                                                                    
         (                                                                                                                                                                                                                                                                                                                                                                             
                 SELECT                                                                                                                                                                                                                                                                                                                                                                
                         json_agg(e) AS courtdetails FROM                                                                                                                                                                                                                                                                                                                              
                 (                                                                                                                                                                                                                                                                                                                                                                     
                         SELECT                                                                                                                                                                                                                                                                                                                                                        
                                 isrcod.intakeservreqcourtorderdetailsid,isrcod.checklistid,isrcod.checklisttypekey,isrcod.isselected,isrcod.remarks,                                                                                                                                                                                                                                  
                                 (                                                                                                                                                                                                                                                                                                                                                     
                                         SELECT                                                                                                                                                                                                                                                                                                                                        
                                                 json_agg(x) AS courtlanguage                                                                                                                                                                                                                                                                                                          
                                         FROM                                                                                                                                                                                                                                                                                                                                          
                                         (                                                                                                                                                                                                                                                                                                                                             
                                                 SELECT                                                                                                                                                                                                                                                                                                                                
                                                         cl.checklistname,cl.description AS checklistdesc                                                                                                                                                                                                                                                                              
                                                 FROM checklist cl                                                                                                                                                                                                                                                                                                                     
                                                 INNER JOIN referencevalues rvs ON rvs.ref_key=isrcod.checklisttypekey AND rvs.activeflag=1                                                                                                                                                                                                                                            
                                                 WHERE isrcod.intakeservreqcourtorderid=isrco.intakeservreqcourtorderid AND isrcod.activeflag=1 AND rvs.ref_key='COLANG'                                                                                                                                                                                                               
                                         )  x                                                                                                                                                                                                                                                                                                                                          
                                 ),                                                                                                                                                                                                                                                                                                                                                    
                                 (                                                                                                                                                                                                                                                                                                                                                     
                                         SELECT                                                                                                                                                                                                                                                                                                                                        
                                                 json_agg(y) AS courtpermanencyplan                                                                                                                                                                                                                                                                                                    
                                         FROM                                                                                                                                                                                                                                                                                                                                          
                                         (                                                                                                                                                                                                                                                                                                                                             
                                                 SELECT                                                                                                                                                                                                                                                                                                                                
                                                         cl.checklistname,cl.description AS checklistdesc                                                                                                                                                                                                                                                                              
                                                 FROM checklist cl                                                                                                                                                                                                                                                                                                                     
                                                 INNER JOIN referencevalues rvs ON rvs.ref_key=isrcod.checklisttypekey AND rvs.activeflag=1                                                                                                                                                                                                                                            
                                                 WHERE isrcod.intakeservreqcourtorderid=isrco.intakeservreqcourtorderid AND isrcod.activeflag=1 AND rvs.ref_key='COPP'                                                                                                                                                                                                                 
                                         ) y                                                                                                                                                                                                                                                                                                                                           
                                 ),                                                                                                                                                                                                                                                                                                                                                    
                                 (                                                                                                                                                                                                                                                                                                                                                     
                                         SELECT                                                                                                                                                                                                                                                                                                                                        
                                                 json_agg(z) AS courthearingoutcome                                                                                                                                                                                                                                                                                                    
                                         FROM                                                                                                                                                                                                                                                                                                                                          
                                         (                                                                                                                                                                                                                                                                                                                                             
                                                 SELECT                                                                                                                                                                                                                                                                                                                                
                                                         cl.checklistname,cl.description AS checklistdesc                                                                                                                                                                                                                                                                              
                                                 FROM checklist cl                                                                                                                                                                                                                                                                                                                     
                                                 INNER JOIN referencevalues rvs ON rvs.ref_key=isrcod.checklisttypekey AND rvs.activeflag=1                                                                                                                                                                                                                                            
                                                 WHERE isrcod.intakeservreqcourtorderid=isrco.intakeservreqcourtorderid AND isrcod.activeflag=1 AND rvs.ref_key='COHO'                                                                                                                                                                                                                 
                                         ) z                                                                                                                                                                                                                                                                                                                                           
                                 )                                                                                                                                                                                                                                                                                                                                                     
                         FROM intakeservreqcourtorderdetails isrcod                                                                                                                                                                                                                                                                                                                    
                         WHERE isrcod.intakeservreqcourtorderid=isrco.intakeservreqcourtorderid AND isrcod.activeflag=1                                                                                                                                                                                                                                                                
                 )  e                                                                                                                                                                                                                                                                                                                                                                  
         ),
         (select ac.personid from intakeservicerequestactor isra join actor ac on ac.actorid = isra.actorid where isra.intakeservicerequestactorid = isrco.intakeservicerequestactorid),
         (select case when inch.activeflag = 1 then true else false end as isactivehearing)                                                                                                                                                                                                                                                                                                                                                                        
 FROM intakeservreqcourtorder isrco                                                                                                                                                                                                                                                                                                                                                    
 LEFT JOIN referencevalues ppt ON ppt.ref_key=isrco.hearingoutcometypekey AND ppt.activeflag=1     
 left join intakeservicerequestcourthearing inch on inch.intakeservicerequestcourthearingid = isrco.intakeservicerequesthearingid                                                                                                                                                                                                                                                                                         
 left join referencevalues rtd on rtd.ref_key=isrco.childpermanencyplankey and rtd.referencetypeid=137 and rtd.activeflag=1                                                                                                                                                                                                                                                            
 WHERE isrco.activeflag=1 AND isrco.intakeserviceid=v_intakeserviceid;  
END IF;                                                                                                                                                                                                                                                                                                             
END;                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                       
 $function$
;
