 CREATE OR REPLACE FUNCTION public.getfiscalcategorylist(v_fiscal_category_id integer, v_lipagesize bigint, v_lipagenumber bigint, sortcolumn character varying, sortorder character varying)                                                                                                                                              
  RETURNS TABLE(totalcount bigint, fiscal_category_id integer, fiscal_category_cd character, fiscal_category_desc character varying, eligibility_cd character varying, eligibilitytype character varying, payment_type_cd character varying, ancillary_maintenance_sw character, paymenttype character varying, start_dt date, end_dt date)
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                         
 AS $function$                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                         
 DECLARE                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                         
         v_pagenumber int;                                                                                                                                                                                                                                                                                                               
         v_pageoffset int;                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                         
 BEGIN                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                         
 IF COALESCE(v_liPageSize, 0) < 1 THEN                                                                                                                                                                                                                                                                                                   
         v_liPageSize := 10;                                                                                                                                                                                                                                                                                                             
 END IF;                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                         
 IF COALESCE(v_liPageNumber, 0) < 1                                                                                                                                                                                                                                                                                                      
 THEN                                                                                                                                                                                                                                                                                                                                    
         v_liPageNumber := 1;                                                                                                                                                                                                                                                                                                            
 end if;                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                         
 v_pagenumber := v_liPageNumber - 1;                                                                                                                                                                                                                                                                                                     
 v_pageoffset := v_pagenumber * v_liPageSize;                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                         
 return query                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                         
 select count(1) over() as totalcount,tfc.fiscal_category_id,tfc.fiscal_category_cd,tfc.fiscal_category_desc,tfc.eligibility_cd,(select value_tx from tb_picklist_values where PICKLIST_type_id=446 AND delete_sw='N'                                                                                                                    
 AND active_sw='Y' AND TRIM(PICKLIST_VALUE_CD)=TRIM(tfc.eligibility_cd)) eligibilitytype,tfc.payment_type_cd,                                                                                                                                                                                                                            
 tfc.ancillary_maintenance_sw,(select value_tx from tb_picklist_values where PICKLIST_type_id=1 AND delete_sw='N'                                                                                                                                                                                                                        
 AND active_sw='Y' AND TRIM(PICKLIST_VALUE_CD)=TRIM(tfc.payment_type_cd)) as paymenttype,tfc.start_dt,tfc.end_dt from TB_FISCAL_CATEGORY_MASTER tfc                                                                                                                                                                                      
                  where tfc.delete_sw='N'                                                                                                                                                                                                                                                                                                
                  and                                                                                                                                                                                                                                                                                                                    
                  (v_fiscal_category_id is null or tfc.fiscal_category_id=v_fiscal_category_id)                                                                                                                                                                                                                                          
                 order by ( CASE sortorder when 'asc' then                                                                                                                                                                                                                                                                               
                 CASE sortcolumn                                                                                                                                                                                                                                                                                                         
                 when 'fiscal_category_desc' then                                                                                                                                                                                                                                                                                        
           cast( tfc.fiscal_category_desc as character varying)                                                                                                                                                                                                                                                                          
                 else null end end) asc,                                                                                                                                                                                                                                                                                                 
                 ( CASE sortorder when 'desc' then                                                                                                                                                                                                                                                                                       
                 CASE sortcolumn                                                                                                                                                                                                                                                                                                         
                 when 'fiscal_category_desc' then                                                                                                                                                                                                                                                                                        
           cast( tfc.fiscal_category_desc as character varying)                                                                                                                                                                                                                                                                          
                 else null end end) desc,tfc.create_ts desc nulls last                                                                                                                                                                                                                                                                   
 LIMIT v_liPageSize OFFSET v_pageoffset;                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                         
 END;                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                         
 $function$                                                                                                                                                                                                                                                                                                                                

