 CREATE OR REPLACE FUNCTION public.getmanageaccesslist(_filtertype character varying, _uuid character varying, _role_type character varying, _first_name character varying, _last_name character varying, _position_code character varying)
  RETURNS json                                                                                                                                                                                                                             
  LANGUAGE plpgsql                                                                                                                                                                                                                         
 AS $function$                                                                                                                                                                                                                           
 DECLARE result json;                                                                                                                                                                                                                    
 DECLARE uuidid uuid;                                                                                                                                                                                                                    
 DECLARE role_type character varying;                                                                                                                                                                                                    
 DECLARE first_name character varying;                                                                                                                                                                                                   
 DECLARE last_name character varying;                                                                                                                                                                                                    
 DECLARE position_code character varying;                                                                                                                                                                                                
 BEGIN                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                         
       IF _uuid = 'undefined' THEN                                                                                                                                                                                                       
            uuidid = null;                                                                                                                                                                                                               
       ELSE                                                                                                                                                                                                                              
            uuidid = CAST(_uuid AS UUID);                                                                                                                                                                                                
       END IF;                                                                                                                                                                                                                           
                                                                                                                                                                                                                                         
       IF _first_name = 'undefined' THEN                                                                                                                                                                                                 
            first_name = null;                                                                                                                                                                                                           
       ELSE                                                                                                                                                                                                                              
            first_name = _first_name;                                                                                                                                                                                                    
       END IF;                                                                                                                                                                                                                           
                                                                                                                                                                                                                                         
       IF _last_name = 'undefined' THEN                                                                                                                                                                                                  
           last_name = null;                                                                                                                                                                                                             
       ELSE                                                                                                                                                                                                                              
           last_name = _last_name;                                                                                                                                                                                                       
       END IF;                                                                                                                                                                                                                           
                                                                                                                                                                                                                                         
       IF _position_code = 'undefined' THEN                                                                                                                                                                                              
          position_code = null;                                                                                                                                                                                                          
       ELSE                                                                                                                                                                                                                              
          position_code = _position_code;                                                                                                                                                                                                
       END IF;                                                                                                                                                                                                                           
                                                                                                                                                                                                                                         
       IF _role_type = 'undefined' THEN                                                                                                                                                                                                  
          role_type = null;                                                                                                                                                                                                              
       ELSE                                                                                                                                                                                                                              
          role_type = _role_type;                                                                                                                                                                                                        
       END IF;                                                                                                                                                                                                                           
                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                         
      select array_to_json(array_agg(e)) from                                                                                                                                                                                            
       (SELECT array_to_json(array_agg(row_to_json(d))) as "data" from (                                                                                                                                                                 
       SELECT A.teammemberid,A.positioncode,A.roletypekey,A.displayname,COALESCE(D.activeflag,0) as activeflag FROM                                                                                                                      
       (SELECT A.teammemberid,A.roletypekey,C.displayname,A.positioncode,A.loadnumber FROM teammember A, teammemberassignment B, userprofile C                                                                                           
         WHERE A.teammemberid = B.teammemberid                                                                                                                                                                                           
           AND B.SecurityUsersId = C.SecurityUsersId  AND CASE WHEN first_name != null THEN C.firstname LIKE first_name || '%' ELSE TRUE END                                                                                             
           AND CASE WHEN last_name != null THEN  C.lastname  LIKE last_name || '%' ELSE TRUE END                                                                                                                                         
           AND CASE WHEN position_code != null THEN A.positioncode LIKE position_code || '%' ELSE TRUE END                                                                                                                               
         ) A                                                                                                                                                                                                                             
             LEFT OUTER JOIN accesslist D ON A.loadnumber = D.loadnumber                                                                                                                                                                 
             AND CASE WHEN uuidid != null THEN serviceRequestTypeConfigId = uuidid ELSE FALSE END                                                                                                                                        
             GROUP BY A.teammemberid,A.positioncode,A.roletypekey,A.displayname,D.activeflag                                                                                                                                             
             ORDER BY D.activeflag ASC,A.displayname ASC                                                                                                                                                                                 
                                                                                                                                                                                                                                         
             )d)e INTO result;                                                                                                                                                                                                           
                                                                                                                                                                                                                                         
 RETURN COALESCE(result,'[]');                                                                                                                                                                                                           
                                                                                                                                                                                                                                         
 END; $function$                                                                                                                                                                                                                           

