 CREATE OR REPLACE FUNCTION cjams.getmaltreatment_invsummary(v_investigationid uuid)                                                                                                                                          
  RETURNS json                                                                                                                                                                                                                 
  LANGUAGE plpgsql                                                                                                                                                                                                             
 AS $function$                                                                                                                                                                                                               
                                                                                                                                                                                                                             
 DECLARE                                                                                                                                                                                                                     
 l_maltreatment json;                                                                                                                                                                                                        
                                                                                                                                                                                                                             
 begin                                                                                                                                                                                                                       
                                                                                                                                                                                                                             
         SELECT Json_agg(a)                                                                                                                                                                                                  
                 INTO   l_maltreatment                                                                                                                                                                                       
                 FROM   (                                                                                                                                                                                                    
                   SELECT     IMA.intakeservicerequestactorid,                                                                                                                                                               
                              im.maltreatmentid,                                                                                                                                                                             
                              im.householdkey,                                                                                                                                                                               
                              im.isjurisdiction,                                                                                                                                                                             
                              im.countyid,                                                                                                                                                                                   
                              p.personid,                                                                                                                                                                                    
                              im.incidentlocationtypekey,                                                                                                                                                                    
                                          ILT.typename incidentlocation,                                                                                                                                                     
                              COALESCE(p.firstname,'')                                                                                                                                                                       
                                         ||' '                                                                                                                                                                               
                                         ||COALESCE(p.lastname,'') AS personname,                                                                                                                                            
                                                                 P.DOB,                                                                                                                                                      
                                                                 P.gendertypekey,                                                                                                                                            
                                                                 (SELECT coalesce(pa.address,'') ||' '                                                                                                                       
                                                 || coalesce(pa.address2,'')  ||' '                                                                                                                                          
                                                 || coalesce(pa.city,'') ||' '                                                                                                                                               
                                                 || coalesce(pa.zipcode,'')  address                                                                                                                                         
                                         FROM personaddress pa                                                                                                                                                               
                                         WHERE pa.personid = p.personid                                                                                                                                                      
                                         AND pa.activeflag =1                                                                                                                                                                
                                         AND pa.personaddresstypekey ='C' limit 1                                                                                                                                            
                                         ) address,                                                                                                                                                                          
                          (                                                                                                                                                                                                  
                                     SELECT Json_agg(a)                                                                                                                                                                      
                                     FROM   (                                                                                                                                                                                
                                                   SELECT ia.investigationallegationid,                                                                                                                                      
                                                          ia.maltreatmentid,                                                                                                                                                 
                                                          ia.allegationid,                                                                                                                                                   
                                                          ia.sextrafficking,                                                                                                                                                 
                                                          im.enddate,                                                                                                                                                        
                                                          im.isapproximatedate,                                                                                                                                              
                                                          im.timeofincidence,                                                                                                                                                
                                                          im.incidentlocationtypekey,                                                                                                                                        
                                                          al.NAME,                                                                                                                                                           
                                                          ia.indicators,                                                                                                                                                     
                                                          ia.comments,                                                                                                                                                       
                                                          ia.injurycomments,                                                                                                                                                 
                                                          ia.incidentdate,                                                                                                                                                   
                                                          ia.sextrafficking ,                                                                                                                                                
                                                                          (SELECT   IFT.description findingtype                                                                                                              
                                                                 FROM   investigationfinding IAF                                                                                                                             
                                                                        INNER JOIN investigationfindingtype IFT                                                                                                              
                                                                                ON IFT.investigationfindingtypekey =                                                                                                         
                                                                                   IAF.investigationfindingtypekey                                                                                                           
                                                                               AND IFT.activeflag = 1                                                                                                                        
                                                                                           WHERE IAF.ACTIVEFLAG =1                                                                                                           
                                                                                          -- AND IAF.investigationallegationactorid =ia.investigationallegationactorid                                                       
                                                                                                                   LIMIT 1       )   findings,                                                                               
                                                          (                                                                                                                                                                  
                                                                 SELECT Json_agg(ind)                                                                                                                                        
                                                                 FROM   (                                                                                                                                                    
                                                                                   SELECT     iai.intakeservicerequestactorid ,                                                                                              
                                                                                              (pr.lastname                                                                                                                   
                                                                                                         ||', '                                                                                                              
                                                                                                         || pr.firstname ) personname,                                                                                       
                                                                                                                         pr.dob, atp.typedescription as role,                                                                
                                                                                                                 (SELECT description                                                                                         
                                                                                                                                                                                                 FROM   actorrelationship AR 
                                                                                                 INNER JOIN relationshiptype rt                                                                                              
                                                                                                    ON rt.relationshiptypekey = ar.relationshiptypekey                                                                       
                                                                                                    AND rt.activeflag = 1                                                                                                    
                                                                                                 WHERE  ar.activeflag = 1                                                                                                    
                                                                                                 AND ar.intakeservicerequestactorid = iai.intakeservicerequestactorid limit 1)                                               
                                                                                                                   relationship                                                                                              
                                                                                   FROM       investigationallegationmaltreators IAI                                                                                         
                                                                                   INNER JOIN intakeservicerequestactor ISRA                                                                                                 
                                                                                   ON         isra.intakeservicerequestactorid= iai.intakeservicerequestactorid                                                              
                                                                                   AND        isra.activeflag =1                                                                                                             
                                                                                           INNER JOIN actortype atp ON atp.actortype = ISRA.intakeservicerequestpersontypekey                                                
                                                                                           AND           atp.activeflag =1                                                                                                   
                                                                                   INNER JOIN person pr                                                                                                                      
                                                                                   ON         pr.personid= isra.personid                                                                                                     
                                                                                   AND        pr.activeflag =1                                                                                                               
                                                                                   WHERE      iai.investigationallegationid = ia.investigationallegationid and iai.activeflag = 1 )ind )::json AS maltreators,                                       
                                                          (                                                                                                                                                                  
                                                                 SELECT json_agg(inj)                                                                                                                                        
                                                                 from   (                                                                                                                                                    
                                                                               select iaai.injurytypekey,                                                                                                                    
                                                                                   it.typedescription injury                                                                                                                 
                                                                               FROM   investigationallegationinjury iaai                                                                                                     
                                                                                   INNER JOIN INJURYtype it ON it.injurytypekey  = iaai.injurytypekey                                                                        
                                                                                   AND IT.activeflag =1                                                                                                                      
                                                                               WHERE  iaai.investigationallegationid = ia.investigationallegationid                                                                          
                                                                               AND    iaai.activeflag =1 ) inj )::json AS injurytype,                                                                                        
                                                          (                                                                                                                                                                  
                                                                 SELECT json_agg(characters)                                                                                                                                 
                                                                 FROM  (                                                                                                                                                     
                                                                               SELECT iamc.maltreatmentcharactersticstypekey,                                                                                                
                                                                                   mct.typedescription characterstics                                                                                                        
                                                                               FROM   investigationallegationcharacterstics iamc                                                                                             
                                                                                   INNER JOIN Maltreatmentcharactersticstype mct                                                                                             
                                                                                         ON mct.maltreatmentcharactersticstypekey  = iamc.maltreatmentcharactersticstypekey                                                  
                                                                                          AND mct.activeflag =1                                                                                                              
                                                                               WHERE  iamc.investigationallegationid = ia.investigationallegationid                                                                          
                                                                               AND    iamc.activeflag =1 )characters )::json AS maltreatmentcharactersticstypekey,                                                           
                                                          (                                                                                                                                                                  
                                                                 SELECT json_agg(injchar)                                                                                                                                    
                                                                 FROM   (                                                                                                                                                    
                                                                               SELECT iaic.injurycharactersticstypekey,                                                                                                      
                                                                                              mct.typedescription injurycharacterstics                                                                                       
                                                                               FROM   investigationallegationinjurycharacterstics iaic                                                                                       
                                                                                   INNER JOIN injurycharactersticstype mct                                                                                                   
                                                                                         ON mct.injurycharactersticstypekey  = iaic.injurycharactersticstypekey                                                              
                                                                                          AND mct.activeflag =1                                                                                                              
                                                                               WHERE  iaic.investigationallegationid = ia.investigationallegationid                                                                          
                                                                               AND    iaic.activeflag =1 )injchar )::json AS injurycharactersticstype                                                                        
                                                   FROM   investigationallegation ia                                                                                                                                         
                                                           INNER JOIN allegation al on al.allegationid= ia.allegationid                                                                                                      
                                                                         AND ia.activeflag =1                                                                                                                                
                                                   WHERE  ia.maltreatmentid = im.maltreatmentid                                                                                                                              
                                                   AND    ia.activeflag =1 ) a) AS investigationallegation                                                                                                                   
                   FROM       investigationmaltreatment im                                                                                                                                                                   
                   INNER JOIN Investigationmaltreatmentactor IMA on IMA.maltreatmentid = IM.maltreatmentid and IMA.activeflag =1                                                                                             
                   INNER JOIN intakeservicerequestactor ISRA on ISRA.intakeservicerequestactorid = IMA.intakeservicerequestactorid                                                                                           
                   LEFT JOIN incidentlocationtype ILT                                                                                                                                                                        
                   ON ILT.incidentlocationtypekey = im.incidentlocationtypekey                                                                                                                                               
                   and ILT.activeflag =1                                                                                                                                                                                     
                   INNER JOIN person p                                                                                                                                                                                       
                   ON         p.personid = ISRA.personid                                                                                                                                                                     
                   WHERE      im.investigationid = v_investigationid                                                                                                                                                         
                   AND        im.activeflag =1                                                                                                                                                                               
                   ) a;                                                                                                                                                                                                      
                                                                                                                                                                                                                             
   RETURN  l_maltreatment;                                                                                                                                                                                                   
                                                                                                                                                                                                                             
                                                                                                                                                                                                                             
  END;                                                                                                                                                                                                                       
                                                                                                                                                                                                                             
                                                                                                                                                                                                                             
 $function$                                                                                                                                                                                                                    

