 CREATE OR REPLACE FUNCTION public.getresources(in_limit integer, in_page integer, _permissiongroupid uuid)                                                                                                                             
  RETURNS TABLE(permissiongroupid uuid, permissiongroupname character varying, parentid uuid, parentname character varying, resourceid uuid, resourcename character varying, isvisible boolean, isenabled boolean, resourcetype integer)
  LANGUAGE plpgsql                                                                                                                                                                                                                      
 AS $function$                                                                                                                                                                                                                          
                                                                                                                                                                                                                                        
 BEGIN                                                                                                                                                                                                                                  
             in_page := (in_page-1)*   10;                                                                                                                                                                                              
                                                                                                                                                                                                                                        
     RETURN QUERY                                                                                                                                                                                                                       
                                                                                                                                                                                                                                        
                 select  Distinct pg.permissiongroupid, pg.permissiongroupname,r.parentid, r.parentname,r.id as resourceid,                                                                                                             
                 r.resourcename, pgr.isvisible, pgr.isenabled, r.resourcetype from pgresource pgr join (                                                                                                                                
                 select r2.resourcename as parentname, r1.* from resource r1 left join resource r2 on r1.parentid = r2.id                                                                                                               
                 and r1.activeflag = 1 and r2.activeflag = 1                                                                                                                                                                            
                 ) r on r.id = pgr.resourceid                                                                                                                                                                                           
                 join permissiongroup pg on pg.permissiongroupid = pgr.permissiongroupid                                                                                                                                                
                 where pgr.isallowed = true and pgr.activeflag = 1 and pg.activeflag = 1                                                                                                                                                
                 and pg.permissiongroupid = _permissiongroupid                                                                                                                                                                          
                 --order by pg.permissiongroupname                                                                                                                                                                                      
                 LIMIT in_limit OFFSET in_page;                                                                                                                                                                                         
   END;                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                        
 $function$                                                                                                                                                                                                                             

