 CREATE OR REPLACE FUNCTION public.getrstnccunoteslist(v_intakeserviceid uuid, pagenumber bigint, pagesize bigint)                                                                                                                                         
  RETURNS TABLE(totalcount bigint, restitutionccuconfigid uuid, restitutionno integer, ccuno integer, ccunotes text, status character varying, createdby character varying, insertedon timestamp without time zone, servicerequestnumber character varying)
  LANGUAGE plpgsql                                                                                                                                                                                                                                         
 AS $function$                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                         
 declare                                                                                                                                                                                                                                                 
 v_searchkey character varying ;                                                                                                                                                                                                                         
 v_pageoffset int;                                                                                                                                                                                                                                       
 v_pagenumber int;                                                                                                                                                                                                                                       
 declare searchstring character varying(5000);                                                                                                                                                                                                           
                                                                                                                                                                                                                                                         
 BEGIN                                                                                                                                                                                                                                                   
        v_pagenumber := pagenumber-1;                                                                                                                                                                                                                    
        v_pageoffset = v_pagenumber * pagesize;                                                                                                                                                                                                          
                                                                                                                                                                                                                                                         
     Return Query                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                         
         select count(1) over() totalcount, RCCUC.restitutionccuconfigid , RCCUC.restitutionno, RCCUC.ccuno, RCCUC.ccunotes, RCCUC.status, up.fullname as createdby, RCCUC.insertedon as createdon, ISR.servicerequestnumber                             
 from restitutionccuconfig as RCCUC                                                                                                                                                                                                                      
 join intakeserreqrestitution as ISRR                                                                                                                                                                                                                    
      on ISRR.restitutionno = RCCUC.restitutionno and ISRR.activeflag = 1                                                                                                                                                                                
 join intakeservicerequest as ISR                                                                                                                                                                                                                        
      on ISR.intakeserviceid = ISRR.intakeserviceid and ISR.activeflag = 1                                                                                                                                                                               
 join userprofile as UP                                                                                                                                                                                                                                  
      on UP.securityusersid = RCCUC.insertedby and UP.activeflag = 1                                                                                                                                                                                     
 where  ISR.intakeserviceid = v_intakeserviceid order by RCCUC.ccuno asc                                                                                                                                                                                 
 LIMIT pagesize OFFSET v_pageoffset;                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                         
   end;                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                         
 $function$                                                                                                                                                                                                                                                

