 CREATE OR REPLACE FUNCTION public.getrequesttypeconfigrolelist(_servicerequesttypeconfigid uuid, _activeflag integer, _entityroletype character varying)                                                               
  RETURNS json                                                                                                                                                                                                          
  LANGUAGE plpgsql                                                                                                                                                                                                      
 AS $function$                                                                                                                                                                                                          
 DECLARE result json;                                                                                                                                                                                                   
 DECLARE totalcount integer;                                                                                                                                                                                            
                                                                                                                                                                                                                        
 BEGIN                                                                                                                                                                                                                  
                                                                                                                                                                                                                        
 -- User Role                                                                                                                                                                                                           
         IF _entityroletype = 'UserRole' THEN                                                                                                                                                                           
                                                                                                                                                                                                                        
         select array_to_json(array_agg(e)) from                                                                                                                                                                        
         (SELECT array_to_json(array_agg(row_to_json(d))) as "data" from (                                                                                                                                              
         SELECT a.servicerequesttypeconfigroleid as id,a.entityroletypekey as name,b.description as description,a.activeflag as activeflag FROM servicerequesttypeconfigrole a,itemstable b                             
         WHERE a.entityroletypekey = b.name                                                                                                                                                                             
         AND a.servicerequesttypeconfigid = _servicerequesttypeconfigid                                                                                                                                                 
         AND a.activeflag = 1                                                                                                                                                                                           
         AND a.entityroletype = _entityroletype                                                                                                                                                                         
         AND b.itemtype = 0)d)e INTO result;                                                                                                                                                                            
                                                                                                                                                                                                                        
         END IF;                                                                                                                                                                                                        
                                                                                                                                                                                                                        
         IF _entityroletype = 'EntityRoleType' THEN -- EntityRoleType                                                                                                                                                   
                                                                                                                                                                                                                        
         select array_to_json(array_agg(e)) from                                                                                                                                                                        
         (SELECT array_to_json(array_agg(row_to_json(d))) as "data" from (                                                                                                                                              
            SELECT a.servicerequesttypeconfigroleid as id,a.entityroletypekey as name,b.typedescription as description,a.activeflag as activeflag FROM servicerequesttypeconfigrole a,agencyroletype b                  
            WHERE a.entityroletypekey = b.agencyroletypekey                                                                                                                                                             
            AND a.servicerequesttypeconfigid = _servicerequesttypeconfigid                                                                                                                                              
            AND a.activeflag = 1                                                                                                                                                                                        
            AND a.entityroletype = _entityroletype)d)e INTO result;                                                                                                                                                     
                                                                                                                                                                                                                        
         END IF;                                                                                                                                                                                                        
                                                                                                                                                                                                                        
         IF _entityroletype = 'DocumentType' THEN -- DocumentType                                                                                                                                                       
                                                                                                                                                                                                                        
        select array_to_json(array_agg(e)) from                                                                                                                                                                         
         (SELECT array_to_json(array_agg(row_to_json(d))) as "data" from (                                                                                                                                              
             SELECT a.servicerequesttypeconfigroleid as id,a.entityroletypekey as name,b.typedescription as description,a.activeflag as activeflag FROM servicerequesttypeconfigrole a,provideragreementdocumenttype b  
             WHERE a.entityroletypekey = b.provideragreementdocumenttypekey                                                                                                                                             
             AND a.servicerequesttypeconfigid = _servicerequesttypeconfigid                                                                                                                                             
             AND a.activeflag = 1                                                                                                                                                                                       
             AND a.entityroletype = _entityroletype)d)e INTO result;                                                                                                                                                    
                                                                                                                                                                                                                        
        END IF;                                                                                                                                                                                                         
                                                                                                                                                                                                                        
         IF _entityroletype = 'PersonRole' THEN -- PersonRole                                                                                                                                                           
                                                                                                                                                                                                                        
         --Get Count                                                                                                                                                                                                    
         SELECT count(*) into totalcount  FROM servicerequesttypeconfigrole a,actortype b                                                                                                                               
           WHERE a.entityroletypekey = b.actortype                                                                                                                                                                      
           AND a.servicerequesttypeconfigid = _servicerequesttypeconfigid                                                                                                                                               
           AND a.activeflag = 1                                                                                                                                                                                         
           AND a.entityroletype = 'PersonRole';                                                                                                                                                                         
                                                                                                                                                                                                                        
        select array_to_json(array_agg(e)) from                                                                                                                                                                         
         (SELECT array_to_json(array_agg(row_to_json(d))) as "data",totalcount as "count" from (                                                                                                                        
          SELECT a.servicerequesttypeconfigroleid as id,a.entityroletypekey as name,b.typedescription as description,a.activeflag as activeflag,                                                                        
          a.isdefault FROM servicerequesttypeconfigrole a,actortype b                                                                                                                                                   
           WHERE a.entityroletypekey = b.actortype                                                                                                                                                                      
           AND a.servicerequesttypeconfigid = _servicerequesttypeconfigid                                                                                                                                               
           AND a.activeflag = 1                                                                                                                                                                                         
           AND a.entityroletype = 'PersonRole')d)e INTO result;                                                                                                                                                         
                                                                                                                                                                                                                        
        END IF;                                                                                                                                                                                                         
                                                                                                                                                                                                                        
         IF _entityroletype = 'EntityRole' THEN  -- EntityRole                                                                                                                                                          
                                                                                                                                                                                                                        
     select array_to_json(array_agg(e)) from                                                                                                                                                                            
         (SELECT array_to_json(array_agg(row_to_json(d))) as "data" from (                                                                                                                                              
          SELECT a.servicerequesttypeconfigroleid as id,a.entityroletypekey as name,b.description as description,a.activeflag as activeflag FROM servicerequesttypeconfigrole a,agencycategory b                        
          WHERE a.entityroletypekey = b.agencycategorykey                                                                                                                                                               
          AND a.servicerequesttypeconfigid = _servicerequesttypeconfigid                                                                                                                                                
          AND a.activeflag = 1                                                                                                                                                                                          
          AND a.entityroletype = _entityroletype)d)e INTO result;                                                                                                                                                       
                                                                                                                                                                                                                        
        END IF;                                                                                                                                                                                                         
                                                                                                                                                                                                                        
 RETURN COALESCE(result,'[]');                                                                                                                                                                                          
                                                                                                                                                                                                                        
 END; $function$                                                                                                                                                                                                        

