 CREATE OR REPLACE FUNCTION public.getrestitutioncaseworker(i_intakeserviceid uuid, i_restitutionid uuid, pagenumber bigint, pagesize bigint)                                                                                                                                                                                                                                                                                               
  RETURNS TABLE(totalcount bigint, intakeserreqrestitutionid uuid, restitutionnumber integer, caseid uuid, intakenumber character varying, casenumber character varying, amount numeric, duedate date, sources character varying, relation character varying, frequency character varying, focusperson json, victim json, liableperson json, installmentamount numeric, initialpaymentdate date, courtdeferredduedate date, balance numeric)
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                                                                          
 AS $function$                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                          
 declare searchrestitutionid character varying;                                                                                                                                                                                                                                                                                                                                                                                           
 declare querytxt text;                                                                                                                                                                                                                                                                                                                                                                                                                   
 begin                                                                                                                                                                                                                                                                                                                                                                                                                                    
         --filter based on restitution id                                                                                                                                                                                                                                                                                                                                                                                                 
          if(I_restitutionid :: character varying != '' and I_restitutionid is not null)                                                                                                                                                                                                                                                                                                                                                  
         then                                                                                                                                                                                                                                                                                                                                                                                                                             
                 searchrestitutionid :=  ' AND inr.intakeserreqrestitutionid =  ''' || I_restitutionid || '''';                                                                                                                                                                                                                                                                                                                           
     else                                                                                                                                                                                                                                                                                                                                                                                                                                 
          searchrestitutionid := '';                                                                                                                                                                                                                                                                                                                                                                                                      
         end if;                                                                                                                                                                                                                                                                                                                                                                                                                          
         --get restitution details for case worker                                                                                                                                                                                                                                                                                                                                                                                        
                 querytxt =                                                                                                                                                                                                                                                                                                                                                                                                               
                  'select  count(1) over() totalcount, inr.intakeserreqrestitutionid, inr.restitutionno as restiutionnumber ,                                                                                                                                                                                                                                                                                                             
  inr.intakeserviceid as caseid,inr.intakenumber,ins.servicerequestnumber as casenumber,inr.payment as amount                                                                                                                                                                                                                                                                                                                             
  ,inr.duedate ,inr.restitutiontype  as sources , inr.liablepersonrelationtypekey as relation ,inr.frequency,                                                                                                                                                                                                                                                                                                                             
  (select row_to_json(x) from (select p.firstname,p.lastname,p.personid as pid,p.cjamspid from person p where p.personid=inr.youthpersonid limit 1) as x ) as focusperson,                                                                                                                                                                                                                                                                
  (select row_to_json(x) from (select p.firstname,p.lastname,p.personid as pid,p.cjamspid from person p where p.personid=inr.victimpersonid limit 1) as x ) as victim,                                                                                                                                                                                                                                                                    
  (select row_to_json(x) from (                                                                                                                                                                                                                                                                                                                                                                                                           
  select p.firstname,p.lastname,p.personid as pid,inri.liablepersonrelationtypekey as relationship,rst.description as relationshipdescription ,p.cjamspid                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                          
  from person p                                                                                                                                                                                                                                                                                                                                                                                                                           
  join intakeserreqrestitution inri on inri.liablepersonid=p.personid                                                                                                                                                                                                                                                                                                                                                                     
  join relationshiptype rst on rst.relationshiptypekey=inri.liablepersonrelationtypekey                                                                                                                                                                                                                                                                                                                                                   
  where p.personid=inr.liablepersonid  limit 1                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                          
  ) as x ) as liableperson,inr.installmentamount ,inr.paymentstartdate as initialpaymentdate,inr.courtdeferredduedate,--(inr.payment - coalesce(inr.paidamount,0)) as balance                                                                                                                                                                                                                                                             
  --(coalesce(inr.payment, 0) - coalesce(inr.waivedamount, 0) + coalesce(inr.additionalamount, 0)) - coalesce(inr.paidamount, 0) as balance                                                                                                                                                                                                                                                                                               
 (coalesce(inr.payment, 0)) - coalesce(inr.paidamount, 0) as balance                                                                                                                                                                                                                                                                                                                                                                      
  from                                                                                                                                                                                                                                                                                                                                                                                                                                    
 (select restitutionno, max(insertedon) insertedon from intakeserreqrestitution where activeflag = 1 group by restitutionno) res                                                                                                                                                                                                                                                                                                          
 JOin intakeserreqrestitution inr on inr.restitutionno = res.restitutionno and inr.insertedon = res.insertedon                                                                                                                                                                                                                                                                                                                            
  left join intakeserreqrestitutionpayment inrp on inrp.intakeserreqrestitutionid=inr.intakeserreqrestitutionid and inrp.activeflag=1                                                                                                                                                                                                                                                                                                     
  left join intakeservicerequest ins on ins.intakeserviceid=inr.intakeserviceid                                                                                                                                                                                                                                                                                                                                                           
  where inr.intakeserviceid='''||I_intakeserviceid||''' and inr.activeflag=1 --and inr.status != ''Closed''                                                                                                                                                                                                                                                                                                                               
  '||searchrestitutionid||'                                                                                                                                                                                                                                                                                                                                                                                                               
  order by inr.insertedon desc limit ' ||pagesize||' offset '|| pagenumber ;                                                                                                                                                                                                                                                                                                                                                              
                 return query execute querytxt;                                                                                                                                                                                                                                                                                                                                                                                           
                 end;                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                          
 $function$                                                                                                                                                                                                                                                                                                                                                                                                                                 

