export class UirDetail {
    uir_no:string;
    is_draft: boolean;
    inserted_on: string;
    updated_on: string;
    updated_by: string;
    inserted_by: string;
    created_on: string | Date;
    created_by: string;
    created_by_name: string;
    status: string;
	displayname: string;
	provider_id: number;
	provider_uir_id: string;
	class1_typekey: any [];
	class2_typekey: any [];
	class3_typekey: any[];
	licence_type: string;
	level_supervision: string;
	location_incident: string;
	location_area: string;
	location_area_other: string;
	discovered_datetime: string | Date;
	incident_datetime: string | Date;
	narrative_before_incident: string;
	narrative_incident_occur: string;
	narrative_during_incident: string;
	narrative_after_incident: string;
	role_incident: number;
	restraint_typekey: string;
	duration_restraint: number;
	duration_restraint_other: string;
	is_de_escalation: number;
	is_seen_medical: number;
	is_injury_sustained: number;
	is_staff_assaulted: number;
	is_injury_result: number;
	injury_severity_rating: number;
	duration_seclusion: number;
	gang_related_explain: string;
	gang_incident_videotapped: string;
	gang_support_evidence: string;
	notification_comments: string;
	notifiy_attach_other: string;
	notifiy_is_attach: boolean;
	notifiy_signdatetime: string | Date;
	notifiy_staff_member: string;
	noticationinformation: any[];
}

export class Supervisory {
	supervisor_comments: string;
	supervisor_name: string;
	supervisor_signdate: string;
	is_section_filledout: boolean;
	is_supervisor_comments: boolean;
	is_youth_witness: boolean;
	is_notification: boolean;
	is_nurses_reports: boolean;
	is_signed_dates: boolean;
	is_check_spelling: boolean;
	is_comments_location: boolean;
	is_addition_support: boolean;
	is_incident_report: boolean;
	uir_no: string;
	provider_uir_id: string;
	provider_uir_supervisory_id: string;
	other_section_filledout:  string;
	other_supervisor_comments: string;
	other_youth_witness: string;
	other_notification: string;
	other_nurses_reports: string;
	other_signed_dates: string;
	other_check_spelling: string;
	other_comments_location: string;
	other_addition_support: string;
	other_incident_report: string;
	completed_by_name: string;
	completed_by_date: string;
}

export class YouthInvolved {
	duration_mechanical_restraint: number;
	duration_mechanical_restraint_other: string;
	duration_phiscial_restraint: number;
	duration_phiscial_restraint_other: string;
	duration_seclusion: string;
	injury_severity_rating: number;
	is_de_escalation: boolean;
	is_flexcuff: boolean;
	is_handcuff: boolean;
	is_handcuff_legiron: boolean;
	is_injury_result: boolean;
	is_injury_sustained: boolean;
	is_intervention: true;
	is_seclusion: number;
	is_seen_medical: number;
	is_staff_assaulted: boolean;
	is_leaving_supervision: boolean;
	is_protective_device: boolean;
	is_helmets: boolean;
	provider_uir_actor_detail_id: string;
	provider_uir_id: string;
	restraint_typekey: string;
	role_incident: number;
	uir_no: string;
	provider_staff_id: string;
	is_prevention: boolean;
	is_legiron: boolean;
}

export class Notification {
	notification_comments: string;
	notifiy_attach_other: string;
	notifiy_is_attach: boolean;
	notifiy_signdatetime: string | Date;
	notifiy_staff_member: string;
	notification: any[];
}
export class PersonSearchResponse {
    alias: string;
    personid: string;
    personroleid: string;
    personroletype: string;
    personrolesubtype: string;
    firstname: string;
    middlename: string;
    lastname: string;
    dob: Date;
    dangerlevel: string;
    ssn: string;
    dcn: string;
    primaryaddress: string;
    homephone: string;
    gendertypekey: string;
    loadnumber: string;
    teamname: string;
    source?: string;
    middleName?: string;
    gender?: string;
    city?: string;
    zipcode?: string;
    county?: string;
    priors: number;
    relationscount: number;
    relations: string;
    socialmediasource: string;
    suffix: string;
}