# This is a sample build configuration for Node JS.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.2

pipelines:
  branches:
    deploy:
      - step:
          script:
           - apt-get update
           - python --version
           - apt-get -y install python-dev
           - apt-get -y install python-pip
           - pip install awscli
           - pip install boto3==1.3.0
           - pip --help
           - tar czf cjams-api.tar.gz client/ deploy/ package-lock.json common/ process.yml definitions/ package.json server/ appspec.yml
           - python codedeploy.py