 CREATE OR REPLACE FUNCTION public.validateadoptionplan(v_intakeserviceid uuid)                                                                                                                                               
  RETURNS TABLE(statuscode integer, status_description character varying, messages text[])                                                                                                                                    
  LANGUAGE plpgsql                                                                                                                                                                                                            
 AS $function$                                                                                                                                                                                                              
                                                                                                                                                                                                                            
 DECLARE                                                                                                                                                                                                                    
 n_count int;                                                                                                                                                                                                               
 p_count int;                                                                                                                                                                                                               
 tpr_count int;                                                                                                                                                                                                             
 l_servicerequestnumber character varying;                                                                                                                                                                                  
 statuscode integer;                                                                                                                                                                                                        
 status_description character varying;                                                                                                                                                                                      
                                                                                                                                                                                                                            
 BEGIN                                                                                                                                                                                                                      
                                                                                                                                                                                                                            
         SELECT servicerequestnumber INTO l_servicerequestnumber FROM intakeservicerequest WHERE intakeserviceid = v_intakeserviceid;                                                                                       
                                                                                                                                                                                                                            
         SELECT                                                                                                                                                                                                             
                 count(1) INTO n_count                                                                                                                                                                                      
         FROM tb_placement pl                                                                                                                                                                                               
         INNER JOIN Tb_placement_providers pp ON pp.placement_id=pl.placement_id AND pp.service_id != 500                                                                                                                   
         WHERE pl.case_id:: character varying =l_servicerequestnumber AND pl.exit_dt IS NOT NULL;                                                                                                                           
                                                                                                                                                                                                                            
         SELECT                                                                                                                                                                                                             
                 count(1) INTO p_count                                                                                                                                                                                      
         FROM tb_placement pl                                                                                                                                                                                               
         INNER JOIN Tb_placement_providers pp ON pp.placement_id = pl.placement_id AND pp.service_id = 500                                                                                                                  
         WHERE  pl.case_id:: character varying =l_servicerequestnumber AND pl.entry_dt IS NOT null AND pl.exit_dt IS NULL ;                                                                                                 
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            
         SELECT                                                                                                                                                                                                             
                 count(1) INTO tpr_count                                                                                                                                                                                    
         FROM routing r                                                                                                                                                                                                     
         INNER JOIN Tprrecommendation tpr ON tpr.tprrecommendationid::character varying = r.objectid                                                                                                                        
         WHERE tpr.intakeserviceid = v_intakeserviceid AND r.eventcode = 'TPRR' AND r.routingstatustypeid = 16;                                                                                                             
                 n_count:= COALESCE(n_count,0);                                                                                                                                                                             
                 p_count:= COALESCE(p_count,0);                                                                                                                                                                             
                 tpr_count:= COALESCE(tpr_count,0);                                                                                                                                                                         
         IF (n_count >= 1 AND  p_count >= 1 AND tpr_count >= 1) THEN                                                                                                                                                        
                 statuscode:= 200;                                                                                                                                                                                          
                 status_description := 'Valid';                                                                                                                                                                             
     END IF;                                                                                                                                                                                                                
                                                                                                                                                                                                                            
         IF(((p_count <1 OR n_count < 1 )  AND tpr_count <1) ) THEN                                                                                                                                                         
                 statuscode:= 500;                                                                                                                                                                                          
                 status_description := 'Invalid';                                                                                                                                                                           
                 messages := ARRAY['The youth is not yet in a pre-adoptive resource home.','Must wait for a court order from the appeals hearing upholding the TPR decision prior to moving to an adoption planning case.'];
         ELSIF((p_count<1) OR (n_count <1)) THEN                                                                                                                                                                            
                 statuscode:= 500;                                                                                                                                                                                          
                 status_description := 'Invalid';                                                                                                                                                                           
                 messages := ARRAY['The youth is not yet in a pre-adoptive resource home.'];                                                                                                                                
     ELSIF(tpr_count <1) THEN                                                                                                                                                                                               
                 statuscode:= 500;                                                                                                                                                                                          
                 status_description := 'Invalid';                                                                                                                                                                           
                 messages := ARRAY['Must wait for a court order from the appeals hearing upholding the TPR decision prior to moving to an adoption planning case.'];                                                        
         END IF;                                                                                                                                                                                                            
                                                                                                                                                                                                                            
 RETURN  QUERY                                                                                                                                                                                                              
                                                                                                                                                                                                                            
 SELECT statuscode,status_description,messages;                                                                                                                                                                             
                                                                                                                                                                                                                            
 END;                                                                                                                                                                                                                       
                                                                                                                                                                                                                            
 $function$                                                                                                                                                                                                                   

