select * from cjams.addpgresourcebyresource('Medical Specialist', '[{"resourceid":"person.Health.behavioraldelete","resourcename":"behavioraldelete","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.disabilitysave","resourcename":"disabilitysave","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.medconditiondelete","resourcename":"medconditiondelete","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.reproductivedelete","resourcename":"reproductivedelete","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.mobilityadd","resourcename":"mobilityadd","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.reproductiveedit","resourcename":"reproductiveedit","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.involved.edit","resourcename":"edit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.medconditionadd","resourcename":"medconditionadd","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.sleepingadd","resourcename":"sleepingadd","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.involved.editassignment","resourcename":"editassignment","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.eliminationsave","resourcename":"eliminationsave","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.involved.placement","resourcename":"placement","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.involved.search","resourcename":"search","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.examinationadd","resourcename":"examinationadd","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.involved.program","resourcename":"program","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.examinationdelete","resourcename":"examinationdelete","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.examinationedit","resourcename":"examinationedit","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.familyhistoryadd","resourcename":"familyhistoryadd","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.familyhistoryedit","resourcename":"familyhistoryedit","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.familyhistorydelete","resourcename":"familyhistorydelete","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.feedingadd","resourcename":"feedingadd","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.feedingedit","resourcename":"feedingedit","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.feedingdelete","resourcename":"feedingdelete","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.hospitalizationadd","resourcename":"hospitalizationadd","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.hospitalizationdelete","resourcename":"hospitalizationdelete","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person","resourcename":"person","isallowed":true,"isenabled":null,"isvisible":null}, 
 {"resourceid":"person.person.Finance","resourcename":"Finance","isallowed":true,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.behavioraladd","resourcename":"behavioraladd","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.birthupdate","resourcename":"birthupdate","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.hospitalizationedit","resourcename":"hospitalizationedit","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.psychotropicadd","resourcename":"psychotropicadd","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.person.Education","resourcename":"Education","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.insuranceadd","resourcename":"insuranceadd","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.person.Employment","resourcename":"Employment","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.behavioraledit","resourcename":"behavioraledit","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.immunizationsave","resourcename":"immunizationsave","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.reproductiveadd","resourcename":"reproductiveadd","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.involved.delete","resourcename":"delete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.person.Health","resourcename":"Health","isallowed":true,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.birthsave","resourcename":"birthsave","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.insuranceedit","resourcename":"insuranceedit","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.provideradd","resourcename":"provideradd","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.involved.addassignment","resourcename":"addassignment","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.person.involved","resourcename":"involved","isallowed":true,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.insurancedelete","resourcename":"insurancedelete","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Education.delete","resourcename":"delete","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.medconditionedit","resourcename":"medconditionedit","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.involved.removal","resourcename":"removal","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.involved.addperson","resourcename":"addperson","isallowed":null,"isenabled":false,"isvisible":false}]'); 
select * from cjams.addpgresourcebyresource('Resource Specialist', '[{"resourceid":"person.Health.examinationadd","resourcename":"examinationadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.involved.program","resourcename":"program","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.examinationedit","resourcename":"examinationedit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.provideradd","resourcename":"provideradd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.feedingadd","resourcename":"feedingadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.involved.placement","resourcename":"placement","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.sleepingadd","resourcename":"sleepingadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.familyhistoryedit","resourcename":"familyhistoryedit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.examinationdelete","resourcename":"examinationdelete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.hospitalizationadd","resourcename":"hospitalizationadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.hospitalizationedit","resourcename":"hospitalizationedit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.insurancedelete","resourcename":"insurancedelete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.familyhistorydelete","resourcename":"familyhistorydelete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.immunizationsave","resourcename":"immunizationsave","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.hospitalizationdelete","resourcename":"hospitalizationdelete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.insuranceadd","resourcename":"insuranceadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.involved.editassignment","resourcename":"editassignment","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.familyhistoryadd","resourcename":"familyhistoryadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.feedingedit","resourcename":"feedingedit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person","resourcename":"person","isallowed":true,"isenabled":null,"isvisible":null}, 
 {"resourceid":"person.person.Health","resourcename":"Health","isallowed":true,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.involved.addperson","resourcename":"addperson","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.birthupdate","resourcename":"birthupdate","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.medconditionadd","resourcename":"medconditionadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.involved.removal","resourcename":"removal","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.person.Education","resourcename":"Education","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.behavioraldelete","resourcename":"behavioraldelete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.disabilitysave","resourcename":"disabilitysave","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.feedingdelete","resourcename":"feedingdelete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.reproductivedelete","resourcename":"reproductivedelete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.person.Employment","resourcename":"Employment","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.behavioraladd","resourcename":"behavioraladd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.involved.delete","resourcename":"delete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.medconditiondelete","resourcename":"medconditiondelete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.reproductiveadd","resourcename":"reproductiveadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.person.Finance","resourcename":"Finance","isallowed":true,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.involved.addassignment","resourcename":"addassignment","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.birthsave","resourcename":"birthsave","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.medconditionedit","resourcename":"medconditionedit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.psychotropicadd","resourcename":"psychotropicadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.person.involved","resourcename":"involved","isallowed":true,"isenabled":true,"isvisible":true}, 
 {"resourceid":"person.Health.behavioraledit","resourcename":"behavioraledit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.involved.edit","resourcename":"edit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.mobilityadd","resourcename":"mobilityadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.reproductiveedit","resourcename":"reproductiveedit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.eliminationsave","resourcename":"eliminationsave","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.insuranceedit","resourcename":"insuranceedit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.involved.search","resourcename":"search","isallowed":null,"isenabled":false,"isvisible":false}]'); 
select * from cjams.addpgresourcebyresource('IV-E Eligibility Administrator', '[{"resourceid":"IV-E Eligibility Administrator","resourcename":"IV-E Eligibility Administrator","isallowed":true,"isenabled":null,"isvisible":null}]'); 
select * from cjams.addpgresourcebyresource('IV-E Eligibility Administrator Assistant', '[{"resourceid":"IV-E Eligibility Administrator Assistant","resourcename":"IV-E Eligibility Administrator Assistant","isallowed":true,"isenabled":null,"isvisible":null}]'); 
select * from cjams.addpgresourcebyresource('IV-E Eligibility Analyst', '[{"resourceid":"IV-E Eligibility Analyst","resourcename":"IV-E Eligibility Analyst","isallowed":true,"isenabled":null,"isvisible":null}]'); 
select * from cjams.addpgresourcebyresource('IV-E Eligibility Quality Assurance', '[{"resourceid":"Validation","resourcename":"Validation","isallowed":null,"isenabled":true,"isvisible":true}, 
 {"resourceid":"IV-E Eligibility Quality Assurance","resourcename":"IV-E Eligibility Quality Assurance","isallowed":true,"isenabled":null,"isvisible":null}]'); 
select * from cjams.addpgresourcebyresource('IV-E Liaison', '[{"resourceid":"IV-E Liaison","resourcename":"IV-E Liaison","isallowed":true,"isenabled":null,"isvisible":null}]'); 
select * from cjams.addpgresourcebyresource('Finance Ar Receivable', '[{"resourceid":"finance","resourcename":"Finance","isallowed":true,"isenabled":null,"isvisible":null}, 
 {"resourceid":"accountsreceivable","resourcename":"Accounts Receivable","isallowed":true,"isenabled":true,"isvisible":true}]'); 
select * from cjams.addpgresourcebyresource('Licensing Coordinator', '[{"resourceid":"accountsreceivable","resourcename":"Accounts Receivable","isallowed":true,"isenabled":null,"isvisible":true}, 
 {"resourceid":"providerchecklist","resourcename":"Financereferences -> Provider Checklist","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"maintenancesubsidypayment","resourcename":"Accountspayable -> Maintenance/Subsidy Payment","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"providercontractrate","resourcename":"Financereferences -> Provider Contract Rate","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"financeapproval","resourcename":"Finance Approval","isallowed":false,"isenabled":null,"isvisible":null}, 
 {"resourceid":"fostercarerate","resourcename":"Financereferences -> Foster Care Rate","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"approval","resourcename":"Accountspayable  -> Approval","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"accountspayable","resourcename":"Accounts Payable","isallowed":true,"isenabled":null,"isvisible":true}, 
 {"resourceid":"ancillarypayments","resourcename":"Accountspayable - >Ancillary Payments","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"history","resourcename":"Accountspayable  -> History","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"finance","resourcename":"Finance","isallowed":true,"isenabled":null,"isvisible":null}, 
 {"resourceid":"Licensing Coordinator","resourcename":"Licensing Coordinator","isallowed":true,"isenabled":null,"isvisible":null}, 
 {"resourceid":"financereferences","resourcename":"Finance References","isallowed":false,"isenabled":false,"isvisible":false}]'); 
select * from cjams.addpgresourcebyresource('QA Coordinator', '[{"resourceid":"finance","resourcename":"Finance","isallowed":true,"isenabled":null,"isvisible":null}, 
 {"resourceid":"accountsreceivable","resourcename":"Accounts Receivable","isallowed":true,"isenabled":null,"isvisible":true}, 
 {"resourceid":"financereferences","resourcename":"Finance References","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"maintenancesubsidypayment","resourcename":"Accountspayable -> Maintenance/Subsidy Payment","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"accountspayable","resourcename":"Accounts Payable","isallowed":true,"isenabled":null,"isvisible":true}, 
 {"resourceid":"approval","resourcename":"Accountspayable  -> Approval","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"history","resourcename":"Accountspayable  -> History","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"providercontractrate","resourcename":"Financereferences -> Provider Contract Rate","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"providerchecklist","resourcename":"Financereferences -> Provider Checklist","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"QA Coordinator","resourcename":"QA Coordinator","isallowed":true,"isenabled":null,"isvisible":null}, 
 {"resourceid":"fostercarerate","resourcename":"Financereferences -> Foster Care Rate","isallowed":false,"isenabled":false,"isvisible":false}, 
 {"resourceid":"ancillarypayments","resourcename":"Accountspayable - >Ancillary Payments","isallowed":false,"isenabled":false,"isvisible":false}]'); 
select * from cjams.addpgresourcebyresource('Placement Validation - PGNo Acess', '[{"resourceid":"Placement Validation","resourcename":"Placement Validation","isallowed":false,"isenabled":null,"isvisible":null}]'); 
select * from cjams.addpgresourcebyresource('Client Demographic search - PGRead', '[{"resourceid":"person.involved.search","resourcename":"search","isallowed":null,"isenabled":false,"isvisible":true}]'); 
select * from cjams.addpgresourcebyresource('Client Demographics-IVE-PGRead Excep', '[{"resourceid":"person.Employment.edit","resourcename":"edit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.psychotropicadd","resourcename":"psychotropicadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.reproductiveedit","resourcename":"reproductiveedit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.disabilitysave","resourcename":"disabilitysave","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.reproductivedelete","resourcename":"reproductivedelete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.sleepingadd","resourcename":"sleepingadd","isallowed":null,"isenabled":true,"isvisible":false}, 
 {"resourceid":"person.Education.edit","resourcename":"edit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.reproductiveadd","resourcename":"reproductiveadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.involved.editassignment","resourcename":"editassignment","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.eliminationsave","resourcename":"eliminationsave","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.examinationadd","resourcename":"examinationadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.examinationdelete","resourcename":"examinationdelete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.familyhistoryedit","resourcename":"familyhistoryedit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.feedingdelete","resourcename":"feedingdelete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.feedingedit","resourcename":"feedingedit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.hospitalizationadd","resourcename":"hospitalizationadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.hospitalizationdelete","resourcename":"hospitalizationdelete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.hospitalizationedit","resourcename":"hospitalizationedit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.immunizationsave","resourcename":"immunizationsave","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.insuranceadd","resourcename":"insuranceadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Education.add","resourcename":"add","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.behavioraldelete","resourcename":"behavioraldelete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.medconditionadd","resourcename":"medconditionadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.insurancedelete","resourcename":"insurancedelete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Employment.add","resourcename":"add","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.behavioraledit","resourcename":"behavioraledit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.familyhistorydelete","resourcename":"familyhistorydelete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.insuranceedit","resourcename":"insuranceedit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.involved.addassignment","resourcename":"addassignment","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.birthsave","resourcename":"birthsave","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.feedingadd","resourcename":"feedingadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.medconditiondelete","resourcename":"medconditiondelete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.involved.addperson","resourcename":"addperson","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.birthupdate","resourcename":"birthupdate","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.examinationedit","resourcename":"examinationedit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.medconditionedit","resourcename":"medconditionedit","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.behavioraladd","resourcename":"behavioraladd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Education.delete","resourcename":"delete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.familyhistoryadd","resourcename":"familyhistoryadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.mobilityadd","resourcename":"mobilityadd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Employment.delete","resourcename":"delete","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.Health.provideradd","resourcename":"provideradd","isallowed":null,"isenabled":false,"isvisible":false}, 
 {"resourceid":"person.involved.search","resourcename":"search","isallowed":null,"isenabled":false,"isvisible":false}]'); 
 select * from cjams.addpgresourcebyresource('Court_Order_FA','[{"resourceid":"Court_Order_FA","resourcename":"Court_Order_FA","isallowed":true,"isenabled":null,"isvisible":null}]');
update role_resource rr set rr.activeflag = 0 from role where role.id = rr.roleid and role.name in ('IV-E Eligibility Administrator', 'IV-E Eligibility Analyst', 'IV-E Eligibility Quality Assurance');




