select * from cjams.createnewuser('stg.bcsupervisor1@maryland.gov','Stg','BCSupervisor1',' ','Stg BCSupervisor1','CW','CJAMS_CWSUPERVISOR','1429','1429_42','Family Services #20','Baltimore City','3052 E. Biddle Street','Baltimore','21213','','bcsup1','1429','Supervisor,CW','','anthony.campbell@maryland.gov','sheritta.barr-stanley1@maryland.gov','add');
select * from cjams.createnewuser('stg.bcsupervisor1@maryland.gov','Stg','BCSupervisor1',' ','Stg BCSupervisor1','AS','CJAMS_ASSUPERVISOR','1429','1429_AS34','AS UNIT','Baltimore City','3053 E. Biddle Street','Baltimore','21213','','bcsup1','1429','Supervisor,AS','','anthony.campbell@maryland.gov','sheritta.barr-stanley1@maryland.gov','add');
select * from cjams.createnewuser('stg.bcsupervisor1@maryland.gov','Stg','BCSupervisor1',' ','Stg BCSupervisor1','LDSS','CJAMS_LDSS_SUPERVISOR','1429','1429_42','Family Services #20','Baltimore City','3054 E. Biddle Street','Baltimore','21213','','bcsup1','1429','Supervisor, LDSS','','anthony.campbell@maryland.gov','sheritta.barr-stanley1@maryland.gov','add');
select * from cjams.createnewuser('stg.bcsupervisor1@maryland.gov','Stg','BCSupervisor1',' ','Stg BCSupervisor1','OLM','CJAMS_OLM_PGM_MGR','1429','1429_42','Family Services #20','Baltimore City','3055 E. Biddle Street','Baltimore','21213','','bcsup1','1429','Program Manager, OLM','','anthony.campbell@maryland.gov','sheritta.barr-stanley1@maryland.gov','add');
select * from cjams.createnewuser('rafael.lopez@maryland.gov','Rafael','Lopez',' ','Rafael Lopez','CW','CJAMS_CWSUPERVISOR','1429','1429_42','Family Services #20','Baltimore City','3052 E. Biddle Street','Baltimore','21213','','rafaellopez','1429','Supervisor,CW','','anthony.campbell@maryland.gov','sheritta.barr-stanley1@maryland.gov','add');
select * from cjams.createnewuser('rafael.lopez@maryland.gov','Rafael','Lopez',' ','Rafael Lopez','AS','CJAMS_ASSUPERVISOR','1429','1429_AS34','AS UNIT','Baltimore City','3053 E. Biddle Street','Baltimore','21213','','rafaellopez','1429','Supervisor,AS','','anthony.campbell@maryland.gov','sheritta.barr-stanley1@maryland.gov','add');
select * from cjams.createnewuser('rafael.lopez@maryland.gov','Rafael','Lopez',' ','Rafael Lopez','LDSS','CJAMS_LDSS_SUPERVISOR','1429','1429_42','Family Services #20','Baltimore City','3054 E. Biddle Street','Baltimore','21213','','rafaellopez','1429','Supervisor, LDSS','','anthony.campbell@maryland.gov','sheritta.barr-stanley1@maryland.gov','add');
select * from cjams.createnewuser('rafael.lopez@maryland.gov','Rafael','Lopez',' ','Rafael Lopez','OLM','CJAMS_OLM_PGM_MGR','1429','1429_42','Family Services #20','Baltimore City','3055 E. Biddle Street','Baltimore','21213','','rafaellopez','1429','Program Manager, OLM','','anthony.campbell@maryland.gov','sheritta.barr-stanley1@maryland.gov','add');
select * from cjams.createnewuser('alger.studstill@maryland.gov','Alger','Studstill',' ','Alger Studstill','CW','CJAMS_CWSUPERVISOR','1429','1429_42','Family Services #20','Baltimore City','3056 E. Biddle Street','Baltimore','21213','','algersstill','1429','Supervisor,CW','','rafael.lopez@maryland.gov','rafael.lopez@maryland.gov','add');
select * from cjams.createnewuser('alger.studstill@maryland.gov','Alger','Studstill',' ','Alger Studstill','AS','CJAMS_ASSUPERVISOR','1429','1429_AS34','AS UNIT','Baltimore City','3057 E. Biddle Street','Baltimore','21213','','algersstill','1429','Supervisor,AS','','rafael.lopez@maryland.gov','rafael.lopez@maryland.gov','add');
select * from cjams.createnewuser('alger.studstill@maryland.gov','Alger','Studstill',' ','Alger Studstill','LDSS','CJAMS_LDSS_SUPERVISOR','1429','1429_42','Family Services #20','Baltimore City','3058 E. Biddle Street','Baltimore','21213','','algersstill','1429','Supervisor, LDSS','','rafael.lopez@maryland.gov','rafael.lopez@maryland.gov','add');
select * from cjams.createnewuser('alger.studstill@maryland.gov','Alger','Studstill',' ','Alger Studstill','OLM','CJAMS_OLM_PGM_MGR','1429','1429_42','Family Services #20','Baltimore City','3059 E. Biddle Street','Baltimore','21213','','algersstill','1429','Program Manager, OLM','','rafael.lopez@maryland.gov','rafael.lopez@maryland.gov','add');
select * from cjams.createnewuser('heather.zenone@maryland.gov','Heather','Zenone',' ','Heather Zenone','CW','CJAMS_CWSUPERVISOR','1429','1429_42','Family Services #20','Baltimore City','3060 E. Biddle Street','Baltimore','21213','','heatherzenone','1429','Supervisor,CW','','rafael.lopez@maryland.gov','rafael.lopez@maryland.gov','add');
select * from cjams.createnewuser('heather.zenone@maryland.gov','Heather','Zenone',' ','Heather Zenone','AS','CJAMS_ASSUPERVISOR','1429','1429_AS34','AS UNIT','Baltimore City','3061 E. Biddle Street','Baltimore','21213','','heatherzenone','1429','Supervisor,AS','','rafael.lopez@maryland.gov','rafael.lopez@maryland.gov','add');
select * from cjams.createnewuser('heather.zenone@maryland.gov','Heather','Zenone',' ','Heather Zenone','LDSS','CJAMS_LDSS_SUPERVISOR','1429','1429_42','Family Services #20','Baltimore City','3062 E. Biddle Street','Baltimore','21213','','heatherzenone','1429','Supervisor, LDSS','','rafael.lopez@maryland.gov','rafael.lopez@maryland.gov','add');
select * from cjams.createnewuser('heather.zenone@maryland.gov','Heather','Zenone',' ','Heather Zenone','OLM','CJAMS_OLM_PGM_MGR','1429','1429_42','Family Services #20','Baltimore City','3063 E. Biddle Street','Baltimore','21213','','heatherzenone','1429','Program Manager, OLM','','rafael.lopez@maryland.gov','rafael.lopez@maryland.gov','add');
select * from cjams.createnewuser('carnitra.white@maryland.gov','Carnitra','White',' ','Carnitra White','CW','CJAMS_CWSUPERVISOR','1429','1429_42','Family Services #20','Baltimore City','3064 E. Biddle Street','Baltimore','21213','','cwhite','1429','Supervisor,CW','','rafael.lopez@maryland.gov','rafael.lopez@maryland.gov','add');
select * from cjams.createnewuser('carnitra.white@maryland.gov','Carnitra','White',' ','Carnitra White','AS','CJAMS_ASSUPERVISOR','1429','1429_AS34','AS UNIT','Baltimore City','3065 E. Biddle Street','Baltimore','21213','','cwhite','1429','Supervisor,AS','','rafael.lopez@maryland.gov','rafael.lopez@maryland.gov','add');
select * from cjams.createnewuser('carnitra.white@maryland.gov','Carnitra','White',' ','Carnitra White','LDSS','CJAMS_LDSS_SUPERVISOR','1429','1429_42','Family Services #20','Baltimore City','3066 E. Biddle Street','Baltimore','21213','','cwhite','1429','Supervisor, LDSS','','rafael.lopez@maryland.gov','rafael.lopez@maryland.gov','add');
select * from cjams.createnewuser('carnitra.white@maryland.gov','Carnitra','White',' ','Carnitra White','OLM','CJAMS_OLM_PGM_MGR','1429','1429_42','Family Services #20','Baltimore City','3067 E. Biddle Street','Baltimore','21213','','cwhite','1429','Program Manager, OLM','','rafael.lopez@maryland.gov','rafael.lopez@maryland.gov','add');
update teammember
set roletypekey = 'CWSP'
where roletypekey <> 'CWSP'
and teammemberid in ( select tma.teammemberid 
    from userprofile a, teammemberassignment tma
    where a.securityusersid = tma.securityusersid and a.email in ('alger.studstill@maryland.gov', 'carnitra.white@maryland.gov', 'heather.zenone@maryland.gov', 'rafael.lopez@maryland.gov', 'stg.bcsupervisor1@maryland.gov') );
