 CREATE OR REPLACE FUNCTION cjams.otheragencyrouting(v_objectid character varying, v_securityuserid character varying, appeventcode character varying, v_routingstatusid integer, v_teamid uuid, v_fromrolekey character varying, v_torolekey character varying, commenttext text, v_notifymsg character varying DEFAULT ''::character varying, v_routeddescription character varying DEFAULT ''::character varying, v_intakeserviceid character varying DEFAULT ''::character varying, v_intakeserreqstatustypeid character varying DEFAULT ''::character varying, isservicecase integer DEFAULT 0)
  RETURNS text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
 AS $function$                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
 /* One Parameter added decision - intakeserreqstatustypeid  */                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
 DECLARE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 v_date timestamp without time zone;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
  v_servicerequestno character varying;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  v_tosecurityusersid character varying;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
  v_msg character varying;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  v_username character varying;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  v_returnstatus character varying;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  BEGIN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  v_date:= now();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
         IF (  COALESCE (isservicecase,0)=0  ) THEN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                 SELECT servicerequestnumber into v_servicerequestno FROM intakeservicerequest                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                 WHERE intakeserviceid :: character varying = v_intakeserviceid;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
         ELSE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                 SELECT servicecasenumber INTO v_servicerequestno FROM servicecase                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                 WHERE  servicecaseid :: character varying = v_intakeserviceid;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
         END IF;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
     raise notice 'v_servicerequestno%',v_servicerequestno;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
     SELECT tma.SecurityUsersId , COALESCE(up.firstname,'') || ' ' || COALESCE(up.lastname,'')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
     INTO v_tosecurityusersid, v_username                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
      FROM teammemberassignment tma                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                  INNER JOIN teammember tm                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                         ON tm.teammemberid = tma.teammemberid  AND tm.activeflag= 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                 INNER JOIN userprofile up                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                         ON up.securityusersid = tma.securityusersid AND up.activeflag= 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                 INNER JOIN routingcONfig rc                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                         ON rc.targetrolekey = tm.roletypekey   AND rc.activeflag= 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                         AND rc.sourcerolekey =v_fromrolekey                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                     AND rc.targetrolekey   =v_torolekey                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                 WHERE rc.eventcode =appeventcode AND tm.teamid =v_teamid                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                 AND tm.isdefaultroute  =1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                 AND tma.activeflag =1 limit 1;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
        IF ((COALESCE(v_fromrolekey,'') = 'CWSP') AND (COALESCE(v_torolekey,'') = 'IVESV') AND (v_routingstatusid = 16)) THEN
        /* ---------- Title4E code begins here ---------- */
        /* Cases should be assigned to IV-E Supervisor irrespective of teams */
        INSERT INTO routing(
            eventcode, fromsecurityusersid, tosecurityusersid, teamid, 
            FROMroleid, toroleid,objectid , routingstatustypeid,
            insertedby,  updatedby,insertedon,updatedon,  
            servicerequestnumber)
        VALUES( appeventcode, v_securityuserid, NULL, NULL,
                v_fromrolekey,  v_torolekey, v_objectid,v_routingstatusid,
                v_securityuserid,v_securityuserid, v_date,v_date, 
                v_servicerequestno); 
        v_returnstatus:='Success';
        -- TODO: Send notifications to all IV-E supervisors
        /* ---------- Title4E code ends here ---------- */
    ELSE
        IF COALESCE(v_tosecurityusersid,'') <>'' THEN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                INSERT INTO routing(
                        eventcode, fromsecurityusersid, tosecurityusersid, teamid,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                        FROMroleid, toroleid,objectid , routingstatustypeid,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                        insertedby,  updatedby,insertedon,updatedon,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                        servicerequestnumber)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                VALUES( appeventcode, v_securityuserid,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                        v_tosecurityusersid, v_teamid,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        v_fromrolekey,  v_torolekey,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                        v_objectid,v_routingstatusid,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                        v_securityuserid,v_securityuserid,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                        v_date,v_date, v_servicerequestno);

                v_msg:=  v_notifymsg || ' by '  ||   v_username;

                SELECT send_notIFication INTO v_returnstatus FROM send_notIFication(v_tosecurityusersid,
                                                v_securityuserid, v_tosecurityusersid,
                                                'System', 'High', v_msg,
                                                v_msg , v_objectid);
                v_returnstatus:='Success';
        ELSE
                v_returnstatus:='User not available for this role';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
        END IF;
    END IF;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
 RETURN  v_returnstatus::text;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 END  ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  $function$                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

