 CREATE OR REPLACE FUNCTION public.listservicestatus(userid character varying, page integer, pagelimit integer)                                                                                                                               
  RETURNS TABLE(intakenumber character varying, daterecieved timestamp without time zone, narrative text, insertedon timestamp without time zone, insertedby character varying, sstastatustypekey character varying, raname character varying)
  LANGUAGE plpgsql                                                                                                                                                                                                                            
 AS $function$                                                                                                                                                                                                                                
                                                                                                                                                                                                                                              
 DECLARE v_pageoffset int;                                                                                                                                                                                                                    
 v_pagenumber int;                                                                                                                                                                                                                            
 searchstring character varying;                                                                                                                                                                                                              
 DECLARE totalcount integer;                                                                                                                                                                                                                  
                                                                                                                                                                                                                                              
  BEGIN                                                                                                                                                                                                                                       
  v_pagenumber := (page-1)*   pagelimit;                                                                                                                                                                                                      
                                                                                                                                                                                                                                              
  RETURN QUERY                                                                                                                                                                                                                                
         select ids.intakenumber,ids.daterecieved,ids.narrative,ids.insertedon,ids.insertedby,ids.sstastatustypekey,ids.raname                                                                                                                
         from intakedastaging  ids where ids.insertedby = userid and ids.activeflag=1                                                                                                                                                         
         and ids.sstastatustypekey='Pending'                                                                                                                                                                                                  
         order by insertedon  desc  LIMIT pagelimit  OFFSET v_pagenumber;                                                                                                                                                                     
                                                                                                                                                                                                                                              
 END                                                                                                                                                                                                                                          
 $function$                                                                                                                                                                                                                                   

