import { SDMDescription } from './../_entities/newintakeModel';
const specifyothers = 'Other (specify)';
export const sdmData: SDMDescription = {
    malpa_suspeciousdeath: 'Suspicious death of a child due to abuse',
    malpa_nonaccident: 'Non-accidental physical injury',
    malpa_injuryinconsistent: 'Injury inconsistent with explanation',
    malpa_insjury: 'Injury that appears suspicious',
    malpa_childtoxic: 'Giving child toxic chemicals, alcohol, or drugs',
    malpa_caregiver: 'Caregiver action that likely caused injury',
    malsa_sexualmolestation: 'Sexual molestation of a child by an adult caregiver, family member, or household member',
    malsa_sexualact: 'Sexual act(s) among siblings or other children living in the home that is outsideofnormal',
    malsa_sexualexploitation: 'Sexual exploitation of a child by an adult caregiver, family member, or household member',
    malsa_physicalindicators: 'Physical, behavioral, or suspicious indicators consistent with sexual abuse',
    neggn_suspiciousdeath: 'Suspicious death of a child due to neglect',
    neggn_signsordiagnosis: 'Signs or diagnosis of non-organic failure to thrive',
    neggn_inadequatefood: 'Inadequate food/nutrition, or signs of malnutrition',
    neggn_exposuretounsafe: 'Exposure to unsafe conditions in the home',
    neggn_inadequateclothing: 'Inadequate clothing or hygiene',
    neggn_inadequatesupervision: 'Inadequate supervision',
    neggn_childdischarged: 'A child is being discharged from a facility and parents refuse to participate in planning for the child',
    // tslint:disable-next-line:max-line-length
    negfp_cargiverintervene: 'he caregiver does not intervene .despite knowledge (or reasonable expectation that the caregiver should have knowledge) that the child is being harmed (includes physical or sexual abuse, neglect, or mental injury) by another person',
    negab_abandoned: 'A child of any age has been abandoned',
    neguc_leftunsupervised: 'A child of any age who is physically, intellectually, or cognitively disabled is left unsupervised or with responsibilities beyond his or her capabilities',
    neguc_leftaloneinappropriatecare: 'A child under the age of  8 & has been left alone or in the care of an inappropriate caregiver',
    neguc_leftalonewithoutsupport: 'A child over the age of  8 & has been left alone without support systems for long periods of time or with responsibilities beyond his or her capabilities',
    negrh_priordeath: 'Prior death or serious injury of a child due to child abuse or neglect, and a new child is now in the Drug-exposed newborn',
    negrh_sexualperpetrator: 'Known sexual perpetrator has unsupervised or unrestricted access to child',
    negrh_basicneedsunmet: 'Child s basic needs are likely to be unmet due to caregiver impairment',
    negmn_unreasonabledelay: 'The unreasonable  delay, refusal, or failure on the part of the caregiver to seek, obtain, and/or maintain necessary medical, dental, or mental health care',
    // tslint:disable-next-line:max-line-length
    menab_psycologicalability: 'A child has an observable, identifiable, and substantial impairment of his/her mental or psychological ability to function as a result of an act of a pat:~nt,permanent or temporary caregiver, or household or family member.',
    // tslint:disable-next-line:max-line-length
    menng_psycologicalability: 'A child has an observable, identifiable, and substantial impairment of his/her mental or psychological ability to function as a result of failure to act by a parent, permanent or temporary caregiver, or household or family member',
    ScreenOUT: 'Screen out (no maltreatment type is marked)',
    Scrnin: 'Screen in (one or more maltreatment types are marked)',
    OvrScrnout: 'Screen out: One or more maltreatment types are marked, but referral will be screened out (mark all that apply)',
    isscrnoutrecovr_insufficient: 'Insufficient information to locate child/family',
    isscrnoutrecovr_information: 'Information forwarded to another jurisdiction',
    isscrnoutrecovr_historicalinformation: 'Historical information, victim is now an adult, and no children are in the care of alleged perpetrator',
    isscrnoutrecovr_otherspecify: specifyothers,
    Ovrscrnin: 'Screen in: No maltreatment type is marked, but referral will be opened and assigned for child protective services (CPS) investigation (mark all that apply)',
    isscrninrecovr_courtorder: 'Court order for an investigation',
    isscrninrecovr_otherspecify: specifyothers,
    isfinalscreenin: '',
    isfinalscreeninIn: 'Screen in: At least one maltreatment type or screen-in override is marked AND no screen-out overrides are marked. Complete Section 3, Response Time Decision',
    isfinalscreeninOut: 'Screen out: No maltreatment type is marked AND no screen-in overrides apply',
    isimmed_childfaatility: 'Child fatality or near fatality where abuse/neglect is suspected',
    isimmed_seriousinjury: 'Serious injury to child and other children remain in home',
    isimmed_childleftalone: 'Child left alone/abandoned and requires immediate care. Age of youngest child in years',
    isimmed_allegation: 'Allegation of child abuse or neglect in an out-of-home setting',
    isimmed_otherspecify: specifyothers,
    isnoimmed_physicalabuse: 'Physical abuse-response within 24 hours',
    isnoimmed_sexualabuse: 'Sexual abuse-response within 24 hours',
    isnoimmed_neglectresponse: 'Neglect-response within 5 days',
    isnoimmed_mentalinjury: 'Mental injury-response within 5 days D Screen-in Override',
    isImmediateYes: 'Immediate response required based on one or more criteria below',
    isImmediateNo: 'No immediate response criteria exist and allegations include the following'
};


