/*
  Issue Description: CDM-31376- Missing service case
  Root cause: Service case is not being populated 
   Pull request# for code fix: 
   Reason why no related code fix: 
   Status of the code fix if already submitted and expected prod fix date:  
   Backup before update/ delete:
*/

select * from cjams.createservicecase('c22f8a91-5762-4f9c-a604-5afab50cae18','',1,'1804702e-ca93-4850-b968-39fb243a44d6','ASSGN','CDM-31376');