drop index if exists IDX_ACCOUNT_FAST_ENTRY_fast_entry_id ;
CREATE INDEX IDX_ACCOUNT_FAST_ENTRY_fast_entry_id 
ON TB_ACCOUNT_FAST_ENTRY (fast_entry_id);

drop index if exists IDX_ACCOUNT_FAST_ENTRY_client_acc_id;
CREATE INDEX IDX_ACCOUNT_FAST_ENTRY_client_acc_id 
ON TB_ACCOUNT_FAST_ENTRY (client_account_id);

drop index if exists IDX_ACCOUNT_FAST_ENTRY_transaction_id;
CREATE INDEX IDX_ACCOUNT_FAST_ENTRY_transaction_id 
ON TB_ACCOUNT_FAST_ENTRY (transaction_id);

drop index if exists IDX_ACCOUNT_FAST_ENTRY_benefit_start_dt;
CREATE INDEX IDX_ACCOUNT_FAST_ENTRY_benefit_start_dt 
ON TB_ACCOUNT_FAST_ENTRY (benefit_start_dt);

drop index if exists IDX_comm_acct_trans_id;
CREATE INDEX IDX_comm_acct_trans_id
ON TB_COMM_ACCT_TRANSACTIONS (comm_acct_trans_id);

drop index if exists IDX_comm_acct_trans_comm_account_id;
CREATE INDEX IDX_comm_acct_trans_comm_account_id
ON TB_COMM_ACCT_TRANSACTIONS (comm_account_id);

drop index if exists IDX_COMMINGLED_ACCOUNT_ID;
CREATE INDEX IDX_COMMINGLED_ACCOUNT_ID
ON TB_COMMINGLED_ACCOUNT (comm_account_id);

drop index if exists IDX_CHILD_ACCOUNT_DISBURSEMENT_ID;
CREATE INDEX IDX_CHILD_ACCOUNT_DISBURSEMENT_ID
ON TB_CHILD_ACCOUNT_DISBURSEMENT (disbursement_id);

drop index if exists IDX_CHILD_ACCOUNT_DISBURSEMENT_client_id;
CREATE INDEX IDX_CHILD_ACCOUNT_DISBURSEMENT_client_id
ON TB_CHILD_ACCOUNT_DISBURSEMENT (client_id);

drop index if exists IDX_CHILD_ACCOUNT_DISBURSEMENT_payment_id;
CREATE INDEX IDX_CHILD_ACCOUNT_DISBURSEMENT_payment_id
ON TB_CHILD_ACCOUNT_DISBURSEMENT (payment_id);

drop index if exists IDX_CHILD_ACCOUNT_DISBURSEMENT_tax_id_no;
CREATE INDEX IDX_CHILD_ACCOUNT_DISBURSEMENT_tax_id_no
ON TB_CHILD_ACCOUNT_DISBURSEMENT (tax_id_no);

drop index if exists IDX_CHILD_ACCOUNT_DISBURSEMENT_client_account_id;
CREATE INDEX IDX_CHILD_ACCOUNT_DISBURSEMENT_client_account_id
ON TB_CHILD_ACCOUNT_DISBURSEMENT (client_account_id);

drop index if exists IDX_ACCOUNT_TRANSACTION_client_account_id;
CREATE INDEX IDX_ACCOUNT_TRANSACTION_client_account_id
ON TB_ACCOUNT_TRANSACTION (client_account_id);

drop index if exists IDX_ACCOUNT_TRANSACTION_ID;
CREATE INDEX IDX_ACCOUNT_TRANSACTION_ID
ON TB_ACCOUNT_TRANSACTION (transaction_id);

drop index if exists IDX_ACCOUNT_TRANSACTION_benefit_start_dt;
CREATE INDEX IDX_ACCOUNT_TRANSACTION_benefit_start_dt
ON TB_ACCOUNT_TRANSACTION (benefit_start_dt);

drop index if exists IDX_ACCOUNT_TRANSACTION_payment_detail_id;
CREATE INDEX IDX_ACCOUNT_TRANSACTION_payment_detail_id
ON TB_ACCOUNT_TRANSACTION (payment_detail_id);

drop index if exists IDX_ACCOUNT_TRANSACTION_authorization_id;
CREATE INDEX IDX_ACCOUNT_TRANSACTION_authorization_id
ON TB_ACCOUNT_TRANSACTION (authorization_id);

drop index if exists IDX_CLIENT_ACCOUNT_ID;
CREATE INDEX IDX_CLIENT_ACCOUNT_ID
ON TB_CLIENT_ACCOUNT (client_account_id);

drop index if exists IDX_batch_runtime_log_id;
CREATE INDEX IDX_batch_runtime_log_id
ON tb_batch_runtime_log (runtime_log_id);

drop index if exists IDX_CLIENT_ACCOUNT_ID;
CREATE INDEX IDX_CLIENT_ACCOUNT_ID
ON TB_CLIENT_ACCOUNT (client_account_id);

drop index if exists IDX_CLIENT_ACCOUNT_CLIENT_ID;
CREATE INDEX IDX_CLIENT_ACCOUNT_CLIENT_ID
ON TB_CLIENT_ACCOUNT (client_id);

drop index if exists IDX_CLIENT_ACCOUNT_CASE_ID;
CREATE INDEX IDX_CLIENT_ACCOUNT_CASE_ID
ON TB_CLIENT_ACCOUNT (case_id);

drop index if exists IDX_CLIENT_ACCOUNT_COMM_ACCOUNT_ID;
CREATE INDEX IDX_CLIENT_ACCOUNT_COMM_ACCOUNT_ID
ON TB_CLIENT_ACCOUNT (comm_account_id);

drop index if exists IDX_SERVICES_SERVICE_ID;
CREATE INDEX IDX_SERVICES_SERVICE_ID
ON TB_SERVICES (service_id);

drop index if exists IDX_AGENCYPROGRAMAREA_PROGRAMNAME;
CREATE INDEX IDX_AGENCYPROGRAMAREA_PROGRAMNAME
ON agencyprogramarea (programname);

drop index if exists IDX_PROGRAMCATEGORYLINK_FISCALCATEGORYID;
CREATE INDEX IDX_PROGRAMCATEGORYLINK_FISCALCATEGORYID
ON programcategorylink (fiscalcategoryid);

drop index if exists IDX_SERVICE_LOG_ID;
CREATE INDEX IDX_SERVICE_LOG_ID
ON TB_SERVICE_LOG (service_log_id);

drop index if exists IDX_SERVICE_LOG_CLIENT_ID;
CREATE INDEX IDX_SERVICE_LOG_CLIENT_ID
ON TB_SERVICE_LOG (client_id);

drop index if exists IDX_SERVICE_LOG_case_id;
CREATE INDEX IDX_SERVICE_LOG_case_id
ON TB_SERVICE_LOG (case_id);

drop index if exists IDX_SERVICE_LOG_PROVIDER_SERVICE_ID;
CREATE INDEX IDX_SERVICE_LOG_PROVIDER_SERVICE_ID
ON TB_SERVICE_LOG (provider_service_id);

drop index if exists IDX_SERVICE_PURCHASE_AUTHORIZATION_AUTHORIZATION_ID;
CREATE INDEX IDX_SERVICE_PURCHASE_AUTHORIZATION_AUTHORIZATION_ID
ON TB_SERVICE_PURCHASE_AUTHORIZATION (authorization_id);

drop index if exists IDX_SERVICE_PURCHASE_AUTHORIZATION_SERVICE_LOG_ID;
CREATE INDEX IDX_SERVICE_PURCHASE_AUTHORIZATION_SERVICE_LOG_ID
ON TB_SERVICE_PURCHASE_AUTHORIZATION (service_log_id);

drop index if exists IDX_SERVICE_PURCHASE_AUTHORIZATION_FISCAL_CATEGORY_CD;
CREATE INDEX IDX_SERVICE_PURCHASE_AUTHORIZATION_FISCAL_CATEGORY_CD
ON TB_SERVICE_PURCHASE_AUTHORIZATION (fiscal_category_cd);

drop index if exists IDX_SLPA_SNAPSHOT_SLPA_SNAPSHOT_ID;
CREATE INDEX IDX_SLPA_SNAPSHOT_SLPA_SNAPSHOT_ID
ON TB_SLPA_SNAPSHOT (slpa_snapshot_id);

drop index if exists IDX_SLPA_SNAPSHOT_AUTHORIZATION_ID;
CREATE INDEX IDX_SLPA_SNAPSHOT_AUTHORIZATION_ID
ON TB_SLPA_SNAPSHOT (authorization_id);

drop index if exists IDX_SLPA_SNAPSHOT_SERVICE_LOG_ID;
CREATE INDEX IDX_SLPA_SNAPSHOT_SERVICE_LOG_ID
ON TB_SLPA_SNAPSHOT (service_log_id);

drop index if exists IDX_SLPA_SNAPSHOT_PROVIDER_ID;
CREATE INDEX IDX_SLPA_SNAPSHOT_PROVIDER_ID
ON TB_SLPA_SNAPSHOT (provider_id);

drop index if exists IDX_SLPA_SNAPSHOT_TAX_ID_NO;
CREATE INDEX IDX_SLPA_SNAPSHOT_TAX_ID_NO
ON TB_SLPA_SNAPSHOT (tax_id_no);

drop index if exists IDX_SLPA_SNAPSHOT_client_id;
CREATE INDEX IDX_SLPA_SNAPSHOT_client_id
ON TB_SLPA_SNAPSHOT (client_id);

drop index if exists IDX_SLPA_SNAPSHOT_case_id;
CREATE INDEX IDX_SLPA_SNAPSHOT_case_id
ON TB_SLPA_SNAPSHOT (case_id);