export class MyNewintakeConstants {
    public static Intake = {
        PersonsInvolved: {
            Health: {
                Health: 'health',
                Physician: 'health_physician',
                PhysicianFromIntake: 'intake_health_physician',
                Insurance: 'health_insurance'
            },
            Work: {
                Work: 'work',
                Employer: 'employer',
                CareerGoals: 'career_goals',
                EmployActivity: 'employ_activity'
            },
            Educational: 'education-profile'
        },
        timeleft: 'timeleft',
        ispreintake: 'ispreintake',
        agency: 'agency',
        intakenumber: 'intakenumber',
        selectedPurpose: 'selectedPurpose',
        purposeValue: 'purpose',
        preIntakeDisposition: 'preIntakeDisposition',
        createdCases: 'createdCases',
        disposition: 'disposition',
        addedPersons: 'addedPersons',
        evalFields: 'evalFields',
        intakeappointment: 'intakeappointment',
        preIntakeSupDicision: 'preIntakeSupDicision',
        communications: 'communications',
        generatedDocuments: 'generatedDocument',
        courtDetails: 'courtDetails',
        petitionDetails: 'petitionDetails',
        saoResponse: 'saoResponse',
        scheduledHearings: 'scheduledHearings',
        completedHearings: 'completedHearings',
        intakeModel: 'intakeModel',
        purposeID: 'purposeID',
        ChildProtection: 'ChildProtection',
        allegedOffenseType: 'allegation',
        waivedOffenseType: 'waived',
        ICJRequisitionDuetoWarrant: 'ICJ Receiving requisition due to warrant',
        ICJReceivingProbation: 'ICJ Receiving Probation',
        ICJReentry: 'ICJ Receiving Re-Entry'
    };
    public static REFERRAL = {
        TRANSFER_FROM_ADULT: 'Transfer from Adult',
        INTERSTATE_COMPACT: 'Interstate Compact',
        EDUCATIONAL: 'Educational',
        WAIVER_FROM_ADUL_COURT: 'Waiver from Adult Court',
        LAW_ENFORCEMENT: 'Law Enforcement',
        ADULT_HOLD_DETENTION: 'Adult Hold',
        PEACE_ORDER: 'Peace order'
    };

    public static PURPOSE = {
        CHILD_PROTECTION_SERVICES : 'CHILD',
        INFORMATION_AND_REFERRAL: 'Information and Referral',
        REQUEST_FOR_SERVICES: 'Request for services',
        RISK_OF_HARM_INTAKE: 'ROH',
        ROA_CPS: 'ROACPS',
        KINSHIP_NAVIGATOR:'Kinship Navigator'       

    };
}

export enum IntakeStoreConstants {
    addNarrative = 'addNarrative',
    evalFields = 'evalFields',
    No_Jurisdiction = 'No_Jurisdiction',
    timeleft = 'timeleft',
    ispreintake = 'ispreintake',
    agency = 'agency',
    intakenumber = 'intakenumber',
    purposeSelected = 'purposeSelected',
    preIntakeDisposition = 'preIntakeDisposition',
    createdCases = 'createdCases',
    disposition = 'disposition',
    addedPersons = 'addedPersons',
    addedUnkPersons = 'addedUnkPersons',
    ADDED_IDENTIFIED_PERSONS = 'ADDED_IDENTIFIED_PERSONS',
    quickPersonsHistory= 'QUICK_PERSONS_HISTORY',
    PERSON_SEARCH_CASE = 'PERSON_SEARCH_CASE',
    PERSON_TO_SEARCH = 'PERSON_TO_SEARCH',
    intakeappointment = 'intakeappointment',
    preIntakeSupDicision = 'preIntakeSupDicision',
    communications = 'communications',
    generatedDocuments = 'generatedDocument',
    courtDetails = 'courtDetails',
    petitionDetails = 'petitionDetails',
    saoResponse = 'saoResponse',
    scheduledHearings = 'scheduledHearings',
    completedHearings = 'completedHearings',
    intakeModel = 'intakeModel',
    ChildProtection = 'ChildProtection',
    general = 'general',
    attachements = 'attachements',
    generatedDocumentDownloadKey = 'generatedDocumentDownloadKey',
    intakeSDM = 'intakeSDM',
    dispositionReadOnly = 'dispositionReadOnly',
    assessmentScore = 'assessmentScore',
    cpsDocument = 'cpsDocument',
    reviewstatus = 'reviewstatus',
    attachments = 'attachments',
    narrativeText = 'narrativeText',
    roacps = 'roacps',
    clearhistory = 'clearhistory',
    closeintakecw = 'closeintakecw',
    zipcode = 'zipcode',
    communicationFields = 'communicationFields',
    intakeService = 'intakeService',
    reviewStatus = 'reviewStatus',
    assingedIntakeWokerId = 'assingedIntakeWokerId',
    addedCrossReference = 'addedCrossReference',
    crossReferenceFromEvals = 'crossReferenceFromEvals',
    addedEntities = 'addedEntities',
    IntakeAction = 'IntakeAction',
    adultScreenTool = 'adultScreenTool',
    childfatality = 'childfatality',
    childfatalityUpdate = 'childfatalityUpdate',
    childfatalityPersonLevelUpdate = 'childfatalityPersonLevelUpdate',
    loadHTML = 'loadhtml',
    youthStatus = 'youthstatus',
    youthid = 'youthid',
    statusChanged = 'statuschanged',
    FocuspersonCaseDetails = 'focuspersoncasedetails',
    FocuspersonCaseDetailsFormValid = 'focuspersoncasedetailsformvalid',
    paymentSchedule = 'paymentSchedule',
    restiutionDocumentInfo = 'restiutionDocumentInfo',
    restitutionSearchParams = 'restitutionSearchParams',
    intakeServiceGrid = 'intakeServiceGrid',
    restitution = 'restitution',
    addedPlacement = 'addedPlacement',
    receivedDate = 'receivedDate',
    reasonintakeinterview = 'reasonintakeinterview',
    complaintInfoReview = 'complaintInfoReview',
    insufficientInfoNarrative = 'insufficientInfoNarrative',
    detentionOpened = 'detentionOpened',
    isUnknownReporter = 'isUnknownReporter',
    REFERALSOURCE = 'REFERALSOURCE',
    MDCASESEARCH = 'MDCASESEARCH',
    DPSCSSAFETY = 'DPSCSSAFETY',
    NOTES = 'NOTES',
    NAVIGATE_TO_PERSON = 'NAVIGATE_TO_PERSON',
    SELECT_PERSON_TAB_INTAKE = 'SELECT_PERSON_TAB_INTAKE',
    INTAKE_STATUS = 'INTAKE_STATUS',
    PRIVATE_ADOPTION = 'privateAdoption',
    INTAKE_IS_CLOSED = 'intakeIsClosed',
    ACCESS_STATUS = 'accessStatus',
    USER_COUNTY = 'USER_COUNTY',
    IS_DRAFT = 'IS_DRAFT',
    DATE_OF_BIRTH = 'selectedPersonDOB',
    SELECTED_INTAKE_CASE_DETAILS = 'selected_intake_case_details',
    INVOLVED_PERSON= 'Involved_Person',
    navigatetonarrative ='navigatetonarrative',
    addendumNarrative ='addendumNarrative',
    isaddendumnarrativeupdated ='isaddendumnarrativeupdated'
}
