/*
   Issue Description: CDM-32021
   Category/ Module  : 
   Root cause: user want to update service plan approved by
   Pull request# for code fix: 
   Reason why no related code fix: 
   Status of the code fix if already submitted and expected prod fix date: 
    . Need to do data fix
*/ 
update snapshothist set updatedby='ec693824-e034-4e25-bd4b-232e3d5f305a' where id='990a93e2-6661-4bf6-af66-6b13d8f145d2'
and objectid='90613376-f433-4d7a-a02b-cee04fa2b21f';