update snapshothist

set snapshotdata = '[
  {
    "caseworker": "Mellisa Moss",
    "versionList": [
      {
        "id": "7ab3158c-139d-4284-aaa4-810758a1f44e",
        "serviceplanid": "52a2130a-5132-4dc1-854b-116d049da44c"
      }
    ],
    "jurisdiction": "Baltimore",
    "assetsdetails": null,
    "fatherdetails": null,
    "headersection": {
      "dob": "2002-01-22T00:00:00",
      "cisid": "400162417",
      "mdm_id": "MDT-128169055",
      "enddate": null,
      "clientid": 4115127,
      "childname": "MIRACLE OLAWOYIN",
      "startdate": "2020-05-01T04:00:00"
    },
    "incomedetails": null,
    "motherdetails": null,
    "cplanquestions": {
      "dayCare": null,
      "iepDated": null,
      "parentName": "Abosede Adeyefa",
      "refMadeDate": null,
      "respiteCare": null,
      "otherReasons": null,
      "reimbursement": true,
      "tprDeniedDate": null,
      "blockEComments": "He is working towards his High School diploma. He does not enjoy school but is working daily to his goal. ",
      "healthPassport": true,
      "schoolSchedule": null,
      "tprGrantedDate": null,
      "transportation": null,
      "discussServices": "Michael communicates during monthly visits and via text message weekly with this writer on his needs for reimbursement, school and his future. He is improving in school an dwishes to try and visit his mother out of the country summer 2021 COVID-19 permitting. He is scheduling appointments with Ashley Craig at his placement for his health. He has his own insurance card. ",
      "faceToFaceVisit": null,
      "specialTraining": true,
      "tprPetitionDate": null,
      "writeOtherReson": null,
      "atOrNearAgeLevel": null,
      "diagnosedAxisOne": false,
      "diagnosedAxisTwo": false,
      "financialSupport": true,
      "lengthOfHomeless": "No",
      "outOfHomeService": "He is doing well in his ILP. He will continue to work on his goals of a diploma and then move toward savings and obtaining a car and drivers license. He recently got his permit 10/2020. ",
      "addressChildNeeds": "This writer meets with his team monthly for his schooling, and contact his team via email weekly. This writer meets with him and discusses his needs and submitted for reimbursement for drivers permit.",
      "diagnosedAxisFive": false,
      "diagnosedAxisFour": false,
      "episodeExperience": "No",
      "isChildCoComitted": "No, child remains in the care of the agency. ",
      "reasonTPRPetition": "He is turning 18 and his mother can not return to this country ",
      "diagnosedAxisThree": false,
      "childInAndOutOfHome": "Yes",
      "currentRelationship": "Michael has a positive relationship with his mother, aunt and grand mother. His mother is out of the country and he stays in contact via phone and video calls. ",
      "tprAppealDateFather": null,
      "tprAppealDateMother": null,
      "educationProgramGoal": "high school diploma",
      "servicesForStability": null,
      "discussVisitationPlan": "There is no plan since his mother is unable to return to this country. ",
      "explainChangeOfSchool": "N/A",
      "conditionsAndAllergies": "He has his own insurance card and no meds nor allergies at this time. ",
      "discussionOfVisitation": true,
      "episodesOfHomelessness": "No",
      "lastprogressreportdate": "2020-11-20T05:00:00.000Z",
      "parentChildInteraction": "He states to this writer he enjoys speaking to his mother and wishes to visit her in summer 2021 in her country. ",
      "placementChangedSchool": "No",
      "schoolProximityToPrior": "Yes, it is cirtual learning online for his 11-12th grade yea due to COVID-19",
      "childEnrolledInFiveDays": "Yes",
      "diagnosedAxisOneComment": "",
      "diagnosedAxisTwoComment": "",
      "discussionOfChildsNeeds": true,
      "problemsWithPeersBlockD": null,
      "problemsWithPeersBlockE": null,
      "sixMonthsPlacementExpln": null,
      "behavioralProblemsBlockD": null,
      "behavioralProblemsBlockE": null,
      "diagnosedAxisFiveComment": "",
      "diagnosedAxisFourComment": "",
      "emotionalSupportGuidance": true,
      "episodeExperienceExplain": "None ",
      "juvenileCourtInvolvement": "No",
      "schoolAdjustmentComments": "He has no behavioral issues with school and it is currently e-learning.",
      "servicecourtorderdetails": "He will remain in care of the agency.",
      "describeStrengthsAndNeeds": "His needs are beign met via the tutor and his assignments and attendance is improvinbg. ",
      "diagnosedAxisThreeComment": "",
      "extraCurricularActivities": "football",
      "physicalOrMentaldiagnosis": "He has no medical diagnosis and has an updated physical. ",
      "childCurrentReportCardCopy": "He has completed two previous courses and working towards two more. He also attends 12th grade courses. ",
      "faceToFaceVisitContactDate": null,
      "individualEducationProgram": null,
      "passportRecordConfirmation": "Annual exams are up to date pending a vision. ",
      "servicesForPermanencyOther": null,
      "specifyTheNeedsAndServices": null,
      "supportiveServicesRequired": "He will need to save money and seek where he will live. ",
      "faceToFaceVisitAuthoredDate": null,
      "passportRecordConfirmedDate": "2020-11-23T05:00:00.000Z",
      "tprAppealDecisionDateFather": null,
      "tprAppealDecisionDateMother": null,
      "utilizationOrNonUtilization": "He is in an ILP and works with Mr. Kevon for independent skill building. ",
      "visitationcourtorderdetails": "He has court again 01/11/2021.",
      "educationalServicesReceiving": "Tutoring services. ",
      "servicesForPermanencyClients": [
        "4115127"
      ],
      "voluntarySignatureDateFather": null,
      "voluntarySignatureDateMother": null,
      "educationalParentSurrogateName": null,
      "eighteenToTwentyOneChildStatus": "He is turning 18 and has a job in addition to school. ",
      "isChildEnrolledInSpecialProgram": "N/A",
      "educationalParentSurrogateAddress": null,
      "educationalParentSurrogateWeakness": "He does not enjoy e-learning due to COVID.",
      "educationalParentSurrogateRequested": null,
      "educationalParentSurrogateStrengths": "He is able to work with his tutor to complete assignments. ",
      "facilitatePermanencySelfSufficiency": "Michael is working with Kevon C. to complete life skills training. He is attending school and has a tutor Mrs. Ford unbtil he graduates in June. ",
      "discussChildCurrentEducationalSetting": "He is doing virtual learning and has a tutor Mr.s Ford. ",
      "facilitatePermanencySelfSufficiencyEndDate": "2021-06-23T04:00:00.000Z",
      "facilitatePermanencySelfSufficiencyStartDate": "2020-09-08T04:00:00.000Z"
    },
    "supportdetails": null,
    "childannualexam": null,
    "childinitialexam": null,
    "childremovaldate": "2017-11-13T00:00:00",
    "childfollowupexam": null,
    "servicecasenumber": "3279208",
    "childremovalreason": "(Abandonment)",
    "servicecourtdetails": null,
    "placementinformation": null,
    "assessmentinformation": null,
    "childdbehaviourhealth": null,
    "childlegalinformation": null,
    "visitationcourtdetails": null,
    "childtprlegalinformation": null,
    "caseworkerservicesandplan": {
      "establisheddate": "2020-02-24T00:00:00",
      "cuurentplacetolive": "Independent Living Residential Program",
      "permanancyplandata": null,
      "facetofacecontactdate": null,
      "primarypermanencytype": "APPLA",
      "treatmentteameetingdate": null,
      "concurrentpermanencytype": "APPLA"
    },
    "childeducationinformation": [
      {
        "end_dt": null,
        "sasidno": null,
        "setting": null,
        "tel_num": "2407402700",
        "start_dt": "09/03/2019",
        "school_nm": "Albert Einstein High School",
        "grade_last": "Grade 10",
        "mode_trans": null,
        "type_class": "High School",
        "edu_program": null,
        "exit_reason": null,
        "grade_current": "Grade 11",
        "fungrade_level": null,
        "school_address": "Albert Einstein High School,,Maryland",
        "special_ed_code": null,
        "quarterly_grade1": null,
        "quarterly_grade2": null,
        "quarterly_grade3": null,
        "quarterly_grade4": null
      }
    ],
    "childdisabilityinformation": null,
    "childemploymentinformation": [
      {
        "earnings": null,
        "employed": "Yes",
        "cur_employer": "Buffalo Wild Wings Restaurant ",
        "cur_employment": " days"
      }
    ],
    "childmedicationinformation": null
  }
]', updatedon = now(), updatedby = 'CDM-7292'
where id = '0d890066-7c21-4e4b-a9ba-4e02d562a75a';