update intakeservicerequest set intakedaterecieved = '2020-12-08 15:00:00',updatedon = now(),updatedby = 'CDM-7801' where intakenumber = 'I202000407170';

update intakedastaging set daterecieved = '2020-12-08 15:00:00', timerecieved = '2020-12-09 15:00:00',updatedon = now(),updatedby = 'CDM-7801' where intakenumber = 'I202000168860' and activeflag = 1;

update intakesnapshot set jsondata = 
'{
    "sdm": {
        "isar": true,
        "isir": false,
        "isroh": false,
        "worker": "",
        "comments": "",
        "countyid": null,
        "isschool": false,
        "provider": [],
        "screenIn": {},
        "immediate": "No Immediate",
        "screenOut": {
            "duplicatereportflag": null
        },
        "referralid": "",
        "reportdate": null,
        "riskofHarm": {
            "isnegrh_exposednewborn": false
        },
        "supervisor": "",
        "workerdate": null,
        "badgenumber": "",
        "isoutofhome": false,
        "referraldob": "1970-01-01T00:00:00.000Z",
        "sexualAbuse": {},
        "maltreatment": "no",
        "recordnumber": "",
        "referralname": "",
        "allegedvictim": [
            {
                "victimname": "CLOE  SWEITZER"
            }
        ],
        "childfatality": "no",
        "immediateList": {
            "immediateList6": null,
            "isimmed_allegation": null,
            "isimmed_otherspecify": null,
            "isimmed_seriousinjury": null,
            "isimmed_childfaatility": null,
            "isimmed_childleftalone": null
        },
        "isreportmeets": false,
        "issexualabuse": false,
        "physicalAbuse": {},
        "providerKnown": null,
        "generalNeglect": {},
        "immediateList6": null,
        "ismaltreatment": false,
        "supervisordate": null,
        "cpsResponseType": "CPS-AR",
        "ischildfatality": false,
        "isfinalscreenin": true,
        "noImmediateList": {
            "isnoimmed_risk_harm": false,
            "isnoimmed_sexualabuse": false,
            "isnoimmed_mentalinjury": false,
            "isnoimmed_physicalabuse": false,
            "isnoimmed_neglectresponse": true,
            "isnoimmed_substantial_risk": false
        },
        "officerlastname": "",
        "unattendedChild": {},
        "arGeneralNeglect": {
            "isneggn_exposuretounsafe": true
        },
        "isdeathorserious": false,
        "isrecsc_scrrenin": true,
        "officerfirstname": "",
        "allegedmaltreator": [
            {
                "maltreatorsname": "CHARLES R HOUSLEY"
            },
            {
                "maltreatorsname": "KRISTEN DIANE SWEITZER"
            }
        ],
        "childUnderOneYear": "",
        "childunderoneyear": "",
        "islicenseddaycare": false,
        "isrecsc_screenout": false,
        "officermiddlename": "",
        "isimmed_allegation": null,
        "isprivateplacement": false,
        "issignordiagonises": false,
        "screeningRecommend": "Scrnin",
        "duplicatereportflag": null,
        "isnoimmed_risk_harm": false,
        "scnRecommendOveride": "",
        "disqualifyingFactors": {},
        "isfcplacementsetting": false,
        "isimmed_otherspecify": null,
        "disqualifyingCriteria": {
            "isoutofhome": false,
            "isreportmeets": false,
            "issexualabuse": false,
            "isdeathorserious": false,
            "issignordiagonises": false
        },
        "isimmed_seriousinjury": null,
        "isnoimmed_sexualabuse": false,
        "providerunknowndetail": null,
        "isimmed_childfaatility": null,
        "isimmed_childleftalone": null,
        "isnegrh_exposednewborn": false,
        "isnoimmed_mentalinjury": false,
        "isnoimmed_physicalabuse": false,
        "isneggn_exposuretounsafe": true,
        "isnegfp_cargiverintervene": false,
        "isnegmn_unreasonabledelay": false,
        "isnoimmed_neglectresponse": true,
        "isnoimmed_substantial_risk": false,
        "ismenab_psycologicalability": false,
        "ismenng_psycologicalability": false
    },
    "DAType": {
        "DATypeDetail": [
            {
                "caseID": "",
                "reason": "",
                "Summary": "",
                "DAStatus": "Approved",
                "comments": "",
                "DaTypeKey": "247a8b26-cdee-4ce8-b36e-b37e49fd0103",
                "supStatus": "Approved",
                "agencyName": "",
                "agencyType": "",
                "GroupNumber": null,
                "supComments": "",
                "DasubtypeKey": "b74ded78-12dc-4e6d-94db-7662d6eaf093",
                "GroupComment": null,
                "intakeAction": "",
                "issubtypekey": true,
                "DADisposition": "Scrnin",
                "agencyContact": "",
                "captureReason": "",
                "serviceTypeID": "",
                "ReasonforDelay": "",
                "supDisposition": "Scrnin",
                "GroupReasonType": null,
                "dispositioncode": "Scrnin",
                "ServiceRequestNumber": "I202000407170",
                "intakeserreqstatustypekey": "Review",
                "supMultipleDispositionDropdown": [],
                "intakeMultipleDispositionDropdown": []
            }
        ]
    },
    "roacps": null,
    "General": {
        "Time": "2020-12-10T20:05:12.829Z",
        "Iscps": null,
        "Agency": "CW",
        "Author": "MissyOrr",
        "Source": "0bdda2ab-b74f-4d74-ba17-3b9b37a9ca19",
        "Purpose": "247a8b26-cdee-4ce8-b36e-b37e49fd0103",
        "Lastname": "Myers",
        "countyid": "ec6a5d23-4bc8-451a-9ea6-9253448aeb8a",
        "Firstname": "Bryson ",
        "Narrative": "<p>Outside of house dirty, disorderly, trash laying around. Exposed panel electric box with live wires running to it. When they arrived and entered the residence, there was a tv with pornography paused on it. Cloe was wearing a stained sweatshirt, her general appearance was unkempt. Cloe is currently failing in all her classes this semester. </p>",
        "AgencyCode": "CW",
        "Middlename": "",
        "CreatedDate": "2020-12-10T19:08:41.859Z",
        "InputSource": "0bdda2ab-b74f-4d74-ba17-3b9b37a9ca19",
        "PurposeName": "Child Protective Services",
        "RecivedDate": "12/8/2020, 3:00:00 PM",
        "IntakeNumber": "I202000407170",
        "intakeservice": [],
        "isDisposition": false,
        "islocalreferal": 0,
        "servicerequest": [],
        "HeadofHousehold": "KRISTEN DIANE SWEITZER",
        "offenselocation": "",
        "queAdditionDate": "2020-12-10T20:04:11.626Z",
        "RefuseToShareZip": false,
        "IsUnknownReporter": false,
        "suggestedresource": [],
        "IsAnonymousReporter": false,
        "cpsHistoryClearance": "<p>CPS History</p><p>Charles CPS IR 2/13/06 Physical Abuse/Indicated</p><p>Kristen CPS AR 10/18/19 Neglect</p><p><br></p><p>MD Judiciary</p><p>Charles - Multiple traffic charges, battery, burglary</p><p><br></p><p>MD SOR</p><p>No Results</p>",
        "narrativeUpdatedDate": "2020-12-10T19:16:20.403Z",
        "communicationDescription": "Phone"
    },
    "clwStatus": null,
    "narrative": [
        {
            "Role": "LLECJP",
            "email": "",
            "title": "",
            "ZipCode": "",
            "Lastname": "Myers",
            "RoleName": "Legal, law enforcement, or criminal justice person",
            "Firstname": "Bryson ",
            "Middlename": "",
            "PhoneNumber": "",
            "incidentdate": "2020-12-04T05:00:00.000Z",
            "organization": "",
            "isapproximate": false,
            "requestercity": "",
            "PhoneNumberExt": "",
            "requesterstate": "",
            "offenselocation": "",
            "requestercounty": "",
            "incidentlocation": "Garrett County",
            "requesteraddress1": "",
            "requesteraddress2": "",
            "requestercountyname": ""
        }
    ],
    "Allegations": [],
    "disposition": [
        {
            "caseID": "",
            "reason": "",
            "Summary": "",
            "DAStatus": "Approved",
            "comments": "",
            "DaTypeKey": "247a8b26-cdee-4ce8-b36e-b37e49fd0103",
            "supStatus": "Approved",
            "agencyName": "",
            "agencyType": "",
            "GroupNumber": null,
            "supComments": "",
            "DasubtypeKey": "b74ded78-12dc-4e6d-94db-7662d6eaf093",
            "GroupComment": null,
            "intakeAction": "",
            "issubtypekey": true,
            "DADisposition": "Scrnin",
            "agencyContact": "",
            "captureReason": "",
            "serviceTypeID": "",
            "ReasonforDelay": "",
            "supDisposition": "Scrnin",
            "GroupReasonType": null,
            "dispositioncode": "Scrnin",
            "ServiceRequestNumber": "I202000407170",
            "intakeserreqstatustypekey": "Review",
            "supMultipleDispositionDropdown": [],
            "intakeMultipleDispositionDropdown": []
        }
    ],
    "createdCases": null,
    "reviewstatus": {
        "status": "Approved",
        "appevent": "INTR",
        "commenttext": "",
        "ispreintakeapproved": false,
        "youthstatuseventcode": ""
    },
    "persondetails": {
        "Person": [
            {
                "Dob": "1974-01-31T04:00:00.000Z",
                "Pid": "1708fb5f-8b70-44a7-bb15-01236740e0f5",
                "Zip": "21538",
                "ssn": "200545791",
                "City": "Kitzmiller",
                "Role": "AM",
                "race": [
                    {
                        "value_text": "White",
                        "racetypekey": "WH"
                    }
                ],
                "State": "MD",
                "County": "Anne Arundel",
                "Gender": "M",
                "county": "ec6a5d23-4bc8-451a-9ea6-9253448aeb8a",
                "school": [],
                "Address": "907 State St",
                "address": [
                    {
                        "city": "Linthicum",
                        "state": "MD",
                        "county": "Anne Arundel",
                        "endDate": "04/29/2019",
                        "phoneNo": "",
                        "zipcode": "21090",
                        "Address2": "",
                        "address1": "849 Internation",
                        "addressid": "",
                        "startDate": "",
                        "activeflag": 1,
                        "addresstype": "31",
                        "addresstypeLabel": "Home",
                        "knownDangerAddress": "",
                        "knownDangerAddressReason": ""
                    }
                ],
                "emailID": [],
                "testing": [],
                "Lastname": "HOUSLEY",
                "cjamspid": "1175132",
                "contacts": [],
                "employer": [],
                "fullName": "CHARLES R HOUSLEY",
                "guardian": {},
                "vocation": [],
                "Firstname": "CHARLES",
                "emergency": [],
                "personRole": [
                    {
                        "hidden": false,
                        "rolekey": "OtherADULT",
                        "isprimary": "true",
                        "description": "Other Adult",
                        "relationshiptorakey": ""
                    },
                    {
                        "hidden": false,
                        "rolekey": "AM",
                        "isprimary": "true",
                        "description": "Alleged Maltreator",
                        "relationshiptorakey": ""
                    }
                ],
                "substances": [],
                "addressinfo": [
                    {
                        "city": "Kitzmiller",
                        "state": "MD",
                        "county": "ec6a5d23-4bc8-451a-9ea6-9253448aeb8a",
                        "danger": false,
                        "address": "907 State St",
                        "country": "USA",
                        "mergeid": null,
                        "zipcode": "21538",
                        "address2": "",
                        "adrboxno": null,
                        "activeflag": 1,
                        "directions": null,
                        "streetname": null,
                        "addresstype": "Home",
                        "county_desc": "Garrett",
                        "durationday": null,
                        "changereason": null,
                        "dangerreason": null,
                        "addressstatus": null,
                        "acknowledgement": null,
                        "personaddressid": "4abb34ef-7586-4028-ac32-7f5e0309024e",
                        "addressstartdate": null,
                        "incidentlocation": null,
                        "personadrenddate": null,
                        "formattedcityname": null,
                        "ishouseholdmember": true,
                        "personadrstartdate": null,
                        "acknowledgementflag": null,
                        "currentlocationflag": 1,
                        "formattedstreetname": null,
                        "incidentlocationflag": null,
                        "personaddresstypekey": "HO",
                        "adrstreetsuffixtypekey": null,
                        "personaddresssubtypekey": null
                    },
                    {
                        "city": "Kitzmiller",
                        "state": "MD",
                        "county": null,
                        "danger": false,
                        "address": "83 VINDEX RD",
                        "country": "USA",
                        "mergeid": null,
                        "zipcode": "21538",
                        "address2": "",
                        "adrboxno": null,
                        "activeflag": 1,
                        "directions": null,
                        "streetname": "Vindex",
                        "addresstype": "Home",
                        "county_desc": null,
                        "durationday": null,
                        "changereason": null,
                        "dangerreason": null,
                        "addressstatus": null,
                        "acknowledgement": null,
                        "personaddressid": "b94b944e-d33b-4f24-9144-e19a1955969a",
                        "addressstartdate": "2006-09-19T00:00:00",
                        "incidentlocation": null,
                        "personadrenddate": null,
                        "formattedcityname": null,
                        "ishouseholdmember": false,
                        "personadrstartdate": "2006-09-19T00:00:00",
                        "acknowledgementflag": null,
                        "currentlocationflag": 0,
                        "formattedstreetname": null,
                        "incidentlocationflag": null,
                        "personaddresstypekey": "HO",
                        "adrstreetsuffixtypekey": "RD",
                        "personaddresssubtypekey": null
                    }
                ],
                "fullAddress": "907 State St",
                "ishousehold": "yes",
                "personpayee": [],
                "phoneNumber": [],
                "contactsmail": [],
                "Dangerousself": "no",
                "Mentealimpair": "no",
                "personsupport": [],
                "physicianinfo": [],
                "Mentealillness": "no",
                "accomplishment": [],
                "Dangerousworker": "no",
                "healthinsurance": [],
                "primarylanguage": "ENG",
                "RelationshiptoRA": "SELF",
                "persondentalinfo": [],
                "personhealthexam": [],
                "ishouseholdmember": 1,
                "safehavenbabyflag": 1,
                "citizenalenageflag": "1",
                "personAddressInput": [
                    {
                        "city": "Linthicum",
                        "state": "MD",
                        "county": "Anne Arundel",
                        "endDate": "04/29/2019",
                        "phoneNo": "",
                        "zipcode": "21090",
                        "Address2": "",
                        "address1": "849 Internation",
                        "addressid": "",
                        "startDate": "",
                        "activeflag": 1,
                        "addresstype": "31",
                        "addresstypeLabel": "Home",
                        "knownDangerAddress": "",
                        "knownDangerAddressReason": ""
                    }
                ],
                "personabusehistory": [],
                "everbeenadoptedflag": 0,
                "personabusesubstance": [],
                "drugexposednewbornflag": 0,
                "personbehavioralhealth": [],
                "personmedicalcondition": [],
                "sexoffenderregisteredflag": 0,
                "fetalalcoholspctrmdisordflag": 0,
                "personmedicationphyscotropic": [],
                "probationsearchconductedflag": 0
            },
            {
                "Dob": "1981-01-05T05:00:00.000Z",
                "Pid": "b0333d2a-66ad-40a0-b26e-f1479d926348",
                "Zip": "21538",
                "ssn": "220175294",
                "City": "Kitzmiller",
                "Role": "AM",
                "race": [
                    {
                        "value_text": "White",
                        "racetypekey": "WH"
                    }
                ],
                "State": "MD",
                "County": "Anne Arundel",
                "Gender": "F",
                "county": "ec6a5d23-4bc8-451a-9ea6-9253448aeb8a",
                "school": [],
                "Address": "907 State St",
                "address": [
                    {
                        "city": "Linthicum",
                        "state": "MD",
                        "county": "Anne Arundel",
                        "endDate": "04/29/2019",
                        "phoneNo": "",
                        "zipcode": "21090",
                        "Address2": "",
                        "address1": "849 Internation",
                        "addressid": "",
                        "startDate": "",
                        "activeflag": 1,
                        "addresstype": "31",
                        "addresstypeLabel": "Home",
                        "knownDangerAddress": "",
                        "knownDangerAddressReason": ""
                    }
                ],
                "emailID": [],
                "testing": [],
                "Lastname": "SWEITZER",
                "cjamspid": "3514042",
                "contacts": [],
                "employer": [],
                "fullName": "KRISTEN DIANE SWEITZER",
                "guardian": {},
                "vocation": [],
                "Firstname": "KRISTEN",
                "emergency": [],
                "personRole": [
                    {
                        "hidden": false,
                        "rolekey": "AM",
                        "isprimary": "true",
                        "description": "Alleged Maltreator",
                        "relationshiptorakey": ""
                    },
                    {
                        "hidden": false,
                        "rolekey": "PARENT",
                        "isprimary": "true",
                        "description": "Parent",
                        "relationshiptorakey": ""
                    }
                ],
                "substances": [],
                "addressinfo": [
                    {
                        "city": "Kitzmiller",
                        "state": "MD",
                        "county": "ec6a5d23-4bc8-451a-9ea6-9253448aeb8a",
                        "danger": null,
                        "address": "907 State St",
                        "country": "USA",
                        "mergeid": null,
                        "zipcode": "21538",
                        "address2": "",
                        "adrboxno": null,
                        "activeflag": 1,
                        "directions": null,
                        "streetname": null,
                        "addresstype": "Home",
                        "county_desc": "Garrett",
                        "durationday": null,
                        "changereason": null,
                        "dangerreason": null,
                        "addressstatus": null,
                        "acknowledgement": null,
                        "personaddressid": "165c719d-ed24-459e-9ad4-8872782cfc07",
                        "addressstartdate": "2006-09-19T04:00:00",
                        "incidentlocation": null,
                        "personadrenddate": null,
                        "formattedcityname": null,
                        "ishouseholdmember": true,
                        "personadrstartdate": null,
                        "acknowledgementflag": null,
                        "currentlocationflag": 1,
                        "formattedstreetname": null,
                        "incidentlocationflag": null,
                        "personaddresstypekey": "HO",
                        "adrstreetsuffixtypekey": null,
                        "personaddresssubtypekey": null
                    }
                ],
                "fullAddress": "907 State St",
                "ishousehold": "yes",
                "personpayee": [],
                "phoneNumber": [],
                "contactsmail": [],
                "Dangerousself": "no",
                "Mentealimpair": "no",
                "personsupport": [],
                "physicianinfo": [],
                "Mentealillness": "no",
                "accomplishment": [],
                "Dangerousworker": "no",
                "healthinsurance": [],
                "primarylanguage": "ENG",
                "RelationshiptoRA": "SELF",
                "persondentalinfo": [],
                "personhealthexam": [],
                "isheadofhousehold": true,
                "ishouseholdmember": 1,
                "safehavenbabyflag": 1,
                "citizenalenageflag": "1",
                "personAddressInput": [
                    {
                        "city": "Linthicum",
                        "state": "MD",
                        "county": "Anne Arundel",
                        "endDate": "04/29/2019",
                        "phoneNo": "",
                        "zipcode": "21090",
                        "Address2": "",
                        "address1": "849 Internation",
                        "addressid": "",
                        "startDate": "",
                        "activeflag": 1,
                        "addresstype": "31",
                        "addresstypeLabel": "Home",
                        "knownDangerAddress": "",
                        "knownDangerAddressReason": ""
                    }
                ],
                "personabusehistory": [],
                "everbeenadoptedflag": 0,
                "personabusesubstance": [],
                "drugexposednewbornflag": 0,
                "personbehavioralhealth": [],
                "personmedicalcondition": [],
                "sexoffenderregisteredflag": 1,
                "fetalalcoholspctrmdisordflag": 0,
                "personmedicationphyscotropic": [],
                "probationsearchconductedflag": 1
            },
            {
                "Dob": "2008-02-29T05:00:00.000Z",
                "Pid": "7f87d5f1-966a-401a-a38b-4934ab68a49d",
                "Zip": "21538",
                "ssn": "215811008",
                "City": "Kitzmiller",
                "Role": "CHILD",
                "race": [
                    {
                        "value_text": "White",
                        "racetypekey": "WH"
                    }
                ],
                "State": "MD",
                "County": "Anne Arundel",
                "Gender": "F",
                "county": "ec6a5d23-4bc8-451a-9ea6-9253448aeb8a",
                "school": [],
                "Address": "907 State St",
                "address": [
                    {
                        "city": "Linthicum",
                        "state": "MD",
                        "county": "Anne Arundel",
                        "endDate": "04/29/2019",
                        "phoneNo": "",
                        "zipcode": "21090",
                        "Address2": "",
                        "address1": "849 Internation",
                        "addressid": "",
                        "startDate": "",
                        "activeflag": 1,
                        "addresstype": "31",
                        "addresstypeLabel": "Home",
                        "knownDangerAddress": "",
                        "knownDangerAddressReason": ""
                    }
                ],
                "emailID": [],
                "testing": [],
                "Lastname": "SWEITZER",
                "cjamspid": "3514040",
                "contacts": [],
                "employer": [],
                "fullName": "CLOE  SWEITZER",
                "guardian": {},
                "vocation": [],
                "Firstname": "CLOE",
                "emergency": [],
                "personRole": [
                    {
                        "hidden": false,
                        "rolekey": "CHILD",
                        "isprimary": "true",
                        "description": "Child",
                        "relationshiptorakey": ""
                    },
                    {
                        "hidden": false,
                        "rolekey": "AV",
                        "isprimary": "true",
                        "description": "Alleged Victim",
                        "relationshiptorakey": ""
                    }
                ],
                "substances": [],
                "addressinfo": [
                    {
                        "city": "Kitzmiller",
                        "state": "MD",
                        "county": "ec6a5d23-4bc8-451a-9ea6-9253448aeb8a",
                        "danger": false,
                        "address": "907 State St",
                        "country": "USA",
                        "mergeid": null,
                        "zipcode": "21538",
                        "address2": "",
                        "adrboxno": null,
                        "activeflag": 1,
                        "directions": null,
                        "streetname": null,
                        "addresstype": "Home",
                        "county_desc": "Garrett",
                        "durationday": null,
                        "changereason": null,
                        "dangerreason": null,
                        "addressstatus": null,
                        "acknowledgement": null,
                        "personaddressid": "5b8e038e-dce7-4612-86f0-06bb33aa35ab",
                        "addressstartdate": "2006-09-19T08:00:00",
                        "incidentlocation": null,
                        "personadrenddate": null,
                        "formattedcityname": null,
                        "ishouseholdmember": true,
                        "personadrstartdate": null,
                        "acknowledgementflag": null,
                        "currentlocationflag": 1,
                        "formattedstreetname": null,
                        "incidentlocationflag": null,
                        "personaddresstypekey": "HO",
                        "adrstreetsuffixtypekey": null,
                        "personaddresssubtypekey": null
                    }
                ],
                "fullAddress": "907 State St",
                "ishousehold": "yes",
                "personpayee": [],
                "phoneNumber": [],
                "contactsmail": [],
                "Dangerousself": "no",
                "Mentealimpair": "no",
                "maritalstatus": "Single",
                "personsupport": [],
                "physicianinfo": [],
                "Mentealillness": "no",
                "accomplishment": [],
                "Dangerousworker": "no",
                "healthinsurance": [],
                "primarylanguage": "ENG",
                "RelationshiptoRA": "SELF",
                "persondentalinfo": [],
                "personhealthexam": [],
                "ishouseholdmember": 1,
                "safehavenbabyflag": 1,
                "citizenalenageflag": "1",
                "personAddressInput": [
                    {
                        "city": "Linthicum",
                        "state": "MD",
                        "county": "Anne Arundel",
                        "endDate": "04/29/2019",
                        "phoneNo": "",
                        "zipcode": "21090",
                        "Address2": "",
                        "address1": "849 Internation",
                        "addressid": "",
                        "startDate": "",
                        "activeflag": 1,
                        "addresstype": "31",
                        "addresstypeLabel": "Home",
                        "knownDangerAddress": "",
                        "knownDangerAddressReason": ""
                    }
                ],
                "personabusehistory": [],
                "everbeenadoptedflag": 0,
                "personabusesubstance": [],
                "drugexposednewbornflag": 0,
                "personbehavioralhealth": [],
                "personmedicalcondition": [],
                "sexoffenderregisteredflag": 0,
                "fetalalcoholspctrmdisordflag": 0,
                "personmedicationphyscotropic": [],
                "probationsearchconductedflag": 0
            }
        ]
    },
    "officelocation": "Garrett",
    "securityuserid": "760bbede-3181-44a0-9d99-36a9b86d777d",
    "CrossReferences": [],
    "evaluationFields": null,
    "intakeDATypeDetails": [
        {
            "caseID": "",
            "reason": "",
            "Summary": "",
            "DAStatus": "Approved",
            "comments": "",
            "DaTypeKey": "247a8b26-cdee-4ce8-b36e-b37e49fd0103",
            "supStatus": "Approved",
            "agencyName": "",
            "agencyType": "",
            "GroupNumber": null,
            "supComments": "",
            "DasubtypeKey": "b74ded78-12dc-4e6d-94db-7662d6eaf093",
            "GroupComment": null,
            "intakeAction": "",
            "issubtypekey": true,
            "DADisposition": "Scrnin",
            "agencyContact": "",
            "captureReason": "",
            "serviceTypeID": "",
            "ReasonforDelay": "",
            "supDisposition": "Scrnin",
            "GroupReasonType": null,
            "dispositioncode": "Scrnin",
            "ServiceRequestNumber": "I202000407170",
            "intakeserreqstatustypekey": "Review",
            "supMultipleDispositionDropdown": [],
            "intakeMultipleDispositionDropdown": []
        }
    ],
    "focuspersoncasedetails": []
}',updatedon =now(),updatedby = 'CDM-7801' where intakenumber = 'I202000407170' and activeflag = 1;




