/*
   Issue Description: CDM-29923
   Category/ Module  : relationship
   Root cause: Please add caregiver flag in relationship tab for 
   Lakinia Hundt (CJAMS ID: 3111566) - Biological Mother with Caregiver flag 
   Davon Booth (CJAMS ID: 1649234) -Biological Father with Caregiver flag
   Case # 221020227268.Also need data fix to stop the response timer based on contact date (6/14/2022 5:35 PM)
   User requested to update the response timer
*/

INSERT INTO
    cjams.actorrelationship (
        actorrelationshipid,
        relationshiptypekey,
        insertedby,
        insertedon,
        updatedby,
        updatedon,
        "timestamp",
        effectivedate,
        expirationdate,
        activeflag,
        intakeservicerequestactorid,
        old_id,
        client1id,
        client2id,
        caregiverflag,
        paternityestdflag,
        paternityestddate,
        paternitycourtorderflag,
        maternityestdflag,
        maternityestddate,
        maternitycourtorderflag,
        "comments",
        startdate,
        enddate,
        sysgenflag,
        origclientid,
        caseid,
        referralid,
        expungementflag,
        datavalidflag,
        clientmergeid,
        fk1_id,
        fk2_id,
        fk3_id,
        person1id,
        person2id,
        servicecaseid,
        intakeserviceid,
        intakenumber,
        etl_userid,
        etl_load_date
    )
VALUES
    (
        gen_random_uuid(),
        'BGMTHR',
        'CDM-29923',
        NOW(),
        'CDM-29923',
        NOW(),
        NULL,
        NOW(),
        NULL,
        1,
        '3071954b-2d80-41b1-a69a-0f53a28951e6' :: uuid,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '3d0a4b3f-2f5e-43c7-ab53-5301a53dc656' :: uuid,
        '1c721bc6-b7e0-4aeb-a98a-77c746ee1fef' :: uuid,
        NULL,
        '8ce0101b-f4ca-470f-a21e-1a784552a47c' :: uuid,
        NULL,
        NULL,
        NULL
    );


INSERT INTO
    cjams.actorrelationship (
        actorrelationshipid,
        relationshiptypekey,
        insertedby,
        insertedon,
        updatedby,
        updatedon,
        "timestamp",
        effectivedate,
        expirationdate,
        activeflag,
        intakeservicerequestactorid,
        old_id,
        client1id,
        client2id,
        caregiverflag,
        paternityestdflag,
        paternityestddate,
        paternitycourtorderflag,
        maternityestdflag,
        maternityestddate,
        maternitycourtorderflag,
        "comments",
        startdate,
        enddate,
        sysgenflag,
        origclientid,
        caseid,
        referralid,
        expungementflag,
        datavalidflag,
        clientmergeid,
        fk1_id,
        fk2_id,
        fk3_id,
        person1id,
        person2id,
        servicecaseid,
        intakeserviceid,
        intakenumber,
        etl_userid,
        etl_load_date
    )
VALUES
(
        gen_random_uuid(),
        'BGCHLD',
        'CDM-29923',
        NOW(),
        'CDM-29923',
        NOW(),
        NULL,
        NOW(),
        NULL,
        1,
        '3071954b-2d80-41b1-a69a-0f53a28951e6' :: uuid,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '1c721bc6-b7e0-4aeb-a98a-77c746ee1fef' :: uuid,
        '3d0a4b3f-2f5e-43c7-ab53-5301a53dc656' :: uuid,
        NULL,
        '8ce0101b-f4ca-470f-a21e-1a784552a47c' :: uuid,
        NULL,
        NULL,
        NULL
    );




INSERT INTO
    cjams.actorrelationship (
        actorrelationshipid,
        relationshiptypekey,
        insertedby,
        insertedon,
        updatedby,
        updatedon,
        "timestamp",
        effectivedate,
        expirationdate,
        activeflag,
        intakeservicerequestactorid,
        old_id,
        client1id,
        client2id,
        caregiverflag,
        paternityestdflag,
        paternityestddate,
        paternitycourtorderflag,
        maternityestdflag,
        maternityestddate,
        maternitycourtorderflag,
        "comments",
        startdate,
        enddate,
        sysgenflag,
        origclientid,
        caseid,
        referralid,
        expungementflag,
        datavalidflag,
        clientmergeid,
        fk1_id,
        fk2_id,
        fk3_id,
        person1id,
        person2id,
        servicecaseid,
        intakeserviceid,
        intakenumber,
        etl_userid,
        etl_load_date
    )
VALUES
(
        gen_random_uuid(),
        'BGFTHR',
        'CDM-29923',
        NOW(),
        'CDM-29923',
        NOW(),
        NULL,
        NOW(),
        NULL,
        1,
        '3071954b-2d80-41b1-a69a-0f53a28951e6' :: uuid,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'ede2115d-87c9-43bf-8c35-04ce19420a08' :: uuid,
        '1c721bc6-b7e0-4aeb-a98a-77c746ee1fef' :: uuid,
        NULL,
        '8ce0101b-f4ca-470f-a21e-1a784552a47c' :: uuid,
        NULL,
        NULL,
        NULL
    );



INSERT INTO
    cjams.actorrelationship (
        actorrelationshipid,
        relationshiptypekey,
        insertedby,
        insertedon,
        updatedby,
        updatedon,
        "timestamp",
        effectivedate,
        expirationdate,
        activeflag,
        intakeservicerequestactorid,
        old_id,
        client1id,
        client2id,
        caregiverflag,
        paternityestdflag,
        paternityestddate,
        paternitycourtorderflag,
        maternityestdflag,
        maternityestddate,
        maternitycourtorderflag,
        "comments",
        startdate,
        enddate,
        sysgenflag,
        origclientid,
        caseid,
        referralid,
        expungementflag,
        datavalidflag,
        clientmergeid,
        fk1_id,
        fk2_id,
        fk3_id,
        person1id,
        person2id,
        servicecaseid,
        intakeserviceid,
        intakenumber,
        etl_userid,
        etl_load_date
    )
VALUES
(
        gen_random_uuid(),
        'BGCHLD',
        'CDM-29923',
        NOW(),
        'CDM-29923',
        NOW(),
        NULL,
        NOW(),
        NULL,
        1,
        '3071954b-2d80-41b1-a69a-0f53a28951e6' :: uuid,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '1c721bc6-b7e0-4aeb-a98a-77c746ee1fef' :: uuid,
        'ede2115d-87c9-43bf-8c35-04ce19420a08' :: uuid,
        NULL,
        '8ce0101b-f4ca-470f-a21e-1a784552a47c' :: uuid,
        NULL,
        NULL,
        NULL
    );



INSERT INTO
    cjams.actorrelationship (
        actorrelationshipid,
        relationshiptypekey,
        insertedby,
        insertedon,
        updatedby,
        updatedon,
        "timestamp",
        effectivedate,
        expirationdate,
        activeflag,
        intakeservicerequestactorid,
        old_id,
        client1id,
        client2id,
        caregiverflag,
        paternityestdflag,
        paternityestddate,
        paternitycourtorderflag,
        maternityestdflag,
        maternityestddate,
        maternitycourtorderflag,
        "comments",
        startdate,
        enddate,
        sysgenflag,
        origclientid,
        caseid,
        referralid,
        expungementflag,
        datavalidflag,
        clientmergeid,
        fk1_id,
        fk2_id,
        fk3_id,
        person1id,
        person2id,
        servicecaseid,
        intakeserviceid,
        intakenumber,
        etl_userid,
        etl_load_date
    )
VALUES
(
        gen_random_uuid(),
        'BGCHLD',
        'CDM-29923',
        NOW(),
        'CDM-29923',
        NOW(),
        NULL,
        NOW(),
        NULL,
        1,
        '68ad1b35-7a0a-411e-a6a8-633ba32eff1a' :: uuid,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'd1120b7d-9381-4815-92d8-d2048dff82d8' :: uuid,
        '3d0a4b3f-2f5e-43c7-ab53-5301a53dc656' :: uuid,
        NULL,
        '8ce0101b-f4ca-470f-a21e-1a784552a47c' :: uuid,
        NULL,
        NULL,
        NULL
    );



INSERT INTO
    cjams.actorrelationship (
        actorrelationshipid,
        relationshiptypekey,
        insertedby,
        insertedon,
        updatedby,
        updatedon,
        "timestamp",
        effectivedate,
        expirationdate,
        activeflag,
        intakeservicerequestactorid,
        old_id,
        client1id,
        client2id,
        caregiverflag,
        paternityestdflag,
        paternityestddate,
        paternitycourtorderflag,
        maternityestdflag,
        maternityestddate,
        maternitycourtorderflag,
        "comments",
        startdate,
        enddate,
        sysgenflag,
        origclientid,
        caseid,
        referralid,
        expungementflag,
        datavalidflag,
        clientmergeid,
        fk1_id,
        fk2_id,
        fk3_id,
        person1id,
        person2id,
        servicecaseid,
        intakeserviceid,
        intakenumber,
        etl_userid,
        etl_load_date
    )
VALUES
(
        gen_random_uuid(),
        'BGMTHR',
        'CDM-29923',
        NOW(),
        'CDM-29923',
        NOW(),
        NULL,
        NOW(),
        NULL,
        1,
        '68ad1b35-7a0a-411e-a6a8-633ba32eff1a' :: uuid,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '3d0a4b3f-2f5e-43c7-ab53-5301a53dc656' :: uuid,
        'd1120b7d-9381-4815-92d8-d2048dff82d8' :: uuid,
        NULL,
        '8ce0101b-f4ca-470f-a21e-1a784552a47c' :: uuid,
        NULL,
        NULL,
        NULL
    );


    INSERT INTO
    cjams.actorrelationship (
        actorrelationshipid,
        relationshiptypekey,
        insertedby,
        insertedon,
        updatedby,
        updatedon,
        "timestamp",
        effectivedate,
        expirationdate,
        activeflag,
        intakeservicerequestactorid,
        old_id,
        client1id,
        client2id,
        caregiverflag,
        paternityestdflag,
        paternityestddate,
        paternitycourtorderflag,
        maternityestdflag,
        maternityestddate,
        maternitycourtorderflag,
        "comments",
        startdate,
        enddate,
        sysgenflag,
        origclientid,
        caseid,
        referralid,
        expungementflag,
        datavalidflag,
        clientmergeid,
        fk1_id,
        fk2_id,
        fk3_id,
        person1id,
        person2id,
        servicecaseid,
        intakeserviceid,
        intakenumber,
        etl_userid,
        etl_load_date
    )
VALUES
(
        gen_random_uuid(),
        'BGCHLD',
        'CDM-29923',
        NOW(),
        'CDM-29923',
        NOW(),
        NULL,
        NOW(),
        NULL,
        1,
        '68ad1b35-7a0a-411e-a6a8-633ba32eff1a' :: uuid,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'd1120b7d-9381-4815-92d8-d2048dff82d8' :: uuid,
        'ede2115d-87c9-43bf-8c35-04ce19420a08' :: uuid,
        NULL,
        '8ce0101b-f4ca-470f-a21e-1a784552a47c' :: uuid,
        NULL,
        NULL,
        NULL
    );


   INSERT INTO
    cjams.actorrelationship (
        actorrelationshipid,
        relationshiptypekey,
        insertedby,
        insertedon,
        updatedby,
        updatedon,
        "timestamp",
        effectivedate,
        expirationdate,
        activeflag,
        intakeservicerequestactorid,
        old_id,
        client1id,
        client2id,
        caregiverflag,
        paternityestdflag,
        paternityestddate,
        paternitycourtorderflag,
        maternityestdflag,
        maternityestddate,
        maternitycourtorderflag,
        "comments",
        startdate,
        enddate,
        sysgenflag,
        origclientid,
        caseid,
        referralid,
        expungementflag,
        datavalidflag,
        clientmergeid,
        fk1_id,
        fk2_id,
        fk3_id,
        person1id,
        person2id,
        servicecaseid,
        intakeserviceid,
        intakenumber,
        etl_userid,
        etl_load_date
    )
VALUES
(
        gen_random_uuid(),
        'BGFTHR',
        'CDM-29923',
        NOW(),
        'CDM-29923',
        NOW(),
        NULL,
        NOW(),
        NULL,
        1,
        '68ad1b35-7a0a-411e-a6a8-633ba32eff1a' :: uuid,
        NULL,
        NULL,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'ede2115d-87c9-43bf-8c35-04ce19420a08' :: uuid,
        'd1120b7d-9381-4815-92d8-d2048dff82d8' :: uuid,
        NULL,
        '8ce0101b-f4ca-470f-a21e-1a784552a47c' :: uuid,
        NULL,
        NULL,
        NULL
    );


UPDATE
    intakeservicerequest
SET
    responsetimer = '2022-06-14 17:35:00.000',
    updatedby = 'CDM-29923',
    updatedon = now()
WHERE
    servicerequestnumber = '221020227268';