update intakesnapshot i set updatedby = 'CDM-8837', updatedon = now(), 
jsondata = '{
  "sdm": {
    "isar": false,
    "isir": false,
    "isroh": false,
    "worker": "",
    "comments": "",
    "countyid": null,
    "isschool": false,
    "provider": [],
    "screenIn": {
      "scrnin_description": null,
      "isscrninrecovr_courtorder": null,
      "isscrninrecovr_otherspecify": null
    },
    "immediate": "",
    "screenOut": {
      "duplicatereportflag": null,
      "scrnout_description": "SN: Baltimore City Screened Out same referral on 1/9/21 (i202100615205) The EH worker called 911 and Officer Johnson, K283, Eastern District, 443 938-2569, responded to the call. Officer Johnson went to the address given by the caller, 806 Webb St. Baltimore, MD, 21202, and the Officer reported that the mother and child did not live at that address. The EH worker gave the Officer another address, 835 McKim St. Baltimore, MD, 21202, and the mother and child were at that address. The Officer reported that the child had 3 dark marks on his head and one on his nose. The Officer reported that the marks did not look like bruises, but just dark areas on the child''s face and nose. The Officer spoke to the mother and the mother reported that the child had seizures and the marks have been on his head and nose for a while. The Officer stated that the mother showed him a picture taken in September 2020, with the same marks on the child. The Officer gave the EH worker a CC# 3210102295 for unfounded child abuse.",
      "isscrnoutrecovr_information": true,
      "isscrnoutrecovr_otherspecify": true
    },
    "referralid": "",
    "reportdate": null,
    "riskofHarm": {
      "isnegrh_exposednewborn": false
    },
    "supervisor": "",
    "workerdate": null,
    "badgenumber": "",
    "isoutofhome": false,
    "referraldob": "1970-01-01T00:00:00.000Z",
    "sexualAbuse": {},
    "maltreatment": "no",
    "recordnumber": "",
    "referralname": "",
    "allegedvictim": [],
    "childfatality": "no",
    "immediateList": {},
    "isreportmeets": false,
    "issexualabuse": false,
    "physicalAbuse": {
      "ismalpa_insjury": true
    },
    "providerKnown": null,
    "generalNeglect": {},
    "ismaltreatment": false,
    "supervisordate": null,
    "cpsResponseType": null,
    "ischildfatality": false,
    "isfinalscreenin": false,
    "ismalpa_insjury": true,
    "noImmediateList": {},
    "officerlastname": "",
    "unattendedChild": {},
    "arGeneralNeglect": {},
    "isdeathorserious": false,
    "isrecsc_scrrenin": true,
    "officerfirstname": "",
    "allegedmaltreator": [],
    "childUnderOneYear": "",
    "childunderoneyear": "",
    "islicenseddaycare": false,
    "isrecsc_screenout": false,
    "officermiddlename": "",
    "isprivateplacement": false,
    "issignordiagonises": false,
    "screeningRecommend": "Scrnin",
    "scrnin_description": null,
    "duplicatereportflag": null,
    "scnRecommendOveride": "",
    "scrnout_description": "SN: Baltimore City Screened Out same referral on 1/9/21 (i202100615205) The EH worker called 911 and Officer Johnson, K283, Eastern District, 443 938-2569, responded to the call. Officer Johnson went to the address given by the caller, 806 Webb St. Baltimore, MD, 21202, and the Officer reported that the mother and child did not live at that address. The EH worker gave the Officer another address, 835 McKim St. Baltimore, MD, 21202, and the mother and child were at that address. The Officer reported that the child had 3 dark marks on his head and one on his nose. The Officer reported that the marks did not look like bruises, but just dark areas on the child''s face and nose. The Officer spoke to the mother and the mother reported that the child had seizures and the marks have been on his head and nose for a while. The Officer stated that the mother showed him a picture taken in September 2020, with the same marks on the child. The Officer gave the EH worker a CC# 3210102295 for unfounded child abuse.",
    "disqualifyingFactors": {},
    "isfcplacementsetting": false,
    "disqualifyingCriteria": {
      "isoutofhome": false,
      "isreportmeets": false,
      "issexualabuse": false,
      "isdeathorserious": false,
      "issignordiagonises": false
    },
    "providerunknowndetail": null,
    "isnegrh_exposednewborn": false,
    "isnegfp_cargiverintervene": false,
    "isnegmn_unreasonabledelay": false,
    "isscrninrecovr_courtorder": null,
    "ismenab_psycologicalability": false,
    "ismenng_psycologicalability": false,
    "isscrninrecovr_otherspecify": null,
    "isscrnoutrecovr_information": true,
    "isscrnoutrecovr_otherspecify": true
  },
  "DAType": {
    "DATypeDetail": [
      {
        "caseID": "",
        "reason": "",
        "Summary": "",
        "DAStatus": "Approved",
        "comments": "SOI",
        "DaTypeKey": "247a8b26-cdee-4ce8-b36e-b37e49fd0103",
        "supStatus": "Approved",
        "agencyName": "",
        "agencyType": "",
        "GroupNumber": null,
        "supComments": "screen out: family resides in Baltimore City. Police observed child and intake was not accepted by Baltimore City",
        "GroupComment": null,
        "intakeAction": "",
        "issubtypekey": true,
        "DADisposition": "ScreenOUT",
        "agencyContact": "",
        "captureReason": "",
        "serviceTypeID": "",
        "ReasonforDelay": "",
        "supDisposition": "ScreenOUT",
        "GroupReasonType": null,
        "dispositioncode": "ScreenOUT",
        "ServiceRequestNumber": "I202100015250",
        "intakeserreqstatustypekey": "Review",
        "supMultipleDispositionDropdown": [],
        "intakeMultipleDispositionDropdown": []
      }
    ]
  },
  "roacps": null,
  "General": {
    "Time": "2021-01-11T22:03:10.444Z",
    "Iscps": null,
    "Agency": "CW",
    "Author": "Lindsay Chen",
    "Source": "0bdda2ab-b74f-4d74-ba17-3b9b37a9ca19",
    "Purpose": "247a8b26-cdee-4ce8-b36e-b37e49fd0103",
    "Lastname": "Hartman",
    "countyid": "f5214cb2-953e-41a9-a4ad-71341501e2ad",
    "Firstname": "Jessica",
    "Narrative": "<p><span style=\"color: rgb(34, 34, 34);\">Reporter/Speech therapist: Jessica Hartman</span></p><p><span style=\"color: rgb(34, 34, 34);\">Hebron Harman Elementary School</span></p><p><span style=\"color: rgb(34, 34, 34);\">7660 Ridge Chapel Road</span></p><p><span style=\"color: rgb(34, 34, 34);\">Hanover, Maryland 21076</span></p><p><span style=\"color: rgb(34, 34, 34);\">412-443-8752</span></p><p><span style=\"color: rgb(34, 34, 34);\"> </span></p><p><span style=\"color: rgb(34, 34, 34);\">Mother: Latisha Alston DOB: 1/10/94&nbsp;Telephone: 443-413-8308</span></p><p><span style=\"color: rgb(34, 34, 34);\">Child: Lonnie Edwards DOB: 9/17/14&nbsp;</span></p><p><span style=\"color: rgb(34, 34, 34);\">Address: 835 McKim Street Baltimore, Maryland 21202</span></p><p><br></p><p><span style=\"color: rgb(34, 34, 34);\">Cousin/Former Custodian: Kimberly Richardson DOB: 8/14/82 Telephone: 443-558-8301</span></p><p><span style=\"color: rgb(34, 34, 34);\">Address: 1518 Penzance Way Hanover, MD 21076</span></p><p><span style=\"color: rgb(34, 34, 34);\"> </span></p><p><span style=\"color: rgb(34, 34, 34);\">1/9/2021 4:50 pm ENI Worker L. Chen received the following report: The reporter advised that Lonnie used to live with his cousin in Anne Arundel County where he appeared to well cared for however it appears that he has been staying with his mother within recent weeks and that he was observed on Thursday (1/7/2021) to have 3 purple-colored bruises on his forehead that were small and appeared to be almost like fingerprints. The reporter advised that she did not immediately report it because the guidance counselor and her supervisor had been going back and forth about whether or not to make a report about this because Lonnie’s speech is so delayed, thus he was not able to explain what had happened in addition to his mother being present while the reporter was trying to observe the marks through the virtual session.</span></p><p><span style=\"color: rgb(34, 34, 34);\"> </span></p><p><span style=\"color: rgb(34, 34, 34);\"> Reporter advised that Lonnie’s mother yells at him when he cannot remember the answer to a question. Lonnie has Lowe Syndrome and has regular seizures as well as visual deficits.</span></p><p><span style=\"color: rgb(34, 34, 34);\"> </span></p><p><span style=\"color: rgb(34, 34, 34);\"> Worker advised reporter to make a report to Baltimore City as it appears that the bruises would have come from his mother’s home in Baltimore City.</span></p><p><span style=\"color: rgb(34, 34, 34);\">&nbsp;</span></p><p><span style=\"color: rgb(34, 34, 34);\"> SN: Case was received after hours.&nbsp;Referral will be reviewed for acceptance by screening supervisor the next business day.&nbsp;</span></p><p><br></p><p><span style=\"color: rgb(34, 34, 34);\">SN: Baltimore City Screened Out same referral on 1/9/21 (i202100615205) </span>The EH worker called 911 and Officer Johnson, K283, Eastern District, 443 938-2569, responded to the call. Officer Johnson went to the address given by the caller, 806 Webb St. Baltimore, MD, 21202, and the Officer reported that the mother and child did not live at that address. The EH worker gave the Officer another address, 835 McKim St. Baltimore, MD, 21202, and the mother and child were at that address. The Officer reported that the child had 3 dark marks on his head and one on his nose. The Officer reported that the marks did not look like bruises, but just dark areas on the child''s face and nose. The Officer spoke to the mother and the mother reported that the child had seizures and the marks have been on his head and nose for a while. The Officer stated that the mother showed him a picture taken in September 2020, with the same marks on the child. The Officer gave the EH worker a CC# 3210102295 for unfounded child abuse.</p>",
    "AgencyCode": "CW",
    "Middlename": "",
    "CreatedDate": "2021-01-11T00:09:55.324Z",
    "InputSource": "0bdda2ab-b74f-4d74-ba17-3b9b37a9ca19",
    "PurposeName": "Child Protective Services",
    "RecivedDate": "1/10/2021, 7:09:55 PM",
    "IntakeNumber": "I202100015250",
    "intakeservice": [],
    "isDisposition": false,
    "requestercity": "Hanover",
    "islocalreferal": 0,
    "requesterstate": "MD",
    "servicerequest": [],
    "offenselocation": "21076",
    "queAdditionDate": "2021-01-11T22:03:03.565Z",
    "requestercounty": "f5214cb2-953e-41a9-a4ad-71341501e2ad",
    "RefuseToShareZip": false,
    "IsUnknownReporter": false,
    "requesteraddress1": "7660 Ridge Chapel Rd",
    "suggestedresource": [],
    "IsAnonymousReporter": false,
    "cpsHistoryClearance": "<p><span style=\"color: rgb(34, 34, 34);\">CPS: 008009779&nbsp;30 CW&nbsp;AR&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C&nbsp;&nbsp;&nbsp;10 20 20 12 08 20</span></p><p><span style=\"color: rgb(34, 34, 34);\">002954550&nbsp;30 CW&nbsp;INV&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A&nbsp;&nbsp;&nbsp;04 06 20</span></p><p><span style=\"color: rgb(34, 34, 34);\">002946870&nbsp;30 CW&nbsp;INV&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C&nbsp;&nbsp;&nbsp;11 12 19 01 10 20</span></p><p><span style=\"color: rgb(34, 34, 34);\">002939907&nbsp;30 CW&nbsp;INV&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C&nbsp;&nbsp;&nbsp;07 17 19 09 09 19</span></p><p><span style=\"color: rgb(34, 34, 34);\">002900353&nbsp;30 CW&nbsp;INV&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C&nbsp;&nbsp;&nbsp;11 30 17 01 02 18</span></p><p><span style=\"color: rgb(34, 34, 34);\">003148504&nbsp;30 CW&nbsp;INHM&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C&nbsp;&nbsp;&nbsp;07 24 06 11 03 06</span></p><p><span style=\"color: rgb(34, 34, 34);\">740086247 334 SS&nbsp;05N1&nbsp;GC&nbsp;C&nbsp;&nbsp;&nbsp;07 24 06 10 18 06</span></p><p><span style=\"color: rgb(34, 34, 34);\">770019818 349 SS&nbsp;05C3&nbsp;GC&nbsp;C&nbsp;&nbsp;&nbsp;05 20 05 09 08 05</span></p><p><span style=\"color: rgb(34, 34, 34);\">220073744 349 SS&nbsp;05C4&nbsp;CB&nbsp;C&nbsp;&nbsp;&nbsp;05 20 05 09 08 05</span></p><p><span style=\"color: rgb(34, 34, 34);\">390073842 349 SS&nbsp;05P1&nbsp;SE&nbsp;C&nbsp;&nbsp;&nbsp;05 20 05 09 08 05</span></p><p><span style=\"color: rgb(34, 34, 34);\">770019818 348 SS&nbsp;05C3&nbsp;GC&nbsp;C&nbsp;&nbsp;&nbsp;11 17 04 05 03 05</span></p><p><span style=\"color: rgb(34, 34, 34);\">390073842 348 SS&nbsp;05P1&nbsp;SE&nbsp;C&nbsp;&nbsp;&nbsp;11 17 04 05 03 05</span></p><p><br></p><p><span style=\"color: rgb(34, 34, 34);\">MJCS: No criminal history for Latisha Alston within last 5 years in Maryland </span></p><p><br></p><p><span style=\"color: rgb(34, 34, 34);\">NSOR: No matches for Latisha Alston</span></p>",
    "requestercountyname": "Anne Arundel",
    "narrativeUpdatedDate": "2021-01-11T21:48:20.125Z",
    "communicationDescription": "Phone"
  },
  "clwStatus": null,
  "narrative": [
    {
      "Role": "EP",
      "email": "",
      "title": "",
      "ZipCode": "",
      "Lastname": "Hartman",
      "RoleName": "Education personnel",
      "Firstname": "Jessica",
      "Middlename": "",
      "PhoneNumber": "4124438752",
      "incidentdate": "2021-01-07T05:00:00.000Z",
      "organization": "Hebron Harman Elementary School",
      "isapproximate": true,
      "requestercity": "Hanover",
      "PhoneNumberExt": "",
      "requesterstate": "MD",
      "offenselocation": "21076",
      "requestercounty": "f5214cb2-953e-41a9-a4ad-71341501e2ad",
      "incidentlocation": "Baltimore City",
      "requesteraddress1": "7660 Ridge Chapel Rd",
      "requesteraddress2": "",
      "requestercountyname": "Anne Arundel"
    }
  ],
  "Allegations": [],
  "disposition": [
    {
      "caseID": "",
      "reason": "",
      "Summary": "",
      "DAStatus": "Approved",
      "comments": "SOI",
      "DaTypeKey": "247a8b26-cdee-4ce8-b36e-b37e49fd0103",
      "supStatus": "Approved",
      "agencyName": "",
      "agencyType": "",
      "GroupNumber": null,
      "supComments": "screen out: family resides in Baltimore City. Police observed child and intake was not accepted by Baltimore City",
      "GroupComment": null,
      "intakeAction": "",
      "issubtypekey": true,
      "DADisposition": "ScreenOUT",
      "agencyContact": "",
      "captureReason": "",
      "serviceTypeID": "",
      "ReasonforDelay": "",
      "supDisposition": "ScreenOUT",
      "GroupReasonType": null,
      "dispositioncode": "ScreenOUT",
      "ServiceRequestNumber": "I202100015250",
      "intakeserreqstatustypekey": "Review",
      "supMultipleDispositionDropdown": [],
      "intakeMultipleDispositionDropdown": []
    }
  ],
  "createdCases": null,
  "reviewstatus": {
    "status": "Approved",
    "appevent": "INTR",
    "commenttext": "screen out: family resides in Baltimore City. Police observed child and intake was not accepted by Baltimore City",
    "ispreintakeapproved": false,
    "youthstatuseventcode": ""
  },
  "persondetails": {
    "Person": [
      {
        "Dob": "2014-09-17T04:00:00.000Z",
        "Pid": "39f91f0b-f24b-4137-ba0f-2690ce55f5be",
        "Zip": "21202",
        "ssn": "071996252",
        "City": "Baltimore",
        "Role": "CHILD",
        "race": [
          {
            "value_text": "Black or African American",
            "racetypekey": "BA"
          }
        ],
        "State": "MD",
        "County": "Anne Arundel",
        "Gender": "M",
        "county": "7665ca54-5374-4174-be07-a687b811a82c",
        "school": [],
        "Address": "835 Mckim St",
        "address": [
          {
            "city": "Linthicum",
            "state": "MD",
            "county": "Anne Arundel",
            "endDate": "04/29/2019",
            "phoneNo": "",
            "zipcode": "21090",
            "Address2": "",
            "address1": "849 Internation",
            "addressid": "",
            "startDate": "",
            "activeflag": 1,
            "addresstype": "31",
            "addresstypeLabel": "Home",
            "knownDangerAddress": "",
            "knownDangerAddressReason": ""
          }
        ],
        "emailID": [],
        "testing": [],
        "Lastname": "EDWARDS",
        "cjamspid": "4168461",
        "contacts": [],
        "employer": [],
        "fullName": "LONNIE H EDWARDS Jr.",
        "guardian": {},
        "vocation": [],
        "Firstname": "LONNIE",
        "emergency": [],
        "personRole": [
          {
            "hidden": false,
            "rolekey": "CHILD",
            "isprimary": "true",
            "description": "Child",
            "relationshiptorakey": ""
          }
        ],
        "substances": [],
        "addressinfo": [
          {
            "city": "Baltimore",
            "state": "MD",
            "county": "7665ca54-5374-4174-be07-a687b811a82c",
            "danger": null,
            "address": "835 Mckim St",
            "country": "USA",
            "mergeid": null,
            "zipcode": "21202",
            "address2": "",
            "adrboxno": null,
            "activeflag": 1,
            "directions": null,
            "streetname": null,
            "addresstype": "Home",
            "county_desc": "Baltimore",
            "durationday": null,
            "changereason": null,
            "dangerreason": null,
            "addressstatus": null,
            "acknowledgement": null,
            "personaddressid": "44293eb9-a193-4ddb-a9c2-e74d1b5a9584",
            "addressstartdate": "2021-01-09T00:00:00",
            "incidentlocation": null,
            "personadrenddate": null,
            "formattedcityname": null,
            "ishouseholdmember": true,
            "personadrstartdate": null,
            "acknowledgementflag": null,
            "currentlocationflag": 1,
            "formattedstreetname": null,
            "incidentlocationflag": null,
            "personaddresstypekey": "HO",
            "adrstreetsuffixtypekey": null,
            "personaddresssubtypekey": null
          },
          {
            "city": "Baltimore",
            "state": "MD",
            "county": "7665ca54-5374-4174-be07-a687b811a82c",
            "danger": null,
            "address": "806 Webb Ct",
            "country": "USA",
            "mergeid": null,
            "zipcode": "21202",
            "address2": "",
            "adrboxno": null,
            "activeflag": 1,
            "directions": null,
            "streetname": null,
            "addresstype": "Home",
            "county_desc": "Baltimore",
            "durationday": null,
            "changereason": null,
            "dangerreason": null,
            "addressstatus": null,
            "acknowledgement": null,
            "personaddressid": "0230932e-3413-496e-9166-07030673633b",
            "addressstartdate": "2017-11-23T10:00:00",
            "incidentlocation": null,
            "personadrenddate": null,
            "formattedcityname": null,
            "ishouseholdmember": true,
            "personadrstartdate": null,
            "acknowledgementflag": null,
            "currentlocationflag": 0,
            "formattedstreetname": null,
            "incidentlocationflag": null,
            "personaddresstypekey": "HO",
            "adrstreetsuffixtypekey": null,
            "personaddresssubtypekey": null
          },
          {
            "city": "Baltimore",
            "state": "MD",
            "county": "7665ca54-5374-4174-be07-a687b811a82c",
            "danger": false,
            "address": "843 HILLMAN CT",
            "country": "USA",
            "mergeid": null,
            "zipcode": "21201",
            "address2": "",
            "adrboxno": null,
            "activeflag": 1,
            "directions": null,
            "streetname": "Hillman",
            "addresstype": "Home",
            "county_desc": "Baltimore",
            "durationday": null,
            "changereason": null,
            "dangerreason": null,
            "addressstatus": null,
            "acknowledgement": null,
            "personaddressid": "6d074213-a767-4a25-9136-9dca7e8ee5d9",
            "addressstartdate": "2017-11-23T00:00:00",
            "incidentlocation": null,
            "personadrenddate": null,
            "formattedcityname": null,
            "ishouseholdmember": false,
            "personadrstartdate": "2017-11-23T00:00:00",
            "acknowledgementflag": null,
            "currentlocationflag": 0,
            "formattedstreetname": null,
            "incidentlocationflag": null,
            "personaddresstypekey": "HO",
            "adrstreetsuffixtypekey": "CT",
            "personaddresssubtypekey": null
          }
        ],
        "fullAddress": "835 Mckim St",
        "ishousehold": "yes",
        "personpayee": [],
        "phoneNumber": [],
        "contactsmail": [],
        "Dangerousself": "no",
        "Mentealimpair": "no",
        "maritalstatus": "Single",
        "personsupport": [],
        "physicianinfo": [],
        "Mentealillness": "no",
        "accomplishment": [],
        "Dangerousworker": "no",
        "healthinsurance": [],
        "primarylanguage": "ENG",
        "RelationshiptoRA": "SELF",
        "persondentalinfo": [],
        "personhealthexam": [],
        "ishouseholdmember": 1,
        "safehavenbabyflag": 1,
        "citizenalenageflag": "1",
        "personAddressInput": [
          {
            "city": "Linthicum",
            "state": "MD",
            "county": "Anne Arundel",
            "endDate": "04/29/2019",
            "phoneNo": "",
            "zipcode": "21090",
            "Address2": "",
            "address1": "849 Internation",
            "addressid": "",
            "startDate": "",
            "activeflag": 1,
            "addresstype": "31",
            "addresstypeLabel": "Home",
            "knownDangerAddress": "",
            "knownDangerAddressReason": ""
          }
        ],
        "personabusehistory": [],
        "everbeenadoptedflag": 0,
        "personabusesubstance": [],
        "drugexposednewbornflag": 0,
        "personbehavioralhealth": [],
        "personmedicalcondition": [],
        "sexoffenderregisteredflag": 0,
        "fetalalcoholspctrmdisordflag": 0,
        "personmedicationphyscotropic": [],
        "probationsearchconductedflag": 0
      },
	  {
	  
      "Dob": "1993-01-10 00:00:00Z",
      "Pid": "3f5a598e-a8e9-43b7-bc4b-835000e789c6",
      "Zip": "21202",
      "ssn": "214397730",
      "City": "Baltimore",
      "Role": "PARENT",
      "race": [
        {
          "value_text": "Black or African American",
          "racetypekey": "BA"
        }
      ],
      "State": "MD",
      "County": "Anne Arundel",
      "Gender": "F",
      "county": "7665ca54-5374-4174-be07-a687b811a82c",
      "school": [],
      "Address": "835 Mckim St",
      "emailID": [],
      "testing": [],
      "Lastname": "ALSTON",
      "cjamspid": "1726691",
      "employer": [],
      "fullName": "LATISHA W ALSTON",
      "guardian": {},
      "vocation": [],
      "Firstname": "LATISHA",
      "emergency": [],
      "personRole": [
        {
          "hidden": false,
          "rolekey": "PARENT",
          "isprimary": "true",
          "description": "Parent",
          "relationshiptorakey": ""
        }
      ],
      "substances": [],
      "addressinfo": [
        {
          "city": "Baltimore",
          "state": "MD",
          "county": "7665ca54-5374-4174-be07-a687b811a82c",
          "danger": null,
          "address": "835 Mckim St",
          "country": "USA",
          "mergeid": null,
          "zipcode": "21202",
          "address2": "",
          "adrboxno": null,
          "activeflag": 1,
          "directions": null,
          "streetname": null,
          "addresstype": "Home",
          "county_desc": "Baltimore",
          "durationday": null,
          "changereason": null,
          "dangerreason": null,
          "addressstatus": null,
          "acknowledgement": null,
          "personaddressid": "44293eb9-a193-4ddb-a9c2-e74d1b5a9584",
          "addressstartdate": "2021-01-09T00:00:00",
          "incidentlocation": null,
          "personadrenddate": null,
          "formattedcityname": null,
          "ishouseholdmember": true,
          "personadrstartdate": null,
          "acknowledgementflag": null,
          "currentlocationflag": 1,
          "formattedstreetname": null,
          "incidentlocationflag": null,
          "personaddresstypekey": "HO",
          "adrstreetsuffixtypekey": null,
          "personaddresssubtypekey": null
        },
        {
          "city": "Baltimore",
          "state": "MD",
          "county": "7665ca54-5374-4174-be07-a687b811a82c",
          "danger": null,
          "address": "806 Webb Ct",
          "country": "USA",
          "mergeid": null,
          "zipcode": "21202",
          "address2": "",
          "adrboxno": null,
          "activeflag": 1,
          "directions": null,
          "streetname": null,
          "addresstype": "Home",
          "county_desc": "Baltimore",
          "durationday": null,
          "changereason": null,
          "dangerreason": null,
          "addressstatus": null,
          "acknowledgement": null,
          "personaddressid": "0230932e-3413-496e-9166-07030673633b",
          "addressstartdate": "2017-11-23T10:00:00",
          "incidentlocation": null,
          "personadrenddate": null,
          "formattedcityname": null,
          "ishouseholdmember": true,
          "personadrstartdate": null,
          "acknowledgementflag": null,
          "currentlocationflag": 0,
          "formattedstreetname": null,
          "incidentlocationflag": null,
          "personaddresstypekey": "HO",
          "adrstreetsuffixtypekey": null,
          "personaddresssubtypekey": null
        },
        {
          "city": "Baltimore",
          "state": "MD",
          "county": "7665ca54-5374-4174-be07-a687b811a82c",
          "danger": false,
          "address": "843 HILLMAN CT",
          "country": "USA",
          "mergeid": null,
          "zipcode": "21201",
          "address2": "",
          "adrboxno": null,
          "activeflag": 1,
          "directions": null,
          "streetname": "Hillman",
          "addresstype": "Home",
          "county_desc": "Baltimore",
          "durationday": null,
          "changereason": null,
          "dangerreason": null,
          "addressstatus": null,
          "acknowledgement": null,
          "personaddressid": "6d074213-a767-4a25-9136-9dca7e8ee5d9",
          "addressstartdate": "2017-11-23T00:00:00",
          "incidentlocation": null,
          "personadrenddate": null,
          "formattedcityname": null,
          "ishouseholdmember": false,
          "personadrstartdate": "2017-11-23T00:00:00",
          "acknowledgementflag": null,
          "currentlocationflag": 0,
          "formattedstreetname": null,
          "incidentlocationflag": null,
          "personaddresstypekey": "HO",
          "adrstreetsuffixtypekey": "CT",
          "personaddresssubtypekey": null
        }
      ],
      "fullAddress": "835 Mckim St",
      "ishousehold": "yes",
      "personpayee": [],
      "phoneNumber": [],
      "Dangerousself": "no",
      "Mentealimpair": "no",
      "maritalstatus": "Single",
      "personsupport": [],
      "physicianinfo": [],
      "Mentealillness": "no",
      "accomplishment": [],
      "Dangerousworker": "no",
      "healthinsurance": [],
      "primarylanguage": "ENG",
      "RelationshiptoRA": "SELF",
      "persondentalinfo": [],
      "personhealthexam": [],
      "ishouseholdmember": 1,
      "safehavenbabyflag": 1,
      "citizenalenageflag": "1",
      "personAddressInput": [
        {
          "city": "Linthicum",
          "state": "MD",
          "county": "Anne Arundel",
          "endDate": "04/29/2019",
          "phoneNo": "",
          "zipcode": "21090",
          "Address2": "",
          "address1": "849 Internation",
          "addressid": "",
          "startDate": "",
          "activeflag": 1,
          "addresstype": "31",
          "addresstypeLabel": "Home",
          "knownDangerAddress": "",
          "knownDangerAddressReason": ""
        }
      ],
      "personabusehistory": [],
      "everbeenadoptedflag": 0,
      "personabusesubstance": [],
      "drugexposednewbornflag": 0,
      "personbehavioralhealth": [],
      "personmedicalcondition": [],
      "sexoffenderregisteredflag": 0,
      "fetalalcoholspctrmdisordflag": 0,
      "personmedicationphyscotropic": [],
      "probationsearchconductedflag": 0
	  }
    ]
  },
  "officelocation": "Anne Arundel",
  "securityuserid": "0f8fbcb4-bc95-4005-9c54-4747eb2dc6b6",
  "CrossReferences": [],
  "evaluationFields": null,
  "intakeDATypeDetails": [
    {
      "caseID": "",
      "reason": "",
      "Summary": "",
      "DAStatus": "Approved",
      "comments": "SOI",
      "DaTypeKey": "247a8b26-cdee-4ce8-b36e-b37e49fd0103",
      "supStatus": "Approved",
      "agencyName": "",
      "agencyType": "",
      "GroupNumber": null,
      "supComments": "screen out: family resides in Baltimore City. Police observed child and intake was not accepted by Baltimore City",
      "GroupComment": null,
      "intakeAction": "",
      "issubtypekey": true,
      "DADisposition": "ScreenOUT",
      "agencyContact": "",
      "captureReason": "",
      "serviceTypeID": "",
      "ReasonforDelay": "",
      "supDisposition": "ScreenOUT",
      "GroupReasonType": null,
      "dispositioncode": "ScreenOUT",
      "ServiceRequestNumber": "I202100015250",
      "intakeserreqstatustypekey": "Review",
      "supMultipleDispositionDropdown": [],
      "intakeMultipleDispositionDropdown": []
    }
  ],
  "focuspersoncasedetails": []
}' where intakenumber = 'I202100015250' and activeflag= 1;
