-- CDM-9418 - Update education information in the case plan snapshot

update snapshothist set updatedby = 'CDM-9418', updatedon = now(), snapshotdata = '
[
  {
    "caseworker": "Brooke Davis",
    "serviceLogs": [
      {
        "cjamspid": "200007261",
        "fullname": " CHRISTOPHER  SEAL ",
        "personid": "64e3812d-a1c4-4503-b101-12f56865a0b7",
        "agencyServiceList": null,
        "referredServiceList": [
          {
            "zip": "21239",
            "notes": null,
            "status": "Forwarded to Case Supervisor",
            "tax_id": "520909347",
            "outcome": null,
            "authflag": true,
            "duration": "Not Specified/Not Applicable",
            "end_time": null,
            "frequency": "As Necessary",
            "courtorder": "N",
            "current_dt": "2021-01-26T05:00:00.000Z",
            "service_id": 1026,
            "start_time": null,
            "totalcount": "8",
            "duration_cd": "6056",
            "provider_id": 5001284,
            "provider_nm": "Nexus Woodbourne Family Healing",
            "frequency_cd": "6061",
            "service_name": "Remedial/Special Education (Paid) ",
            "service_type": "3334",
            "referred_date": "2020-12-01T05:00:00.000Z",
            "serviceplanid": null,
            "service_log_id": "1984270",
            "actual_end_date": "2020-12-22T05:00:00.000Z",
            "serviceplanname": null,
            "ongoingtransflag": true,
            "actual_start_date": "2020-12-01T05:00:00.000Z",
            "agency_program_nm": "Out of Home",
            "no_service_reason": null,
            "estimated_end_date": "2020-12-22T05:00:00.000Z",
            "service_end_reason": "Funding Terminated",
            "provider_service_id": "9694",
            "serviceplanactionid": null,
            "estimated_start_date": "2020-12-01T05:00:00.000Z",
            "no_service_reason_cd": null,
            "service_end_reason_cd": "1822 ",
            "serviceplanactionname": null,
            "agency_program_area_id": "OOH"
          },
          {
            "zip": "21239",
            "notes": null,
            "status": "Approved",
            "tax_id": "520909347",
            "outcome": null,
            "authflag": true,
            "duration": "Pre-arranged",
            "end_time": null,
            "frequency": "Five times weekly",
            "courtorder": "N",
            "current_dt": "2021-01-26T05:00:00.000Z",
            "service_id": 1026,
            "start_time": null,
            "totalcount": "8",
            "duration_cd": "6059",
            "provider_id": 5001284,
            "provider_nm": "Nexus Woodbourne Family Healing",
            "frequency_cd": "6067",
            "service_name": "Remedial/Special Education (Paid) ",
            "service_type": "3334",
            "referred_date": "2020-11-02T05:00:00.000Z",
            "serviceplanid": null,
            "service_log_id": "1974830",
            "actual_end_date": "2020-11-30T05:00:00.000Z",
            "serviceplanname": null,
            "ongoingtransflag": false,
            "actual_start_date": "2020-11-02T05:00:00.000Z",
            "agency_program_nm": "Out of Home",
            "no_service_reason": null,
            "estimated_end_date": "2020-11-30T05:00:00.000Z",
            "service_end_reason": "Service Completed",
            "provider_service_id": "9694",
            "serviceplanactionid": null,
            "estimated_start_date": "2020-11-02T05:00:00.000Z",
            "no_service_reason_cd": null,
            "service_end_reason_cd": "1824 ",
            "serviceplanactionname": null,
            "agency_program_area_id": "OOH"
          },
          {
            "zip": "21239",
            "notes": null,
            "status": "Approved",
            "tax_id": "520909347",
            "outcome": null,
            "authflag": true,
            "duration": "Not Specified/Not Applicable",
            "end_time": null,
            "frequency": "Daily",
            "courtorder": "N",
            "current_dt": "2021-01-26T05:00:00.000Z",
            "service_id": 1026,
            "start_time": null,
            "totalcount": "8",
            "duration_cd": "6056",
            "provider_id": 5001284,
            "provider_nm": "Nexus Woodbourne Family Healing",
            "frequency_cd": "6063",
            "service_name": "Remedial/Special Education (Paid) ",
            "service_type": "3334",
            "referred_date": "2020-10-01T04:00:00.000Z",
            "serviceplanid": null,
            "service_log_id": "1972077",
            "actual_end_date": "2020-10-31T04:00:00.000Z",
            "serviceplanname": null,
            "ongoingtransflag": false,
            "actual_start_date": "2020-10-01T04:00:00.000Z",
            "agency_program_nm": "Out of Home",
            "no_service_reason": null,
            "estimated_end_date": "2020-10-31T04:00:00.000Z",
            "service_end_reason": "Service Completed",
            "provider_service_id": "9694",
            "serviceplanactionid": null,
            "estimated_start_date": "2020-10-01T04:00:00.000Z",
            "no_service_reason_cd": null,
            "service_end_reason_cd": "1824 ",
            "serviceplanactionname": null,
            "agency_program_area_id": "OOH"
          },
          {
            "zip": "21239",
            "notes": null,
            "status": "Approved",
            "tax_id": "520909347",
            "outcome": null,
            "authflag": true,
            "duration": "Ongoing/Unlimited",
            "end_time": null,
            "frequency": "Other",
            "courtorder": "N",
            "current_dt": "2021-01-26T05:00:00.000Z",
            "service_id": 1026,
            "start_time": null,
            "totalcount": "8",
            "duration_cd": "6057",
            "provider_id": 5001284,
            "provider_nm": "Nexus Woodbourne Family Healing",
            "frequency_cd": "6071",
            "service_name": "Remedial/Special Education (Paid) ",
            "service_type": "3334",
            "referred_date": "2020-09-08T04:00:00.000Z",
            "serviceplanid": null,
            "service_log_id": "1968836",
            "actual_end_date": "2020-09-30T04:00:00.000Z",
            "serviceplanname": null,
            "ongoingtransflag": false,
            "actual_start_date": "2020-09-08T04:00:00.000Z",
            "agency_program_nm": "Out of Home",
            "no_service_reason": null,
            "estimated_end_date": "2020-09-30T04:00:00.000Z",
            "service_end_reason": "Funding Terminated",
            "provider_service_id": "9694",
            "serviceplanactionid": null,
            "estimated_start_date": "2020-09-08T04:00:00.000Z",
            "no_service_reason_cd": null,
            "service_end_reason_cd": "1822 ",
            "serviceplanactionname": null,
            "agency_program_area_id": "OOH"
          }
        ]
      }
    ],
    "jurisdiction": "Carroll",
    "assetsdetails": [
      {
        "facevalue": 0,
        "detailtype": "None",
        "assettypekey": "NON",
        "disposaldate": null,
        "purchasedate": "2020-07-08T00:00:00"
      }
    ],
    "fatherdetails": {
      "dob": "1971-08-29T00:00:00",
      "akaname": " ",
      "clientid": 200007639,
      "ssnvalue": null,
      "parentname": "David Seal",
      "phonenumber": null,
      "parentaddress": "615 Lynn Way  Sykesville MD 21784"
    },
    "headersection": {
      "dob": "2004-05-07T00:00:00",
      "cisid": "411055225",
      "mdm_id": "MDT-129414492",
      "enddate": "2021-01-04T05:00:00",
      "clientid": 200007261,
      "childname": "CHRISTOPHER SEAL",
      "startdate": "2020-09-06T04:00:00"
    },
    "incomedetails": [
      {
        "amount": 0.01,
        "enddate": null,
        "startdate": "2019-09-01T00:00:00",
        "detailtype": null,
        "incomesourcetypekey": null
      },
      {
        "amount": 0,
        "enddate": null,
        "startdate": "2020-07-08T00:00:00",
        "detailtype": "None - Earned",
        "incomesourcetypekey": "13"
      },
      {
        "amount": 0,
        "enddate": null,
        "startdate": "2020-07-08T00:00:00",
        "detailtype": "None - Unearned",
        "incomesourcetypekey": "4"
      }
    ],
    "motherdetails": {
      "dob": "1971-07-25T00:00:00",
      "akaname": " ",
      "clientid": 200007262,
      "ssnvalue": "***-**-6023",
      "parentname": "JOHANNA SEAL",
      "phonenumber": null,
      "parentaddress": "947 Lorimel Rd  Sykesville MD 21784"
    },
    "cplanquestions": {
      "dayCare": null,
      "iepDated": null,
      "parentName": "Johanna Seal",
      "refMadeDate": null,
      "respiteCare": null,
      "otherReasons": null,
      "reimbursement": null,
      "tprDeniedDate": null,
      "blockEComments": "Christopher is now attending Nexus-Woodbourne School as of his admission date to the facility in July 2020. He is expected to transition back to public school upon his discharge from Nexus-Woodbourne. ",
      "healthPassport": true,
      "schoolSchedule": null,
      "tprGrantedDate": null,
      "transportation": null,
      "discussServices": "The Department provides payment for Christopher to attend school at Nexus-Woodbourne while in placement, which is not covered by his public school education. There is ongoing discussion regarding his visitation, treatment and care while at the facility, ongoing with his parents and therapist and also during monthly treatment team meetings. ",
      "faceToFaceVisit": null,
      "specialTraining": null,
      "tprPetitionDate": null,
      "writeOtherReson": "Payment for special education while in placement",
      "atOrNearAgeLevel": "At grade level",
      "diagnosedAxisOne": false,
      "diagnosedAxisTwo": false,
      "financialSupport": true,
      "lengthOfHomeless": "N/A",
      "outOfHomeService": "Not determined at this time. ",
      "addressChildNeeds": "Contact notes for monthly visits with Christopher are detailed above. Worker visits with him in-person, remains in communication with Mr. and Mrs. Seal,  Christopher''s therapist at his placement and participates in monthly treatment team meetings. Christopher''s medical, educational, and mental health needs and services are reviewed and discussed. ",
      "diagnosedAxisFive": false,
      "diagnosedAxisFour": false,
      "episodeExperience": "No",
      "isChildCoComitted": "No",
      "reasonTPRPetition": null,
      "diagnosedAxisThree": false,
      "childInAndOutOfHome": "No-this case is a VPA",
      "currentRelationship": "Chris continues to work on managing his emotions, improving communication skills with others especially when upset or angry, and working on improving his self-esteem.  Relationship dynamics within the family including Christopher feeling unsupported by his father are actively being worked on in family therapy. Mr. and Mrs. Seal have been very involved in Christopher''s treatment and are committed to continuing to work together to improve family relationships. ",
      "tprAppealDateFather": null,
      "tprAppealDateMother": null,
      "educationProgramGoal": "High School Diploma-June 2022",
      "servicesForStability": null,
      "discussVisitationPlan": "Visitation is coordinated by Woodbourne and Mr./Ms. Seal as deemed therapeutically appropriate. Visits may include video calls or on grounds visits. Both Mrs. Seal and Christopher separately indicated the family visits have gone well so far. Christopher’s two older sister also visited, along with both of his parents. Chris had a 2-day home pass over Thanksgiving and for Christmas.  ",
      "explainChangeOfSchool": "Christopher needed to attend school at his placement which is part of the program requirement. ",
      "conditionsAndAllergies": null,
      "discussionOfVisitation": true,
      "episodesOfHomelessness": "No ",
      "lastprogressreportdate": null,
      "parentChildInteraction": "Visitation between Christopher and his family, including during two weekend home passes, have gone well. There has been appropriate communication and interaction reported. They all reported enjoying the home passes and look forward to another being approved. ",
      "placementChangedSchool": "Yes",
      "schoolProximityToPrior": "No, he is placed out of county .",
      "childEnrolledInFiveDays": "Yes, Christopher was enrolled in school at Nexus-Woodbourne upon admission to the facility. He participated in the summer session of school. This is listed in the education section but is not populating into this screen above. ",
      "diagnosedAxisOneComment": "",
      "diagnosedAxisTwoComment": "",
      "discussionOfChildsNeeds": null,
      "problemsWithPeersBlockD": null,
      "problemsWithPeersBlockE": null,
      "sixMonthsPlacementExpln": null,
      "behavioralProblemsBlockD": null,
      "behavioralProblemsBlockE": null,
      "diagnosedAxisFiveComment": "",
      "diagnosedAxisFourComment": "",
      "emotionalSupportGuidance": true,
      "episodeExperienceExplain": null,
      "juvenileCourtInvolvement": "No",
      "schoolAdjustmentComments": "School information for Woodbourne is updated in the education section but is not populating into this area. ",
      "servicecourtorderdetails": "Court was held on 12/15/20 for continuation of the VPA. The current Court order does not outline specific Court orders pertaining to Christopher but does grant continuation of the VPA with a follow-up court hearing scheduled for 6/15/21.",
      "describeStrengthsAndNeeds": "Christopher will be evaluated for an IEP at the request of his Mother, Mrs. Seal. She is concerned about him returning to public school without more support in place academically and given his mental health diagnoses. She feels he is benefitting from the smaller learning environment his current school is providing. ",
      "diagnosedAxisThreeComment": "",
      "extraCurricularActivities": null,
      "physicalOrMentaldiagnosis": "Christopher''s current diagnosis are as follows-Major Depressive Disorder, recurrent episode, moderate (primary) Attention Deficit-Hyperactivity Disorder Oppositional Defiant Disorder  Anxiety Cannabis Dependence Nicotine Dependence ",
      "childCurrentReportCardCopy": "Yes, quarter 1 report card is in the filing cabinet. ",
      "faceToFaceVisitContactDate": null,
      "individualEducationProgram": "N/A",
      "passportRecordConfirmation": "Provided to placement at admission",
      "servicesForPermanencyOther": "Individual therapy, substance abuse group, medication management, family therapy",
      "specifyTheNeedsAndServices": null,
      "supportiveServicesRequired": "Not determined at this time. The plan for this VPA case is reunification home to parents. ",
      "faceToFaceVisitAuthoredDate": null,
      "passportRecordConfirmedDate": "2020-07-09T04:00:00.000Z",
      "tprAppealDecisionDateFather": null,
      "tprAppealDecisionDateMother": null,
      "utilizationOrNonUtilization": "None at this time. Christopher is not yet in active discharge planning phase. There will be appropriate assessment for relevant community and in-home supports when he enters the discharge planning phase. ",
      "visitationcourtorderdetails": "Continuation of Voluntary Placement granted 12/15/20 with a subsequent hearing date of 6/15/21.",
      "educationalServicesReceiving": "Educational services in line with his 11th grade curriculum. Mrs. Seal requested an IEP through Baltimore City Public Schools. A meeting is scheduled for the first week of February. ",
      "servicesForPermanencyClients": [
        "200007261"
      ],
      "voluntarySignatureDateFather": null,
      "voluntarySignatureDateMother": null,
      "educationalParentSurrogateName": null,
      "eighteenToTwentyOneChildStatus": "N/A",
      "isChildEnrolledInSpecialProgram": "N/A",
      "educationalParentSurrogateAddress": null,
      "educationalParentSurrogateWeakness": null,
      "educationalParentSurrogateRequested": null,
      "educationalParentSurrogateStrengths": "Christopher had zero absences through the first quarter. He received one A, one B and the rest C''s or passing grades. ",
      "facilitatePermanencySelfSufficiency": "Christopher and his family speak regularly and visit on a weekly basis. He had two home passes so far, one for Ther on aanksgiving and another over Christmas. They participate in family therapy together on a bi-weekly basis. Christopher and his parents are actively working towards reunification. Monthly treatment team meetings are held at the beginning of each calendar month and review Christopher''s placement and progress as it relates to family reunification. ",
      "discussChildCurrentEducationalSetting": "Christopher is attending school on site at Nexus-Woodbourne. He is participating in school both in person and virtually, in a hybrid model. He is in the most appropriate educational setting at this time. ",
      "facilitatePermanencySelfSufficiencyEndDate": "2021-01-08T05:00:00.000Z",
      "facilitatePermanencySelfSufficiencyStartDate": "2020-07-09T04:00:00.000Z"
    },
    "supportdetails": null,
    "childannualexam": null,
    "childinitialexam": null,
    "childremovaldate": "2020-07-08T00:00:00",
    "childfollowupexam": null,
    "servicecasenumber": "2020011501151",
    "childremovalreason": "(\"Child’s Behavior Problem\"),(\"Drug Abuse (Child)\"),(\"Voluntary Placement\")",
    "servicecourtdetails": null,
    "placementinformation": [
      {
        "address": "Name: Nexus-Woodbourne Family Healing- DETP - CSE Address: 1301 Woodbourne Baltimore Md 21239 Phone Number: ",
        "cpahomes": null,
        "serviceid": 14,
        "enddatetime": null,
        "servicename": "Residential Group Homes",
        "placementtype": "Placement",
        "startdatetime": "2020-07-08T00:00:00",
        "livingarrangementtype": null,
        "livingarrangementaddress": "Name:  Address: Woodbourne  Baltimore Md 21239 Phone Number: "
      }
    ],
    "assessmentinformation": [
      {
        "outcome": "",
        "assessmentname": "MARYLAND FAMILY RISK REASSESSMENT",
        "assessmentcompletiondate": "2020-12-14T07:15:14"
      },
      {
        "outcome": "",
        "assessmentname": "CANS-OUT OF HOME PLACEMENT SERVICE",
        "assessmentcompletiondate": "2020-12-14T07:04:59"
      },
      {
        "outcome": "",
        "assessmentname": "SAFE-C OHP",
        "assessmentcompletiondate": "2020-11-22T15:38:32"
      }
    ],
    "childdbehaviourhealth": null,
    "childlegalinformation": [
      {
        "courtdocketnum": "C-06-JV-20-000104",
        "hearingdetails": [
          {
            "hearingdate": "2020-12-15T11:00:00",
            "hearingtype": "Voluntary Placement Hearing",
            "hearingstatus": "Concluded"
          }
        ],
        "childattorneyinfo": null
      }
    ],
    "visitationcourtdetails": null,
    "childtprlegalinformation": null,
    "caseworkerservicesandplan": {
      "establisheddate": "2020-07-09T04:00:00",
      "cuurentplacetolive": "Residential Group Homes",
      "permanancyplandata": {
        "lifebookExpln": "Not at this time, it is a VPA case. ",
        "isProviderAgree": "1",
        "permToPermExpln": "N/A",
        "courtOrdersExpln": "This is a VPA case so there are no current court orders at this time. Court will be held prior to 1/9/21.  ",
        "safeAndCareExpln": "The Department is ensuring Christopher''s needs are met by his placement in compliance with the terms of the VPA.",
        "isInClosedProximity": "1",
        "isProviderAgreeExpln": null,
        "assessmentPeriodExpln": "Family therapy will be starting as will in person visits with Christopher and his family in accordance with the placement''s protocols for COVID-19.",
        "serviceAgreementExpln": "A service agreement will be established now that the case is open and will reflect the terms of the VPA they agreed to and signed. ",
        "meetingSafetyNeedsExpln": null,
        "sixMonthsPlacementExpln": "Christopher was placed at Woodbourne RTC for a VPA placement on 7/9/20. His placement there will be reassessed ongoing and reviewed prior to 6 months from admission to discuss discharge recommendations and planning. ",
        "isInClosedProximityExpln": "Located within one hour",
        "serviceAgreementForOtherExpln": "Visitation and contact is flexible and as arranged between the parents and the placement. "
      },
      "facetofacecontactdate": [
        {
          "insertedon": "2020-09-10T15:52:24",
          "contactdate": "2020-09-10T00:00:00"
        },
        {
          "insertedon": "2020-10-15T13:54:43",
          "contactdate": "2020-10-14T00:00:00"
        },
        {
          "insertedon": "2020-11-17T11:11:24",
          "contactdate": "2020-11-16T00:00:00"
        },
        {
          "insertedon": "2020-12-14T15:25:31",
          "contactdate": "2020-12-14T00:00:00"
        }
      ],
      "primarypermanencytype": "Reunification",
      "treatmentteameetingdate": null,
      "concurrentpermanencytype": "Guardianship by relative"
    },
    "childeducationinformation": [
      {
        "end_dt": null,
        "sasidno": null,
        "setting": "Private",
        "tel_num": null,
        "start_dt": "07/09/2020",
        "school_nm": "Nexus-Woodbourne",
        "grade_last": "Grade 10",
        "mode_trans": "Other",
        "type_class": "High School",
        "edu_program": null,
        "exit_reason": null,
        "grade_current": "Grade 11",
        "fungrade_level": null,
        "school_address": "Nexus-Woodbourne,,Maryland",
        "special_ed_code": null,
        "quarterly_grade1": "Good",
        "quarterly_grade2": null,
        "quarterly_grade3": null,
        "quarterly_grade4": null
      }
    ],
    "childdisabilityinformation": null,
    "childemploymentinformation": null,
    "childmedicationinformation": null
  }
]
' where id='79a6ed34-25e0-4322-b99d-11da413bcc27' and activeflag=1;