/*
   Issue Description: CDM-29656
   Category/ Module  :  I231010545526 attempting to case connect referral, service case #3307792. 
   user missed the pop up window to crete servicecase, so system autogenerated the new service case.
   Root cause: User error case connect
   Pull request# for code fix: 8545
   Reason why no related code fix: 
   user error - requested a data fix
*/
select * from cjams.createservicecase
('c5fa46aa-097a-4aac-bfa8-3853ef97077c', '45cbd5dc-3a38-452e-9395-28d6d36c267e', 0, 'ba2dbc8f-3213-4b1b-9905-d643e1692db1','intake');