/*
 *
 *
 *
 *{"intakeservreqchildremovalid":"d871f8cb-1a5d-4e4f-8729-e1de71f5c5d0","familystructuretypekey":"288","agencytypekey":"RTC","isdisability":null,"removaltypekey":"CDVP","removaldate":"2021-09-22T00:00:00","exitdate":null,"exittime":null,"removaltime":"2021-09-22T11:00:00","rmvdfrmpersonname":null,"primarycaregiveractorid":"07c30a26-a1ed-48a0-854f-c013aec2b78a","seccaregiveractorid":null,"removaladd1":"7840 Hampton Way, Owings, MD","vpabegindate":"2021-09-22","vpaenddate":"2022-03-22T00:00:00","vpaparentssigneddate":null,"parent2signeddate":null,"vpaguardiansigneddate":"2021-09-22","parent1id":null,"parent2id":null,"guardianid":200775433,"vpa2parentssigneddate":null,"parent2sigmissreason":null,"primarycaregiveradd":"7840 Hampton Way, Owings, MD","ischildaddressasprimaryaddress":1,"childhomeaddress":null,"childphysicalremovaladdress":null,"ischildphysicalremovaladdressverified":null,"seccaregiveradd":null,"isverifiedcaregiver1add":1,"isverifiedcaregiver2add":0,"vpayouthsigneddate":null,"isbothparentssigned":2,"volrelinquishment":1,"agencysigneddate":"2021-09-22T00:00:00","removalreason":["CBP","VP","CD"],"removalexitreason":null,"caregiverreason":null,"reasonableefforts":["INCC","SES","HOSP","FSS","FPS","REMNH"],"notmakingefforts":null,"specifiedrelativename":null,"returndate":null,"returntime":null,"specifiedrelativedatechildlastlivedwith":null,"exitreason":null,"parent2comments":"2nd Parent Signature date","comments":"The recommendation for Ellis is for a structured and twenty-four-hour supportive setting in a residential treatment center that includes intensive ongoing therapy and medication management to work on developing necessary coping skills for Ellis’s safety as well as the safety of her family and others.","reasonableeffortsmade":null,"isverifiedreporteradd":1,"placement":"","familyhistory":"","childdesc":null,"justification":"Placement in RTC per recommendation.","familystructuretypekeyref":"Divorced Female","agencytypekeyref":"Residential Treatment Center","removaltypekeyref":"Children With Disabilities Voluntary Placement","primarycaregiveractoridref":"Dawn Bunting - 200775433","seccaregiveractoridref":null,"parent1idref":null,"parent2idref":null,"removalreasonref":"Child’s Behavior Problem, Child’s Disabilities, Voluntary Placement","removalexitreasonref":null,"reasonableeffortsref":", Family Preservation Services, Family Support Services, Hospitalization, Individual Crisis Counseling, Routine/Emergency Mental Health, Social/Emotional Support","notmakingeffortsref":null,"isuploadedmanually":1,"isshelterauthcompleted":1}
 */
update intakeservreqchildremoval_history set parent2comments = null, actualdata = '{
  "intakeservreqchildremovalid": "d871f8cb-1a5d-4e4f-8729-e1de71f5c5d0",
  "familystructuretypekey": "288",
  "agencytypekey": "RTC",
  "isdisability": null,
  "removaltypekey": "CDVP",
  "removaldate": "2021-09-22T00:00:00",
  "exitdate": null,
  "exittime": null,
  "removaltime": "2021-09-22T11:00:00",
  "rmvdfrmpersonname": null,
  "primarycaregiveractorid": "07c30a26-a1ed-48a0-854f-c013aec2b78a",
  "seccaregiveractorid": null,
  "removaladd1": "7840 Hampton Way, Owings, MD",
  "vpabegindate": "2021-09-22",
  "vpaenddate": "2022-03-22T00:00:00",
  "vpaparentssigneddate": null,
  "parent2signeddate": null,
  "vpaguardiansigneddate": "2021-09-22",
  "parent1id": null,
  "parent2id": null,
  "guardianid": 200775433,
  "vpa2parentssigneddate": null,
  "parent2sigmissreason": null,
  "primarycaregiveradd": "7840 Hampton Way, Owings, MD",
  "ischildaddressasprimaryaddress": 1,
  "childhomeaddress": null,
  "childphysicalremovaladdress": null,
  "ischildphysicalremovaladdressverified": null,
  "seccaregiveradd": null,
  "isverifiedcaregiver1add": 1,
  "isverifiedcaregiver2add": 0,
  "vpayouthsigneddate": null,
  "isbothparentssigned": 2,
  "volrelinquishment": 1,
  "agencysigneddate": "2021-09-22T00:00:00",
  "removalreason": [
    "CBP",
    "VP",
    "CD"
  ],
  "removalexitreason": null,
  "caregiverreason": null,
  "reasonableefforts": [
    "INCC",
    "SES",
    "HOSP",
    "FSS",
    "FPS",
    "REMNH"
  ],
  "notmakingefforts": null,
  "specifiedrelativename": null,
  "returndate": null,
  "returntime": null,
  "specifiedrelativedatechildlastlivedwith": null,
  "exitreason": null,
  "parent2comments": null,
  "comments": "The recommendation for Ellis is for a structured and twenty-four-hour supportive setting in a residential treatment center that includes intensive ongoing therapy and medication management to work on developing necessary coping skills for Ellis’s safety as well as the safety of her family and others.",
  "reasonableeffortsmade": null,
  "isverifiedreporteradd": 1,
  "placement": "",
  "familyhistory": "",
  "childdesc": null,
  "justification": "Placement in RTC per recommendation. Biological father is unknown",
  "familystructuretypekeyref": "Divorced Female",
  "agencytypekeyref": "Residential Treatment Center",
  "removaltypekeyref": "Children With Disabilities Voluntary Placement",
  "primarycaregiveractoridref": "Dawn Bunting - 200775433",
  "seccaregiveractoridref": null,
  "parent1idref": null,
  "parent2idref": null,
  "removalreasonref": "Child’s Behavior Problem, Child’s Disabilities, Voluntary Placement",
  "removalexitreasonref": null,
  "reasonableeffortsref": ", Family Preservation Services, Family Support Services, Hospitalization, Individual Crisis Counseling, Routine/Emergency Mental Health, Social/Emotional Support",
  "notmakingeffortsref": null,
  "isuploadedmanually": 1,
  "isshelterauthcompleted": 1
}'
, modifieddata = '{"justification": "Placement in RTC per recommendation. Biological father is unknown"}'
,updatedby='CDM-21143', updatedon=now() where intakeservreqchildremovalhistoryid = '18281d3c-d756-4693-af71-73902457f6ef' and activeflag = 1;