-- CDM-43113 - Allegation disposition is doubled
/*
 -- Issue Description: In this case, investigation tab is showing duplicated result
 --  case number: 241022830590
 -- Category/ Module: Investigation Findings
 -- Root cause: Two records were created in investigation findings.
 -- Fix Provided: Datafix has been added by deleting the record against investigation allegation id and allegation id.
 -- Pull request# N/A 
 -- Reason why no related code fix: N/A
 -- Status of the code fix if already submitted and expected prod fix date: N/A
 */

--reverting previous commit
UPDATE cjams.investigationallegation
SET activeflag=1,
updatedby='CDM-43113',
updatedon=now()
WHERE investigationallegationid='ee5f1254-5a65-4290-bf76-ec2218fb0398'
and allegationid='2482ea5f-2cfa-434c-b2e7-e0501371b961' and activeflag=0;

--updating current value
UPDATE cjams.investigationallegation
SET activeflag=1,
updatedby='CDM-43113',
updatedon=now()
WHERE investigationallegationid='4a7743a8-7b56-4904-aaa0-8962cffadbfa'
and allegationid='627b574e-aa98-48c1-98c3-cf6f5d155eff' and activeflag=0;

UPDATE cjams.investigationallegation
SET activeflag=1, 
updatedby='CDM-43113', 
updatedon=now(), "comments"='Ms. Racheal Ssekiranda stated that her son Daniel Miriti attacked her and she defended herself by hitting him with a belt. The two started to tussle and the child hit his head on the lap top computer causing a gash.',
incidentdate='2024-08-18 00:00:00.000',  timeofincidence='2024-10-09 12:00:00.000', 
victim_explanation='On 08/27/24 at Digital Harbor High School at 1100 Covington St, Baltimore, MD 21230, Daniel Miriti (12/16/09) disclosed different occurrences of the two fighting. He explained that at 2am after a verbal altercation the previous day, Ms. Racheal Ssekiranda (12/16/87) woke him up out of his sleep by beating him with a belt, he grabbed the belt, and she began scratching him and trying to bite him, while saying things like "I brought you into this world and I can take you out." Daniel expressed that he and Ms. Ssekiranda fought over a laptop she had taken from him, he reported that he pushed Ms Ssekiranda to the ground and her desktop computer fell on him causing a gash in his forehead. Daniel reported that he has never seen Ms. Ssekiranda with a gun. Daniel states he doesn''t know why Ms. Ssekiranda does these things.
On December 4, 2024, at 300 Saint Paul Pl, Baltimore, MD 21202, Daniel Miriti (12/16/09) reported that things have been good between him and his mother Ms. Racheal Ssekiranda (12/16/87). The child reported that he feels good about living back at home and "not much has been going on." He stated that there hasn’t been any physical altercations or issues since being back in Ms. Ssekiranda’s care. In reference to medication, he reported that he feels careless and doesn''t worry so much anymore; he feels like the medication is working. In reference to the reported incident, the child refused to talk about it. Daniel repeatedly stated, "I don''t want to talk about it" while shaking his head no. He further explained "In therapy they told me let the past be the past." When asked if there are any reason(s) why he didn''t want to talk about the fight and he stated no he didn''t have one and just doesn''t want to talk about it. The child shared that he and Ms.Ssekiranda are getting along better now. When asked if he could elaborate on him and his mother''s relationship he refused. The child declined having concerns about Ms. Ssekiranda’s parenting and discipline. Daniel reported that he feels safe at home with Ms. Ssekiranda.  ',
sibling_explanation='N/A', 
guardian_explanation='On September 16, 2024, over the phone, Mr. Samuel Miriti (08/21/77) reported that he hasn''t been having any issues with Daniel''s behavior. He stated that he is trying to protect Daniel, his wife Florence Ferguson, and their 7-year-old son from negative behaviors to protect the entire family. Mr. Miriti informed that Daniel, and the 7-year-old child will be always supervised to assure Daniel isn''t aggressive with the child. Daniel reportedly listens to his dad more, so Ms. Ferguson will allow Mr. Miriti to lead more. Mr. Miriti reported that when he spoke to Ms. Ssekiranda about the incidents between her and Daniel, they both blame each other, do not have a good dynamic, and Ms. Ssekiranda didn''t feel safe. Mr. Miriti reported that he and his wife are working on getting Daniel evaluated and enrolled in mental health services.
On December 4, 2024, over the phone, Mr. Miriti reported that on Friday 10/18, Daniel Miriti (12/16/09) had gotten into an argument with his stepmom Florence Ferguson (8/11/77) where Daniel was threatening to kill her. Ms. Ferguson called the police, and upon their arrival he was still hostile threatening to beat her up and shoot her. The police transported the child to Holy Cross Hospital at 1500 Forest Glen Rd, Silver Spring, MD 20910. The child spent 10/18-10/23 at Holy Cross Hospital and was transferred to Sheppard Pratt at 7220 Discovery Dr, Elkridge, MD 21075. Mr. Miriti reported that this was the first time an incident like this has happened while in his care. Mr. Miriti stated that overall he thought Daniel was doing okay, and he had no issues with the child’s behavior, and the family was discussing Mr. Miriti gaining custody. Mr. Miriti disclosed that he wasn''t aware of what was going on with Daniel because he says everything is "Good" and "Fine" every time Mr. Miriti asks about how his day and school was. Mr. Miriti stated that Daniel was not communicating with him. Mr. Miriti explained that Daniel expressed that Ms. Ferguson doesn''t like him nor want him there; Mr. Miriti asked if she has ever said that, and that child claimed he can feel it. Mr. Miriti shared he believes this is where the argument on 10/18 derived from. Mr. Miriti explained that he doesn''t trust Daniel in his home because Ms. Ferguson fears him; therefore the child returned to Ms. Ssekiranda’s care. Mr. Miriti has not had any contact with the child. Mr. Miriti stated that Daniel is home with Ms. Ssekiranda who has gotten him the help he needs.', 
maltreator_explanation='On 08/21/24 at 300 St Paul Pl, Baltimore, MD 21202, Ms. Racheal Ssekiranda (12/16/87) stated that Daniel Miriti (12/16/09) attacked her over a laptop and cellphone that she took from him. She explained that Daniel aggressively and repeatedly demanded to have his laptop back and told Ms. Racheal Sserikanda (12/16/87) that he was going to take her work laptop if she didn''t give his back. She further explained that they began tussling over the laptop and they both fell to which Daniel started punching and repeatedly slamming Ms. Ssekiranda onto the floor. She reported that Daniel got a gash on his forehead and was bleeding due to the fall and hitting his head on the computer desk while she has bruises. Ms. Ssekiranda disclosed that during the altercation, Daniel yelled things like "I don''t get any freedom. I don''t get to do what I want. I want my laptop mom, I don''t care." She disclosed that Daniel doesn''t listen to authority and has behavioral issues since he was a child. The child was sent to live with his father, Samuel Miriti (08/21/77) at 14206 Greenview Dr, Laurel, MD, following this incident. 
On December 3, 2024, at 300 Saint Paul Pl, Baltimore, Maryland 21202, Ms. Racheal Ssekiranda (12/16/87) reported that Daniel Miriti (12/16/09) returned to her care because Mr. Samuel Miriti (08/21/77) refused to pick the child up upon his discharge from Sheppard Pratt at 7220 Discovery Dr, Elkridge, MD 21075, due to Daniel''s hostility and threats to harm his wife Florence Ferguson (08/11/77). Ms. Ssekiranda explained that Mr. Miriti has cut communication with Daniel, and he is not allowed at his home even to visit. In reference to the reported incident, she explained that Daniel wanted his laptop that she had taken away, and he tried to take her work laptop saying, "Now that you took my laptop, I''m going to take yours." The two began wrestling over the laptop. Ms. Ssekiranda denied punching Daniel but shared that she fell to the floor, and he continuously punched her. She further explained that she ran in her bedroom to call the police. Stated that she kept trying to walk away and disengage but the child kept following her and punching her. Ms. Ssekiranda reported that she said she was going to get her gun to scare Daniel because the police were taking too long. Daniel ran out the house and she locked herself in the bathroom. Ms. Ssekiranda reported that she does not own a gun but wanted to scare the child. She is unsure of what point he got the gash on his forehead and just remembers seeing blood in the area "It all happened so fast," she reported. Ms. Ssekiranda reported that now Daniel is consistent with mental health services and medication daily. Daniel sees a therapist, Mr. Reginal Bowers once a week and a psychiatrist, Dr. Barbara Sartell, once a month; both services started in November and are through All By The Grace. Ms. Ssekiranda shared that she does family therapy with Daniel. Daniel takes Prozac and Abilify for ADHD, Major Depressive Disorder, and Oppositional Defiant Disorder and is reportedly doing great on the medication. She observed that the child has calmed down, smiles more, more mellow, and his mood doesn''t change so often. The two are able to discuss things better and enjoy activities together now. There haven’t been any physical altercations since his return home as his behavior completely changed. ', 
med_assessmnts='On 8/18/24 at Johns Hopkins Hospital at 1800 Orleans St, Baltimore, MD 21287, Physician Jennifer Forest Anders, MD reported that “Daniel was not in any acute distress and had a normal appearance. He had a normal heart rate and regular rhythm. He was experiencing normal breath sounds. He had an abrasion to the center of the forehead with dried blood, no active bleeding, no gaping wound along with several superficial abrasions/ welts on the neck and upper arms. He appeared to have normal behavior and be alert and oriented to person, place, and time.
-Child report of physical altercation with mother, child with multiple minor wounds consistent with physical assault – there are some marks that appear consistent with fingernails scratched (per history) and others with curvilinear form possibly consistent with a looped belt or cord. Possible physical child abuse. Discussed with Officer Hassan and CPS Social Worker at bedside. CPS states plan for Safety Plan and discharge with mother. Patient expresses his desire to go home and for mother to come back to the room with him. Deferred to CPS/police on whether mother can be brought to the room vs stay in the wait room. SW expected in by 830 for further liaison with CPS.”
On November 12, 2024 at Sheppard Pratt at 7220 Discovery Dr, Elkridge, MD 21075, Registered Nurse Gwendolyn Johnson, reported that the child was admitted for relapse of illness. His diagnosis for this admission was Oppositional Defiant Disorder, ADHD, Pharyngitis, Major Depressive Disorder, mild acne, and tobacco use within 30 days of admission. The child''s discharge plan is to follow up with a scheduled appointment with the psychiatrist Barbara Sartell within 7 days of discharge. Daniel was prescribed Fluoxetine (Prozac) and Aripiprazole (Abilify). The child was discharged to his mother Racheal Ssekiranda. ', 
expert_assessmnts='On December 4, 2024, via phone call, Mr. Reginal Bowers reported that he sees the Daniel Miriti (12/16/09) for therapy and meets with him once a week. Mr. Bowers shared that their first meeting was at Daniel and Ms. Racheal Ssekiranda’s (12/16/87) residence and he didn’t see anything out of the ordinary between the two. He stated that overall, Daniel seemed like a normal kid. He described the child as really “flat,” and strongly suggested that the medication is causing him to have no expression due to a lack of facial expressions and smiling. Mr. Bowers explained that he is still getting to know the child and figuring out the situation. Mr. Bowers reported that Daniel expressed to him that the medication takes away his worries. Mr. Bowers has observed the child doing things with no problem whether he is or isn’t asked to. Mr. Bowers stated that their encounters are too new to provide further information but feels that overall the child is in a good place and sees no issues or concerns. ', 
collateral_interviews='On 08/21/24 at 300 St Paul Pl, Baltimore, MD 21202, Ms. Denise Law, a neighbor, reported that she heard Ms. Racheal Ssekiranda (12/16/87) yelling in the hallways of the apartment building "Help, help, help" as she found the mother and child tussling. She stated that Daniel Miriti (12/16/09) was persistent about getting his cellphone from her. Ms. Denise has also witnessed Daniel be aggressive toward his mother over the phone insisting that she stops working because he wants her to or to cook for him. Ms. Denise explained that she feels the child doesn''t have issues with listening to authority overall rather has resentment toward his mother and treats her as such. ', 
criminal_history_inv='During this investigation, Ms. Ssekiranda received a summons to attend court on 12/4/2024.', 
home_conditions='This worker conducted a home visit to 300 St Paul Pl, Baltimore, MD, 21202.The home had two bedrooms, two bathrooms, one living room, and kitchen.  The residence met all the basic health and sanitation needs required. There were no issues of utilities working improperly. The residence did not appear to have any rodent or insect infestation present. The home had an adequate amount of food and hygiene necessities present. The child has his own room and bed.', 
law_enforcement_inv='On 8/18/24  Officer Hassan (Badge #184), responded to a 9-1-1 call at 300 St Paul Pl, Baltimore, MD 21202 (CC #240805664). According to Officer Hassan, Ms. Ssekiranda stated that Daniel threatened her with a knife and Daniel stated that his mother threatened to shoot him with a gun. The officer transported Daniel to Johns Hopkins Hospital for evaluation.' 
WHERE investigationallegationid='4a7743a8-7b56-4904-aaa0-8962cffadbfa'::uuid;
