-- Revert case connect

update intakeservicerequest i set servicecaseid = null,updatedby = 'CDM-13777', updatedon = now() 
where servicerequestnumber = '211020114260' and intakeserviceid = 'd35f09ef-d151-46a9-9aca-8a0bb9c47092';

--updating statuses 

update cjams.intakesnapshot set activeflag =0, updatedby ='CDM-13777', updatedon =now() where intakenumber ='I211010162864';

update cjams.routing set routingstatustypeid =1, updatedby ='e4018de0-28aa-499d-886c-3ebcc314a109' where objectid ='I211010162864';

update cjams.intakedastatus set status = null, updatedby ='e4018de0-28aa-499d-886c-3ebcc314a109' where intakenumber ='I211010162864';

update cjams.intakedastaging set ispreintake ='false' where intakenumber ='I211010162864';

-- Updating previous version of json data 

update cjams.intakedastaging set status ='pending', updatedon =now(),jsondata ='{
  "sdm": {
    "isar": false,
    "isir": false,
    "worker": "",
    "comments": "",
    "countyid": null,
    "isschool": false,
    "provider": [],
    "screenIn": {},
    "immediate": "No Immediate",
    "screenOut": {
      "duplicatereportflag": null
    },
    "referralid": "",
    "reportdate": null,
    "riskofHarm": {
      "isnegrh_exposednewborn": true
    },
    "supervisor": "",
    "workerdate": null,
    "badgenumber": "",
    "isoutofhome": false,
    "referraldob": null,
    "sexualAbuse": {},
    "maltreatment": "no",
    "recordnumber": "",
    "referralname": "",
    "allegedvictim": [
      {
        "victimname": " Allen  King "
      }
    ],
    "childfatality": "no",
    "immediateList": {
      "immediateList6": null,
      "isimmed_allegation": null,
      "isimmed_otherspecify": null,
      "isimmed_seriousinjury": null,
      "isimmed_childfaatility": null,
      "isimmed_childleftalone": null
    },
    "isreportmeets": false,
    "issexualabuse": false,
    "physicalAbuse": {},
    "providerKnown": null,
    "generalNeglect": {},
    "immediateList6": null,
    "ismaltreatment": false,
    "supervisordate": null,
    "cpsResponseType": null,
    "ischildfatality": false,
    "isfinalscreenin": "Ovr_as_noncps",
    "noImmediateList": {
      "isnoimmed_risk_harm": false,
      "isnoimmed_sexualabuse": false,
      "isnoimmed_mentalinjury": false,
      "isnoimmed_physicalabuse": false,
      "isnoimmed_neglectresponse": false,
      "isnoimmed_substantial_risk": true
    },
    "officerlastname": "",
    "unattendedChild": {},
    "arGeneralNeglect": {},
    "isdeathorserious": false,
    "isrecsc_scrrenin": false,
    "officerfirstname": "",
    "allegedmaltreator": [
      {
        "maltreatorsname": "ELYSSA P KING"
      }
    ],
    "childUnderOneYear": "",
    "childunderoneyear": "No",
    "islicenseddaycare": false,
    "isrecsc_screenout": false,
    "officermiddlename": "",
    "isimmed_allegation": null,
    "isprivateplacement": false,
    "issignordiagonises": false,
    "screeningRecommend": "accept_as_noncps",
    "duplicatereportflag": null,
    "isnoimmed_risk_harm": false,
    "scnRecommendOveride": "",
    "disqualifyingFactors": {},
    "isfcplacementsetting": false,
    "isimmed_otherspecify": null,
    "disqualifyingCriteria": {
      "isoutofhome": false,
      "isreportmeets": false,
      "issexualabuse": false,
      "isdeathorserious": false,
      "issignordiagonises": false
    },
    "isimmed_seriousinjury": null,
    "isnoimmed_sexualabuse": false,
    "providerunknowndetail": null,
    "isimmed_childfaatility": null,
    "isimmed_childleftalone": null,
    "isnegrh_exposednewborn": true,
    "isnoimmed_mentalinjury": false,
    "isnoimmed_physicalabuse": false,
    "isnegfp_cargiverintervene": false,
    "isnegmn_unreasonabledelay": false,
    "isnoimmed_neglectresponse": false,
    "isnoimmed_substantial_risk": true,
    "ismenab_psycologicalability": false,
    "ismenng_psycologicalability": false
  },
  "agency": "CW",
  "roacps": null,
  "General": {
    "Time": "2021-06-01T16:18:50.326Z",
    "Iscps": null,
    "Agency": "CW",
    "Author": "JamieCugler",
    "Purpose": "247a8b26-cdee-4ce8-b36e-b37e49fd0103~CW",
    "countyid": "1e886503-ef0a-450c-8607-566c45fa75e4",
    "Narrative": "<p>After Hours Referral:</p><p>2:00 P.M. -Worker Waller received a call from Somerset Central. Worker was informed to phone Annie Boyer at Tidal Health Hospital.</p><p>&nbsp;</p><p>Worker immediately contacted Ms. Annie Boyer at Tidal Health who wanted to report a SEN’S case. Ms. Boyer informed this worker that she was the reporter and that the attending Social Worker was Sandra Welch. Ms. Welch spent time with the family while in the hospital.</p><p>&nbsp;</p><p>Worker was informed by Annie Boyer at Tidal Health that she was calling with a report of a newborn exposed to Marijuana.</p><p>&nbsp;</p><p>That on 5/27/2021 Elyssa King gave birth to a male infant, Allen King, at Tidal Health Medical Center. That the birth was full term with no complications. That the infant Allen was born at 5.42 lbs. and is healthy; however, substance exposed. The meconium tested positive for Marijuana. Infant Allan has no withdraws and presents healthy. Mother and Infant were discharged to go home on 5/29/2021. They are to be residing with the father of the baby at his home address of 11984 Drexwood Drive, Princess Anne, Maryland 21853.</p><p>Worker phoned several times with no answer. The phone that is listed under the mother is not working at this time due to the bill not being paid.&nbsp;They are using the phone number listed with the father to be reached at this time.&nbsp;Worker was able to eventually get in touch with Mr. Chris Maag, father of the baby. He was working at this time and state he will inform Elyssa who is visiting her family with the baby for the day. That they will all return home between 6:00 P.M. and 6:30 P.M. to receive a visit from this worker.&nbsp;Worker has scheduled an appointment to meet face to face with then at that time in the home together with the infant.</p><p>Family informed the hospital that they have everything they need for the baby. That they are registared for WIC. That they are with Chesapeake Pediatrics, Dr. Kovacs, 106 Milford Street, Ste 20, Salisbury, Md. 21804.</p><p>&nbsp;</p><p>King/Maag home.&nbsp;Worker found Elyssa at home with the Infant Allen and was carrying him around with her when this worker got there. There were a lot of cars in the drive. In the home there were two other adults and a small male child. It is possible that they are living in the home as well. There is a swing set in the back yard that would be appropriate for the age of the child in the home. He was having his hair braided by his mother while his father watched TV. The home needed to be picked up but did not appear to be dirty. The only odor with the smell of cigarette smoke. Worker was led to the back bedroom that contained a twin bed, a bassinet, an infant car seat and a box of used infant clothing sitting on the floor. Worker asked if the baby is exposed to cigarette smoke in the home that could be very bad for him.&nbsp;She assured this worker that he is not.&nbsp;That baby Allen is sleeping well and eating well.&nbsp;She has started to pump milk but is bottle feeding with formula.&nbsp;Elyssa stated she is confused as to what formula he should be on and states she does not know what they had him on at the hospital. The milk from pumping was in the pump bottle sitting on the floor. Worker informed Elyssa to call the hospital on Monday and ask about the formula because WIC would need to know this as well. Elyssa stated she is to call WIC on Tuesday and she has an appointment for Allen at his pediatricians on Tuesday at a 1:00 P.M. Allen’s pediatrician is Dr. Taylor. Worker also noticed that the bassinet is very wobbly and should be replaced for safety reasons. Elyssa asked if Social Service could help with a pack and play or new bassinet and some newborn diapers that she needs.&nbsp;Elyssa appeared to be very comfortable with the baby and never put him down while this worker was in the home. She does seem to have questions due to insecurity of being a new mother and seems to be very caring of her son. She informed this worker that she has a 6 week check up with her doctor and then will return to work at the Cookout in Salisbury. Worker did not discuss daycare with her at this time. Allen presented as healthy and content being in his mother’s arms. Questions were answered, baby items were reviewed, safety for the infant was discussed, worker explained that a report would be made to Somerset DSS and a safety plan was written, discussed and signed by Elyssa.&nbsp;</p><p>&nbsp;</p><p>Worker waited for some time for Mr. Maag to come home which was planned but at 7:30 P.m. this worker got another afterhours call and had to leave.</p><p>&nbsp;</p><p>DSS History: Elyssa was a child - Case # 3244233 (Open 9/17/2014 – Closed 10-08-2014)</p><p>This is all this worker has to report on this situation.</p><p>Case # 3011250</p><p>CJAMS # 1599178</p><p>&nbsp;</p><p>Tess Waller – After Hours worker</p><p>Worcester County Caseworker II</p><p><br></p><p>(Maternal Grandmother)</p><p>Holly Carson&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(40)&nbsp;&nbsp;&nbsp;&nbsp;DOB: 12/09/1980&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;White/Female&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SS# 212-17-7668</p><p>221 Gold St., Salisbury, MD 21804</p><p>443-859–6071</p><p><strong>&nbsp;</strong></p><p>Dr. Kovacs/Chesapeake Pediatrics</p><p>106 Milford St., #20, Salisbury, Md. 21804 </p><p>410-543 - 1616</p>",
    "CreatedDate": "2021-06-01T16:05:10.012Z",
    "InputSource": "0bdda2ab-b74f-4d74-ba17-3b9b37a9ca19",
    "PurposeName": "Child Protective Services",
    "RecivedDate": "5/30/2021, 2:00:00 PM",
    "teamtypekey": "CW",
    "IntakeNumber": "I211010162864",
    "intakeservice": [],
    "requestercity": "Salisbury",
    "islocalreferal": 0,
    "requesterstate": "MD",
    "servicerequest": [],
    "supervisorflag": "N",
    "HeadofHousehold": "ELYSSA P KING",
    "offenselocation": "21801",
    "queAdditionDate": "2021-06-01T16:16:27.779Z",
    "requestercounty": "19d487dd-8865-4ac4-b43f-9782b110a478",
    "RefuseToShareZip": false,
    "IsUnknownReporter": false,
    "requesteraddress1": "100 E Carroll St",
    "suggestedresource": [],
    "IsAnonymousReporter": false,
    "cpsHistoryClearance": "<p>431024057&nbsp;&nbsp;<strong>KING&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ELYSSA&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;P</strong> 05 23 2001 F&nbsp;C 213 61 8552</p><p>As of 2/19/21 CIS has address of 221 Gold St., Salisbury, MD 21804 &amp; phone 443 855 3231</p><p>Only self listed for FS Case list</p><p>Negative CPS hx</p><p>Listed under Holly Carson service cases #<span style=\"color: windowtext;\">3244233</span></p><p>Negative MD Judiciary &amp; Ntl. SOR.</p><p>&nbsp;</p><p>446018229&nbsp;&nbsp;<strong>MAAG&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CHRISTOPHER&nbsp;L</strong> 10 24 1998 M&nbsp;P 217 53 3337</p><p>As of 6/1/21 CIS has address of 221 Gold St., Salisbury, MD 21804 &amp; phone 443 397 2634</p><p>Negative FS case list</p><p>Maltreator AR neglect in Jan. 2019</p><p>Victim unsub neglect in Dec. 2007.</p><p>Listed under Angela Arecement #<span style=\"color: windowtext;\">3012037</span> &amp; Shirley Carter #<span style=\"color: windowtext;\">3155450</span></p><p>Negative MD Judiciary &amp; Ntl. SOR.</p><p>&nbsp;</p><p>Jan. 2019 (#<span style=\"color: windowtext;\">CW2925553</span>) - The family came to the attention of the agency through an afterhours report from Peninsula Regional Medical Center. Ms. Arcement brought child, Ma Kayla, to the hospital with concerns that she was tired, lethargic, crying on and off, and overall, not acting like herself. The hospital ran tests and Ma Kayla tested positive for THC (marijuana).</p><p><br></p><p>Dec. 2007 (#<span style=\"color: windowtext;\">CW2369486</span>) – no narrative</p>",
    "requestercountyname": "Wicomico",
    "narrativeUpdatedDate": "2021-06-01T16:08:12.147Z",
    "isacknowledgementletter": 1,
    "communicationDescription": "Phone"
  },
  "persons": [
    {
      "Dob": "2001-05-23T04:00:00.000Z",
      "Pid": "7c93acf6-3ab9-4811-8100-127b9017c1fd",
      "Zip": "21853",
      "ssn": "213618552",
      "City": "Princess Anne",
      "Role": "AM",
      "race": [
        {
          "value_text": "White",
          "racetypekey": "WH"
        }
      ],
      "State": "MD",
      "County": "Anne Arundel",
      "Gender": "F",
      "county": "1e886503-ef0a-450c-8607-566c45fa75e4",
      "school": [],
      "Address": "11984 Drexwood Dr",
      "emailID": [],
      "testing": [],
      "Lastname": "KING",
      "cjamspid": "3693139",
      "employer": [],
      "fullName": "ELYSSA P KING",
      "guardian": {},
      "vocation": [],
      "Firstname": "ELYSSA",
      "emergency": [],
      "personRole": [
        {
          "hidden": false,
          "rolekey": "PARENT",
          "isprimary": "true",
          "description": "Parent",
          "relationshiptorakey": ""
        },
        {
          "hidden": false,
          "rolekey": "AM",
          "isprimary": "true",
          "description": "Alleged Maltreator",
          "relationshiptorakey": ""
        }
      ],
      "substances": [],
      "addressinfo": [
        {
          "city": "Princess Anne",
          "state": "MD",
          "county": "1e886503-ef0a-450c-8607-566c45fa75e4",
          "danger": null,
          "address": "11984 Drexwood Dr",
          "country": "USA",
          "mergeid": null,
          "zipcode": "21853",
          "address2": "",
          "adrboxno": null,
          "activeflag": 1,
          "directions": null,
          "streetname": null,
          "addresstype": "Home",
          "county_desc": "Somerset",
          "durationday": null,
          "changereason": null,
          "dangerreason": null,
          "addressstatus": null,
          "acknowledgement": null,
          "personaddressid": "9d4f0a2a-7bd9-480d-8d38-84d64b753ab8",
          "addressstartdate": "2021-05-30T00:00:00",
          "incidentlocation": null,
          "personadrenddate": null,
          "formattedcityname": null,
          "ishouseholdmember": true,
          "personadrstartdate": null,
          "acknowledgementflag": null,
          "currentlocationflag": 1,
          "formattedstreetname": null,
          "incidentlocationflag": null,
          "personaddresstypekey": "HO",
          "adrstreetsuffixtypekey": null,
          "personaddresssubtypekey": null
        }
      ],
      "fullAddress": "11984 Drexwood Dr",
      "ishousehold": "yes",
      "personpayee": [],
      "phoneNumber": [],
      "phonedetails": [
        {
          "enddate": null,
          "ismobile": null,
          "startdate": "2021-02-19T05:00:00",
          "phonenumber": "4438553231",
          "phoneextension": null,
          "personphonetype": "Cell",
          "personphonetypekey": "CL",
          "reversephonenumber": null,
          "personphonenumberid": "9def713e-61b4-42f4-8497-25a51c646cf1"
        },
        {
          "enddate": null,
          "ismobile": null,
          "startdate": "2021-05-30T04:00:00",
          "phonenumber": "4434344041",
          "phoneextension": null,
          "personphonetype": "Cell",
          "personphonetypekey": "CL",
          "reversephonenumber": null,
          "personphonenumberid": "5d58b760-f970-475d-8874-47c98afc94b7"
        }
      ],
      "Dangerousself": "no",
      "Mentealimpair": "no",
      "maritalstatus": "Living Together, Unmarried",
      "personsupport": [],
      "physicianinfo": [],
      "Mentealillness": "no",
      "accomplishment": [],
      "Dangerousworker": "no",
      "healthinsurance": [],
      "primarylanguage": "ENG",
      "RelationshiptoRA": "SELF",
      "persondentalinfo": [],
      "personhealthexam": [],
      "isheadofhousehold": true,
      "ishouseholdmember": 1,
      "safehavenbabyflag": 1,
      "citizenalenageflag": "1",
      "personAddressInput": [
        {
          "city": "Linthicum",
          "state": "MD",
          "county": "Anne Arundel",
          "endDate": "04/29/2019",
          "phoneNo": "",
          "zipcode": "21090",
          "Address2": "",
          "address1": "849 Internation",
          "addressid": "",
          "startDate": "",
          "activeflag": 1,
          "addresstype": "31",
          "addresstypeLabel": "Home",
          "knownDangerAddress": "",
          "knownDangerAddressReason": ""
        }
      ],
      "personabusehistory": [],
      "everbeenadoptedflag": 0,
      "personabusesubstance": [],
      "drugexposednewbornflag": 0,
      "personbehavioralhealth": [],
      "personmedicalcondition": [],
      "sexoffenderregisteredflag": 1,
      "fetalalcoholspctrmdisordflag": 0,
      "personmedicationphyscotropic": [],
      "probationsearchconductedflag": 1
    },
    {
      "Dob": "2021-05-27T04:00:00.000Z",
      "Pid": "0fe03f7f-1727-4cc8-8f65-3b841e676757",
      "Zip": "21853",
      "City": "Princess Anne",
      "Role": "CHILD",
      "race": [
        {
          "value_text": "White",
          "racetypekey": "WH"
        }
      ],
      "State": "MD",
      "County": "Anne Arundel",
      "Gender": "M",
      "county": "1e886503-ef0a-450c-8607-566c45fa75e4",
      "school": [],
      "Address": "11984 Drexwood Dr",
      "emailID": [],
      "testing": [],
      "Lastname": "King",
      "cjamspid": "200672039",
      "employer": [],
      "fullName": " Allen  King ",
      "guardian": {},
      "vocation": [],
      "Firstname": "Allen",
      "emergency": [],
      "personRole": [
        {
          "hidden": false,
          "rolekey": "CHILD",
          "isprimary": "true",
          "description": "Child",
          "relationshiptorakey": ""
        },
        {
          "hidden": false,
          "rolekey": "AV",
          "isprimary": "true",
          "description": "Alleged Victim",
          "relationshiptorakey": ""
        }
      ],
      "substances": [],
      "addressinfo": [
        {
          "city": "Princess Anne",
          "state": "MD",
          "county": "1e886503-ef0a-450c-8607-566c45fa75e4",
          "danger": null,
          "address": "11984 Drexwood Dr",
          "country": "USA",
          "mergeid": null,
          "zipcode": "21853",
          "address2": "",
          "adrboxno": null,
          "activeflag": 1,
          "directions": null,
          "streetname": null,
          "addresstype": "Home",
          "county_desc": "Somerset",
          "durationday": null,
          "changereason": null,
          "dangerreason": null,
          "addressstatus": null,
          "acknowledgement": null,
          "personaddressid": "9a86f524-949a-4412-b6a7-9e0ebf3b39b4",
          "addressstartdate": "2021-05-30T04:00:00",
          "incidentlocation": null,
          "personadrenddate": null,
          "formattedcityname": null,
          "ishouseholdmember": true,
          "personadrstartdate": null,
          "acknowledgementflag": null,
          "currentlocationflag": 1,
          "formattedstreetname": null,
          "incidentlocationflag": null,
          "personaddresstypekey": "HO",
          "adrstreetsuffixtypekey": null,
          "personaddresssubtypekey": null
        }
      ],
      "fullAddress": "11984 Drexwood Dr",
      "ishousehold": "yes",
      "personpayee": [],
      "phoneNumber": [],
      "Dangerousself": "no",
      "Mentealimpair": "no",
      "maritalstatus": "Single",
      "personsupport": [],
      "physicianinfo": [],
      "Mentealillness": "no",
      "accomplishment": [],
      "Dangerousworker": "no",
      "healthinsurance": [],
      "primarylanguage": "ENG",
      "RelationshiptoRA": "SELF",
      "persondentalinfo": [],
      "personhealthexam": [],
      "ishouseholdmember": 1,
      "safehavenbabyflag": 1,
      "citizenalenageflag": "1",
      "personAddressInput": [
        {
          "city": "Linthicum",
          "state": "MD",
          "county": "Anne Arundel",
          "endDate": "04/29/2019",
          "phoneNo": "",
          "zipcode": "21090",
          "Address2": "",
          "address1": "849 Internation",
          "addressid": "",
          "startDate": "",
          "activeflag": 1,
          "addresstype": "31",
          "addresstypeLabel": "Home",
          "knownDangerAddress": "",
          "knownDangerAddressReason": ""
        }
      ],
      "personabusehistory": [],
      "everbeenadoptedflag": 0,
      "personabusesubstance": [],
      "drugexposednewbornflag": 1,
      "personbehavioralhealth": [],
      "personmedicalcondition": [],
      "sexoffenderregisteredflag": 0,
      "fetalalcoholspctrmdisordflag": 0,
      "personmedicationphyscotropic": [],
      "probationsearchconductedflag": 0
    },
    {
      "Dob": "1998-10-24T04:00:00.000Z",
      "Pid": "5838c29f-e5b2-4699-8767-3138bb524ef6",
      "Zip": "21853",
      "ssn": "217533337",
      "City": "Princess Anne",
      "Role": "PARENT",
      "race": [
        {
          "value_text": "Native Hawaiian or Pacific Islander",
          "racetypekey": "PI"
        },
        {
          "value_text": "White",
          "racetypekey": "WH"
        }
      ],
      "State": "MD",
      "County": "Anne Arundel",
      "Gender": "M",
      "county": "1e886503-ef0a-450c-8607-566c45fa75e4",
      "school": [],
      "Address": "11984 Drexwood Dr",
      "emailID": [],
      "testing": [],
      "Lastname": "MAAG",
      "cjamspid": "2014383",
      "employer": [],
      "fullName": "CHRISTOPHER LEE MAAG II",
      "guardian": {},
      "vocation": [],
      "Firstname": "CHRISTOPHER",
      "emergency": [],
      "personRole": [
        {
          "hidden": false,
          "rolekey": "PARENT",
          "isprimary": "true",
          "description": "Parent",
          "relationshiptorakey": ""
        }
      ],
      "substances": [],
      "addressinfo": [
        {
          "city": "Princess Anne",
          "state": "MD",
          "county": "1e886503-ef0a-450c-8607-566c45fa75e4",
          "danger": null,
          "address": "11984 Drexwood Dr",
          "country": "USA",
          "mergeid": null,
          "zipcode": "21853",
          "address2": "",
          "adrboxno": null,
          "activeflag": 1,
          "directions": null,
          "streetname": null,
          "addresstype": "Home",
          "county_desc": "Somerset",
          "durationday": null,
          "changereason": null,
          "dangerreason": null,
          "addressstatus": null,
          "acknowledgement": null,
          "personaddressid": "66ff749b-fdff-439a-806b-2e811f67d4fb",
          "addressstartdate": "2021-05-30T08:00:00",
          "incidentlocation": null,
          "personadrenddate": null,
          "formattedcityname": null,
          "ishouseholdmember": true,
          "personadrstartdate": null,
          "acknowledgementflag": null,
          "currentlocationflag": 1,
          "formattedstreetname": null,
          "incidentlocationflag": null,
          "personaddresstypekey": "HO",
          "adrstreetsuffixtypekey": null,
          "personaddresssubtypekey": null
        },
        {
          "city": "Princess Anne",
          "state": "MD",
          "county": null,
          "danger": false,
          "address": "11357 BROCKETT SQ UNIT 8K",
          "country": "USA",
          "mergeid": null,
          "zipcode": "21853",
          "address2": "",
          "adrboxno": null,
          "activeflag": 1,
          "directions": null,
          "streetname": "Brockett ",
          "addresstype": "Home",
          "county_desc": null,
          "durationday": null,
          "changereason": null,
          "dangerreason": null,
          "addressstatus": null,
          "acknowledgement": null,
          "personaddressid": "055f4f32-7ea4-4eb5-bf2c-8195d43a25aa",
          "addressstartdate": "2019-01-25T00:00:00",
          "incidentlocation": null,
          "personadrenddate": null,
          "formattedcityname": null,
          "ishouseholdmember": false,
          "personadrstartdate": "2019-01-25T00:00:00",
          "acknowledgementflag": null,
          "currentlocationflag": 0,
          "formattedstreetname": null,
          "incidentlocationflag": null,
          "personaddresstypekey": "HO",
          "adrstreetsuffixtypekey": "SQ",
          "personaddresssubtypekey": null
        },
        {
          "city": "Salisbury",
          "state": "MD",
          "county": null,
          "danger": false,
          "address": "310 PARK AVE APT 1",
          "country": "USA",
          "mergeid": null,
          "zipcode": null,
          "address2": "",
          "adrboxno": null,
          "activeflag": 1,
          "directions": null,
          "streetname": "Park",
          "addresstype": "Home",
          "county_desc": null,
          "durationday": null,
          "changereason": null,
          "dangerreason": null,
          "addressstatus": null,
          "acknowledgement": null,
          "personaddressid": "48165201-6629-484b-87a3-aec381e8b11f",
          "addressstartdate": "2007-11-09T00:00:00",
          "incidentlocation": null,
          "personadrenddate": null,
          "formattedcityname": null,
          "ishouseholdmember": false,
          "personadrstartdate": "2007-11-09T00:00:00",
          "acknowledgementflag": null,
          "currentlocationflag": 0,
          "formattedstreetname": null,
          "incidentlocationflag": null,
          "personaddresstypekey": "HO",
          "adrstreetsuffixtypekey": "AVE",
          "personaddresssubtypekey": null
        },
        {
          "city": "Ocean City",
          "state": "MD",
          "county": null,
          "danger": false,
          "address": "504   1/2 Lark LN",
          "country": "USA",
          "mergeid": null,
          "zipcode": "21842",
          "address2": " ",
          "adrboxno": null,
          "activeflag": 1,
          "directions": null,
          "streetname": " 1/2 Lark",
          "addresstype": "Home",
          "county_desc": null,
          "durationday": null,
          "changereason": null,
          "dangerreason": null,
          "addressstatus": null,
          "acknowledgement": null,
          "personaddressid": "c6b610f4-2c7d-4384-b302-30120d24e633",
          "addressstartdate": "2007-09-24T00:00:00",
          "incidentlocation": null,
          "personadrenddate": null,
          "formattedcityname": null,
          "ishouseholdmember": false,
          "personadrstartdate": "2007-09-24T00:00:00",
          "acknowledgementflag": null,
          "currentlocationflag": 0,
          "formattedstreetname": null,
          "incidentlocationflag": null,
          "personaddresstypekey": "HO",
          "adrstreetsuffixtypekey": "LN",
          "personaddresssubtypekey": null
        }
      ],
      "fullAddress": "11984 Drexwood Dr",
      "ishousehold": "yes",
      "personpayee": [],
      "phoneNumber": [],
      "phonedetails": [
        {
          "enddate": null,
          "ismobile": null,
          "startdate": "2021-05-30T04:00:00",
          "phonenumber": "4433972634",
          "phoneextension": null,
          "personphonetype": "Cell",
          "personphonetypekey": "CL",
          "reversephonenumber": null,
          "personphonenumberid": "e076e05b-87c7-4832-bfad-14fa2452815f"
        },
        {
          "enddate": null,
          "ismobile": null,
          "startdate": null,
          "phonenumber": "3022585036",
          "phoneextension": null,
          "personphonetype": "Home",
          "personphonetypekey": "HM",
          "reversephonenumber": null,
          "personphonenumberid": "2c17e47b-b677-488f-8f49-1caa888718f7"
        }
      ],
      "Dangerousself": "no",
      "Mentealimpair": "no",
      "maritalstatus": "Single",
      "personsupport": [],
      "physicianinfo": [],
      "Mentealillness": "no",
      "accomplishment": [],
      "Dangerousworker": "no",
      "healthinsurance": [],
      "primarylanguage": "ENG",
      "RelationshiptoRA": "SELF",
      "persondentalinfo": [],
      "personhealthexam": [],
      "ishouseholdmember": 1,
      "safehavenbabyflag": 1,
      "citizenalenageflag": "1",
      "personAddressInput": [
        {
          "city": "Linthicum",
          "state": "MD",
          "county": "Anne Arundel",
          "endDate": "04/29/2019",
          "phoneNo": "",
          "zipcode": "21090",
          "Address2": "",
          "address1": "849 Internation",
          "addressid": "",
          "startDate": "",
          "activeflag": 1,
          "addresstype": "31",
          "addresstypeLabel": "Home",
          "knownDangerAddress": "",
          "knownDangerAddressReason": ""
        }
      ],
      "personabusehistory": [],
      "everbeenadoptedflag": 0,
      "personabusesubstance": [],
      "drugexposednewbornflag": 0,
      "personbehavioralhealth": [],
      "personmedicalcondition": [],
      "sexoffenderregisteredflag": 1,
      "fetalalcoholspctrmdisordflag": 0,
      "personmedicationphyscotropic": [],
      "probationsearchconductedflag": 1
    }
  ],
  "userrole": "CWIW",
  "clwStatus": null,
  "narrative": [
    {
      "Role": "REP",
      "email": "",
      "title": null,
      "ZipCode": "",
      "Lastname": "Boyer",
      "RoleName": "Reporter",
      "Firstname": "Annie",
      "Middlename": "",
      "PhoneNumber": "4109126338",
      "incidentdate": "2021-05-27T04:00:00.000Z",
      "organization": "Tidal Health/PRMC",
      "isapproximate": true,
      "PhoneNumberExt": "",
      "incidentlocation": "Somerset Co."
    }
  ],
  "disposition": null,
  "createdCases": null,
  "reviewstatus": {
    "status": "",
    "appevent": "DRAFT",
    "commenttext": "",
    "ispreintake": false
  },
  "crossReference": [],
  "officelocation": "Somerset",
  "reasonforDraft": [
    {
      "time": 1622563670508
    },
    {
      "time": 1622563672793
    },
    {
      "time": 1622563692935
    },
    {
      "time": 1622563696098
    },
    {
      "time": 1622563834454
    },
    {
      "time": 1622564052007
    },
    {
      "time": 1622564187802
    },
    {
      "time": 1622564318767
    },
    {
      "time": 1622564330326
    }
  ],
  "securityuserid": "e4018de0-28aa-499d-886c-3ebcc314a109",
  "evaluationFields": null,
  "intakeDATypeDetails": [],
  "focuspersoncasedetails": []
}'
where intakenumber ='I211010162864' and activeflag =1;