/*
   Issue Description: CIDM-8559 -Removing invalid characters in CSMS auto referral payload
   Category/ Module  :  IVE
   Root cause: 
   Pull request# for code fix: 
   Reason why no related code fix: 
   Status of the code fix if already submitted and expected prod fix date: 
*/

/* payload for 965029
{"iveCaseNumber":4155835,"iveCaseStatus":"APPROVED","iveCaseType":"S","iveApprovalDate":"2024-03-07","effectiveDate":"2017-11-08","iveGrantEndDate":"2021-10-15","ivdRecordType":"NAPP","iveGrantDate":"2021-05-31","iveGrantAmount":0,"parentalRightsTerminationInd":"N","courtOrderInd":"N","courtOrderType":null,"familyViolenceIndicator":null,"referralId":null,"referralDate":"2024-03-07","referralWorkerCaseNotes":null,"referralJurisd":"30","referralWorkerName":"Crystal Aye","referralWorkerCounty":"24510","referralWorkerEmail":"crystal.aye@maryland.gov","referralWorkerPhone":null,"children":[{"childIrn":400492278,"firstName":"JULZ","lastName":"HARRIS","middleName":"T","suffixName":null,"maidenName":null,"race":"BA","gender":"F","dateOfBirth":"2016-10-02","ssn":"388-41-2910","childMbrType":"RE","healthInsuranceDetails":{"insuranceCarrierName":null,"isInsuranceCoveredBy":"CHILD","insurancePolicyNumber":null,"insuranceGroupNumber":null,"insCoveredBy":null,"effectiveDate":"2021-11-04","expirationDate":null,"ismedicaidmedicare":null,"isInsProvidedByEmployer":"","insProvidedByEmployerId":"","otherProviderName":""},"paternityEstablishedInd":"N","medicalCoverageInd":"","fosterCareDetails":{"agencyName":"Pearl Nesbeth","providerid":5038883,"agencyPlacementCd":"PRPL","agencyPhoneNum":"","agencyFax":"","agencyAddress":{"addressLine1":"5720","addressLine2":"Utrecht","city":"Baltimore","state":"MD","zipCode":"21206","country":"USA","smartyStreetValidatedInd":"","addrVerificationDt":null,"isInternationalAddr":"N","county":"1430","lastAddrDt":"0001-01-01","addrExist":""}},"mdmId":"MDT-128657556","childOnCrtord":"","tprInitDate":null,"email":null,"resAddress":{"addressLine1":"528 Grovethorn Rd","addressLine2":"","city":"Middle River","state":"MD","zipCode":"21220","county":"1429","country":"USA","smartyStreetValidatedInd":"N","isInternationalAddr":"N","lastAddrDt":"0001-01-01","addrVerificationDt":null},"mailingAddress":{"addressLine1":"528 Grovethorn Rd","addressLine2":"","city":"Middle River","state":"MD","zipCode":"21220","county":"1429","country":"USA","smartyStreetValidatedInd":"N","isInternationalAddr":"N","lastAddrDt":"0001-01-01","addrVerificationDt":null}}],"nonCustodialParents":[{"clientid":1660107,"personid":"0cdd3e3d-1171-4f57-b401-0053bd9e672e","mdmId":"MDT-123582457","ncpIrn":415014565,"firstName":"ANDREA","lastName":"SCOTT","middleName":"A","suffixName":null,"maidenName":null,"race":"BA","gender":"F","dateOfBirth":"1991-06-20","ssn":"214336787","ncpMbrType":"AP","ncpRelationshipCode":"","ncpLegalEstablishedInd":"","ncpLegalEstablishedDate":"0001-01-01","ncpBirthHospital":"","ncpBirthCity":"","ncpBirthState":"","ncpDeathDate":"","ncpMaritalStatus":"","ncpMarriageDate":"","ncpMarriageTermDate":"","ncpMarriageTermCity":"","healthInsuranceInd":"","email":null,"lastKnownAddressType":null,"lastKnownAddress":null,"lastKnownEmployerDetails":null,"militaryServiceDetails":null,"healthInsuranceDetails":{"insuranceCarrierName":null,"insurancePolicyNumber":"30816234910","insuranceGroupNumber":null,"insCoveredBy":null,"effectiveDate":null,"expirationDate":null,"ismedicaidmedicare":true,"isInsProvidedByEmployer":"","insProvidedByEmployerId":"","otherProviderName":""}}, 
 {"clientid":3498874,"personid":"4bb155d9-5d09-46f5-a4d7-e4297ff72166","mdmId":"MDT-125188097","ncpIrn":447013958,"firstName":"HARVEY","lastName":"HARRIS","middleName":"T","suffixName":null,"maidenName":null,"race":"BA","gender":"M","dateOfBirth":"1979-02-24","ssn":"219921314","ncpMbrType":"AP","ncpRelationshipCode":"","ncpLegalEstablishedInd":"","ncpLegalEstablishedDate":"0001-01-01","ncpBirthHospital":"","ncpBirthCity":"","ncpBirthState":"","ncpDeathDate":"","ncpMaritalStatus":"","ncpMarriageDate":"","ncpMarriageTermDate":"","ncpMarriageTermCity":"","healthInsuranceInd":"","email":null,"lastKnownAddressType":null,"lastKnownAddress":{"addressLine1":"2027 ROBB ST","addressLine2":"","city":"Baltimore","state":"MD","zipCode":"21218","county":null,"country":"USA","smartyStreetValidatedInd":"N","isInternationalAddr":"N","lastAddrDt":"0001-01-01"},"lastKnownEmployerDetails":null,"militaryServiceDetails":null,"healthInsuranceDetails":null}]}
*/

-- payload for 913096
/*
{"iveCaseNumber":200162002,"iveCaseStatus":"APPROVED","iveCaseType":"S","iveApprovalDate":"2024-03-07","effectiveDate":"2020-10-17","iveGrantEndDate":"2021-09-02","ivdRecordType":"NAPP","iveGrantDate":"0001-01-01","iveGrantAmount":null,"parentalRightsTerminationInd":"N","courtOrderInd":"N","courtOrderType":null,"familyViolenceIndicator":null,"referralId":null,"referralDate":"2024-03-07","referralWorkerCaseNotes":null,"referralJurisd":"08","referralWorkerName":"Cortney Carey","referralWorkerCounty":"24017","referralWorkerEmail":"cortney.carey@maryland.gov","referralWorkerPhone":"9999999999","children":[{"childIrn":null,"firstName":"Keturah","lastName":"Scott","middleName":"","suffixName":"","maidenName":null,"race":"BA","gender":"F","dateOfBirth":"2019-08-07","ssn":"1131-73-561","childMbrType":"RE","healthInsuranceDetails":null,"paternityEstablishedInd":"N","medicalCoverageInd":"","fosterCareDetails":{"agencyName":"Felecia Brown","providerid":6003510,"agencyPlacementCd":"PRPL","agencyPhoneNum":"","agencyFax":"","agencyAddress":{"addressLine1":"8221","addressLine2":"Bishopsgate","city":"Charles County","state":"MD","zipCode":"20695","country":"USA","smartyStreetValidatedInd":"","addrVerificationDt":null,"isInternationalAddr":"N","county":"1435","lastAddrDt":"0001-01-01","addrExist":""}},"mdmId":null,"childOnCrtord":"","tprInitDate":null,"email":null,"resAddress":{"addressLine1":"519 W PRATT ST","addressLine2":"Apt 1","city":"Baltimore","state":"MD","zipCode":"21201","county":"1429","country":"USA","smartyStreetValidatedInd":"N","isInternationalAddr":"N","lastAddrDt":"0001-01-01","addrVerificationDt":null},"mailingAddress":{"addressLine1":"519 W PRATT ST","addressLine2":"Apt 1","city":"Baltimore","state":"MD","zipCode":"21201","county":"1429","country":"USA","smartyStreetValidatedInd":"N","isInternationalAddr":"N","lastAddrDt":"0001-01-01","addrVerificationDt":null}}],"nonCustodialParents":[{"clientid":3464066,"personid":"2051cb7d-4099-465a-bac2-9c743a49e14f","mdmId":"MDT-124616358","ncpIrn":436014959,"firstName":"STEPHANIE","lastName":"Coleman","middleName":"A","suffixName":null,"maidenName":null,"race":"BA","gender":"F","dateOfBirth":"1992-05-21","ssn":"218359026","ncpMbrType":"AP","ncpRelationshipCode":"","ncpLegalEstablishedInd":"","ncpLegalEstablishedDate":"0001-01-01","ncpBirthHospital":"","ncpBirthCity":"","ncpBirthState":"","ncpDeathDate":"","ncpMaritalStatus":"","ncpMarriageDate":"","ncpMarriageTermDate":"","ncpMarriageTermCity":"","healthInsuranceInd":"","email":null,"lastKnownAddressType":null,"lastKnownAddress":{"addressLine1":"519 W PRATT ST","addressLine2":"Apt 1","city":"Baltimore","state":"MD","zipCode":"21201","county":"1429","country":"USA","smartyStreetValidatedInd":"N","isInternationalAddr":"N","lastAddrDt":"0001-01-01"},"lastKnownEmployerDetails":null,"militaryServiceDetails":null,"healthInsuranceDetails":null}, 
 {"clientid":200162051,"personid":"be842108-448c-4ab7-9598-5c4750eca589","mdmId":"MDT-127938846","ncpIrn":30061413,"firstName":"Kevin","lastName":"Scott","middleName":"","suffixName":"","maidenName":null,"race":"BA","gender":"M","dateOfBirth":"1970-07-16","ssn":"216788705","ncpMbrType":"AP","ncpRelationshipCode":"","ncpLegalEstablishedInd":"","ncpLegalEstablishedDate":"0001-01-01","ncpBirthHospital":"","ncpBirthCity":"","ncpBirthState":"","ncpDeathDate":"","ncpMaritalStatus":"","ncpMarriageDate":"","ncpMarriageTermDate":"","ncpMarriageTermCity":"","healthInsuranceInd":"","email":null,"lastKnownAddressType":null,"lastKnownAddress":{"addressLine1":"519 W PRATT ST","addressLine2":"Apt 1","city":"Baltimore","state":"MD","zipCode":"21201","county":"1429","country":"USA","smartyStreetValidatedInd":"N","isInternationalAddr":"N","lastAddrDt":"0001-01-01"},"lastKnownEmployerDetails":null,"militaryServiceDetails":null,"healthInsuranceDetails":null}]}
*/




update ive_auto_approvals set csmsrefpayload = '{
  "iveCaseNumber": 4155835,
  "iveCaseStatus": "APPROVED",
  "iveCaseType": "S",
  "iveApprovalDate": "2024-03-07",
  "effectiveDate": "2017-11-08",
  "iveGrantEndDate": "2021-10-15",
  "ivdRecordType": "NAPP",
  "iveGrantDate": "2021-05-31",
  "iveGrantAmount": 0,
  "parentalRightsTerminationInd": "N",
  "courtOrderInd": "N",
  "courtOrderType": null,
  "familyViolenceIndicator": null,
  "referralId": null,
  "referralDate": "2024-03-07",
  "referralWorkerCaseNotes": null,
  "referralJurisd": "30",
  "referralWorkerName": "Crystal Aye",
  "referralWorkerCounty": "24510",
  "referralWorkerEmail": "crystal.aye@maryland.gov",
  "referralWorkerPhone": null,
  "children": [
    {
      "childIrn": 400492278,
      "firstName": "JULZ",
      "lastName": "HARRIS",
      "middleName": "T",
      "suffixName": null,
      "maidenName": null,
      "race": "BA",
      "gender": "F",
      "dateOfBirth": "2016-10-02",
      "ssn": "388412910",
      "childMbrType": "RE",
      "healthInsuranceDetails": {
        "insuranceCarrierName": null,
        "isInsuranceCoveredBy": "CHILD",
        "insurancePolicyNumber": null,
        "insuranceGroupNumber": null,
        "insCoveredBy": null,
        "effectiveDate": "2021-11-04",
        "expirationDate": null,
        "ismedicaidmedicare": null,
        "isInsProvidedByEmployer": "",
        "insProvidedByEmployerId": "",
        "otherProviderName": ""
      },
      "paternityEstablishedInd": "N",
      "medicalCoverageInd": "",
      "fosterCareDetails": {
        "agencyName": "Pearl Nesbeth",
        "providerid": 5038883,
        "agencyPlacementCd": "PRPL",
        "agencyPhoneNum": "",
        "agencyFax": "",
        "agencyAddress": {
          "addressLine1": "5720",
          "addressLine2": "Utrecht",
          "city": "Baltimore",
          "state": "MD",
          "zipCode": "21206",
          "country": "USA",
          "smartyStreetValidatedInd": "",
          "addrVerificationDt": null,
          "isInternationalAddr": "N",
          "county": "1430",
          "lastAddrDt": "0001-01-01",
          "addrExist": ""
        }
      },
      "mdmId": "MDT-128657556",
      "childOnCrtord": "",
      "tprInitDate": null,
      "email": null,
      "resAddress": {
        "addressLine1": "528 Grovethorn Rd",
        "addressLine2": "",
        "city": "Middle River",
        "state": "MD",
        "zipCode": "21220",
        "county": "1429",
        "country": "USA",
        "smartyStreetValidatedInd": "N",
        "isInternationalAddr": "N",
        "lastAddrDt": "0001-01-01",
        "addrVerificationDt": null
      },
      "mailingAddress": {
        "addressLine1": "528 Grovethorn Rd",
        "addressLine2": "",
        "city": "Middle River",
        "state": "MD",
        "zipCode": "21220",
        "county": "1429",
        "country": "USA",
        "smartyStreetValidatedInd": "N",
        "isInternationalAddr": "N",
        "lastAddrDt": "0001-01-01",
        "addrVerificationDt": null
      }
    }
  ],
  "nonCustodialParents": [
    {
      "clientid": 1660107,
      "personid": "0cdd3e3d-1171-4f57-b401-0053bd9e672e",
      "mdmId": "MDT-123582457",
      "ncpIrn": 415014565,
      "firstName": "ANDREA",
      "lastName": "SCOTT",
      "middleName": "A",
      "suffixName": null,
      "maidenName": null,
      "race": "BA",
      "gender": "F",
      "dateOfBirth": "1991-06-20",
      "ssn": "214336787",
      "ncpMbrType": "AP",
      "ncpRelationshipCode": "",
      "ncpLegalEstablishedInd": "",
      "ncpLegalEstablishedDate": "0001-01-01",
      "ncpBirthHospital": "",
      "ncpBirthCity": "",
      "ncpBirthState": "",
      "ncpDeathDate": "",
      "ncpMaritalStatus": "",
      "ncpMarriageDate": "",
      "ncpMarriageTermDate": "",
      "ncpMarriageTermCity": "",
      "healthInsuranceInd": "",
      "email": null,
      "lastKnownAddressType": null,
      "lastKnownAddress": null,
      "lastKnownEmployerDetails": null,
      "militaryServiceDetails": null,
      "healthInsuranceDetails": {
        "insuranceCarrierName": null,
        "insurancePolicyNumber": "30816234910",
        "insuranceGroupNumber": null,
        "insCoveredBy": null,
        "effectiveDate": null,
        "expirationDate": null,
        "ismedicaidmedicare": true,
        "isInsProvidedByEmployer": "",
        "insProvidedByEmployerId": "",
        "otherProviderName": ""
      }
    },
    {
      "clientid": 3498874,
      "personid": "4bb155d9-5d09-46f5-a4d7-e4297ff72166",
      "mdmId": "MDT-125188097",
      "ncpIrn": 447013958,
      "firstName": "HARVEY",
      "lastName": "HARRIS",
      "middleName": "T",
      "suffixName": null,
      "maidenName": null,
      "race": "BA",
      "gender": "M",
      "dateOfBirth": "1979-02-24",
      "ssn": "219921314",
      "ncpMbrType": "AP",
      "ncpRelationshipCode": "",
      "ncpLegalEstablishedInd": "",
      "ncpLegalEstablishedDate": "0001-01-01",
      "ncpBirthHospital": "",
      "ncpBirthCity": "",
      "ncpBirthState": "",
      "ncpDeathDate": "",
      "ncpMaritalStatus": "",
      "ncpMarriageDate": "",
      "ncpMarriageTermDate": "",
      "ncpMarriageTermCity": "",
      "healthInsuranceInd": "",
      "email": null,
      "lastKnownAddressType": null,
      "lastKnownAddress": {
        "addressLine1": "2027 ROBB ST",
        "addressLine2": "",
        "city": "Baltimore",
        "state": "MD",
        "zipCode": "21218",
        "county": null,
        "country": "USA",
        "smartyStreetValidatedInd": "N",
        "isInternationalAddr": "N",
        "lastAddrDt": "0001-01-01"
      },
      "lastKnownEmployerDetails": null,
      "militaryServiceDetails": null,
      "healthInsuranceDetails": null
    }
  ]
}', updatedon = now(), updatedby = 'CIDM-8559' where eligibility_period_id = '965029';



update ive_auto_approvals set csmsrefpayload = '{
  "iveCaseNumber": 200162002,
  "iveCaseStatus": "APPROVED",
  "iveCaseType": "S",
  "iveApprovalDate": "2024-03-07",
  "effectiveDate": "2020-10-17",
  "iveGrantEndDate": "2021-09-02",
  "ivdRecordType": "NAPP",
  "iveGrantDate": "0001-01-01",
  "iveGrantAmount": null,
  "parentalRightsTerminationInd": "N",
  "courtOrderInd": "N",
  "courtOrderType": null,
  "familyViolenceIndicator": null,
  "referralId": null,
  "referralDate": "2024-03-07",
  "referralWorkerCaseNotes": null,
  "referralJurisd": "08",
  "referralWorkerName": "Cortney Carey",
  "referralWorkerCounty": "24017",
  "referralWorkerEmail": "cortney.carey@maryland.gov",
  "referralWorkerPhone": "9999999999",
  "children": [
    {
      "childIrn": null,
      "firstName": "Keturah",
      "lastName": "Scott",
      "middleName": "",
      "suffixName": "",
      "maidenName": null,
      "race": "BA",
      "gender": "F",
      "dateOfBirth": "2019-08-07",
      "ssn": "113173561",
      "childMbrType": "RE",
      "healthInsuranceDetails": null,
      "paternityEstablishedInd": "N",
      "medicalCoverageInd": "",
      "fosterCareDetails": {
        "agencyName": "Felecia Brown",
        "providerid": 6003510,
        "agencyPlacementCd": "PRPL",
        "agencyPhoneNum": "",
        "agencyFax": "",
        "agencyAddress": {
          "addressLine1": "8221",
          "addressLine2": "Bishopsgate",
          "city": "Charles County",
          "state": "MD",
          "zipCode": "20695",
          "country": "USA",
          "smartyStreetValidatedInd": "",
          "addrVerificationDt": null,
          "isInternationalAddr": "N",
          "county": "1435",
          "lastAddrDt": "0001-01-01",
          "addrExist": ""
        }
      },
      "mdmId": null,
      "childOnCrtord": "",
      "tprInitDate": null,
      "email": null,
      "resAddress": {
        "addressLine1": "519 W PRATT ST",
        "addressLine2": "Apt 1",
        "city": "Baltimore",
        "state": "MD",
        "zipCode": "21201",
        "county": "1429",
        "country": "USA",
        "smartyStreetValidatedInd": "N",
        "isInternationalAddr": "N",
        "lastAddrDt": "0001-01-01",
        "addrVerificationDt": null
      },
      "mailingAddress": {
        "addressLine1": "519 W PRATT ST",
        "addressLine2": "Apt 1",
        "city": "Baltimore",
        "state": "MD",
        "zipCode": "21201",
        "county": "1429",
        "country": "USA",
        "smartyStreetValidatedInd": "N",
        "isInternationalAddr": "N",
        "lastAddrDt": "0001-01-01",
        "addrVerificationDt": null
      }
    }
  ],
  "nonCustodialParents": [
    {
      "clientid": 3464066,
      "personid": "2051cb7d-4099-465a-bac2-9c743a49e14f",
      "mdmId": "MDT-124616358",
      "ncpIrn": 436014959,
      "firstName": "STEPHANIE",
      "lastName": "Coleman",
      "middleName": "A",
      "suffixName": null,
      "maidenName": null,
      "race": "BA",
      "gender": "F",
      "dateOfBirth": "1992-05-21",
      "ssn": "218359026",
      "ncpMbrType": "AP",
      "ncpRelationshipCode": "",
      "ncpLegalEstablishedInd": "",
      "ncpLegalEstablishedDate": "0001-01-01",
      "ncpBirthHospital": "",
      "ncpBirthCity": "",
      "ncpBirthState": "",
      "ncpDeathDate": "",
      "ncpMaritalStatus": "",
      "ncpMarriageDate": "",
      "ncpMarriageTermDate": "",
      "ncpMarriageTermCity": "",
      "healthInsuranceInd": "",
      "email": null,
      "lastKnownAddressType": null,
      "lastKnownAddress": {
        "addressLine1": "519 W PRATT ST",
        "addressLine2": "Apt 1",
        "city": "Baltimore",
        "state": "MD",
        "zipCode": "21201",
        "county": "1429",
        "country": "USA",
        "smartyStreetValidatedInd": "N",
        "isInternationalAddr": "N",
        "lastAddrDt": "0001-01-01"
      },
      "lastKnownEmployerDetails": null,
      "militaryServiceDetails": null,
      "healthInsuranceDetails": null
    },
    {
      "clientid": 200162051,
      "personid": "be842108-448c-4ab7-9598-5c4750eca589",
      "mdmId": "MDT-127938846",
      "ncpIrn": 30061413,
      "firstName": "Kevin",
      "lastName": "Scott",
      "middleName": "",
      "suffixName": "",
      "maidenName": null,
      "race": "BA",
      "gender": "M",
      "dateOfBirth": "1970-07-16",
      "ssn": "216788705",
      "ncpMbrType": "AP",
      "ncpRelationshipCode": "",
      "ncpLegalEstablishedInd": "",
      "ncpLegalEstablishedDate": "0001-01-01",
      "ncpBirthHospital": "",
      "ncpBirthCity": "",
      "ncpBirthState": "",
      "ncpDeathDate": "",
      "ncpMaritalStatus": "",
      "ncpMarriageDate": "",
      "ncpMarriageTermDate": "",
      "ncpMarriageTermCity": "",
      "healthInsuranceInd": "",
      "email": null,
      "lastKnownAddressType": null,
      "lastKnownAddress": {
        "addressLine1": "519 W PRATT ST",
        "addressLine2": "Apt 1",
        "city": "Baltimore",
        "state": "MD",
        "zipCode": "21201",
        "county": "1429",
        "country": "USA",
        "smartyStreetValidatedInd": "N",
        "isInternationalAddr": "N",
        "lastAddrDt": "0001-01-01"
      },
      "lastKnownEmployerDetails": null,
      "militaryServiceDetails": null,
      "healthInsuranceDetails": null
    }
  ]
}', updatedon = now(), updatedby = 'CIDM-8559' where eligibility_period_id = '913096';
