/*
Issue Description: 3043134:A previous ticket was submitted and completed with ticket number (S20250127066399) for 2 APPLA assessments that were submitted for approval but the assessment was blank on the supervisor end to approve. 
The 2 assessments for for Caiden and Kai. That ticket was fixed however, the information entered for youth Kai PID: 4057650 assessment is incorrect and is the information for the other youth Caiden PID 200660576. Caiden's fixed APPLA assessment information is correct with the ticket fix. Kai's is incorrect and shows Caiden's information.
Category/Module: Error
Root cause: Additional worng information was given inside the json as a part of CJAMS-59503 fix.
Fix provided: DB queries to update the previous fix.
Data/Code fix ticket#:
Regression Impacts: N/A
Is Code fix Required?: No
Code fix ticket#: N/A
Reason why no related code fix: Data issue
Status of the code fix if already submitted and expected prod fix date: data fix done, raising the PR
Backup before update/ delete:Query:
*/
-- Q1 to QIII, textboxeight, supervisorname,wasthechildasked and panel38767828842569685ColumnsSelectBoxesField values only got changed from CJAMS-59503.
update assessment
set submissiondata  = '{
  "Q1": "Kai was placed in a facility that was able to meet Kai''s extensive needs.",
  "Q2": "Reunification was considered but it was determined that Kai''s adoptive parents are not able to meet Kai''s extensive needs in their home and maintain safety.",
  "Q3": "Reunification was initial plan but it was determined that Kai''s needs were too significant to allow him to be maintained in a family home environment and maintain safety.",
  "Q5": "This placement is necessary to maintain Kai''s well-being and safety.",
  "Q6": "Kai will move into a DDA approved adult placement at the age of 21 but will remain in a DDA placement for youth until eligible for adult services.",
  "Q7": "Kai will require 24/7 support for his entire life.",
  "Q9": "Determination was made that Kai will require extensive support throughout his lifetime and will best be served in a DDA program.",
  "Q10": "At this time, it is believed that Kai will not be able to transition to independence.",
  "Q12": "supervised living arrangement, DDA services",
  "Q81": 1,
  "Q456": 0,
  "QIII": [
    {
      "panel8479878736818369DataGridColumnsName": "Tabitha and Wayne Moyer",
      "panel8479878736818369DataGridColumnsRelationship": "adoptive parents",
      "panel8479878736818369DataGridColumnsNatureOfSupport": "visitation"
    }
  ],
  "child": {
    "age": "16 Yrs",
    "dob": "2007-09-17T04:00:00.000Z",
    "prefx": null,
    "gender": "Male",
    "suffix": null,
    "cjamspid": "4057650",
    "fullname": "KAI LE SHAY MOYER ",
    "lastname": "MOYER",
    "personid": "b6a1979c-126b-497f-b84f-831ee12c1f86",
    "firstname": "KAI",
    "clientname": "Kai Moyer",
    "middlename": "LE SHAY",
    "placements": [
      {
        "county": null,
        "old_id": null,
        "reason": "",
        "country": null,
        "enddate": null,
        "endtime": null,
        "remarks": "Child stayed with the same program but switched houses",
        "zipcode": 21133,
        "address1": "Pilsen",
        "address2": null,
        "cityname": "Randallstown",
        "isvoided": 0,
        "personid": "b6a1979c-126b-497f-b84f-831ee12c1f86",
        "voiddate": null,
        "partnerid": null,
        "startdate": "2021-01-08T00:00:00",
        "starttime": "2021-01-08 08:00",
        "statename": "Maryland",
        "workphone": null,
        "isEditable": true,
        "providerid": null,
        "service_id": 167,
        "alternateid": 1560133,
        "exittypekey": null,
        "placementid": "cf741a53-e736-43a0-ba4f-540f92bc8384",
        "programname": "DD-Childrens Program/Pilsen Rd. (#50002328)",
        "voidremarks": null,
        "whereabouts": null,
        "contactphone": null,
        "providerdesc": null,
        "rejectreason": null,
        "statetypekey": "MD",
        "comarratedesc": null,
        "countytypekey": "1430",
        "isssaapproval": 0,
        "justification": null,
        "livingenddate": null,
        "routingstatus": "Approved",
        "servicecaseid": "141090ab-81f9-4176-8ca8-60fede95a074",
        "fostercarehome": null,
        "fostercaretext": null,
        "fostercomments": null,
        "revisionupdate": null,
        "transferagency": null,
        "cpahomerevision": [],
        "ifcapprovaldate": null,
        "livingstartdate": "2021-01-08T00:00:00",
        "providerdetails": {
          "address": "8621 Pilsen Rd   Randallstown Md 21133",
          "adr_box_no": null,
          "adr_city_nm": "Randallstown",
          "adr_zip5_no": 21133,
          "phonenumber": null,
          "provider_id": 5086498,
          "adr_state_cd": "MD",
          "providername": "Center for Social Change Pilsen Rd DDA",
          "adr_street_nm": "Pilsen",
          "adr_street_no": null,
          "adr_street_tx": "8621",
          "adr_street_suffix_cd": "RD",
          "provider_category_cd": "3274"
        },
        "ratestructureid": null,
        "rejectreasonkey": null,
        "runawayreported": null,
        "permanencyplanid": "d6b76806-09df-47aa-a3d5-1a9b6e5da9f1",
        "placementtypekey": "PRPL",
        "primarycaregiver": "Center for Social Change Pilsen Rd DDA",
        "providersentdate": "2021-01-08T00:00:00",
        "responseaccepted": "Yes",
        "caregiverclientid": null,
        "contractprogramid": 50002328,
        "exitreasontypekey": null,
        "otherpublicagency": null,
        "placementrevision": [
          {
            "status": null,
            "enddate": null,
            "endtime": null,
            "remarks": "Child stayed with the same program but switched houses",
            "exitdate": null,
            "exittime": null,
            "fullname": "Stacey Weimer",
            "isvoided": 0,
            "entrydate": "2021-01-08T00:00:00",
            "entrytime": "2021-01-08 08:00",
            "activeflag": 0,
            "approvedby": "Jessica Savage",
            "insertedon": "2021-01-10T16:56:47.915901",
            "alternateid": 1092293,
            "exittypekey": null,
            "placementid": "cf741a53-e736-43a0-ba4f-540f92bc8384",
            "provider_id": 5086498,
            "requestedby": "Stacey Weimer",
            "voidremarks": null,
            "approvaldate": null,
            "approveddate": "2021-01-10T00:00:00",
            "placement_id": 1560133,
            "providername": "Center for Social Change Pilsen Rd DDA",
            "justification": null,
            "requesteddate": "2021-01-10T16:56:47.915901",
            "exittypetypkey": null,
            "transferagency": null,
            "exitexplanation": "",
            "transactiondate": "2021-01-10T00:00:00",
            "exitreasontypkey": null,
            "otherpublicagency": null,
            "voidreasontypekey": null,
            "ischangepreadoptive": null,
            "placementrevisionid": "5c097ae0-95e4-43e3-9d2c-aa8534ae8c09",
            "primaryrelationship": null,
            "approvalstatustypkey": "3045",
            "leastrestrictiveplacement": null
          }
        ],
        "servicecasenumber": "3043134",
        "tribalservicearea": null,
        "voidreasontypekey": null,
        "secondarycaregiver": null,
        "exittypedescription": null,
        "fostercarenonfoster": null,
        "ischangepreadoptive": null,
        "primaryrelationship": null,
        "responseacceptedkey": "4612",
        "runawayreportnumber": null,
        "ischildplacedoutside": null,
        "approvalstatustypekey": null,
        "livingarrangementtype": null,
        "placementstructuredesc": "Therapeutic Group Homes",
        "fostercarenonfostertext": null,
        "livingarrangementtypekey": "32944",
        "exitreasontypedescription": null,
        "leastrestrictiveplacement": null,
        "transferagencydescription": null,
        "voidreasontypedescription": null,
        "intakeservicerequestactorid": "3c6d53c1-7294-4254-872b-3799bf3d08d7",
        "intakeservreqchildremovalid": "6f815bb7-4fde-4bb4-b153-71b2a0435a25"
      },
      {
        "county": null,
        "old_id": null,
        "reason": "",
        "country": null,
        "enddate": "2021-01-08T00:00:00",
        "endtime": "2021-01-08 11:00",
        "remarks": "Child staying with Center for Social Change.Just changing houses.",
        "zipcode": 21133,
        "address1": "Lucerne",
        "address2": null,
        "cityname": "Randallstown",
        "isvoided": 0,
        "personid": "b6a1979c-126b-497f-b84f-831ee12c1f86",
        "voiddate": null,
        "partnerid": null,
        "startdate": "2020-07-22T00:00:00",
        "starttime": "2020-07-22 16:00",
        "statename": "Maryland",
        "workphone": null,
        "isEditable": false,
        "providerid": null,
        "service_id": 14,
        "alternateid": 1534046,
        "exittypekey": "CIP",
        "placementid": "3fdade8f-ba3e-488b-aedb-f564b97b6446",
        "programname": "8601 LUCERNE RD (#15033)",
        "voidremarks": null,
        "whereabouts": null,
        "contactphone": null,
        "providerdesc": "818 referral sent",
        "rejectreason": null,
        "statetypekey": "MD",
        "comarratedesc": null,
        "countytypekey": "1430",
        "isssaapproval": 0,
        "justification": null,
        "livingenddate": "2021-01-08T00:00:00",
        "routingstatus": "Approved",
        "servicecaseid": "141090ab-81f9-4176-8ca8-60fede95a074",
        "fostercarehome": null,
        "fostercaretext": null,
        "fostercomments": null,
        "revisionupdate": null,
        "transferagency": null,
        "cpahomerevision": [],
        "ifcapprovaldate": null,
        "livingstartdate": "2020-07-22T00:00:00",
        "providerdetails": {
          "address": "8601 Lucerne Rd   Randallstown Md 21133",
          "adr_box_no": null,
          "adr_city_nm": "Randallstown",
          "adr_zip5_no": 21133,
          "phonenumber": null,
          "provider_id": 5086224,
          "adr_state_cd": "MD",
          "providername": "Center for Social Change Lucerne Rd DDA",
          "adr_street_nm": "Lucerne",
          "adr_street_no": null,
          "adr_street_tx": "8601",
          "adr_street_suffix_cd": "RD",
          "provider_category_cd": "3274"
        },
        "ratestructureid": null,
        "rejectreasonkey": null,
        "runawayreported": null,
        "placementtypekey": "PRPL",
        "primarycaregiver": "Center for Social Change Lucerne Rd DDA",
        "providersentdate": "2020-07-22T00:00:00",
        "responseaccepted": "Yes",
        "caregiverclientid": null,
        "contractprogramid": 15033,
        "exitreasontypekey": "CIPO",
        "otherpublicagency": null,
        "placementrevision": [
          {
            "status": null,
            "enddate": null,
            "endtime": null,
            "remarks": "Child staying with Center for Social Change.Just changing houses.",
            "exitdate": "2021-01-08T00:00:00",
            "exittime": "2021-01-08 11:00",
            "fullname": "Stacey Weimer",
            "isvoided": 0,
            "entrydate": "2020-07-22T00:00:00",
            "entrytime": "2020-07-22 16:00",
            "activeflag": 0,
            "approvedby": "Jessica Savage",
            "insertedon": "2021-01-08T14:05:48.966156",
            "alternateid": 1092210,
            "exittypekey": "CIP",
            "placementid": "3fdade8f-ba3e-488b-aedb-f564b97b6446",
            "provider_id": 5086224,
            "requestedby": "Stacey Weimer",
            "voidremarks": null,
            "approvaldate": null,
            "approveddate": "2021-01-08T00:00:00",
            "placement_id": 1534046,
            "providername": "Center for Social Change Lucerne Rd DDA",
            "justification": null,
            "requesteddate": "2021-01-08T14:05:48.966156",
            "exittypetypkey": null,
            "transferagency": null,
            "exitexplanation": "",
            "transactiondate": "2021-01-08T00:00:00",
            "exitreasontypkey": "CIPO",
            "otherpublicagency": null,
            "voidreasontypekey": null,
            "ischangepreadoptive": null,
            "placementrevisionid": "f270f571-8291-4107-9b34-6d942efb701e",
            "primaryrelationship": null,
            "approvalstatustypkey": "3045",
            "leastrestrictiveplacement": null
          },
          {
            "status": null,
            "enddate": null,
            "endtime": null,
            "remarks": " ",
            "exitdate": null,
            "exittime": null,
            "fullname": "Jessica Savage",
            "isvoided": 0,
            "entrydate": "2020-07-22T00:00:00",
            "entrytime": "2020-07-22 16:00",
            "activeflag": 0,
            "approvedby": "Amanda Richardson",
            "insertedon": "2020-07-23T16:36:33.643328",
            "alternateid": 1075835,
            "exittypekey": null,
            "placementid": "3fdade8f-ba3e-488b-aedb-f564b97b6446",
            "provider_id": 5086224,
            "requestedby": "Jessica Savage",
            "voidremarks": null,
            "approvaldate": "2021-01-08T00:00:00",
            "approveddate": "2020-07-23T00:00:00",
            "placement_id": 1534046,
            "providername": "Center for Social Change Lucerne Rd DDA",
            "justification": null,
            "requesteddate": "2020-07-23T16:36:33.643328",
            "exittypetypkey": null,
            "transferagency": null,
            "exitexplanation": "",
            "transactiondate": "2021-01-08T00:00:00",
            "exitreasontypkey": "CIPO",
            "otherpublicagency": null,
            "voidreasontypekey": null,
            "ischangepreadoptive": null,
            "placementrevisionid": "86997bb6-7d5e-49bd-b26c-dba4acb52067",
            "primaryrelationship": null,
            "approvalstatustypkey": "3045",
            "leastrestrictiveplacement": null
          }
        ],
        "servicecasenumber": "3043134",
        "tribalservicearea": null,
        "voidreasontypekey": null,
        "secondarycaregiver": null,
        "exittypedescription": "Change in Placement",
        "fostercarenonfoster": null,
        "ischangepreadoptive": null,
        "primaryrelationship": null,
        "responseacceptedkey": "4612",
        "runawayreportnumber": null,
        "ischildplacedoutside": null,
        "approvalstatustypekey": null,
        "livingarrangementtype": null,
        "placementstructuredesc": "Residential Group Homes",
        "fostercarenonfostertext": null,
        "livingarrangementtypekey": "32944",
        "exitreasontypedescription": "Other",
        "leastrestrictiveplacement": null,
        "transferagencydescription": null,
        "voidreasontypedescription": null,
        "intakeservicerequestactorid": "3c6d53c1-7294-4254-872b-3799bf3d08d7",
        "intakeservreqchildremovalid": "6f815bb7-4fde-4bb4-b153-71b2a0435a25"
      },
      {
        "county": null,
        "old_id": "660291",
        "reason": "",
        "country": null,
        "enddate": "2020-07-22T00:00:00",
        "endtime": "2020-07-22 09:00",
        "remarks": null,
        "zipcode": null,
        "address1": null,
        "address2": null,
        "cityname": null,
        "isvoided": 0,
        "personid": "b6a1979c-126b-497f-b84f-831ee12c1f86",
        "voiddate": null,
        "partnerid": "00000000-0000-0000-0000-000000000000",
        "startdate": "2017-02-08T00:00:00",
        "starttime": null,
        "statename": null,
        "workphone": null,
        "isEditable": false,
        "providerid": null,
        "service_id": null,
        "alternateid": 1394946,
        "exittypekey": "CIPS",
        "placementid": "203db390-cbc4-4276-aed0-4457e10be63b",
        "programname": null,
        "voidremarks": null,
        "whereabouts": null,
        "contactphone": null,
        "providerdesc": null,
        "rejectreason": null,
        "statetypekey": null,
        "comarratedesc": null,
        "countytypekey": null,
        "isssaapproval": null,
        "justification": null,
        "livingenddate": "2020-07-22T00:00:00",
        "routingstatus": "Approved",
        "servicecaseid": null,
        "fostercarehome": null,
        "fostercaretext": null,
        "fostercomments": null,
        "revisionupdate": null,
        "transferagency": null,
        "cpahomerevision": [],
        "ifcapprovaldate": null,
        "livingstartdate": "2017-02-08T00:00:00",
        "providerdetails": null,
        "ratestructureid": null,
        "rejectreasonkey": null,
        "runawayreported": null,
        "placementtypekey": "LA",
        "primarycaregiver": null,
        "providersentdate": null,
        "responseaccepted": null,
        "caregiverclientid": "00000000-0000-0000-0000-000000000000",
        "contractprogramid": null,
        "exitreasontypekey": null,
        "otherpublicagency": null,
        "placementrevision": [
          {
            "status": null,
            "enddate": null,
            "endtime": null,
            "remarks": null,
            "exitdate": "2020-07-22T00:00:00",
            "exittime": "2020-07-22 09:00",
            "fullname": "Kellie Warnick",
            "isvoided": 0,
            "entrydate": null,
            "entrytime": null,
            "activeflag": 0,
            "approvedby": "Jessica Savage",
            "insertedon": "2021-02-18T10:57:09.487658",
            "alternateid": 1095702,
            "exittypekey": "CIPS",
            "placementid": "203db390-cbc4-4276-aed0-4457e10be63b",
            "provider_id": null,
            "requestedby": "Kellie Warnick",
            "voidremarks": null,
            "approvaldate": null,
            "approveddate": "2021-02-18T00:00:00",
            "placement_id": 1394946,
            "providername": " ",
            "justification": null,
            "requesteddate": "2021-02-18T10:57:09.487658",
            "exittypetypkey": null,
            "transferagency": null,
            "exitexplanation": "",
            "transactiondate": "2021-02-18T00:00:00",
            "exitreasontypkey": null,
            "otherpublicagency": null,
            "voidreasontypekey": null,
            "ischangepreadoptive": null,
            "placementrevisionid": "fa35f4be-a6ad-4253-afe3-2604f99a7155",
            "primaryrelationship": null,
            "approvalstatustypkey": "3045",
            "leastrestrictiveplacement": null
          }
        ],
        "servicecasenumber": null,
        "tribalservicearea": null,
        "voidreasontypekey": null,
        "secondarycaregiver": null,
        "exittypedescription": "Change in Placement Structure",
        "fostercarenonfoster": null,
        "ischangepreadoptive": null,
        "primaryrelationship": null,
        "responseacceptedkey": null,
        "runawayreportnumber": null,
        "ischildplacedoutside": null,
        "approvalstatustypekey": null,
        "livingarrangementtype": "Adoption",
        "placementstructuredesc": null,
        "fostercarenonfostertext": null,
        "livingarrangementtypekey": "ADPN",
        "exitreasontypedescription": null,
        "leastrestrictiveplacement": null,
        "transferagencydescription": null,
        "voidreasontypedescription": null,
        "intakeservicerequestactorid": "3c6d53c1-7294-4254-872b-3799bf3d08d7",
        "intakeservreqchildremovalid": null
      }
    ],
    "removalList": [
      {
        "comments": "Family was provided with in home services and respite services through DDA to assist with stabilizing child to prevent out of home placement.  Child has significant behaviors that require an out of home placement as a result of these services not bringing about any change to child’s behaviors. ",
        "exitdate": null,
        "exittime": null,
        "personid": "b6a1979c-126b-497f-b84f-831ee12c1f86",
        "parent1id": 1272675,
        "parent2id": null,
        "removalid": 250603,
        "exitreason": null,
        "fathername": null,
        "guardianid": null,
        "mothername": null,
        "removalzip": "65559999",
        "returndate": null,
        "vpaenddate": "2021-01-22T00:00:00",
        "removaladd1": "427 Bray School Road, Oakland MD 21550",
        "removaladd2": null,
        "removalcity": null,
        "removaldate": "2020-07-22T00:00:00",
        "removaltime": "2020-07-22T15:00:00",
        "isdisability": null,
        "vpabegindate": "2020-07-22",
        "agencytypekey": "GH",
        "justification": null,
        "removalreason": [
          {
            "description": "Voluntary Placement",
            "removalreasontypekey": "VP"
          },
          {
            "description": "Child’s Disabilities",
            "removalreasontypekey": "CD"
          },
          {
            "description": "Child’s Behavior Problem",
            "removalreasontypekey": "CBP"
          }
        ],
        "servicecaseid": "141090ab-81f9-4176-8ca8-60fede95a074",
        "approvalstatus": "Approved",
        "removalstatecd": null,
        "removaltypekey": "CDVP",
        "revisionrecord": null,
        "transferagency": null,
        "caregiverreason": null,
        "intakeserviceid": null,
        "parent2comments": "Child requires specialized treatment to stabilize his behaviors and address his needs.  Child is extremely aggressive with others making his behaviors extremely dangerous to those around him.  Child engages in self injurious behaviors as well.  Child is non verbal and has a diagnosis of autism. ",
        "relativeactorid": null,
        "seccaregiveradd": "427 Bray School Road, Oakland MD 21550",
        "agencysigneddate": "2020-07-22T00:00:00",
        "isbioadoptedflag": null,
        "notmakingefforts": null,
        "childfactorsentry": null,
        "otherpublicagency": null,
        "parent2signeddate": "2020-07-22",
        "reasonableefforts": [
          {
            "description": "Reasonable efforts have been made but have been unsuccessful in preventing or eliminating the need for removal of child from childs home",
            "otherdescription": null,
            "removalreasontypekey": "REPERCH"
          },
          {
            "description": "Parenting Education and Assistance",
            "otherdescription": null,
            "removalreasontypekey": "PEA"
          },
          {
            "description": "Family Support Services",
            "otherdescription": null,
            "removalreasontypekey": "FSS"
          },
          {
            "description": "Family Preservation Services",
            "otherdescription": null,
            "removalreasontypekey": "FPS"
          }
        ],
        "removalexitreason": null,
        "rmvdfrmisractorid": null,
        "rmvdfrmpersonname": null,
        "servicecasenumber": "3043134",
        "volrelinquishment": 1,
        "isuploadedmanually": 1,
        "locationofadoption": null,
        "primarycaregiverid": null,
        "vpayouthsigneddate": null,
        "isbothparentssigned": 1,
        "primarycaregiveradd": "427 Bray School Road, Oakland MD 21550",
        "removalreasontypeid": null,
        "seccaregiveractorid": "7b52729d-b035-4aba-8c50-ece805687fc4",
        "removalcircumstances": {
          "neglect": false,
          "runaway": false,
          "abandonment": false,
          "sexualabuse": false,
          "childdruguse": false,
          "homelessness": false,
          "physicalabuse": false,
          "familyconflict": false,
          "medicalneglect": false,
          "sextrafficking": false,
          "tribaltitleive": false,
          "childalcoholuse": false,
          "failuretoreturn": false,
          "caretakerdruguse": false,
          "deathofcaretaker": false,
          "domesticviolence": false,
          "inadequatehousing": false,
          "diagnosedcondition": false,
          "whereaboutsunknown": false,
          "caretakeralcoholuse": false,
          "parentalimmigration": false,
          "childbehaviorproblem": true,
          "prenataldrugexposure": false,
          "publicagencytitleive": false,
          "inadequateaccesstomhs": false,
          "childrequestedplacement": false,
          "prenatalalcoholexposure": false,
          "voluntaryrelinquishment": false,
          "incarcerationofcaretaker": false,
          "psychologicalemotionalabuse": false,
          "caretakerignificantimpphysical": false,
          "caretakersignificantimpairment": false,
          "inadequateaccesstomedicalservices": false
        },
        "vpaparentssigneddate": "2020-07-22",
        "isverifiedreporteradd": 1,
        "reasonableeffortsmade": null,
        "specifiedrelativename": null,
        "vpaguardiansigneddate": null,
        "familystructuretypekey": "290",
        "isshelterauthcompleted": 1,
        "environmentatremovalkey": "PAHOLD",
        "isverifiedcaregiver1add": 1,
        "isverifiedcaregiver2add": 1,
        "primarycaregiveractorid": "b680f57d-b86a-4c5a-b0e0-46adab665ca8",
        "removaltypekeydescription": "Children With Disabilities Voluntary Placement",
        "childphysicalremovaladdress": "427 Bray School Road, Oakland MD 21550",
        "intakeservicerequestactorid": "3c6d53c1-7294-4254-872b-3799bf3d08d7",
        "intakeservreqchildremovalid": "6f815bb7-4fde-4bb4-b153-71b2a0435a25",
        "ischildaddressasprimaryaddress": 1,
        "ischildphysicalremovaladdressverified": 1,
        "specifiedrelativedatechildlastlivedwith": null
      }
    ],
    "permanencyplans": [
      {
        "reason": null,
        "status": "Approved",
        "enddate": null,
        "duration": "-65",
        "exitDate": null,
        "parentname": null,
        "reviewdate": null,
        "casedetails": null,
        "parent2name": null,
        "achieveddate": null,
        "planreviewdate": "2024-01-03T05:00:00.000Z",
        "establisheddate": "09/17/2023",
        "primarycomments": null,
        "primaryplandate": "2023-09-17T04:00:00",
        "permanencyplanid": "d6b76806-09df-47aa-a3d5-1a9b6e5da9f1",
        "childhasactivegap": false,
        "permplanquestdata": {
          "lifebookExpln": "yes",
          "isProviderAgree": "1",
          "permToPermExpln": "N/A",
          "courtOrdersExpln": "Worker is communicating with the facility and providing assistance as needed.   Worker is ensuring that youths needs are being met by the facility.  Worker is conducting monthly visits.",
          "safeAndCareExpln": "Worker has ongoing communication with the facility staff and makes monthly face to face visits to the home and/or school.",
          "isInClosedProximity": "2",
          "isProviderAgreeExpln": "Kai has done well and adjusted to the Center for Social Change and the facility supports the permanency plan of APPLA.",
          "assessmentPeriodExpln": "Kai will need ongoing care and supervision throughout his adult life and a permanency plan of APPLA is most appropriate.",
          "serviceAgreementExpln": "n/a",
          "meetingSafetyNeedsExpln": "Kai has been at Center for Social Change for several years and has adjusted well.  All of Kais mental, medical and educational needs are being met.",
          "sixMonthsPlacementExpln": "No changes have occured and there are not anticipated changes.",
          "isInClosedProximityExpln": "N/A",
          "serviceAgreementForOtherExpln": "Kai has weekly phone calls and occasional in-person visits with the Moyers."
        },
        "primarypermanency": [
          {
            "gapstatuscheck": null,
            "permanencyplanid": "d6b76806-09df-47aa-a3d5-1a9b6e5da9f1",
            "plantypedescription": "APPLA",
            "permanencyplantypekey": "APPLA",
            "plansubtypedescription": null
          }
        ],
        "concurrentcomments": null,
        "courtorderreceived": true,
        "concurrentpermanency": [
          {
            "permanencyplanid": "d6b76806-09df-47aa-a3d5-1a9b6e5da9f1",
            "concurrentplantypekey": "Guardianship",
            "concurrentsubdescription": null,
            "concurrentplandescription": "Guardianship by Non-Relative"
          }
        ],
        "permanencyplanremainssame": null,
        "intakeservicerequestactorid": "3c6d53c1-7294-4254-872b-3799bf3d08d7",
        "permanencyplanremainssamedate": null
      },
      {
        "reason": "Permanency plan changed to APPLA",
        "status": "Approved",
        "enddate": "09/17/2023",
        "duration": "-245",
        "exitDate": null,
        "parentname": null,
        "reviewdate": "2024-01-03T05:00:00",
        "casedetails": null,
        "parent2name": null,
        "achieveddate": "2023-09-17T00:00:00",
        "planreviewdate": "2024-07-01T04:00:00.000Z",
        "establisheddate": "06/13/2023",
        "primarycomments": null,
        "primaryplandate": "2023-06-13T04:00:00",
        "permanencyplanid": "caa82ea0-747c-4f77-91c0-36d8bb69be5a",
        "childhasactivegap": false,
        "permplanquestdata": {
          "lifebookExpln": "Yes",
          "isProviderAgree": "1",
          "permToPermExpln": "See previous plan.",
          "courtOrdersExpln": "Worker visits Kai monthly, attends all IEP meetings, coordinates parental visitation and coordinates with Center for Social Change to assist in meeting his needs.",
          "safeAndCareExpln": "See previous plan.",
          "isInClosedProximity": "2",
          "isProviderAgreeExpln": "See previous plan",
          "assessmentPeriodExpln": "Kai’s permanency plan will be moved to APPLA at the age of 16 due to parental inability to meet his daily needs.",
          "serviceAgreementExpln": "N/A",
          "meetingSafetyNeedsExpln": "Kai has been placed with Center for Social Change for the past 3 years and they continue to meet his needs.",
          "sixMonthsPlacementExpln": "There have been no changes.",
          "isInClosedProximityExpln": null,
          "serviceAgreementForOtherExpln": "N/A"
        },
        "primarypermanency": [
          {
            "gapstatuscheck": null,
            "permanencyplanid": "caa82ea0-747c-4f77-91c0-36d8bb69be5a",
            "plantypedescription": "Guardianship by Non-Relative",
            "permanencyplantypekey": "Guardianship",
            "plansubtypedescription": null
          }
        ],
        "concurrentcomments": null,
        "courtorderreceived": true,
        "concurrentpermanency": [
          {
            "permanencyplanid": "caa82ea0-747c-4f77-91c0-36d8bb69be5a",
            "concurrentplantypekey": "APPLA",
            "concurrentsubdescription": null,
            "concurrentplandescription": "APPLA"
          }
        ],
        "permanencyplanremainssame": true,
        "intakeservicerequestactorid": "3c6d53c1-7294-4254-872b-3799bf3d08d7",
        "permanencyplanremainssamedate": "2023-07-12T16:26:00"
      },
      {
        "reason": "Changed to APPLA",
        "status": "Approved",
        "enddate": "07/10/2023",
        "duration": "-65",
        "exitDate": null,
        "parentname": null,
        "reviewdate": "2023-07-07T04:00:00",
        "casedetails": null,
        "parent2name": null,
        "achieveddate": null,
        "planreviewdate": "2024-01-03T05:00:00.000Z",
        "establisheddate": "01/23/2023",
        "primarycomments": null,
        "primaryplandate": "2023-01-23T05:00:00",
        "permanencyplanid": "4d3c27c9-5061-4bf7-b8cb-4df351f62672",
        "childhasactivegap": false,
        "permplanquestdata": {
          "lifebookExpln": "yes",
          "isProviderAgree": "2",
          "permToPermExpln": "Kai has significant special needs and requires 24/7 care and support. He requires a 2-1 aide to help successfully care from him.He continues to meet the requirement for a group home setting.",
          "courtOrdersExpln": "Worker has offered family assistance with visitation.This worker has met with Kais caregivers and teachers on a regular basis and has attended all meetings.",
          "safeAndCareExpln": "Worker completes montly home visits and visits Kai at school.Kai has daily supports in place he requires assistants with feeding himself,bathing,dressing and requires ongoing supervision.Center for Social Change meets his daily needs.",
          "isInClosedProximity": "0",
          "isProviderAgreeExpln": null,
          "assessmentPeriodExpln": "n/a",
          "serviceAgreementExpln": "Parents are not working on reunification services.They cant meet Kais daily needs.",
          "meetingSafetyNeedsExpln": "Worker visits youth monthly.Kai requires a 2-1 aide to assist him with his daily needs.Worker makes necessary referrals and stays in contact with all parties",
          "sixMonthsPlacementExpln": "No anticipated changes in Kais placement are expected.",
          "isInClosedProximityExpln": "Family has not visited with Kai in person they have done weekly virtual contact.",
          "serviceAgreementForOtherExpln": "Kai currently visits with the Moyers virtually.They have not completed any in person visits in the last six months. "
        },
        "primarypermanency": [
          {
            "gapstatuscheck": null,
            "permanencyplanid": "4d3c27c9-5061-4bf7-b8cb-4df351f62672",
            "plantypedescription": "Guardianship by Non-Relative",
            "permanencyplantypekey": "Guardianship",
            "plansubtypedescription": null
          }
        ],
        "concurrentcomments": null,
        "courtorderreceived": null,
        "concurrentpermanency": [
          {
            "permanencyplanid": "4d3c27c9-5061-4bf7-b8cb-4df351f62672",
            "concurrentplantypekey": "APPLA",
            "concurrentsubdescription": null,
            "concurrentplandescription": "APPLA"
          }
        ],
        "permanencyplanremainssame": false,
        "intakeservicerequestactorid": "3c6d53c1-7294-4254-872b-3799bf3d08d7",
        "permanencyplanremainssamedate": "2023-07-10T12:42:00"
      },
      {
        "reason": null,
        "status": "Approved",
        "enddate": "01/23/2023",
        "duration": "295",
        "exitDate": null,
        "parentname": "b680f57d-b86a-4c5a-b0e0-46adab665ca8",
        "reviewdate": null,
        "casedetails": null,
        "parent2name": null,
        "achieveddate": null,
        "planreviewdate": "2023-01-08T05:00:00.000Z",
        "establisheddate": "08/09/2022",
        "primarycomments": null,
        "primaryplandate": "2022-08-09T04:00:00",
        "permanencyplanid": "ad74543c-e20c-42b9-8b0f-79812863b02f",
        "childhasactivegap": false,
        "permplanquestdata": {
          "lifebookExpln": "n/a",
          "isProviderAgree": "1",
          "permToPermExpln": "Kai may require an adult program. His needs require a higher level of care and he is provided a 2-1 aide to help meet his daily needs.  ",
          "courtOrdersExpln": "Worker has offered gas cards,hotels any support needed for the Moyers to complete an in person visit.",
          "safeAndCareExpln": "Monthly visitation and communication with providers,school and medical staff. ",
          "isInClosedProximity": "2",
          "isProviderAgreeExpln": null,
          "assessmentPeriodExpln": "Kais biological was ruled out as a possible resource. ",
          "serviceAgreementExpln": "Parents have not attended any in person visitation.They do visit virtually weekly",
          "meetingSafetyNeedsExpln": "Center for Social Change continue to be the safest,least restrictive placeent for Kai.",
          "sixMonthsPlacementExpln": "Know anticipated changes are anticipated for Kai in the next months",
          "isInClosedProximityExpln": "Kai lives in group home out of county. ",
          "serviceAgreementForOtherExpln": "n/a"
        },
        "primarypermanency": [
          {
            "gapstatuscheck": null,
            "permanencyplanid": "ad74543c-e20c-42b9-8b0f-79812863b02f",
            "plantypedescription": "Reunification",
            "permanencyplantypekey": "Reunification",
            "plansubtypedescription": null
          }
        ],
        "concurrentcomments": null,
        "courtorderreceived": true,
        "concurrentpermanency": [
          {
            "permanencyplanid": "ad74543c-e20c-42b9-8b0f-79812863b02f",
            "concurrentplantypekey": "APPLA",
            "concurrentsubdescription": null,
            "concurrentplandescription": "APPLA"
          }
        ],
        "permanencyplanremainssame": null,
        "intakeservicerequestactorid": "3c6d53c1-7294-4254-872b-3799bf3d08d7",
        "permanencyplanremainssamedate": null
      },
      {
        "reason": "No longer a VPA.Youth found to be CINA",
        "status": "Approved",
        "enddate": "08/09/2022",
        "duration": "1015",
        "exitDate": null,
        "parentname": "b680f57d-b86a-4c5a-b0e0-46adab665ca8",
        "reviewdate": null,
        "casedetails": null,
        "parent2name": null,
        "achieveddate": null,
        "planreviewdate": "2021-01-18T05:00:00.000Z",
        "establisheddate": "09/22/2020",
        "primarycomments": "Voluntary placement",
        "primaryplandate": "2020-09-22T04:00:00",
        "permanencyplanid": "8502f59d-43ae-410c-b770-8906b2041afc",
        "childhasactivegap": false,
        "permplanquestdata": {
          "lifebookExpln": "yes",
          "isProviderAgree": "1",
          "permToPermExpln": "Case will be reviewed in 6 months. ",
          "courtOrdersExpln": "Worker has ongoing contact with all involved parties.Makes necessary referrals and monitors progress",
          "safeAndCareExpln": "Worker has monthly virtual contact with Kai.Worker stays in contact with all parties to ensure that Kais needs are being met.",
          "isInClosedProximity": "1",
          "isProviderAgreeExpln": "This is a VPA placement",
          "assessmentPeriodExpln": "Kai was just placed at Center for Social Change.",
          "serviceAgreementExpln": "Because this is a VPA  parent will continue to work with Center for Social Change and Garrett County Bd.of Education",
          "meetingSafetyNeedsExpln": "Center for Social Change is able to meet all of Kais special needs.",
          "sixMonthsPlacementExpln": "This VPA will be reviewed in 6 months",
          "isInClosedProximityExpln": "This is a Voluntary placement",
          "serviceAgreementForOtherExpln": "Kai identifies with the Moyers as his family."
        },
        "primarypermanency": [
          {
            "gapstatuscheck": null,
            "permanencyplanid": "8502f59d-43ae-410c-b770-8906b2041afc",
            "plantypedescription": "Reunification",
            "permanencyplantypekey": "Reunification",
            "plansubtypedescription": null
          }
        ],
        "concurrentcomments": null,
        "courtorderreceived": null,
        "concurrentpermanency": [
          {
            "permanencyplanid": "8502f59d-43ae-410c-b770-8906b2041afc",
            "concurrentplantypekey": "GUARDR",
            "concurrentsubdescription": null,
            "concurrentplandescription": "Guardianship by relative"
          }
        ],
        "permanencyplanremainssame": null,
        "intakeservicerequestactorid": "3c6d53c1-7294-4254-872b-3799bf3d08d7",
        "permanencyplanremainssamedate": null
      }
    ]
  },
  "Complete": true,
  "userrole": "apcs",
  "disableforms": [],
  "textboxeight": "Kai is developmentally disabled and is placed in a DDA home with 24/7 support and 2:1 supervision.  Kai is placed in a Level III school.",
  "caseworkername": "Tamera Bittinger",
  "supervisorname": "Ashley Stuck",
  "assessmentstatus": "Accepted",
  "wasthechildasked": "Kai is not able to comprehend his permanency plan.",
  "assessmentreviewed": "InProcess",
  "caseworkercomments": "",
  "supervisorcomments": "",
  "panel38767828842569685ColumnsSelectBoxesField": {
    "college": false,
    "employment": false,
    "vocationalTraining": true
  }
}',
updatedby = 'da23f52d-6348-413b-9e37-0de2ab823825', updatedon = '2025-05-06 08:35:27'
where assessmentid = '4f39e7ea-e3e9-49af-9704-3509ef42423e' and activeflag = 1;
