/*
Issue Description: CJAMS-60660 
Category/Module: Overdue Reason
Root cause: User requested to change the narrative should be changed to, "*{}This referral was screened out as it does not meet Maryland's SDM requirements.{}*"
Fix provided: Data fix has been done to update the narrative should be changed to, "*{}This referral was screened out as it does not meet  Maryland's SDM requirements.{}*"
Regression Impacts: N/A
Is Code fix Required?: NO
Code fix ticket#: N/A 
Reason why no related code fix: Data fix needed to correct the user entry error
*/

update intakesnapshot  
set jsondata = jsonb_set(jsondata, '{General, Narrative}',
	'"<p>Rachel Briscoe, mother</p><p>DOB:7/12/1987</p><p>1609 Sherwood Ave.</p><p>Baltimore, MD, 21239</p><p>443 452-0127</p><p><br></p><p>Tyrone Thompson, child</p><p>DOB: 1/29/2011</p><p><br></p><p>Joniah Thompson, child</p><p>DOB; 11/6/2012</p><p><br></p><p>On 7/12/2025 around 6:19 p.m. the caller stated that she wanted to make a family preservation referral. The caller stated that the mother lost her left leg and had a prosthetic leg and had a toe on her right foot amputated. The caller also reported that the mother lost her leg and toe due to type two diabetes. The caller stated that the mother and her two children were living with her brother and his wife, but they could not stay there indefinitely. The caller stated that mother received SSDI in the amount of $1715 a month and $500 in food stamps. The mother stated that she requested housing service from Social Services, but they said that the housing assistance waiting list was closed. The mother stated that she applied for The Uplands, but they denied her because she owed money to Garden Village Apartments in the amount of 7,000 dollars. The mother stated that during this time she was working but got sick due to her health issues.&nbsp;The caller stated that Tyrone attended Overlea High school and was in the 9th grade and Joniah attended Nottingham Middle School and she was in the 7th grade. The caller did not report any substance use, mental illness or domestic violence in the home. The mother and caller were requesting family preservation services for housing.</p><p><br></p><p>The mother was given names of several shelters, options for room for rent, and other resources; MDH Community Options Waiver, Perkins Square income based housing program, United Way, American Association of Diabetes, and the local church.</p><p><br></p><p>***This referral was screened out as it does not meet Maryland''s SDM requirements***</span></p>"'
		),
updatedby = 'CJAMS-60660', updatedon = now()
where intakenumber = 'I251013321195' and activeflag = 1;

update intakedastaging  
set jsondata = jsonb_set(jsondata, '{General, Narrative}',
	'"<p>Rachel Briscoe, mother</p><p>DOB:7/12/1987</p><p>1609 Sherwood Ave.</p><p>Baltimore, MD, 21239</p><p>443 452-0127</p><p><br></p><p>Tyrone Thompson, child</p><p>DOB: 1/29/2011</p><p><br></p><p>Joniah Thompson, child</p><p>DOB; 11/6/2012</p><p><br></p><p>On 7/12/2025 around 6:19 p.m. the caller stated that she wanted to make a family preservation referral. The caller stated that the mother lost her left leg and had a prosthetic leg and had a toe on her right foot amputated. The caller also reported that the mother lost her leg and toe due to type two diabetes. The caller stated that the mother and her two children were living with her brother and his wife, but they could not stay there indefinitely. The caller stated that mother received SSDI in the amount of $1715 a month and $500 in food stamps. The mother stated that she requested housing service from Social Services, but they said that the housing assistance waiting list was closed. The mother stated that she applied for The Uplands, but they denied her because she owed money to Garden Village Apartments in the amount of 7,000 dollars. The mother stated that during this time she was working but got sick due to her health issues.&nbsp;The caller stated that Tyrone attended Overlea High school and was in the 9th grade and Joniah attended Nottingham Middle School and she was in the 7th grade. The caller did not report any substance use, mental illness or domestic violence in the home. The mother and caller were requesting family preservation services for housing.</p><p><br></p><p>The mother was given names of several shelters, options for room for rent, and other resources; MDH Community Options Waiver, Perkins Square income based housing program, United Way, American Association of Diabetes, and the local church.</p><p><br></p><p>***This referral was screened out as it does not meet Maryland''s SDM requirements***</span></p>"'
		),
updatedby = 'CJAMS-60660', updatedon = now()
where intakenumber = 'I251013321195' and activeflag = 1;

update intakedastatus  
set jsondata = jsonb_set(jsondata, '{General, Narrative}',
	'"<p>Rachel Briscoe, mother</p><p>DOB:7/12/1987</p><p>1609 Sherwood Ave.</p><p>Baltimore, MD, 21239</p><p>443 452-0127</p><p><br></p><p>Tyrone Thompson, child</p><p>DOB: 1/29/2011</p><p><br></p><p>Joniah Thompson, child</p><p>DOB; 11/6/2012</p><p><br></p><p>On 7/12/2025 around 6:19 p.m. the caller stated that she wanted to make a family preservation referral. The caller stated that the mother lost her left leg and had a prosthetic leg and had a toe on her right foot amputated. The caller also reported that the mother lost her leg and toe due to type two diabetes. The caller stated that the mother and her two children were living with her brother and his wife, but they could not stay there indefinitely. The caller stated that mother received SSDI in the amount of $1715 a month and $500 in food stamps. The mother stated that she requested housing service from Social Services, but they said that the housing assistance waiting list was closed. The mother stated that she applied for The Uplands, but they denied her because she owed money to Garden Village Apartments in the amount of 7,000 dollars. The mother stated that during this time she was working but got sick due to her health issues.&nbsp;The caller stated that Tyrone attended Overlea High school and was in the 9th grade and Joniah attended Nottingham Middle School and she was in the 7th grade. The caller did not report any substance use, mental illness or domestic violence in the home. The mother and caller were requesting family preservation services for housing.</p><p><br></p><p>The mother was given names of several shelters, options for room for rent, and other resources; MDH Community Options Waiver, Perkins Square income based housing program, United Way, American Association of Diabetes, and the local church.</p><p><br></p><p>***This referral was screened out as it does not meet Maryland''s SDM requirements***</span></p>"'
		),
	updatedby = 'CJAMS-60660', updatedon = now()
where intakenumber = 'I251013321195' and activeflag = 1;

update intakeservicerequest  set 
narrative  = 	'<p>Rachel Briscoe, mother</p><p>DOB:7/12/1987</p><p>1609 Sherwood Ave.</p><p>Baltimore, MD, 21239</p><p>443 452-0127</p><p><br></p><p>Tyrone Thompson, child</p><p>DOB: 1/29/2011</p><p><br></p><p>Joniah Thompson, child</p><p>DOB; 11/6/2012</p><p><br></p><p>On 7/12/2025 around 6:19 p.m. the caller stated that she wanted to make a family preservation referral. The caller stated that the mother lost her left leg and had a prosthetic leg and had a toe on her right foot amputated. The caller also reported that the mother lost her leg and toe due to type two diabetes. The caller stated that the mother and her two children were living with her brother and his wife, but they could not stay there indefinitely. The caller stated that mother received SSDI in the amount of $1715 a month and $500 in food stamps. The mother stated that she requested housing service from Social Services, but they said that the housing assistance waiting list was closed. The mother stated that she applied for The Uplands, but they denied her because she owed money to Garden Village Apartments in the amount of 7,000 dollars. The mother stated that during this time she was working but got sick due to her health issues.&nbsp;The caller stated that Tyrone attended Overlea High school and was in the 9th grade and Joniah attended Nottingham Middle School and she was in the 7th grade. The caller did not report any substance use, mental illness or domestic violence in the home. The mother and caller were requesting family preservation services for housing.</p><p><br></p><p>The mother was given names of several shelters, options for room for rent, and other resources; MDH Community Options Waiver, Perkins Square income based housing program, United Way, American Association of Diabetes, and the local church.</p><p><br></p><p>***This referral was screened out as it does not meet Maryland''s SDM requirements***</span></p>',
updatedby = 'CJAMS-60660', updatedon = now()
where intakenumber = 'I251013321195' and activeflag = 1;