/*
Issue Description: CJAMS-69658 Update the name from an intake report
Category/Module: Intake
Root cause: User error and they want to update the person firstname as Amber Long from Zach Long.
Fix provided: Data fix has been done to update intake narrative information.
Regression Impacts: N/A
Is Code fix Required?: No
Code fix ticket#: N/A
Reason why no related code fix: User error and data fix should fix it.
*/


update intakedastaging
set narrative='<p>Calvert&nbsp;County&nbsp;DSS&nbsp;has&nbsp;requested&nbsp;that&nbsp;a&nbsp;CPS&nbsp;background&nbsp;clearance&nbsp;check&nbsp;be&nbsp;completed&nbsp;on&nbsp;Amber&nbsp;Long&nbsp;for&nbsp;the&nbsp;purposes&nbsp;of&nbsp;adoption&nbsp;and&nbsp;foster&nbsp;care.&nbsp;CJAMS&nbsp;has&nbsp;been&nbsp;checked.&nbsp;Subject&nbsp;is&nbsp;cleared.&nbsp;No&nbsp;further&nbsp;information&nbsp;to&nbsp;report.&nbsp;</p>',
	jsondata='{
  "sdm": {
    "isar": false,
    "isir": false,
    "isroh": true,
    "worker": "",
    "comments": "",
    "countyid": null,
    "isschool": false,
    "objectid": "I261014145700",
    "provider": [],
    "screenIn": {},
    "immediate": "",
    "screenOut": {
      "duplicatereportflag": 0
    },
    "objecttype": "Intake",
    "referralid": "",
    "reportdate": null,
    "riskofHarm": {
      "isnegrh_exposednewborn": false
    },
    "supervisor": "",
    "workerdate": null,
    "badgenumber": "",
    "referraldob": "2026-08-04T19:02:19.628Z",
    "sexualAbuse": {},
    "maltreatment": "no",
    "recordnumber": "",
    "referralname": "",
    "allegedvictim": [],
    "childfatality": "no",
    "immediateList": {},
    "isreportmeets": false,
    "issexualabuse": false,
    "physicalAbuse": {
      "ismalpa_labortrafficking": false
    },
    "providerKnown": null,
    "generalNeglect": {},
    "ismaltreatment": false,
    "linkschidresid": null,
    "supervisordate": null,
    "childsresidence": false,
    "cpsResponseType": null,
    "ischildfatality": false,
    "isfinalscreenin": false,
    "noImmediateList": {},
    "officerlastname": "",
    "providerdetails": "",
    "unattendedChild": {},
    "arGeneralNeglect": {},
    "isdeathorserious": false,
    "officerfirstname": "",
    "allegedmaltreator": [],
    "childUnderOneYear": "",
    "childunderoneyear": "",
    "islicenseddaycare": false,
    "isoverriderequest": false,
    "officermiddlename": "",
    "selecttrafficking": null,
    "confirmtrafficking": "NO",
    "islabortrafficking": false,
    "isprivateplacement": false,
    "issignordiagonises": false,
    "screeningRecommend": false,
    "traffickingupdated": true,
    "duplicatereportflag": 0,
    "maltreatmentupdated": false,
    "scnRecommendOveride": "",
    "childfatalityupdated": "yes",
    "disqualifyingFactors": {},
    "isfcplacementsetting": false,
    "disqualifyingCriteria": {
      "isreportmeets": false,
      "issexualabuse": false,
      "isdeathorserious": false,
      "islabortrafficking": false,
      "issignordiagonises": false
    },
    "isfclivingarrangement": false,
    "providerunknowndetail": null,
    "isnegrh_exposednewborn": false,
    "isseriousphysicalinjury": null,
    "selectedproviderdetails": null,
    "ismalpa_labortrafficking": false,
    "isnegfp_cargiverintervene": false,
    "isnegmn_unreasonabledelay": false,
    "ismenab_psycologicalability": false,
    "ismenng_psycologicalability": false
  },
  "DAType": {
    "DATypeDetail": [
      {
        "caseID": "",
        "DAStatus": "Closed",
        "DaTypeKey": "d207bdd4-f281-4ec8-949c-8fd9657227f9",
        "intakeAction": "",
        "issubtypekey": true,
        "DADisposition": "Closed",
        "serviceTypeID": "",
        "dispositioncode": "Closed",
        "ServiceRequestNumber": "I261014145700",
        "intakeserreqstatustypekey": "Closed",
        "supMultipleDispositionDropdown": [],
        "intakeMultipleDispositionDropdown": []
      }
    ]
  },
  "roacps": null,
  "General": {
    "Time": "2026-08-04T19:03:11.954Z",
    "Iscps": null,
    "Agency": "CW",
    "Author": "JessicaMilstead",
    "Source": "0bdda2ab-b74f-4d74-ba17-3b9b37a9ca19",
    "Purpose": "d207bdd4-f281-4ec8-949c-8fd9657227f9",
    "Lastname": "Lawson",
    "countyid": "b0ca6422-8241-4d86-bfef-51c7225de2fc",
    "Firstname": "Anna",
    "Narrative": "<p>Calvert&nbsp;County&nbsp;DSS&nbsp;has&nbsp;requested&nbsp;that&nbsp;a&nbsp;CPS&nbsp;background&nbsp;clearance&nbsp;check&nbsp;be&nbsp;completed&nbsp;on&nbsp;Amber&nbsp;Long&nbsp;for&nbsp;the&nbsp;purposes&nbsp;of&nbsp;adoption&nbsp;and&nbsp;foster&nbsp;care.&nbsp;CJAMS&nbsp;has&nbsp;been&nbsp;checked.&nbsp;Subject&nbsp;is&nbsp;cleared.&nbsp;No&nbsp;further&nbsp;information&nbsp;to&nbsp;report.&nbsp;</p>",
    "AgencyCode": "CW",
    "Middlename": "",
    "CreatedDate": "2026-08-04T18:59:21.530Z",
    "InputSource": "0bdda2ab-b74f-4d74-ba17-3b9b37a9ca19",
    "PurposeName": "Request for services",
    "RecivedDate": "08/04/2026 02:59:21 PM",
    "IntakeNumber": "I261014145700",
    "intakeservice": [
      {
        "description": "CPS History Clearance",
        "intakeservid": "98bda8ba-a7f9-4dc0-9415-52098a74cff6",
        "intakeservsubtype": [],
        "intakeservtypekey": "CPSHC"
      }
    ],
    "isDisposition": true,
    "receiveddelay": "N/A",
    "requestercity": "Prince Frederick",
    "islocalreferal": 0,
    "requesterstate": "MD",
    "HeadofHousehold": " Amber Michelle Long ",
    "offenselocation": "20678",
    "queAdditionDate": "2026-08-04T19:02:13.518Z",
    "requestercounty": "b0ca6422-8241-4d86-bfef-51c7225de2fc",
    "submissiondelay": "N/A",
    "RefuseToShareZip": false,
    "IsUnknownReporter": false,
    "addendumNarrative": null,
    "requesteraddress1": "200 Duke St",
    "IsAnonymousReporter": false,
    "cpsHistoryClearance": "<p>N/A</p>",
    "requestercountyname": "Calvert",
    "narrativeUpdatedDate": "2026-08-04T19:01:14.384Z",
    "isacknowledgementletter": 1,
    "communicationDescription": "Phone",
    "isaddendumnarrativeupdated": false
  },
  "clwStatus": null,
  "narrative": [
    {
      "Role": "SSP",
      "email": "calvert.resourcehomes@maryland.gov",
      "title": "",
      "ZipCode": "",
      "Lastname": "Lawson",
      "RoleName": "Social Services personnel",
      "Firstname": "Anna",
      "Middlename": "",
      "PhoneNumber": "4435506900",
      "incidentdate": "",
      "organization": "Calvert County DSS",
      "isapproximate": false,
      "requestercity": "Prince Frederick",
      "PhoneNumberExt": "",
      "requesterstate": "MD",
      "offenselocation": "20678",
      "requestercounty": "b0ca6422-8241-4d86-bfef-51c7225de2fc",
      "incidentlocation": "",
      "requesteraddress1": "200 Duke St",
      "requesteraddress2": "",
      "requestercountyname": "Calvert"
    }
  ],
  "Allegations": [],
  "disposition": [
    {
      "caseID": "",
      "DAStatus": "Closed",
      "DaTypeKey": "d207bdd4-f281-4ec8-949c-8fd9657227f9",
      "intakeAction": "",
      "issubtypekey": true,
      "DADisposition": "Closed",
      "serviceTypeID": "",
      "dispositioncode": "Closed",
      "ServiceRequestNumber": "I261014145700",
      "intakeserreqstatustypekey": "Closed",
      "supMultipleDispositionDropdown": [],
      "intakeMultipleDispositionDropdown": []
    }
  ],
  "clearhistory": {
    "close": null,
    "reason": "ADPP",
    "comments": null,
    "individual": null,
    "thirdparty": null,
    "workername": "JessicaMilstead",
    "startdatetime": null
  },
  "createdCases": null,
  "reviewstatus": {
    "appevent": "INTR",
    "commenttext": "",
    "isclosecase": true,
    "isfromintake": true,
    "ispreintakeapproved": false,
    "youthstatuseventcode": ""
  },
  "persondetails": {
    "Person": [
      {
        "Dob": "1985-01-23T05:00:00.000Z",
        "Pid": "5407c7ae-90f5-4b74-961c-c3a24b119f92",
        "Zip": "20639",
        "ssn": "108785163",
        "City": "Huntingtown",
        "Role": "CPSS",
        "race": [
          {
            "value_text": "White",
            "racetypekey": "WH"
          }
        ],
        "State": "MD",
        "email": "thestruggleisreal.forgiven@gmail.com",
        "County": "Anne Arundel",
        "Gender": "F",
        "county": "b0ca6422-8241-4d86-bfef-51c7225de2fc",
        "school": [],
        "Address": "19 Robshire Manor Rd",
        "address": [
          {
            "city": "Linthicum",
            "state": "MD",
            "county": "Anne Arundel",
            "endDate": "04/29/2019",
            "phoneNo": "",
            "zipcode": "21090",
            "Address2": "",
            "address1": "849 Internation",
            "addressid": "",
            "startDate": "",
            "activeflag": 1,
            "addresstype": "31",
            "addresstypeLabel": "Home",
            "knownDangerAddress": "",
            "knownDangerAddressReason": ""
          }
        ],
        "emailID": [],
        "testing": [],
        "Lastname": "Long",
        "cjamspid": "201280588",
        "contacts": [],
        "employer": [],
        "fullName": " Amber Michelle Long ",
        "guardian": {},
        "vocation": [],
        "Ethnicity": "Not Hispanic or Latino",
        "Firstname": "Amber",
        "aliasname": "    ",
        "emergency": [],
        "personRole": [
          {
            "hidden": false,
            "rolekey": "CPSS",
            "isprimary": "true",
            "description": "CPS Hist. Clrnc. - Subject",
            "relationshiptorakey": ""
          }
        ],
        "substances": [],
        "addressinfo": [
          {
            "city": "Huntingtown",
            "state": "MD",
            "county": "b0ca6422-8241-4d86-bfef-51c7225de2fc",
            "danger": null,
            "address": "19 Robshire Manor Rd",
            "country": "USA",
            "mergeid": null,
            "zipcode": "20639",
            "address2": "",
            "adrboxno": null,
            "activeflag": 1,
            "directions": null,
            "streetname": null,
            "addresstype": "Home",
            "county_desc": "Calvert",
            "durationday": null,
            "changereason": null,
            "dangerreason": null,
            "addressstatus": null,
            "acknowledgement": null,
            "personaddressid": "00af2b4a-3ce8-4fc5-8412-ca3eb72dc7e0",
            "addressstartdate": "2023-06-16T00:00:00",
            "incidentlocation": null,
            "personadrenddate": null,
            "formattedcityname": null,
            "ishouseholdmember": true,
            "personadrstartdate": null,
            "acknowledgementflag": null,
            "currentlocationflag": 1,
            "formattedstreetname": null,
            "incidentlocationflag": null,
            "personaddresstypekey": "HO",
            "adrstreetsuffixtypekey": null,
            "personaddresssubtypekey": null
          }
        ],
        "fullAddress": "19 Robshire Manor Rd",
        "ishousehold": "yes",
        "personpayee": [],
        "phoneNumber": [],
        "contactsmail": [],
        "emaildetails": [
          {
            "email": "thestruggleisreal.forgiven@gmail.com",
            "old_id": null,
            "enddate": null,
            "personid": "5407c7ae-90f5-4b74-961c-c3a24b119f92",
            "startdate": "2023-06-16T04:00:00",
            "timestamp": null,
            "updatedby": "5b6f8fab-f495-494a-ada8-675474160b17",
            "updatedon": "2023-06-16T14:33:37.009809",
            "activeflag": 1,
            "etl_userid": null,
            "insertedby": "5b6f8fab-f495-494a-ada8-675474160b17",
            "insertedon": "2023-06-16T14:33:37.009809",
            "commentsemail": null,
            "effectivedate": "2023-06-16T14:33:37.009809",
            "etl_load_date": null,
            "personemailid": "0a713325-5930-4faa-9117-ad2f2982c03e",
            "expirationdate": null,
            "personemailtypekey": "P"
          }
        ],
        "phonedetails": [
          {
            "enddate": null,
            "ismobile": null,
            "startdate": "2023-06-16T04:00:00",
            "phonenumber": "3152564161",
            "phoneextension": null,
            "personphonetype": "Home",
            "personphonetypekey": "HM",
            "reversephonenumber": null,
            "personphonenumberid": "69e08c17-905e-48a7-a0b6-5d60f7864338"
          }
        ],
        "Dangerousself": "no",
        "Mentealimpair": "no",
        "maritalstatus": "Married Couple",
        "personsupport": [],
        "physicianinfo": [],
        "Mentealillness": "no",
        "accomplishment": [],
        "Dangerousworker": "no",
        "healthinsurance": [],
        "primarylanguage": "ENG",
        "RelationshiptoRA": "SELF",
        "persondentalinfo": [],
        "personhealthexam": [],
        "isheadofhousehold": true,
        "ishouseholdmember": 1,
        "safehavenbabyflag": 1,
        "citizenalenageflag": "1",
        "personAddressInput": [
          {
            "city": "Linthicum",
            "state": "MD",
            "county": "Anne Arundel",
            "endDate": "04/29/2019",
            "phoneNo": "",
            "zipcode": "21090",
            "Address2": "",
            "address1": "849 Internation",
            "addressid": "",
            "startDate": "",
            "activeflag": 1,
            "addresstype": "31",
            "addresstypeLabel": "Home",
            "knownDangerAddress": "",
            "knownDangerAddressReason": ""
          }
        ],
        "personabusehistory": [],
        "personabusesubstance": [],
        "drugexposednewbornflag": 0,
        "personbehavioralhealth": [],
        "personmedicalcondition": [],
        "sexoffenderregisteredflag": 0,
        "fetalalcoholspctrmdisordflag": 0,
        "personmedicationphyscotropic": [],
        "probationsearchconductedflag": 0
      }
    ]
  },
  "officelocation": "Calvert",
  "securityuserid": "1f8d6145-9ad9-4a35-8e9d-5ed6943fd834",
  "CrossReferences": [],
  "evaluationFields": null,
  "intakeDATypeDetails": [
    {
      "caseID": "",
      "DAStatus": "Closed",
      "DaTypeKey": "d207bdd4-f281-4ec8-949c-8fd9657227f9",
      "intakeAction": "",
      "issubtypekey": true,
      "DADisposition": "Closed",
      "serviceTypeID": "",
      "dispositioncode": "Closed",
      "ServiceRequestNumber": "I261014145700",
      "intakeserreqstatustypekey": "Closed",
      "supMultipleDispositionDropdown": [],
      "intakeMultipleDispositionDropdown": []
    }
  ],
  "focuspersoncasedetails": []
}', updatedby='CJAMS-69658', updatedon=now()
where intakenumber='I261014145700' and activeflag=1;

update intakesnapshot
set jsondata='{
  "sdm": {
    "isar": false,
    "isir": false,
    "isroh": true,
    "worker": "",
    "comments": "",
    "countyid": null,
    "isschool": false,
    "objectid": "I261014145700",
    "provider": [],
    "screenIn": {},
    "immediate": "",
    "screenOut": {
      "duplicatereportflag": 0
    },
    "objecttype": "Intake",
    "referralid": "",
    "reportdate": null,
    "riskofHarm": {
      "isnegrh_exposednewborn": false
    },
    "supervisor": "",
    "workerdate": null,
    "badgenumber": "",
    "referraldob": "2026-08-04T19:02:19.628Z",
    "sexualAbuse": {},
    "maltreatment": "no",
    "recordnumber": "",
    "referralname": "",
    "allegedvictim": [],
    "childfatality": "no",
    "immediateList": {},
    "isreportmeets": false,
    "issexualabuse": false,
    "physicalAbuse": {
      "ismalpa_labortrafficking": false
    },
    "providerKnown": null,
    "generalNeglect": {},
    "ismaltreatment": false,
    "linkschidresid": null,
    "supervisordate": null,
    "childsresidence": false,
    "cpsResponseType": null,
    "ischildfatality": false,
    "isfinalscreenin": false,
    "noImmediateList": {},
    "officerlastname": "",
    "providerdetails": "",
    "unattendedChild": {},
    "arGeneralNeglect": {},
    "isdeathorserious": false,
    "officerfirstname": "",
    "allegedmaltreator": [],
    "childUnderOneYear": "",
    "childunderoneyear": "",
    "islicenseddaycare": false,
    "isoverriderequest": false,
    "officermiddlename": "",
    "selecttrafficking": null,
    "confirmtrafficking": "NO",
    "islabortrafficking": false,
    "isprivateplacement": false,
    "issignordiagonises": false,
    "screeningRecommend": false,
    "traffickingupdated": true,
    "duplicatereportflag": 0,
    "maltreatmentupdated": false,
    "scnRecommendOveride": "",
    "childfatalityupdated": "yes",
    "disqualifyingFactors": {},
    "isfcplacementsetting": false,
    "disqualifyingCriteria": {
      "isreportmeets": false,
      "issexualabuse": false,
      "isdeathorserious": false,
      "islabortrafficking": false,
      "issignordiagonises": false
    },
    "isfclivingarrangement": false,
    "providerunknowndetail": null,
    "isnegrh_exposednewborn": false,
    "isseriousphysicalinjury": null,
    "selectedproviderdetails": null,
    "ismalpa_labortrafficking": false,
    "isnegfp_cargiverintervene": false,
    "isnegmn_unreasonabledelay": false,
    "ismenab_psycologicalability": false,
    "ismenng_psycologicalability": false
  },
  "DAType": {
    "DATypeDetail": [
      {
        "caseID": "",
        "DAStatus": "Closed",
        "DaTypeKey": "d207bdd4-f281-4ec8-949c-8fd9657227f9",
        "intakeAction": "",
        "issubtypekey": true,
        "DADisposition": "Closed",
        "serviceTypeID": "",
        "dispositioncode": "Closed",
        "ServiceRequestNumber": "I261014145700",
        "intakeserreqstatustypekey": "Closed",
        "supMultipleDispositionDropdown": [],
        "intakeMultipleDispositionDropdown": []
      }
    ]
  },
  "roacps": null,
  "General": {
    "Time": "2026-08-04T19:03:11.954Z",
    "Iscps": null,
    "Agency": "CW",
    "Author": "JessicaMilstead",
    "Source": "0bdda2ab-b74f-4d74-ba17-3b9b37a9ca19",
    "Purpose": "d207bdd4-f281-4ec8-949c-8fd9657227f9",
    "Lastname": "Lawson",
    "countyid": "b0ca6422-8241-4d86-bfef-51c7225de2fc",
    "Firstname": "Anna",
    "Narrative": "<p>Calvert&nbsp;County&nbsp;DSS&nbsp;has&nbsp;requested&nbsp;that&nbsp;a&nbsp;CPS&nbsp;background&nbsp;clearance&nbsp;check&nbsp;be&nbsp;completed&nbsp;on&nbsp;Amber&nbsp;Long&nbsp;for&nbsp;the&nbsp;purposes&nbsp;of&nbsp;adoption&nbsp;and&nbsp;foster&nbsp;care.&nbsp;CJAMS&nbsp;has&nbsp;been&nbsp;checked.&nbsp;Subject&nbsp;is&nbsp;cleared.&nbsp;No&nbsp;further&nbsp;information&nbsp;to&nbsp;report.&nbsp;</p>",
    "AgencyCode": "CW",
    "Middlename": "",
    "CreatedDate": "2026-08-04T18:59:21.530Z",
    "InputSource": "0bdda2ab-b74f-4d74-ba17-3b9b37a9ca19",
    "PurposeName": "Request for services",
    "RecivedDate": "08/04/2026 02:59:21 PM",
    "IntakeNumber": "I261014145700",
    "intakeservice": [
      {
        "description": "CPS History Clearance",
        "intakeservid": "98bda8ba-a7f9-4dc0-9415-52098a74cff6",
        "intakeservsubtype": [],
        "intakeservtypekey": "CPSHC"
      }
    ],
    "isDisposition": true,
    "receiveddelay": "N/A",
    "requestercity": "Prince Frederick",
    "islocalreferal": 0,
    "requesterstate": "MD",
    "HeadofHousehold": " Amber Michelle Long ",
    "offenselocation": "20678",
    "queAdditionDate": "2026-08-04T19:02:13.518Z",
    "requestercounty": "b0ca6422-8241-4d86-bfef-51c7225de2fc",
    "submissiondelay": "N/A",
    "RefuseToShareZip": false,
    "IsUnknownReporter": false,
    "addendumNarrative": null,
    "requesteraddress1": "200 Duke St",
    "IsAnonymousReporter": false,
    "cpsHistoryClearance": "<p>N/A</p>",
    "requestercountyname": "Calvert",
    "narrativeUpdatedDate": "2026-08-04T19:01:14.384Z",
    "isacknowledgementletter": 1,
    "communicationDescription": "Phone",
    "isaddendumnarrativeupdated": false
  },
  "clwStatus": null,
  "narrative": [
    {
      "Role": "SSP",
      "email": "calvert.resourcehomes@maryland.gov",
      "title": "",
      "ZipCode": "",
      "Lastname": "Lawson",
      "RoleName": "Social Services personnel",
      "Firstname": "Anna",
      "Middlename": "",
      "PhoneNumber": "4435506900",
      "incidentdate": "",
      "organization": "Calvert County DSS",
      "isapproximate": false,
      "requestercity": "Prince Frederick",
      "PhoneNumberExt": "",
      "requesterstate": "MD",
      "offenselocation": "20678",
      "requestercounty": "b0ca6422-8241-4d86-bfef-51c7225de2fc",
      "incidentlocation": "",
      "requesteraddress1": "200 Duke St",
      "requesteraddress2": "",
      "requestercountyname": "Calvert"
    }
  ],
  "Allegations": [],
  "disposition": [
    {
      "caseID": "",
      "DAStatus": "Closed",
      "DaTypeKey": "d207bdd4-f281-4ec8-949c-8fd9657227f9",
      "intakeAction": "",
      "issubtypekey": true,
      "DADisposition": "Closed",
      "serviceTypeID": "",
      "dispositioncode": "Closed",
      "ServiceRequestNumber": "I261014145700",
      "intakeserreqstatustypekey": "Closed",
      "supMultipleDispositionDropdown": [],
      "intakeMultipleDispositionDropdown": []
    }
  ],
  "clearhistory": {
    "close": null,
    "reason": "ADPP",
    "comments": null,
    "individual": null,
    "thirdparty": null,
    "workername": "JessicaMilstead",
    "startdatetime": null
  },
  "createdCases": null,
  "reviewstatus": {
    "appevent": "INTR",
    "commenttext": "",
    "isclosecase": true,
    "isfromintake": true,
    "ispreintakeapproved": false,
    "youthstatuseventcode": ""
  },
  "persondetails": {
    "Person": [
      {
        "Dob": "1985-01-23T05:00:00.000Z",
        "Pid": "5407c7ae-90f5-4b74-961c-c3a24b119f92",
        "Zip": "20639",
        "ssn": "108785163",
        "City": "Huntingtown",
        "Role": "CPSS",
        "race": [
          {
            "value_text": "White",
            "racetypekey": "WH"
          }
        ],
        "State": "MD",
        "email": "thestruggleisreal.forgiven@gmail.com",
        "County": "Anne Arundel",
        "Gender": "F",
        "county": "b0ca6422-8241-4d86-bfef-51c7225de2fc",
        "school": [],
        "Address": "19 Robshire Manor Rd",
        "address": [
          {
            "city": "Linthicum",
            "state": "MD",
            "county": "Anne Arundel",
            "endDate": "04/29/2019",
            "phoneNo": "",
            "zipcode": "21090",
            "Address2": "",
            "address1": "849 Internation",
            "addressid": "",
            "startDate": "",
            "activeflag": 1,
            "addresstype": "31",
            "addresstypeLabel": "Home",
            "knownDangerAddress": "",
            "knownDangerAddressReason": ""
          }
        ],
        "emailID": [],
        "testing": [],
        "Lastname": "Long",
        "cjamspid": "201280588",
        "contacts": [],
        "employer": [],
        "fullName": " Amber Michelle Long ",
        "guardian": {},
        "vocation": [],
        "Ethnicity": "Not Hispanic or Latino",
        "Firstname": "Amber",
        "aliasname": "    ",
        "emergency": [],
        "personRole": [
          {
            "hidden": false,
            "rolekey": "CPSS",
            "isprimary": "true",
            "description": "CPS Hist. Clrnc. - Subject",
            "relationshiptorakey": ""
          }
        ],
        "substances": [],
        "addressinfo": [
          {
            "city": "Huntingtown",
            "state": "MD",
            "county": "b0ca6422-8241-4d86-bfef-51c7225de2fc",
            "danger": null,
            "address": "19 Robshire Manor Rd",
            "country": "USA",
            "mergeid": null,
            "zipcode": "20639",
            "address2": "",
            "adrboxno": null,
            "activeflag": 1,
            "directions": null,
            "streetname": null,
            "addresstype": "Home",
            "county_desc": "Calvert",
            "durationday": null,
            "changereason": null,
            "dangerreason": null,
            "addressstatus": null,
            "acknowledgement": null,
            "personaddressid": "00af2b4a-3ce8-4fc5-8412-ca3eb72dc7e0",
            "addressstartdate": "2023-06-16T00:00:00",
            "incidentlocation": null,
            "personadrenddate": null,
            "formattedcityname": null,
            "ishouseholdmember": true,
            "personadrstartdate": null,
            "acknowledgementflag": null,
            "currentlocationflag": 1,
            "formattedstreetname": null,
            "incidentlocationflag": null,
            "personaddresstypekey": "HO",
            "adrstreetsuffixtypekey": null,
            "personaddresssubtypekey": null
          }
        ],
        "fullAddress": "19 Robshire Manor Rd",
        "ishousehold": "yes",
        "personpayee": [],
        "phoneNumber": [],
        "contactsmail": [],
        "emaildetails": [
          {
            "email": "thestruggleisreal.forgiven@gmail.com",
            "old_id": null,
            "enddate": null,
            "personid": "5407c7ae-90f5-4b74-961c-c3a24b119f92",
            "startdate": "2023-06-16T04:00:00",
            "timestamp": null,
            "updatedby": "5b6f8fab-f495-494a-ada8-675474160b17",
            "updatedon": "2023-06-16T14:33:37.009809",
            "activeflag": 1,
            "etl_userid": null,
            "insertedby": "5b6f8fab-f495-494a-ada8-675474160b17",
            "insertedon": "2023-06-16T14:33:37.009809",
            "commentsemail": null,
            "effectivedate": "2023-06-16T14:33:37.009809",
            "etl_load_date": null,
            "personemailid": "0a713325-5930-4faa-9117-ad2f2982c03e",
            "expirationdate": null,
            "personemailtypekey": "P"
          }
        ],
        "phonedetails": [
          {
            "enddate": null,
            "ismobile": null,
            "startdate": "2023-06-16T04:00:00",
            "phonenumber": "3152564161",
            "phoneextension": null,
            "personphonetype": "Home",
            "personphonetypekey": "HM",
            "reversephonenumber": null,
            "personphonenumberid": "69e08c17-905e-48a7-a0b6-5d60f7864338"
          }
        ],
        "Dangerousself": "no",
        "Mentealimpair": "no",
        "maritalstatus": "Married Couple",
        "personsupport": [],
        "physicianinfo": [],
        "Mentealillness": "no",
        "accomplishment": [],
        "Dangerousworker": "no",
        "healthinsurance": [],
        "primarylanguage": "ENG",
        "RelationshiptoRA": "SELF",
        "persondentalinfo": [],
        "personhealthexam": [],
        "isheadofhousehold": true,
        "ishouseholdmember": 1,
        "safehavenbabyflag": 1,
        "citizenalenageflag": "1",
        "personAddressInput": [
          {
            "city": "Linthicum",
            "state": "MD",
            "county": "Anne Arundel",
            "endDate": "04/29/2019",
            "phoneNo": "",
            "zipcode": "21090",
            "Address2": "",
            "address1": "849 Internation",
            "addressid": "",
            "startDate": "",
            "activeflag": 1,
            "addresstype": "31",
            "addresstypeLabel": "Home",
            "knownDangerAddress": "",
            "knownDangerAddressReason": ""
          }
        ],
        "personabusehistory": [],
        "personabusesubstance": [],
        "drugexposednewbornflag": 0,
        "personbehavioralhealth": [],
        "personmedicalcondition": [],
        "sexoffenderregisteredflag": 0,
        "fetalalcoholspctrmdisordflag": 0,
        "personmedicationphyscotropic": [],
        "probationsearchconductedflag": 0
      }
    ]
  },
  "officelocation": "Calvert",
  "securityuserid": "1f8d6145-9ad9-4a35-8e9d-5ed6943fd834",
  "CrossReferences": [],
  "evaluationFields": null,
  "intakeDATypeDetails": [
    {
      "caseID": "",
      "DAStatus": "Closed",
      "DaTypeKey": "d207bdd4-f281-4ec8-949c-8fd9657227f9",
      "intakeAction": "",
      "issubtypekey": true,
      "DADisposition": "Closed",
      "serviceTypeID": "",
      "dispositioncode": "Closed",
      "ServiceRequestNumber": "I261014145700",
      "intakeserreqstatustypekey": "Closed",
      "supMultipleDispositionDropdown": [],
      "intakeMultipleDispositionDropdown": []
    }
  ],
  "focuspersoncasedetails": []
}', updatedby='CJAMS-69658', updatedon=now()
where intakenumber='I261014145700' and activeflag=1;