/*
Issue Description: Please remove the SEN Flag for CJAMS PID#: 204123842
Category/Module: Error
Root cause: Person can only be viewed, not edited in closed intakes
Fix provided: DB query to deactivate Active Substance exposed new born flag
Data/Code fix ticket#: CJAMS-59178
Regression Impacts: N/A
Is Code fix Required?: No
Code fix ticket#: N/A
Reason why no related code fix: User error
Status of the code fix if already submitted and expected prod fix date: data fix done, raising the PR
Backup before update/ delete:Query:
*/

--Updating SEN flag in person
update person
set 
	senstatusflag = null, substanceexposednewbornflag = null, substanceexposednewbornsourceid = null, substanceexposednewbornsourcetypekey = null,
	substanceexposednewborntimetamp = null, substanceclasses = null, updatedby = 'CJAMS-59178', updatedon = now()
where personid = '261793d8-6f67-4d0d-88c9-4f389d84957f' and activeflag = 1;

update intakedastaging
set jsondata = jsonb_set(jsondata, '{General, Narrative}',
	'"<p>Writer received a call from UMD Capital regional health for a request for services for a mother and her newborn who were set to be discharged. The reporter informed the writer that the mother had tested positive for <span style=\"color: rgb(71, 71, 71);\">buprenorphine or street suboxone. Mom, Destiny Pierce (DOB 12/4/94) is the mother of Loyal Pierce (DOB 4/3/25). The reporter stated that mom currently resides at St. Martins House and Barn in Ridgely MD but could not provide a phone number to contact her. The reporter did give the writer moms caseworker with SMHB; Samantha - 410-634-2537 ext. 105. Reporter stated that the hospital had concerns over mom taking her NICU baby back to the shelter and her ability to provide him with safety and stability within the shelter. The  reporter stated that mom also has a five year old son who appears to have significant mental health needs based on the fact that the SMHB staff had submitted a previous intake report for him back in February of this year for changing at the staff members with a knife. Reporter states that the five year old was supposed to be getting an IEP, is currently on ADHD medication and his mom plans on signing him up with child therapy through For All Seasons once she s discharged but she ll need assistance in doing so. Reporter also informed the writer that mom had had another child born in 2021 that was killed by their father at 2 months old. This is also the father of her five year old. Father was charged for the babies murder but could not give further details regarding that case. </span></p><p><span style=\"color: rgb(71, 71, 71);\">The reporter stated that mom also has an appointment next week to get set up for Suboxone treatments. </span></p><p><br></p><p>During the call, the reporter had initially stated that the newborn was born substance exposed to fentanyl but called the writer back to clarify that they had only been exposed to fentanyl due to the epidural that mom was administered. Mom had not tested positive for fentanyl, only <span style=\"color: rgb(71, 71, 71);\">buprenorphine.No SEN notification or medical documentation received from the hospital for newborn.</span></p><p><br></p><p><span style=\"color: rgb(71, 71, 71);\">After running clearances, the writer realized that the paternal grandfather was charged with second degree murder, not her child s father. </span></p>"'
		),
	updatedby = 'CJAMS-59178', updatedon = now()
where intakenumber = 'I251013268507' and activeflag = 1;



update intakedastatus
set jsondata = jsonb_set(jsondata, '{General, Narrative}',
	'"<p>Writer received a call from UMD Capital regional health for a request for services for a mother and her newborn who were set to be discharged. The reporter informed the writer that the mother had tested positive for <span style=\"color: rgb(71, 71, 71);\">buprenorphine or street suboxone. Mom, Destiny Pierce (DOB 12/4/94) is the mother of Loyal Pierce (DOB 4/3/25). The reporter stated that mom currently resides at St. Martins House and Barn in Ridgely MD but could not provide a phone number to contact her. The reporter did give the writer moms caseworker with SMHB; Samantha - 410-634-2537 ext. 105. Reporter stated that the hospital had concerns over mom taking her NICU baby back to the shelter and her ability to provide him with safety and stability within the shelter. The  reporter stated that mom also has a five year old son who appears to have significant mental health needs based on the fact that the SMHB staff had submitted a previous intake report for him back in February of this year for changing at the staff members with a knife. Reporter states that the five year old was supposed to be getting an IEP, is currently on ADHD medication and his mom plans on signing him up with child therapy through For All Seasons once she s discharged but she ll need assistance in doing so. Reporter also informed the writer that mom had had another child born in 2021 that was killed by their father at 2 months old. This is also the father of her five year old. Father was charged for the babies murder but could not give further details regarding that case. </span></p><p><span style=\"color: rgb(71, 71, 71);\">The reporter stated that mom also has an appointment next week to get set up for Suboxone treatments. </span></p><p><br></p><p>During the call, the reporter had initially stated that the newborn was born substance exposed to fentanyl but called the writer back to clarify that they had only been exposed to fentanyl due to the epidural that mom was administered. Mom had not tested positive for fentanyl, only <span style=\"color: rgb(71, 71, 71);\">buprenorphine.No SEN notification or medical documentation received from the hospital for newborn.</span></p><p><br></p><p><span style=\"color: rgb(71, 71, 71);\">After running clearances, the writer realized that the paternal grandfather was charged with second degree murder, not her child s father. </span></p>"'
		),
	updatedby = 'CJAMS-59178', updatedon = now()
where intakedastatusid = '0d7bc7ab-e2b9-4aa0-8933-b8adecc0d680'  and activeflag = 1;


update intakesnapshot
set jsondata = jsonb_set(jsondata, '{General, Narrative}',
	'"<p>Writer received a call from UMD Capital regional health for a request for services for a mother and her newborn who were set to be discharged. The reporter informed the writer that the mother had tested positive for <span style=\"color: rgb(71, 71, 71);\">buprenorphine or street suboxone. Mom, Destiny Pierce (DOB 12/4/94) is the mother of Loyal Pierce (DOB 4/3/25). The reporter stated that mom currently resides at St. Martins House and Barn in Ridgely MD but could not provide a phone number to contact her. The reporter did give the writer moms caseworker with SMHB; Samantha - 410-634-2537 ext. 105. Reporter stated that the hospital had concerns over mom taking her NICU baby back to the shelter and her ability to provide him with safety and stability within the shelter. The  reporter stated that mom also has a five year old son who appears to have significant mental health needs based on the fact that the SMHB staff had submitted a previous intake report for him back in February of this year for changing at the staff members with a knife. Reporter states that the five year old was supposed to be getting an IEP, is currently on ADHD medication and his mom plans on signing him up with child therapy through For All Seasons once she s discharged but she ll need assistance in doing so. Reporter also informed the writer that mom had had another child born in 2021 that was killed by their father at 2 months old. This is also the father of her five year old. Father was charged for the babies murder but could not give further details regarding that case. </span></p><p><span style=\"color: rgb(71, 71, 71);\">The reporter stated that mom also has an appointment next week to get set up for Suboxone treatments. </span></p><p><br></p><p>During the call, the reporter had initially stated that the newborn was born substance exposed to fentanyl but called the writer back to clarify that they had only been exposed to fentanyl due to the epidural that mom was administered. Mom had not tested positive for fentanyl, only <span style=\"color: rgb(71, 71, 71);\">buprenorphine.No SEN notification or medical documentation received from the hospital for newborn.</span></p><p><br></p><p><span style=\"color: rgb(71, 71, 71);\">After running clearances, the writer realized that the paternal grandfather was charged with second degree murder, not her child s father. </span></p>"'
		),
	updatedby = 'CJAMS-59178', updatedon = now()
where intakesnapshotid = 'a23e22f2-e0ab-4973-bb76-880131b43f0f' and activeflag = 1;


update intakeservicerequest
set narrative  = (
	'<p>Writer received a call from UMD Capital regional health for a request for services for a mother and her newborn who were set to be discharged. The reporter informed the writer that the mother had tested positive for <span style=\"color: rgb(71, 71, 71);\">buprenorphine or street suboxone. Mom, Destiny Pierce (DOB 12/4/94) is the mother of Loyal Pierce (DOB 4/3/25). The reporter stated that mom currently resides at St. Martins House and Barn in Ridgely MD but could not provide a phone number to contact her. The reporter did give the writer moms caseworker with SMHB; Samantha - 410-634-2537 ext. 105. Reporter stated that the hospital had concerns over mom taking her NICU baby back to the shelter and her ability to provide him with safety and stability within the shelter. The  reporter stated that mom also has a five year old son who appears to have significant mental health needs based on the fact that the SMHB staff had submitted a previous intake report for him back in February of this year for changing at the staff members with a knife. Reporter states that the five year old was supposed to be getting an IEP, is currently on ADHD medication and his mom plans on signing him up with child therapy through For All Seasons once she s discharged but she ll need assistance in doing so. Reporter also informed the writer that mom had had another child born in 2021 that was killed by their father at 2 months old. This is also the father of her five year old. Father was charged for the babies murder but could not give further details regarding that case. </span></p><p><span style=\"color: rgb(71, 71, 71);\">The reporter stated that mom also has an appointment next week to get set up for Suboxone treatments. </span></p><p><br></p><p>During the call, the reporter had initially stated that the newborn was born substance exposed to fentanyl but called the writer back to clarify that they had only been exposed to fentanyl due to the epidural that mom was administered. Mom had not tested positive for fentanyl, only <span style=\"color: rgb(71, 71, 71);\">buprenorphine.No SEN notification or medical documentation received from the hospital for newborn.</span></p><p><br></p><p><span style=\"color: rgb(71, 71, 71);\">After running clearances, the writer realized that the paternal grandfather was charged with second degree murder, not her child s father. </span></p>'
		),
	updatedby = 'CJAMS-59178', updatedon = now()
where intakeserviceid  = 'ad69f538-f347-4793-84be-fa9383ce0eea';