-- CDM-21167 - OVERPAYMENT ISSUE
/*
-- Issue Description: 
	Account Receivable did not generated by the finance batch after the Placement exit on 2/22/2022.
   
-- Case ID: 3236684
-- Client ID: 3637750 (JADEN C CAMPBELL) - 3475551f-91fd-4fcc-901b-e2d50d7b29b6
-- Placement ID: 339884 - 2020-03-13 To	2021-12-22 - 7a089c61-384b-4b9a-bf0c-99c2d76bae1a
-- Private Organization: 5000668 (The Children's Choice Of Maryland, Inc.)
-- CPA Office: 5000674 (Children's Choice Baltimore) 
-- Program: 222	(Treatment Foster Care)

-- Category/ Module: Account Receivable (Finance Management) 
-- Root cause: Exit date update did not happen in the Placement Validation table (TDB) 
-- Pull request# N/A
-- Reason why no related code fix: N/A
-- Status of the code fix if already submitted and expected prod fix date: TBD
*/

-- Data fix to update exit date in the Placement Validation table (this will trigger the Under Over batch) 
select placement_id, placement_entry_dt, placement_exit_dt, validation_start_dt, validation_end_dt, 
	validation_status_cd, update_ts, update_user_id, delete_sw 
from cjams.tb_placement_validation 
where placement_id = 339884
	and delete_sw = 'N' ;

Update cjams.tb_placement_validation 
set -- placement_entry_dt = '2020-03-13'::date,
	placement_exit_dt = '2021-12-22'::date,
	update_ts = now(),
	update_user_id = 'CDM-21167'
where placement_id = 339884 
	and delete_sw = 'N';
