-- CDM-18915 - FM145R/overpayment
/*
-- Issue Description: 
	Account Receivable did not generated by the finance batch on Placement exit
   
-- Case ID: 3227216
-- Client ID: 3553092 (ELIJAH AIDEN	FRANKLIN) - bf82cb25-61ac-406a-9fd8-e6deab1bbf61
-- Placement ID: 325772 - 2018-03-17 To	2021-09-03 - 106b51c4-a9e2-4e54-9739-151ca5d4f3b8
-- Provider ID: 5059437	(Billie J Simmons) - Local Department Home

-- Category/ Module: Account Receivable (Finance Management) 
-- Root cause: Unknown at this time (TBD)
-- Pull request# N/A
-- Reason why no related code fix: N/A
-- Status of the code fix if already submitted and expected prod fix date: N/A
*/

-- Data fix to trigger Under Over batch 
select placement_id, placement_entry_dt, placement_exit_dt,  validation_start_dt, validation_end_dt,
	validation_status_cd, update_ts, update_user_id 
from tb_placement_validation 
where placement_validation_id = 1974767
	and delete_sw = 'N' ;

update tb_placement_validation
set validation_status_cd = '1750',
	update_ts = now(),
	update_user_id = 'CDM-18915'
where placement_validation_id = 1974767
	and delete_sw = 'N' ;
	