-- CIDM-6256 - Missing ARs (Overpayments for EFC placements)
/*
-- Issue Description: 
	Account Receivable did not generated by the finance batch for some EFC Placements
   
-- Category/ Module: Account Receivable (Finance Management) 
-- Root cause: Under Over batch was having a flaw in calculations for Emergency Foster Home Care
--			   and the code fix was promoted to prod as a part of CDM-27142 on 12/06/2022.
-- Fix Provided: Datafix to trigger the under/over batch and recalculate the payments for these EFC placements.
--				 So, that system will generate the ARs accordingly. 
-- Pull request# N/A
-- Reason why no related code fix: N/A
-- Status of the code fix if already submitted and expected prod fix date: N/A
*/

-- Data fix to trigger Under Over batch 
select placement_id, placement_entry_dt, placement_exit_dt,  validation_start_dt, validation_end_dt,
	validation_status_cd, update_ts, update_user_id 
from tb_placement_validation 
where placement_id 
		in (	1575956, 1575955, 1583445, 1575130, 1575179, 1574747, 1575046, 1575172, 1574729, 1574658,
				1575134, 1575254, 1575255, 1574326, 1576140, 1574126, 1574125, 1574145, 1573780, 1573781,
				1573885, 1573393, 1571809, 1572468, 1571873, 1571760, 1566975, 1566423, 1566421, 1565527,
				1565619, 1563958, 1561711, 1557262
			)
	and delete_sw = 'N' ;
	
update tb_placement_validation
set validation_status_cd = '1750',
	update_ts = now()
	-- update_user_id = 'CIDM-6256' - Do not update to retain the audit history 
where placement_id 
		in (	1575956, 1575955, 1583445, 1575130, 1575179, 1574747, 1575046, 1575172, 1574729, 1574658,
				1575134, 1575254, 1575255, 1574326, 1576140, 1574126, 1574125, 1574145, 1573780, 1573781,
				1573885, 1573393, 1571809, 1572468, 1571873, 1571760, 1566975, 1566423, 1566421, 1565527,
				1565619, 1563958, 1561711, 1557262
			)
	and delete_sw = 'N' ;


