-- CDM-12634 - Provider J. J. Serrells 5092437
/*
-- Issue Description: 
	Account Receivable did not generated by the finance batch on Placement exit
   
	Client ID: 4066990 (MILES CATHEY) - 101d571a-8103-452e-b375-b0f69f6e17f9
	Provider ID: 5092437 - Joanne Marie Serrels 
    Placement ID: 333065 - 2019-02-12 to 2021-02-17 - ddd3d161-6fe5-4627-94d8-3e3768f9f47d
	
-- Category/ Module: Account Receivable (Finance Management) 
-- Root cause: unknown (exception  scenario)
-- Pull request# N/A
-- Reason why no related code fix: N/A
-- Status of the code fix if already submitted and expected prod fix date: N/A
*/

-- Data fix to trigger Under Over batch 
select placement_id, placement_entry_dt, placement_exit_dt,  validation_start_dt, validation_end_dt,
	validation_status_cd, update_ts, update_user_id 
from tb_placement_validation 
where placement_validation_id = 1950550
	and delete_sw = 'N' ;

update tb_placement_validation
set validation_status_cd = '1750',
	update_ts = now(),
	update_user_id = 'CDM-12634'
where placement_validation_id = 1950550
	and delete_sw = 'N' ;
		
