-- CDM-18914 - FM145/overpayment
/*
-- Issue Description: 
	Account Receivable did not generated by the finance batch on Placement exit
   
-- Case ID: 3227216
-- Client ID: 3553097 (MEYA	FRANKLIN) - 4cfaabc3-2d6d-4e9e-8f51-68b512763d34
-- Placement ID: 323799 - 2017-12-30 To 2021-09-03 - 5aeaf02d-b1c0-40e7-aea3-00eb85673c45
-- Provider ID: 5059437	(Billie J Simmons) - Local Department Home

-- Category/ Module: Account Receivable (Finance Management) 
-- Root cause: Fail-safe code fix has been promoted as a part of CDM-18915
-- Pull request# N/A
-- Reason why no related code fix: N/A
-- Status of the code fix if already submitted and expected prod fix date: Next Prod Deployment
*/

-- Data fix to trigger Under Over batch 
select placement_id, placement_entry_dt, placement_exit_dt,  validation_start_dt, validation_end_dt,
	validation_status_cd, update_ts, update_user_id 
from tb_placement_validation 
where placement_validation_id = 1974731
	and delete_sw = 'N' ;

update tb_placement_validation
set validation_status_cd = '1750',
	update_ts = now(),
	update_user_id = 'CDM-18914'
where placement_validation_id = 1974731
	and delete_sw = 'N' ;
