-- CDM-14119 - AR not generated for Provider
/*
-- Issue Description: 
	Account Receivables did not generated by the finance batch for 2 Placement on exit
   
-- Provider ID: 5076191	(Kimberlee  Mitchell) - Local Department Home
-- Case ID: 3272213 
-- Client ID: 4020286 (JEFFERSON FLORES) - a7f840ae-cd59-400b-ba9c-587b0a37d91e
-- Placement ID: 323932 - 2018-01-16 To	2021-04-26 - 0ff3538a-2dbf-42d7-a044-bfe55798dc9e

-- Client ID: 4028106 (SCARLETT	Y FLORES-LEONES) - e29b02b6-9b69-4663-9186-4559d693062b
-- Placement ID: 323934 - 2018-01-16 To 2021-04-26 - 3a73310e-44a2-4477-a39a-28087d6d47f1	
	
-- Category/ Module: Account Receivable (Finance Management) 
-- Root cause: Unknown (exception scenario)
-- Pull request# N/A
-- Reason why no related code fix: N/A
-- Status of the code fix if already submitted and expected prod fix date: TBD
*/

-- Data fix to trigger Under Over batch 
select placement_id, placement_entry_dt, placement_exit_dt,  validation_start_dt, validation_end_dt,
	validation_status_cd, update_ts, update_user_id 
from tb_placement_validation 
where placement_validation_id in ( 1957048, 1957049 ) 
	and delete_sw = 'N' ;

update tb_placement_validation
set validation_status_cd = '1750',
	update_ts = now(),
	update_user_id = 'CDM-14119'
where placement_validation_id in ( 1957048, 1957049 ) 
	and delete_sw = 'N' ;