-- CDM-27224 - Missing overpayment
/*
-- Issue Description: 
	Account Receivable did not generated by the finance batch on Placement exit
   
-- Case ID: 221030015205
-- Client ID: 200891499 (Wynter Huston) - 6acd0f83-74f9-4100-a9a1-e0b99479a554
-- Placement ID: 1574326 - 2022-08-18 To 2022-09-17 - f89ef29e-cc57-4509-bec7-4de2fb1cbd94
-- Provider ID: 6005563 (Lauren  Ashley Pittack)
-- Emergency Foster Home Care

-- Category/ Module: Account Receivable (Finance Management) 
-- Root cause: Under Over batch was having a flaw in calculations for Emergency Foster Home Care
--			   and the code fix was promoted to prod as a part of CDM-27142 on 12/06/2022.
-- Pull request# N/A
-- Reason why no related code fix: N/A
-- Status of the code fix if already submitted and expected prod fix date: N/A
*/

-- Data fix to trigger Under Over batch 
select placement_id, placement_entry_dt, placement_exit_dt,  validation_start_dt, validation_end_dt,
	validation_status_cd, update_ts, update_user_id 
from tb_placement_validation 
where placement_validation_id = 2018619
	and delete_sw = 'N' ;
	
update tb_placement_validation
set validation_status_cd = '1750',
	update_ts = now(),
	update_user_id = 'CDM-27224'
where placement_validation_id = 2018619
	and delete_sw = 'N' ;

