-- CDM-19153 - No Overpayment Generated
/*
-- Issue Description: 
	Account Receivable did not generated by the finance batch after the Placement exit
   
-- Case ID: 3227216
-- Client ID: 3723701 (MADDOX ISAIAH FRANKLIN) - 2094228d-a3a1-4854-9b48-2dbdce4860b3
-- PLacement ID: 324644 - 2018-02-09 To 2021-09-03 - d1d9827e-807f-42ec-8fd8-1dbbe8670d25
-- Private Organization: 5000364 (The ARC Northern Chesapeake Region, Incorporated)
-- CPA Office: 5000365 (ARC Northern Chesapeake Aberdeen)
-- Program: 2003 (TFC - ARC Northern Chesapeake Aberdeen) - 2006-12-19 To 2022-06-30

-- Category/ Module: Account Receivable (Finance Management) 
-- Root cause: Fail-safe code fix has been promoted as a part of CDM-18915
-- Pull request# N/A
-- Reason why no related code fix: N/A
-- Status of the code fix if already submitted and expected prod fix date: Next Prod Deployment
*/

-- Data fix to trigger Under Over batch 
select placement_id, placement_entry_dt, placement_exit_dt,  validation_start_dt, validation_end_dt,
	validation_status_cd, update_ts, update_user_id 
from tb_placement_validation 
where placement_validation_id = 1974745
	and delete_sw = 'N' ;

update tb_placement_validation
set validation_status_cd = '1750',
	update_ts = now(),
	update_user_id = 'CDM-19153'
where placement_validation_id = 1974745
	and delete_sw = 'N' ;
