-- CDM-18688 - FM145R/overpayment (S20210326035522)
/*
-- Issue Description: 
	Account Receivable did not generated by the finance batch on Placement exit
   
-- Case ID: 3227216
-- Client ID: 3965972 (CASEIN JEREMIAH FRANKLIN) - 6a4984ae-f796-40b3-9a3d-f2d215f7756c
-- Placement ID: 323800 - 2017-12-05 To 2021-09-03 - b938a91b-ceda-401f-b9ce-3722062de21c
-- Provider ID: 5076047	(Candice Lindsey) - Local Department Home

-- Category/ Module: Account Receivable (Finance Management) 
-- Root cause: Unknown at this time (TBD)
-- Pull request# N/A
-- Reason why no related code fix: N/A
-- Status of the code fix if already submitted and expected prod fix date: N/A
*/

-- Data fix to trigger Under Over batch 
select placement_id, placement_entry_dt, placement_exit_dt,  validation_start_dt, validation_end_dt,
	validation_status_cd, update_ts, update_user_id 
from tb_placement_validation 
where placement_validation_id = 1974732
	and delete_sw = 'N' ;

update tb_placement_validation
set validation_status_cd = '1750',
	update_ts = now(),
	update_user_id = 'CDM-18688'
where placement_validation_id = 1974732
	and delete_sw = 'N' ;