-- CDM-28023 - Placement Validations
/*
-- Issue Description: 
	System Adjustment did not generated by the finance batch for Oct 2022 payment
   
-- Case ID: 3194990
-- Client ID: 3180990 (TYESHA HAMMOND) - 75bfa45f-855f-4d87-8be0-bb08ef237e29
-- Placement ID: 1568411 - 2021-12-01 To 2022-10-30 - 99de688b-233d-42b9-ae3b-82f2acec809f
-- Private Organization: 5001294 (King Edwards' Inc.)
-- CPA Office: 5001424 (King Edwards' Inc. ILP)
-- Program ID: 1274 (Ind Liv Pgm King Edwards House, Inc.)

-- Category/ Module: Account Receivable (Finance Management) 
-- Root cause: TBD - For some reason the finance under/over batch did not picked-up this placement to process the late validated Oct 2022 payment.  
-- Fix Provided: Datafix has been promoted to trigger the CJAMS under Over batch, 
--               which is going to re-calculate the payments for this client's placement and will generate the missing Oct 2022 service payment.
-- Pull request# N/A
-- Reason why no related code fix: N/A
-- Status of the code fix if already submitted and expected prod fix date: N/A
*/

-- Data fix to trigger Under Over batch 
select placement_id, placement_entry_dt, placement_exit_dt,  validation_start_dt, validation_end_dt,
	validation_status_cd, update_ts, update_user_id 
from tb_placement_validation 
where placement_validation_id = 2020880
	and delete_sw = 'N' ;
	
update tb_placement_validation
set validation_status_cd = '1750',
	update_ts = now(),
	update_user_id = 'CDM-28023'
where placement_validation_id = 2020880
	and delete_sw = 'N' ;

