-- CDM-17989 - FC overpayment 
/*
-- Issue Description: 
	Account Receivable did not generated by the finance batch on Placement exit
   
-- Case ID: 3244516
-- Client ID: 3725494 (ANIAH RENEE LONG) - f56f919e-957e-4493-a629-f0d160836c4c
-- Placement ID: 1564345 - 2021-07-02 To 2021-08-01 - 677269f3-0566-41cb-a1bb-444d9393378b
-- Provider ID: 5059437	(Billie J Simmons) - Local Department Home

-- Category/ Module: Account Receivable (Finance Management) 
-- Root cause: unknown (exception scenario)
-- Pull request# N/A
-- Reason why no related code fix: N/A
-- Status of the code fix if already submitted and expected prod fix date: N/A
*/

-- Data fix to trigger Under Over batch 
select placement_id, placement_entry_dt, placement_exit_dt,  validation_start_dt, validation_end_dt,
	validation_status_cd, update_ts, update_user_id 
from tb_placement_validation 
where placement_validation_id = 1973565
	and delete_sw = 'N' ;

update tb_placement_validation
set validation_status_cd = '1750',
	update_ts = now(),
	update_user_id = 'CDM-17989'
where placement_validation_id = 1973565
	and delete_sw = 'N' ;
