-- CDM-17901 - No Accounts Receivable was Generated on CJAMS
/*
-- Issue Description: 
	Account Receivable did not generated by the finance batch on Placement exit
   
-- Case ID: 3257386
-- Client ID: 3777921 (JOSEPH MUGAMBI NJUME) - 1bf06b6b-d1af-4b1f-bf0f-f9384ffcf9f6
-- Provider ID: 5048543 (Bruce Lewis)
-- Placement ID: 1557551 - 2020-09-08 To 2021-09-20 - e226105d-8871-46ad-959e-a2ec941dd045

-- GAP ID: 1005842 - 2021-09-20 To 2029-03-31 - b42d0849-cb50-4be1-9158-1ae5da5fd884
	
-- Category/ Module: Account Receivable (Finance Management) 
-- Root cause: unknown (exception scenario)
-- Pull request# N/A
-- Reason why no related code fix: N/A
-- Status of the code fix if already submitted and expected prod fix date: N/A
*/

-- Data fix to trigger Under Over batch 
select placement_id, placement_entry_dt, placement_exit_dt,  validation_start_dt, validation_end_dt,
	validation_status_cd, update_ts, update_user_id 
from tb_placement_validation 
where placement_validation_id = 1975849
	and delete_sw = 'N' ;

update tb_placement_validation
set validation_status_cd = '1750',
	update_ts = now(),
	update_user_id = 'CDM-17901'
where placement_validation_id = 1975849
	and delete_sw = 'N' ;
