-- CDM-18687 - FM145R/overpayment (S20210326035521)
/*
-- Issue Description: 
	Account Receivable did not generated by the finance batch on Placement exit
   
-- Case ID: 3227216
-- Client ID: 4102839 (SCARLETT	GRACE FRANKLIN) - ec89b565-2871-4126-8ed0-e522179802b6
-- Placement ID: 1563576 - 02/03/2021 To 09/17/2021 - 930674f5-5276-4441-9046-40c1a490e4c6
-- Provider ID: 5091328	(Lauren Christopher) - Local Department Home

-- Category/ Module: Account Receivable (Finance Management) 
-- Root cause: Unknown at this time (TBD)
-- Pull request# N/A
-- Reason why no related code fix: N/A
-- Status of the code fix if already submitted and expected prod fix date: N/A
*/

-- Data fix to trigger Under Over batch 
select placement_id, placement_entry_dt, placement_exit_dt,  validation_start_dt, validation_end_dt,
	validation_status_cd, update_ts, update_user_id 
from tb_placement_validation 
where placement_validation_id = 1976733
	and delete_sw = 'N' ;

update tb_placement_validation
set validation_status_cd = '1750',
	update_ts = now(),
	update_user_id = 'CDM-18687'
where placement_validation_id = 1976733
	and delete_sw = 'N' ;
