-- SEQUENCE: cjams.SQ_INTERFACES_ERROR_LOG

-- DROP SEQUENCE cjams.SQ_INTERFACES_ERROR_LOG;

CREATE SEQUENCE cjams.SQ_INTERFACES_ERROR_LOG;

ALTER SEQUENCE cjams.SQ_INTERFACES_ERROR_LOG
    OWNER TO welfareadmin;