DROP   TYPE cjams.getdsdsactionsummarydtls_type CASCADE;

CREATE TYPE cjams.getdsdsactionsummarydtls_type AS (
	da_number varchar,
	da_typeid uuid,
	da_subtypeid uuid,
	da_type varchar,
	da_subtype varchar,
	da_receiveddate timestamp,
	da_focus varchar,
	da_role varchar,
	da_identifier varchar,
	da_region varchar,
	da_county varchar,
	da_zip varchar,
	da_status varchar,
	da_disposition varchar,
	da_assignedto varchar,
	da_completedby varchar,
	da_investigationid uuid,
	da_duedate timestamp,
	da_daystogo int8,
	da_groupnumber varchar,
	da_loadnumber varchar,
	da_focusprofilephoto text,
	teamtypekey varchar,
	intake_jsondata json,
	da_communication varchar,
	da_insertedon timestamp,
	da_complaintid varchar,
	da_communicationid uuid,
	da_intakeworker varchar,
	persondob timestamp,
	da_unsafe bool,
	da_reportername varchar,
	intakenumber varchar,
	da_responsibilitytypekey varchar(50),
	assistpid varchar(50),
	cjamspid int8,
	isenablekinship int4,
	persondod timestamp,
	personid uuid,
	foldertypekey varchar(50),
	foldertypedescription varchar(250),
	isrestitution bool,
	intakeserviceid uuid,
	countyid uuid,
	programarea json,
	case_opendate timestamp,
	case_closedate timestamp,
	responsibleworkers json,
	servicecasenumber varchar(15),
	teamid uuid,
	servicecaseid uuid,
	caseconnectsent int4,
	narrativeUpdatedDate timestamp
	);


    alter table intakeservicerequest 
add column if not  exists narrativeUpdatedDate timestamp ;