DELETE FROM referencetype WHERE referencetypeid = 902;
INSERT INTO  referencetype (referencetypeid,typedescription,tablename,activeflag,insertedby,insertedon,updatedby,updatedon)
   VALUES(902,'Job Title','Job Title',1,'admin',now(),'admin', now());
   
 DELETE FROM referencevalues WHERE referencetypeid = 902;
 INSERT INTO referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,insertedby,insertedon,updatedby,updatedon,teamtypekey)
     VALUES ('8122',902,'Resource Dev. Program Manager','Resource Dev. Program Manager',1,1,'Admin',now(),'Admin',now(),NULL),
('8123',902,'SSA Executive','SSA Executive',1,2,'Admin',now(),'Admin',now(),NULL),
('8124',902,'Central IV-E Specialist','Central IV-E Specialist',1,3,'Admin',now(),'Admin',now(),NULL),
('3797',902,'SSA Director','SSA Director',1,4,'Admin',now(),'Admin',now(),NULL),
('4132',902,'Adoption Program Manager','Adoption Program Manager',1,5,'Admin',now(),'Admin',now(),NULL),
('4133',902,'Adoption Supervisor','Adoption Supervisor',1,6,'Admin',now(),'Admin',now(),NULL),
('4134',902,'Adoption Worker','Adoption Worker',1,7,'Admin',now(),'Admin',now(),NULL),
('4135',902,'Auditor','Auditor',1,8,'Admin',now(),'Admin',now(),NULL),
('4136',902,'Central ICPC Supervisor','Central ICPC Supervisor',1,9,'Admin',now(),'Admin',now(),NULL),
('4137',902,'In-Home Services Program Manager','In-Home Services Program Manager',1,10,'Admin',now(),'Admin',now(),NULL),
('4138',902,'CPS Supervisor','CPS Supervisor',1,11,'Admin',now(),'Admin',now(),NULL),
('4139',902,'CPS Worker','CPS Worker',1,12,'Admin',now(),'Admin',now(),NULL),
('4140',902,'CPS Program Manager','CPS Program Manager',1,13,'Admin',now(),'Admin',now(),NULL),
('4141',902,'External Reviewer','External Reviewer',1,14,'Admin',now(),'Admin',now(),NULL),
('4142',902,'Family Preservation Prog.Manager','Family Preservation Prog.Manager',1,15,'Admin',now(),'Admin',now(),NULL),
('4143',902,'Family Preservation Supervisor','Family Preservation Supervisor',1,16,'Admin',now(),'Admin',now(),NULL),
('4144',902,'Family Preservation Worker','Family Preservation Worker',1,17,'Admin',now(),'Admin',now(),NULL),
('4146',902,'Central Fiscal Staff','Central Fiscal Staff',1,18,'Admin',now(),'Admin',now(),NULL),
('4147',902,'LDSS Fiscal Supervisor','LDSS Fiscal Supervisor',1,19,'Admin',now(),'Admin',now(),NULL),
('4148',902,'LDSS Aide','LDSS Aide',1,20,'Admin',now(),'Admin',now(),NULL),
('4149',902,'LDSS Asst. Director','LDSS Asst. Director',1,21,'Admin',now(),'Admin',now(),NULL),
('4150',902,'LDSS Director','LDSS Director',1,22,'Admin',now(),'Admin',now(),NULL),
('4151',902,'LDSS IV-E Specialist','LDSS IV-E Specialist',1,23,'Admin',now(),'Admin',now(),NULL),
('4152',902,'LDSS Resource Supervisor','LDSS Resource Supervisor',1,24,'Admin',now(),'Admin',now(),NULL),
('4153',902,'LDSS Resource Worker','LDSS Resource Worker',1,25,'Admin',now(),'Admin',now(),NULL),
('4154',902,'LDSS Unit Secretary','LDSS Unit Secretary',1,26,'Admin',now(),'Admin',now(),NULL),
('4156',902,'Central Licensing Supervisor','Central Licensing Supervisor',1,27,'Admin',now(),'Admin',now(),NULL),
('4157',902,'Out of home Placement Program Manager','Out of Home Placement Program Manager',1,28,'Admin',now(),'Admin',now(),NULL),
('4158',902,'Out of Home Placement Supervisor','Out of Home Placement Supervisor',1,29,'Admin',now(),'Admin',now(),NULL),
('4159',902,'Out of Home placement Worker','Out of Home placement Worker',1,30,'Admin',now(),'Admin',now(),NULL),
('4160',902,'Personnel','Personnel',1,31,'Admin',now(),'Admin',now(),NULL),
('4161',902,'Provider Contract Administrator','Provider Contract Administrator',1,32,'Admin',now(),'Admin',now(),NULL),
('4162',902,'Resource Program Manager','Resource Program Manager',1,33,'Admin',now(),'Admin',now(),NULL),
('4163',902,'Screening Supervisor','Screening Supervisor',1,34,'Admin',now(),'Admin',now(),NULL),
('4164',902,'Screening Worker','Screening Worker',1,35,'Admin',now(),'Admin',now(),NULL),
('4165',902,'LDSS Security Monitor','LDSS Security Monitor',1,36,'Admin',now(),'Admin',now(),NULL),
('4168',902,'System Support User','System Support User',1,37,'Admin',now(),'Admin',now(),NULL),
('7569',902,'Adoption Analyst','Adoption Analyst',1,38,'Admin',now(),'Admin',now(),NULL),
('7570',902,'Administrative Hearing Coordinator','Administrative Hearing Coordinator',1,39,'Admin',now(),'Admin',now(),NULL),
('7597',902,'Screening Manager','Screening Manager',1,40,'Admin',now(),'Admin',now(),NULL),
('7599',902,'Central ICPC Staff','Central ICPC Staff',1,41,'Admin',now(),'Admin',now(),NULL),
('7600',902,'LDSS Fiscal Staff','LDSS Fiscal Staff',1,42,'Admin',now(),'Admin',now(),NULL),
('7602',902,'In-Home Services Worker','In-Home Services Worker',1,43,'Admin',now(),'Admin',now(),NULL),
('7609',902,'In-Home Services Supervisor','In-Home Services Supervisor',1,44,'Admin',now(),'Admin',now(),NULL),
('7611',902,'Central Security Officer','Central Security Officer',1,45,'Admin',now(),'Admin',now(),NULL),
('7613',902,'SSA Policy Analyst','SSA Policy Analyst',1,46,'Admin',now(),'Admin',now(),NULL),
('7614',902,'Project Team','Project Team',1,47,'Admin',now(),'Admin',now(),NULL),
('7615',902,'Level 1 Help Desk','Level 1 Help Desk',1,48,'Admin',now(),'Admin',now(),NULL),
('7616',902,'Independent Living Worker','Independent Living Worker',1,49,'Admin',now(),'Admin',now(),NULL),
('7617',902,'Citizens Review Supervisor','Citizens Review Supervisor',1,50,'Admin',now(),'Admin',now(),NULL),
('7618',902,'Citizens Review Staff','Citizens Review Staff',1,51,'Admin',now(),'Admin',now(),NULL),
('8121',902,'Appeals Coordinator','Appeals Coordinator',1,52,'Admin',now(),'Admin',now(),NULL),
('7604',902,'Central Licensing Coordinator','Central Licensing Coordinator',1,53,'Admin',now(),'Admin',now(),NULL),
('10061',902,'Automated Tester','Automated Tester',1,54,'Admin',now(),'Admin',now(),NULL),
('8125',902,'Central Fiscal Director','Central Fiscal Director',1,55,'Admin',now(),'Admin',now(),NULL),
('8126',902,'Central Fiscal Asst. Director','Central Fiscal Asst. Director',1,56,'Admin',now(),'Admin',now(),NULL),
('8127',902,'Central Fiscal Administrator','Central Fiscal Administrator',1,57,'Admin',now(),'Admin',now(),NULL),
('8128',902,'Central Fiscal Supervisor','Central Fiscal Supervisor',1,58,'Admin',now(),'Admin',now(),NULL),
('8129',902,'Non DHR Screening','Non DHR Screening',1,59,'Admin',now(),'Admin',now(),NULL);