insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('AF','310','Afghanistan','Afghanistan',1,1,'AF');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('AX','310','Åland Islands','Åland Islands',1,2,'AX');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('AL','310','Albania','Albania',1,3,'AL');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('DZ','310','Algeria','Algeria',1,4,'DZ');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('AS','310','American Samoa','American Samoa',1,5,'AS');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('AD','310','Andorra','Andorra',1,6,'AD');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('AO','310','Angola','Angola',1,7,'AO');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('AI','310','Anguilla','Anguilla',1,8,'AI');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('AQ','310','Antarctica','Antarctica',1,9,'AQ');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('AG','310','Antigua and Barbuda','Antigua and Barbuda',1,10,'AG');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('AR','310','Argentina','Argentina',1,11,'AR');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('AM','310','Armenia','Armenia',1,12,'AM');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('AW','310','Aruba','Aruba',1,13,'AW');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('AU','310','Australia','Australia',1,14,'AU');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('AT','310','Austria','Austria',1,15,'AT');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('AZ','310','Azerbaijan','Azerbaijan',1,16,'AZ');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BS','310','Bahamas (the)','Bahamas (the)',1,17,'BS');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BH','310','Bahrain','Bahrain',1,18,'BH');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BD','310','Bangladesh','Bangladesh',1,19,'BD');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BB','310','Barbados','Barbados',1,20,'BB');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BY','310','Belarus','Belarus',1,21,'BY');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BE','310','Belgium','Belgium',1,22,'BE');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BZ','310','Belize','Belize',1,23,'BZ');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BJ','310','Benin','Benin',1,24,'BJ');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BM','310','Bermuda','Bermuda',1,25,'BM');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BT','310','Bhutan','Bhutan',1,26,'BT');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BO','310','Bolivia (Plurinational State of)','Bolivia (Plurinational State of)',1,27,'BO');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BQ','310','Bonaire, Sint Eustatius and Saba','Bonaire, Sint Eustatius and Saba',1,28,'BQ');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BA','310','Bosnia and Herzegovina','Bosnia and Herzegovina',1,29,'BA');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BW','310','Botswana','Botswana',1,30,'BW');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BV','310','Bouvet Island','Bouvet Island',1,31,'BV');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BR','310','Brazil','Brazil',1,32,'BR');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('IO','310','British Indian Ocean Territory','British Indian Ocean Territory',1,33,'IO');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BN','310','Brunei Darussalam','Brunei Darussalam',1,34,'BN');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BG','310','Bulgaria','Bulgaria',1,35,'BG');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BF','310','Burkina Faso','Burkina Faso',1,36,'BF');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('BI','310','Burundi','Burundi',1,37,'BI');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('CV','310','Cabo Verde','Cabo Verde',1,38,'CV');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('KH','310','Cambodia','Cambodia',1,39,'KH');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('CM','310','Cameroon','Cameroon',1,40,'CM');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('CA','310','Canada','Canada',1,41,'CA');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('KY','310','Cayman Islands','Cayman Islands',1,42,'KY');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('CF','310','Central African Republic','Central African Republic',1,43,'CF');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('TD','310','Chad','Chad',1,44,'TD');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('CL','310','Chile','Chile',1,45,'CL');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('CN','310','China','China',1,46,'CN');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('CX','310','Christmas Island','Christmas Island',1,47,'CX');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('CC','310','Cocos (Keeling) Islands','Cocos (Keeling) Islands',1,48,'CC');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('CO','310','Colombia','Colombia',1,49,'CO');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('KM','310','Comoros','Comoros',1,50,'KM');	
insert into referencevalues(ref_key,referencetypeid,value_text,description,activeflag,displayorder,mdmcode) values('CD','310','Congo (the Democratic Republic of )','Congo (the Democratic Republic of )',1,51,'CD');
