-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- Revision(s)
-- 05/19/2026 Varun Venugopal - CIDM-11277 - Create statements related to implementing the missing primary key for all the tables 
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
---Delete Duplicate record & existing column PK
DELETE FROM cjams.courtorderlanguage a USING cjams.courtorderlanguage b WHERE a.courtorderid = b.courtorderid AND a.ctid < b.ctid AND a.courtorderid in(select courtorderid from cjams.courtorderlanguage group by courtorderid having  count(*) > 1); 
DELETE FROM cjams.placementadmissionauthorizationtype a USING cjams.placementadmissionauthorizationtype b WHERE a.placementadmissionauthorizationtypeid  = b.placementadmissionauthorizationtypeid  AND a.ctid < b.ctid AND a.placementadmissionauthorizationtypeid  in (select placementadmissionauthorizationtypeid  from cjams.placementadmissionauthorizationtype group by placementadmissionauthorizationtypeid  having  count(*) > 1); 
DELETE FROM cjams.placementadmissionclassificationtype a USING cjams.placementadmissionclassificationtype b WHERE a.placementadmissionclassificationid  = b.placementadmissionclassificationid  AND a.ctid < b.ctid AND a.placementadmissionclassificationid  in (select placementadmissionclassificationid  from cjams.placementadmissionclassificationtype group by placementadmissionclassificationid  having  count(*) > 1); 
DELETE FROM cjams.placementadmissiontype a USING cjams.placementadmissiontype b WHERE a.placementadmissiontypeid  = b.placementadmissiontypeid  AND a.ctid < b.ctid AND a.placementadmissiontypeid  in (select placementadmissiontypeid  from cjams.placementadmissiontype group by placementadmissiontypeid  having  count(*) > 1); 
DELETE FROM cjams.placementprimaryadmissionreasontype a USING cjams.placementprimaryadmissionreasontype b WHERE a.placementprimaryadmissionreasontypeid = b.placementprimaryadmissionreasontypeid AND a.ctid < b.ctid AND a.placementprimaryadmissionreasontypeid in(select placementprimaryadmissionreasontypeid from cjams.placementprimaryadmissionreasontype group by placementprimaryadmissionreasontypeid having  count(*) > 1);  
DELETE FROM cjams.placementprimaryapprovedalttype a USING cjams.placementprimaryapprovedalttype b WHERE a.placementprimaryapprovedalttypeid = b.placementprimaryapprovedalttypeid AND a.ctid < b.ctid AND a.placementprimaryapprovedalttypeid in (select placementprimaryapprovedalttypeid from cjams.placementprimaryapprovedalttype group by placementprimaryapprovedalttypeid having  count(*) > 1);  
DELETE FROM cjams.tb_client_assets a USING cjams.tb_client_assets b WHERE a.asset_id = b.asset_id AND a.ctid < b.ctid  AND a.asset_id in(select asset_id from cjams.tb_client_assets group by asset_id having  count(*) > 1);  
DELETE FROM cjams.tb_client_deprivation a USING cjams.tb_client_deprivation b WHERE a.deprivtion_id = b.deprivtion_id AND a.ctid < b.ctid AND a.deprivtion_id in(select deprivtion_id from cjams.tb_client_deprivation group by deprivtion_id having  count(*) > 1);  
DELETE FROM cjams.tb_gap_rates_revision a USING cjams.tb_gap_rates_revision b WHERE a.gap_rates_revision_id = b.gap_rates_revision_id AND a.ctid < b.ctid  AND a.gap_rates_revision_id in(select gap_rates_revision_id from cjams.tb_gap_rates_revision  group by gap_rates_revision_id having  count(*) > 1); 
DELETE FROM cjams.tb_gap_suspension_revision a USING cjams.tb_gap_suspension_revision b WHERE a.gap_suspension_revision_id = b.gap_suspension_revision_id AND a.ctid < b.ctid AND a.gap_suspension_revision_id in(select gap_suspension_revision_id from cjams.tb_gap_suspension_revision group by gap_suspension_revision_id having  count(*) > 1); 
DELETE FROM cjams.tb_guardian_subsidy_suspension a USING cjams.tb_guardian_subsidy_suspension b WHERE a.suspension_id = b.suspension_id AND a.ctid < b.ctid AND a.suspension_id in(select suspension_id from cjams.tb_guardian_subsidy_suspension group by suspension_id having  count(*) > 1); 
DELETE FROM cjams.tb_ive_deemed_income_clients a USING cjams.tb_ive_deemed_income_clients b WHERE a.ive_deemed_income_clients_id = b.ive_deemed_income_clients_id AND a.ctid < b.ctid  AND a.ive_deemed_income_clients_id in(select ive_deemed_income_clients_id from cjams.tb_ive_deemed_income_clients  group by ive_deemed_income_clients_id having  count(*) > 1); 
DELETE FROM cjams.tb_montg_cnty_payment_interface a USING cjams.tb_montg_cnty_payment_interface b WHERE a.mc_interface_record_id = b.mc_interface_record_id AND a.ctid < b.ctid AND a.mc_interface_record_id in(select mc_interface_record_id from cjams.tb_montg_cnty_payment_interface  group by mc_interface_record_id having  count(*) > 1); 
DELETE FROM cjams.cinasubpoenad a USING cjams.cinasubpoenad b WHERE a.cinasubpoenadid = b.cinasubpoenadid AND a.ctid < b.ctid AND a.cinasubpoenadid in(select cinasubpoenadid from cjams.cinasubpoenad  group by cinasubpoenadid having  count(*) > 1); 
DELETE FROM cjams.intakeagencyrequesttype a USING cjams.intakeagencyrequesttype b WHERE a.intakeagencyreqtypeid = b.intakeagencyreqtypeid AND a.ctid < b.ctid AND a.intakeagencyreqtypeid in(select intakeagencyreqtypeid from cjams.intakeagencyrequesttype  group by intakeagencyreqtypeid having  count(*) > 1); 
DELETE FROM cjams.intakeserreqinterstate a USING cjams.intakeserreqinterstate b WHERE a.intakeserreqinterstateid = b.intakeserreqinterstateid AND a.ctid < b.ctid AND a.intakeserreqinterstateid in(select intakeserreqinterstateid from cjams.intakeserreqinterstate group by intakeserreqinterstateid having  count(*) > 1); 
DELETE FROM cjams.petitionwitness a USING cjams.petitionwitness b WHERE a.petitionwitnessid = b.petitionwitnessid AND a.ctid < b.ctid AND a.petitionwitnessid in(select petitionwitnessid from cjams.petitionwitness group by petitionwitnessid having  count(*) > 1); 
DELETE FROM cjams.tb_ticklers a USING cjams.tb_ticklers b WHERE a.tickler_id = b.tickler_id AND a.ctid < b.ctid AND a.tickler_id in(select tickler_id from cjams.tb_ticklers group by tickler_id having  count(*) > 1); 
DELETE FROM cjams.tb_jcr_foster_care a USING cjams.tb_jcr_foster_care b WHERE a.jcr_fc_id = b.jcr_fc_id AND a.ctid < b.ctid AND a.jcr_fc_id in(select jcr_fc_id from cjams.tb_jcr_foster_care group by jcr_fc_id having  count(*) > 1); 