drop table if exists cjams.adoptionapplicabilityinfo;
CREATE TABLE cjams.adoptionapplicabilityinfo (
	adoptionapplicabilityid uuid NOT NULL DEFAULT gen_random_uuid(),
	removalid int8 NOT NULL,
	clientid int8 NOT NULL,
  childBirthDate timestamp null,
   expectedAdoptionDate timestamp null,
   childAgeTable1618  boolean,
   childAgeTable418  boolean,
   childAgeTable1418  boolean,
   childAgeTable218  boolean,
   childAgeTable1218  boolean,
   childAgeTable018  boolean,
   childAgeTable1018  boolean,
   childAgeTable218dublicate  boolean,
   childAgeTable818  boolean,
   childAgeTable018dublicate  boolean,
   childAgeTable618  boolean,
   childAgeTableChildagenoneoftheagesapply  boolean,
   hasthechildbeenincare60Monthsormore text NULL,
   Isthechildasiblingtoachildwhoqualifiesasanapplicablechildbyage text NULL,
   aCourtOrder text NULL,
   BAvoluntaryplacementagreement text NULL,
   voluntaryRelinquishment text NULL,
   childmeetsSsImedicaldisabledeligliblerequirements text NULL,
   isthechildresidinginafosterfamilyhome text NULL,
   canchildreturntohome text NULL,
   descriptionofreturnhome text NULL,
   childMeetAllMedicalDisabilityRequirementsforSsi text NULL,
   child617Yearsofage  boolean,
   physicalMentalEmotionalDisability  boolean,
   emotionalDisturbance  boolean,
   siblingInformationCheck  boolean,
   recognizedhighriskofphysicaldisability  boolean,
   raceEthnicityofchild  boolean,
   unsuccessfulreasonableeffortsstatusrecords text NULL,
   fosterparentemotionalbonding text NULL,
   childspreviouslyadopted text NULL,
   previousAdoptiveParentsTpr timestamp null,
   adoptiveParentsTprDate timestamp null,
   childscurrentIvEfostercareeligibilitystatus text NULL,
   childsSsIeligibilitystatus text NULL,
   childreceivingSsIatremoval text NULL,
   childhasemotionaldisturbance text NULL,
   removalCourtorderdate timestamp null,
   dateoffirstcourtorderwithCtw timestamp null,
   childRemovalDate timestamp null,
   dateoffirstcourtorderwithbestinterestorCtWfindingifconvertedtoCina timestamp null,
   dateofRelinquishment timestamp null,
   startdateofreceivingSsi timestamp null,
   physicaladdressofchild text null,
   unsuccessfulreasonableeffortsstatusrecordsdescription text null,
   fosterparentemotionalbondingdescription text null,
   childsIvEstatusofpreviousadoption text null,
   columns2Save boolean,
	 CONSTRAINT pk_adoptionapplicabilityinfo PRIMARY KEY (adoptionapplicabilityid)
);


