CREATE TABLE TB_PLACEMENT_FSS_TEMP AS SELECT * FROM TB_PLACEMENT_FSS;

DELETE FROM TB_PLACEMENT_FSS;

ALTER TABLE TB_PLACEMENT_FSS ALTER COLUMN UPDATE_USER_ID TYPE VARCHAR(50) USING UPDATE_USER_ID::VARCHAR;
ALTER TABLE TB_PLACEMENT_FSS ALTER COLUMN EXIT_REASON_CD TYPE VARCHAR(15) USING EXIT_REASON_CD::VARCHAR;
ALTER TABLE TB_PLACEMENT_FSS ALTER COLUMN VOID_REASON_CD TYPE VARCHAR(15) USING VOID_REASON_CD::VARCHAR;
ALTER TABLE TB_PLACEMENT_FSS ALTER COLUMN EXIT_TYPE_CD TYPE VARCHAR(15) USING EXIT_TYPE_CD::VARCHAR;
ALTER TABLE TB_PLACEMENT_FSS ALTER COLUMN CASE_ID TYPE INT8 USING CASE_ID::INT8;
ALTER TABLE TB_PLACEMENT_FSS ALTER COLUMN CLIENT_ID TYPE INT8 USING CLIENT_ID::INT8;
ALTER TABLE TB_PLACEMENT_FSS ALTER COLUMN REMOVAL_ID TYPE INT8 USING REMOVAL_ID::INT8;

INSERT INTO TB_PLACEMENT_FSS SELECT * FROM TB_PLACEMENT_FSS_TEMP;

DROP TABLE TB_PLACEMENT_FSS_TEMP;

ALTER TABLE TB_ADOPTION_SUBSIDY_AGREEMENT_FSS DROP CONSTRAINT PK_ADPN_SUB_AGMT_FSS;