-- Table: cjams.csesoutboundinterface

 DROP TABLE cjams.csesoutboundinterface;

CREATE TABLE cjams.csesoutboundinterface
(
    csesoutboundinterfaceid bigint,
    statustypekey character varying(50) COLLATE pg_catalog."default",
    batchrunon timestamp(6) without time zone,
    batchseqno character varying(50) COLLATE pg_catalog."default",
    transactionseqno character varying(50) COLLATE pg_catalog."default",
    transactiontypekey character varying(50) COLLATE pg_catalog."default",
    cisclientid character varying(12) COLLATE pg_catalog."default",
    recordtypekey character varying(50) COLLATE pg_catalog."default",
    transactionon timestamp(6) without time zone,
    recordseqno character varying(50) COLLATE pg_catalog."default",
    csesoutcol1 character varying(50) COLLATE pg_catalog."default",
    csesoutcol2 character varying(50) COLLATE pg_catalog."default",
    csesoutcol3 character varying(50) COLLATE pg_catalog."default",
    csesoutcol4 character varying(50) COLLATE pg_catalog."default",
    csesoutcol5 character varying(50) COLLATE pg_catalog."default",
    csesoutcol6 character varying(50) COLLATE pg_catalog."default",
    csesoutcol7 character varying(50) COLLATE pg_catalog."default",
    csesoutcol8 character varying(50) COLLATE pg_catalog."default",
    csesoutcol9 character varying(50) COLLATE pg_catalog."default",
    csesoutcol10 character varying(50) COLLATE pg_catalog."default",
    csesoutcol11 character varying(50) COLLATE pg_catalog."default",
    csesoutcol12 character varying(50) COLLATE pg_catalog."default",
    csesoutcol13 character varying(50) COLLATE pg_catalog."default",
    csesoutcol14 character varying(50) COLLATE pg_catalog."default",
    csesoutcol15 character varying(50) COLLATE pg_catalog."default",
    csesoutcol16 character varying(50) COLLATE pg_catalog."default",
    csesoutcol17 character varying(50) COLLATE pg_catalog."default",
    csesoutcol18 character varying(50) COLLATE pg_catalog."default",
    csesoutcol19 character varying(50) COLLATE pg_catalog."default",
    csesoutcol20 character varying(50) COLLATE pg_catalog."default",
    csesoutcol21 character varying(50) COLLATE pg_catalog."default",
    csesoutcol22 character varying(50) COLLATE pg_catalog."default",
    csesoutcol23 character varying(50) COLLATE pg_catalog."default",
    csesoutcol24 character varying(50) COLLATE pg_catalog."default",
    csesoutcol25 character varying(50) COLLATE pg_catalog."default",
    csesoutcol26 character varying(50) COLLATE pg_catalog."default",
    csesoutcol27 character varying(50) COLLATE pg_catalog."default",
    csesoutcol28 character varying(50) COLLATE pg_catalog."default",
    csesoutcol29 character varying(50) COLLATE pg_catalog."default",
    csesoutcol30 character varying(50) COLLATE pg_catalog."default",
    csesoutcol31 character varying(50) COLLATE pg_catalog."default",
    csesoutcol32 character varying(50) COLLATE pg_catalog."default",
    csesoutcol33 character varying(50) COLLATE pg_catalog."default",
    csesoutcol34 character varying(50) COLLATE pg_catalog."default",
    csesoutcol35 character varying(50) COLLATE pg_catalog."default",
    csesoutcol36 character varying(50) COLLATE pg_catalog."default",
    csesoutcol37 character varying(50) COLLATE pg_catalog."default",
    csesoutcol38 character varying(50) COLLATE pg_catalog."default",
    csesoutcol39 character varying(50) COLLATE pg_catalog."default",
    csesoutcol40 character varying(50) COLLATE pg_catalog."default",
    csesoutcol41 character varying(50) COLLATE pg_catalog."default",
    csesoutcol42 character varying(50) COLLATE pg_catalog."default",
    csesoutcol43 character varying(50) COLLATE pg_catalog."default",
    csesoutcol44 character varying(50) COLLATE pg_catalog."default",
    csesoutcol45 character varying(50) COLLATE pg_catalog."default",
    csesoutcol46 character varying(50) COLLATE pg_catalog."default",
    csesoutcol47 character varying(50) COLLATE pg_catalog."default",
    csesoutcol48 character varying(50) COLLATE pg_catalog."default",
    csesoutcol49 character varying(50) COLLATE pg_catalog."default",
    csesoutcol50 character varying(50) COLLATE pg_catalog."default",
    csesoutcol51 character varying(50) COLLATE pg_catalog."default",
    csesoutcol52 character varying(50) COLLATE pg_catalog."default",
    csesoutcol53 character varying(50) COLLATE pg_catalog."default",
    csesoutcol54 character varying(50) COLLATE pg_catalog."default",
    csesoutcol55 character varying(50) COLLATE pg_catalog."default",
    csesoutcol56 character varying(50) COLLATE pg_catalog."default",
    csesoutcol57 character varying(50) COLLATE pg_catalog."default",
    csesoutcol58 character varying(50) COLLATE pg_catalog."default",
    csesoutcol59 character varying(50) COLLATE pg_catalog."default",
    csesoutcol60 character varying(50) COLLATE pg_catalog."default",
    datavalidflag integer,
    old_id character varying(12) COLLATE pg_catalog."default"
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

