DROP TABLE IF EXISTS cjams.tb_receivable_detail_history;

CREATE TABLE cjams.tb_receivable_detail_history (
	receivable_detail_history_id uuid NOT NULL DEFAULT gen_random_uuid(),	 
	receivable_detail_id int4  NULL,	 
	payment_detail_id int4 NULL,
	receivable_id int4  NULL,
	amount_no numeric(10,2) NULL,
	receivable_balance_no numeric(10,2) NULL,
	written_off_amount_no numeric(10,2) NULL,
	receivable_ts varchar(30) NULL,
	receivable_status_cd varchar(5) NULL,
	receivable_status_dt date NULL,
	comments_tx varchar(500) NULL,
	start_dt date NULL,
	end_dt date NULL,
	unit_no int4 NULL,
	manual_sw bpchar(1) NULL,
	county_cd varchar(5) NULL,
	notes_tx varchar(500) NULL,
	approval_status_cd varchar(5) NULL,
	action_dt date NULL,
	approve_staff_id int4 NULL,
	create_ts varchar(30) NULL,
	create_user_id varchar(500)  NULL,
	update_ts varchar(30) NULL,
	update_user_id varchar(500)  NULL,
	delete_sw bpchar(1)  NULL DEFAULT 'N'::bpchar,
	receivable_type varchar(5) NULL,
	write_off_approval_status varchar(5) NULL,
	write_off_action_date date NULL,
	approved_by varchar(50) NULL,
	write_off_request_user_id varchar(50) NULL,
	write_off_request_date date NULL,
	written_off_request_amount_no numeric NULL,
	isreversal bool null,
	activeflag int4 NULL DEFAULT 1
);

