
ALTER TABLE team ADD COLUMN IF NOT EXISTS supervisorid CHARACTER VARYING(50);
ALTER TABLE muser ADD COLUMN IF NOT EXISTS lastlogindt TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE muser ADD COLUMN IF NOT EXISTS loginexpirydt TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE muser ADD COLUMN IF NOT EXISTS islocked INT;
ALTER TABLE userprofile ADD COLUMN IF NOT EXISTS issupervisor INT;
ALTER TABLE personprogramarea ALTER COLUMN entityid TYPE CHARACTER VARYING(50); 