DROP VIEW cjams.sdr_intakeservicerequest_vw;

ALTER TABLE cjams.intakeservicerequest ALTER COLUMN reporterorganization TYPE varchar(120) USING reporterorganization::varchar;

-- View: cjams.sdr_intakeservicerequest_vw



CREATE OR REPLACE VIEW cjams.sdr_intakeservicerequest_vw AS
 SELECT intakeservicerequest.intakeserviceid::character varying(100) AS intakeserviceid,
    intakeservicerequest.activeflag,
    intakeservicerequest.servicerequestnumber,
    intakeservicerequest.servicerequestincidenttypekey,
    intakeservicerequest.narrative,
    intakeservicerequest.title,
    intakeservicerequest.description,
    intakeservicerequest.reporteddate,
    intakeservicerequest.reportedtime,
    intakeservicerequest.reportedarea,
    intakeservicerequest.reportedtypekey,
    intakeservicerequest.reportedbyself,
    intakeservicerequest.sourcearea,
    intakeservicerequest.intakeservreqinputtypeid::character varying(100) AS intakeservreqinputtypeid,
    intakeservicerequest.intakeservreqtypeid::character varying(100) AS intakeservreqtypeid,
    intakeservicerequest.inputtypevalue,
    intakeservicerequest.intakeserreqstatustypeid::character varying(100) AS intakeserreqstatustypeid,
    intakeservicerequest.intakeservicerequestclassid::character varying(100) AS intakeservicerequestclassid,
    intakeservicerequest.crossreferencewith,
    intakeservicerequest.priorityid::character varying(100) AS priorityid,
    intakeservicerequest.statuschangedate,
    intakeservicerequest.statuschangedescription,
    intakeservicerequest.dangerlevel,
    intakeservicerequest.dangerreason,
    intakeservicerequest.accesslevel,
    intakeservicerequest.updatedby,
    intakeservicerequest.updatedon,
    intakeservicerequest.insertedby,
    intakeservicerequest.insertedon,
    intakeservicerequest.archiveon,
    intakeservicerequest.archiveby,
    intakeservicerequest."timestamp",
    intakeservicerequest.old_id,
    intakeservicerequest.effectivedate,
    intakeservicerequest.expirationdate,
    intakeservicerequest.suspiciousdeath,
    intakeservicerequest.missingpersons,
    intakeservicerequest.sharedcaretaxcredit,
    intakeservicerequest.sharedcaretaxcredityear,
    intakeservicerequest.agencyname,
    intakeservicerequest.notes,
    intakeservicerequest.externalagencyphone,
    intakeservicerequest.externalagencyfax,
    intakeservicerequest.externalagencyemail,
    intakeservicerequest.investigatable,
    intakeservicerequest.visitinfo,
    intakeservicerequest.illegalactivity,
    intakeservicerequest.intakeservicerequestillegalactivitytypekey,
    intakeservicerequest.targetcompletedate,
    intakeservicerequest.supervisorreview,
    intakeservicerequest.rarejectedmedicaidstatus,
    intakeservicerequest.moneyfollowsperson,
    intakeservicerequest.im54adate,
    intakeservicerequest.hcb,
    intakeservicerequest.adverseactiondate,
    intakeservicerequest.applicationhearingreceiveddate,
    intakeservicerequest.reversaladverseactiondate,
    intakeservicerequest.monumber,
    intakeservicerequest.intakeservreqinputsourceid::character varying(100) AS intakeservreqinputsourceid,
    intakeservicerequest.isanonymousreporter,
    intakeservicerequest.intakeservreqpurposeid::character varying(100) AS intakeservreqpurposeid,
    intakeservicerequest.isrouted,
    intakeservicerequest.routedusersid,
    intakeservicerequest.intakenumber,
    intakeservicerequest.routedon,
    intakeservicerequest.teamtypekey,
    intakeservicerequest.isotheragency,
    intakeservicerequest.isunknownreporter,
    intakeservicerequest.reporterfirstname,
    intakeservicerequest.reporterlastname,
    intakeservicerequest.isappealed,
    intakeservicerequest.actiontype,
    intakeservicerequest.offenselocation,
    intakeservicerequest.requesterphone,
    intakeservicerequest.requesterzipcode,
    intakeservicerequest.iszipcoderefuse,
    intakeservicerequest.iscps,
    intakeservicerequest.isaccepted,
    intakeservicerequest.accepteddate,
    intakeservicerequest.isdraft,
    intakeservicerequest.foldertypekey,
    intakeservicerequest.folderreasontypekey,
    intakeservicerequest.folderopendatetime,
    intakeservicerequest.foldernotes,
    intakeservicerequest.responsibilitytypekey,
    intakeservicerequest.exitdate,
    intakeservicerequest.islocalreferal,
    intakeservicerequest.referalcomments,
    intakeservicerequest.nonreferalreason,
    intakeservicerequest.screeningname,
    intakeservicerequest.screenintypeflag,
    intakeservicerequest.contacttypekey,
    intakeservicerequest.screenerid,
    intakeservicerequest.recorddate,
    intakeservicerequest.recordtime,
    intakeservicerequest.scnapprovalstatustypekey,
    intakeservicerequest.scnapprovaldate,
    intakeservicerequest.screeningnmsoundex,
    intakeservicerequest.formattedreferralname,
    intakeservicerequest.expungementflag,
    intakeservicerequest.lastexpungementdate,
    intakeservicerequest.demoscreeningcompleteflag,
    intakeservicerequest.narratvscreeningcompleteflag,
    intakeservicerequest.rnmsoundex,
    intakeservicerequest.caseid::character varying(100) AS caseid,
    intakeservicerequest.communicationastncrqrdflag,
    intakeservicerequest.jurisdictionofincidenttypekey,
    intakeservicerequest.historyclearanceinfo,
    intakeservicerequest.histclearanceenteredby,
    intakeservicerequest.histclearanceenteredtimestamp,
    intakeservicerequest.histclearanceeditedby,
    intakeservicerequest.histclearanceeditedtimestamp,
    intakeservicerequest.receivedtime,
    intakeservicerequest.fk1_id,
    intakeservicerequest.requesteraddress1,
    intakeservicerequest.requesteraddress2,
    intakeservicerequest.requestercity,
    intakeservicerequest.requesterstate,
    intakeservicerequest.requestercounty,
    intakeservicerequest.isacknowledgementletter,
    intakeservicerequest.isrestitution,
    intakeservicerequest.servicecaseid::character varying(100) AS servicecaseid,
    intakeservicerequest.countyid::character varying(100) AS countyid,
    intakeservicerequest.constentreceiveddate,
    intakeservicerequest.searchworkername,
    intakeservicerequest.isnoticedthirdparty,
    intakeservicerequest.isnoticedindividual,
    intakeservicerequest.isclosecpshistory,
    intakeservicerequest.clearancereasontypekey,
    intakeservicerequest.fk_source,
    intakeservicerequest.status_indc,
    intakeservicerequest.reportermiddlename,
    intakeservicerequest.reporterphonenumber,
    intakeservicerequest.reporterroletypekey,
    intakeservicerequest.reporterzipcode,
    intakeservicerequest.reporterincidentlocation,
    intakeservicerequest.reporteremail,
    intakeservicerequest.reporterisapproximate,
    intakeservicerequest.reporterorganization,
    intakeservicerequest.reportertitle,
    intakeservicerequest.reporterincidentdate,
    intakeservicerequest.reporterisanonymousreporter,
    intakeservicerequest.reporterisunknownreporter,
    intakeservicerequest.reporternarrative,
    intakeservicerequest.reporterrefusetosharezip,
    intakeservicerequest.reporterisacknowledgementletter,
    intakeservicerequest.reporteraddress1,
    intakeservicerequest.reporteraddress2,
    intakeservicerequest.reportercity,
    intakeservicerequest.reporterstate,
    intakeservicerequest.narrativeupdateddate,
    intakeservicerequest.reporterphonenumberext,
    intakeservicerequest.isscreening
   FROM intakeservicerequest;


