-- Drop table

DROP TABLE IF EXISTS cjams.gapeligibilityinfo;

CREATE TABLE cjams.gapeligibilityinfo (
	gapeligibilityinfoid uuid NOT NULL DEFAULT gen_random_uuid(),
	client_id bigint NOT NULL,
	al_removal_id bigint NULL,
	childname varchar NULL,
	dateofbirth timestamp NULL,
	gender varchar(10) NULL,
	personid uuid NULL,
	childguardianid int NULL,
	childguardianname varchar NULL,
	childsecguardianid int NULL,
	childsecguardianname varchar NULL,
	guardianshipagreementsigneddate timestamp NULL,
	secondaryguardianshipagreementsigneddate timestamp NULL,
	dateofcourtorderguardianshipfinalization timestamp NULL,
	siblinginfo json NULL,
	casenumber varchar NULL,
	childjurisdiction varchar NULL,
	createdate timestamp NULL,
	servicecaseid uuid NULL,
	guardianshipapplicationdate timestamp NULL,
	primaryguardianisrelative varchar NULL,
	primaryguardianrelationshipid int NULL,
	primaryguardianrelationship varchar NULL,
	secondaryguardianisrelative varchar NULL,
	secondguardianrelationshipid int NULL,
	secondguardianrelationship varchar NULL,
	haapprovaldtjson json NULL,
	dateofhomeapproval timestamp null,
	latestfcplacementstartdatewithperpectiveguardian timestamp NULL,
	fosterhomeapprover varchar NULL,
	secondguardianexists boolean NULL,
	successorguardianexists boolean NULL,
	successorguardianname varchar NULL,
	successorguardianid int NULL,	
	dateofsuccessionaddendum timestamp NULL,
	yesindicatetypeofremoval boolean NULL,
	nochildisnoteligibleforgap boolean NULL,
	removalcourtorderdate timestamp NULL,
	removalvpadate timestamp NULL,	
	childremovedbyvpa boolean NULL,
	childremovedbycrt boolean NULL,
	isconsultationchildage varchar NULL,
	isguardianattach varchar NULL,
	ischildsecondguardianattach varchar NULL,
	isreunificationremoved varchar NULL,
	isadoptionremoved varchar NULL,
	iscgprovidesafe varchar NULL,
	secguardlivingwithpriguard varchar NULL,
	last6monthfiscalpaymentstatus varchar NULL,
	primaryGuardian json null,
	primaryGuardianHouseHold json null,
	secondaryGuardian json null,
	secondaryGuardianHouseHold json null,
	providerapprovalid int null,
	isasiblingofachildgappayments boolean null,
	isnotasiblingofachildgappayments boolean null,
	siblingInformationGrid json null,
	insertedby varchar NULL,
	insertedon timestamp NULL DEFAULT now(),
	updatedby varchar NULL,
	updatedon timestamp NULL DEFAULT now(),
	activeflag int null,
	CONSTRAINT pk_gapeligibilityinfo PRIMARY KEY (gapeligibilityinfoid)
);

