DROP TABLE IF EXISTS cjams.servicecaseaffidavit;

CREATE TABLE IF NOT EXISTS cjams.servicecaseaffidavit (
	servicecaseaffidavitid uuid NOT NULL DEFAULT gen_random_uuid(),
	typekey character varying,
	objectid uuid,
	objectkey character varying,
	caregiverid uuid,
	caregivername character varying,
	caregiverdob timestamp with time zone,
	caregiveraddress character varying,
	childrendata json,
	isbloodrelationship boolean,
	ischildfriend boolean,
	ischildfamilfriend boolean,
	hasstrongbondwithchild boolean,
	hasstrongbondwithfamily boolean,
	hasregularcontactwithchild boolean,
	hasregularcontactwithfamily boolean,
	description text,
	applicant1name character varying,
	applicant1signature character varying,
	applicant1date timestamp with time zone,
	applicant2name character varying,
	applicant2signature character varying,
	applicant2date timestamp with time zone,
	parent1name character varying,
	parent1signature character varying,
	parent1date timestamp with time zone,
	parent2name character varying,
	parent2signature character varying,
	parent2date timestamp with time zone,
	childname character varying,
	childsignature character varying,
	childdate timestamp with time zone,
	isapplicantsignatureavailable boolean,
	activeflag int4 NOT NULL DEFAULT 1,
	insertedby varchar(50) NOT NULL,
	insertedon timestamp NOT NULL DEFAULT now(),
	updatedby varchar(50) NOT NULL,
	updatedon timestamp NOT NULL DEFAULT now(),
	CONSTRAINT servicecaseaffidavit_servicecaseaffidavitid PRIMARY KEY (servicecaseaffidavitid)
);