-- Table: cjams.tb_cares_outbound_interface

 --DROP TABLE cjams.tb_cares_outbound_interface;

CREATE TABLE cjams.tb_cares_outbound_interface
(
    cares_record_id integer NOT NULL,
    status_cd character varying(3) COLLATE pg_catalog."default" NOT NULL,
    batch_run_ts timestamp without time zone,
    batch_seq_no character varying(5) COLLATE pg_catalog."default",
    transaction_seq_no character varying(5) COLLATE pg_catalog."default" NOT NULL,
    transaction_type_cd character varying(2) COLLATE pg_catalog."default" NOT NULL,
    cis_client_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    record_type_cd character varying(2) COLLATE pg_catalog."default" NOT NULL,
    transaction_ts timestamp without time zone NOT NULL,
    record_seq_no character varying(3) COLLATE pg_catalog."default" NOT NULL,
    cares_out_col1 character varying(100) COLLATE pg_catalog."default",
    cares_out_col2 character varying(100) COLLATE pg_catalog."default",
    cares_out_col3 character varying(100) COLLATE pg_catalog."default",
    cares_out_col4 character varying(100) COLLATE pg_catalog."default",
    cares_out_col5 character varying(100) COLLATE pg_catalog."default",
    cares_out_col6 character varying(100) COLLATE pg_catalog."default",
    cares_out_col7 character varying(100) COLLATE pg_catalog."default",
    cares_out_col8 character varying(100) COLLATE pg_catalog."default",
    cares_out_col9 character varying(100) COLLATE pg_catalog."default",
    cares_out_col10 character varying(100) COLLATE pg_catalog."default",
    cares_out_col11 character varying(100) COLLATE pg_catalog."default",
    cares_out_col12 character varying(100) COLLATE pg_catalog."default",
    cares_out_col13 character varying(100) COLLATE pg_catalog."default",
    cares_out_col14 character varying(100) COLLATE pg_catalog."default",
    cares_out_col15 character varying(100) COLLATE pg_catalog."default",
    cares_out_col16 character varying(100) COLLATE pg_catalog."default",
    cares_out_col17 character varying(100) COLLATE pg_catalog."default",
    cares_out_col18 character varying(100) COLLATE pg_catalog."default",
    cares_out_col19 character varying(100) COLLATE pg_catalog."default",
    cares_out_col20 character varying(100) COLLATE pg_catalog."default",
    cares_out_col21 character varying(100) COLLATE pg_catalog."default",
    cares_out_col22 character varying(100) COLLATE pg_catalog."default",
    cares_out_col23 character varying(100) COLLATE pg_catalog."default",
    cares_out_col24 character varying(100) COLLATE pg_catalog."default",
    cares_out_col25 character varying(100) COLLATE pg_catalog."default",
    cares_out_col26 character varying(100) COLLATE pg_catalog."default",
    cares_out_col27 character varying(100) COLLATE pg_catalog."default",
    cares_out_col28 character varying(100) COLLATE pg_catalog."default",
    cares_out_col29 character varying(100) COLLATE pg_catalog."default",
    cares_out_col30 character varying(100) COLLATE pg_catalog."default",
    cares_out_col31 character varying(100) COLLATE pg_catalog."default",
    cares_out_col32 character varying(100) COLLATE pg_catalog."default",
    cares_out_col33 character varying(100) COLLATE pg_catalog."default",
    cares_out_col34 character varying(100) COLLATE pg_catalog."default",
    cares_out_col35 character varying(100) COLLATE pg_catalog."default",
    cares_out_col36 character varying(100) COLLATE pg_catalog."default",
    cares_out_col37 character varying(100) COLLATE pg_catalog."default",
    cares_out_col38 character varying(100) COLLATE pg_catalog."default",
    cares_out_col39 character varying(100) COLLATE pg_catalog."default",
    cares_out_col40 character varying(100) COLLATE pg_catalog."default",
    cares_out_col41 character varying(100) COLLATE pg_catalog."default",
    cares_out_col42 character varying(100) COLLATE pg_catalog."default",
    cares_out_col43 character varying(100) COLLATE pg_catalog."default",
    cares_out_col44 character varying(100) COLLATE pg_catalog."default",
    cares_out_col45 character varying(100) COLLATE pg_catalog."default",
    cares_out_col46 character varying(100) COLLATE pg_catalog."default",
    cares_out_col47 character varying(100) COLLATE pg_catalog."default",
    cares_out_col48 character varying(100) COLLATE pg_catalog."default",
    cares_out_col49 character varying(100) COLLATE pg_catalog."default",
    cares_out_col50 character varying(100) COLLATE pg_catalog."default",
    cares_out_col51 character varying(100) COLLATE pg_catalog."default",
    cares_out_col52 character varying(100) COLLATE pg_catalog."default",
    cares_out_col53 character varying(100) COLLATE pg_catalog."default",
    cares_out_col54 character varying(100) COLLATE pg_catalog."default",
    cares_out_col55 character varying(100) COLLATE pg_catalog."default",
    cares_out_col56 character varying(100) COLLATE pg_catalog."default",
    cares_out_col57 character varying(100) COLLATE pg_catalog."default",
    cares_out_col58 character varying(100) COLLATE pg_catalog."default",
    cares_out_col59 character varying(100) COLLATE pg_catalog."default",
    cares_out_col60 character varying(100) COLLATE pg_catalog."default",
    cares_out_col61 character varying(100) COLLATE pg_catalog."default",
    cares_out_col62 character varying(100) COLLATE pg_catalog."default",
    cares_out_col63 character varying(100) COLLATE pg_catalog."default",
    cares_out_col64 character varying(100) COLLATE pg_catalog."default",
    cares_out_col65 character varying(100) COLLATE pg_catalog."default",
    cares_out_col66 character varying(100) COLLATE pg_catalog."default",
    cares_out_col67 character varying(100) COLLATE pg_catalog."default",
    cares_out_col68 character varying(100) COLLATE pg_catalog."default",
    cares_out_col69 character varying(100) COLLATE pg_catalog."default",
    cares_out_col70 character varying(100) COLLATE pg_catalog."default",
    cares_out_col71 character varying(100) COLLATE pg_catalog."default",
    cares_out_col72 character varying(100) COLLATE pg_catalog."default",
    cares_out_col73 character varying(100) COLLATE pg_catalog."default",
    cares_out_col74 character varying(100) COLLATE pg_catalog."default",
    cares_out_col75 character varying(100) COLLATE pg_catalog."default",
    cares_out_col76 character varying(100) COLLATE pg_catalog."default",
    cares_out_col77 character varying(100) COLLATE pg_catalog."default",
    cares_out_col78 character varying(100) COLLATE pg_catalog."default",
    cares_out_col79 character varying(100) COLLATE pg_catalog."default",
    cares_out_col80 character varying(100) COLLATE pg_catalog."default",
    cares_out_col81 character varying(100) COLLATE pg_catalog."default",
    cares_out_col82 character varying(100) COLLATE pg_catalog."default",
    cares_out_col83 character varying(100) COLLATE pg_catalog."default",
    cares_out_col84 character varying(100) COLLATE pg_catalog."default",
    cares_out_col85 character varying(100) COLLATE pg_catalog."default",
    cares_out_col86 character varying(100) COLLATE pg_catalog."default",
    cares_out_col87 character varying(100) COLLATE pg_catalog."default",
    cares_out_col88 character varying(100) COLLATE pg_catalog."default",
    cares_out_col89 character varying(100) COLLATE pg_catalog."default",
    cares_out_col90 character varying(100) COLLATE pg_catalog."default",
    cares_out_col91 character varying(100) COLLATE pg_catalog."default",
    cares_out_col92 character varying(100) COLLATE pg_catalog."default",
    cares_out_col93 character varying(100) COLLATE pg_catalog."default",
    cares_out_col94 character varying(100) COLLATE pg_catalog."default",
    cares_out_col95 character varying(100) COLLATE pg_catalog."default",
    cares_out_col96 character varying(100) COLLATE pg_catalog."default",
    cares_out_col97 character varying(100) COLLATE pg_catalog."default",
    cares_out_col98 character varying(100) COLLATE pg_catalog."default",
    cares_out_col99 character varying(100) COLLATE pg_catalog."default",
    cares_out_col100 character varying(100) COLLATE pg_catalog."default",
    cares_out_col101 character varying(100) COLLATE pg_catalog."default",
    cares_out_col102 character varying(100) COLLATE pg_catalog."default",
    cares_out_col103 character varying(100) COLLATE pg_catalog."default",
    cares_out_col104 character varying(100) COLLATE pg_catalog."default",
    cares_out_col105 character varying(100) COLLATE pg_catalog."default",
    cares_out_col106 character varying(100) COLLATE pg_catalog."default",
    cares_out_col107 character varying(100) COLLATE pg_catalog."default",
    cares_out_col108 character varying(100) COLLATE pg_catalog."default",
    cares_out_col109 character varying(100) COLLATE pg_catalog."default",
    cares_out_col110 character varying(100) COLLATE pg_catalog."default",
    cares_out_col111 character varying(100) COLLATE pg_catalog."default",
    cares_out_col112 character varying(100) COLLATE pg_catalog."default",
    cares_out_col113 character varying(100) COLLATE pg_catalog."default",
    cares_out_col114 character varying(100) COLLATE pg_catalog."default",
    cares_out_col115 character varying(100) COLLATE pg_catalog."default",
    cares_out_col116 character varying(100) COLLATE pg_catalog."default",
    cares_out_col117 character varying(100) COLLATE pg_catalog."default",
    cares_out_col118 character varying(100) COLLATE pg_catalog."default",
    cares_out_col119 character varying(100) COLLATE pg_catalog."default",
    cares_out_col120 character varying(100) COLLATE pg_catalog."default",
    data_valid_sw character(1) COLLATE pg_catalog."default",
    CONSTRAINT pk_car_out_inter PRIMARY KEY (cares_record_id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE cjams.tb_cares_outbound_interface
    OWNER to welfareadmin;