DROP FUNCTION IF EXISTS delete_backup_getdocdetails(integer,integer);
DROP FUNCTION IF EXISTS delete_backup_sp_cares_outbound_interface_gen_data_01(integer,character varying,character varying,integer,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_cares_outbound_interface_gen_data_55(integer,character varying,character varying,integer,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_child_account_release_coc(timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_cses_outbound_interface_gen_data_30(integer,character varying,integer,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_susbsidy_receivables(character,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_overpaymenthistory(integer,bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_copyuserfromanotherenv(character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_f_months_between(timestamp without time zone,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_csrb_get_current_balance(bigint,timestamp without time zone,character varying,character varying,bigint);
DROP FUNCTION IF EXISTS delete_backup_sp_efc_rfc_ticklers(bigint,character,timestamp without time zone,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_getguardianship(uuid,uuid);
DROP FUNCTION IF EXISTS delete_backup_sp_list_overpayment_audit_log(integer,bigint,bigint,integer);
DROP FUNCTION IF EXISTS delete_backup_createnewuser(character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying);
-- DROP FUNCTION IF EXISTS delete_backup_f_ename(character varying,integer,character varying);
DROP FUNCTION IF EXISTS delete_backup_copyuserfromanotherenv(character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_f_sp_efc_days_calculation(character,bigint,timestamp without time zone,timestamp without time zone,timestamp without time zone,timestamp without time zone,integer);
DROP FUNCTION IF EXISTS delete_backup_fostercarereferallistforvalidation(character varying,bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_routingprovider(character varying,character varying,character varying,integer,text,text,timestamp without time zone,text,timestamp without time zone,text,timestamp without time zone,character varying,boolean,boolean,boolean,character varying,character varying,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_f_prim_worker_id(integer,character varying);
DROP FUNCTION IF EXISTS delete_backup_deletequickperson(character varying,uuid,character varying,character varying,character varying,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_adoptioncaselist(uuid,integer,integer);
DROP FUNCTION IF EXISTS delete_backup_adoptionsignature(uuid,text,integer);
DROP FUNCTION IF EXISTS delete_backup_assigncase(character varying,uuid,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_assignintake(character varying,character varying,character varying,character varying,integer);
DROP FUNCTION IF EXISTS delete_backup_complaintsummary(uuid,bigint,bigint,character varying,boolean);
DROP FUNCTION IF EXISTS delete_backup_contactsummary(uuid,bigint,bigint,character varying,boolean);
DROP FUNCTION IF EXISTS delete_backup_cpsresponsetimersaveapproval(json);
DROP FUNCTION IF EXISTS delete_backup_createadoptioncase(uuid,uuid,jsonb,character varying);
DROP FUNCTION IF EXISTS delete_backup_createfacetofaceauditlog(uuid,character varying,uuid);
DROP FUNCTION IF EXISTS delete_backup_documenttemplaterolewiselist(character varying,character varying,uuid,character varying);
-- DROP FUNCTION IF EXISTS delete_backup_f_ename(character varying);
-- DROP FUNCTION IF EXISTS delete_backup_f_ename(character varying,integer);
DROP FUNCTION IF EXISTS delete_backup_f_prim_county(integer);
DROP FUNCTION IF EXISTS delete_backup_f_prim_county(character varying);
DROP FUNCTION IF EXISTS delete_backup_f_prim_county(integer,character varying);
DROP FUNCTION IF EXISTS delete_backup_f_prim_county(integer,date,date);
DROP FUNCTION IF EXISTS delete_backup_f_prim_county(integer,timestamp without time zone,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_f_sp_ename(character varying,integer);
-- DROP FUNCTION IF EXISTS delete_backup_f_prim_worker(integer,character varying);
DROP FUNCTION IF EXISTS delete_backup_f_prim_worker_id(bigint,character varying);
-- DROP FUNCTION IF EXISTS delete_backup_f_prvpcklst_cat(integer,character varying);
DROP FUNCTION IF EXISTS delete_backup_f_sp_csrb_days_calculation(character,bigint,bigint,date,date,date,date);
DROP FUNCTION IF EXISTS delete_backup_f_sp_csrb_days_calculation(character,bigint,bigint,timestamp without time zone,timestamp without time zone,timestamp without time zone,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_f_sp_efc_days_calculation(character,integer,date,date,date,date,integer);
DROP FUNCTION IF EXISTS delete_backup_f_sp_efc_days_calculation(character,integer,timestamp without time zone,timestamp without time zone,timestamp without time zone,timestamp without time zone,integer);
DROP FUNCTION IF EXISTS delete_backup_f_sp_ename(character varying,bigint);
DROP FUNCTION IF EXISTS delete_backup_f_sp_fostercare_calculation(character,character,bigint,timestamp without time zone,timestamp without time zone,timestamp without time zone,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_routingive(character varying,character varying,character varying,integer,text,character varying,boolean,boolean,boolean,character varying,character varying,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_updateplacementstructures(character varying,character varying,character varying,character varying,numeric,character varying);
DROP FUNCTION IF EXISTS delete_backup_firstnotice(character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_fostercarereferallistforvalidation(bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_fostercarereferallistforvalidation(character varying,bigint,bigint,character varying);
DROP FUNCTION IF EXISTS delete_backup_fostercarereferallistforvalidation(character varying,bigint,bigint,character varying,bigint);
DROP FUNCTION IF EXISTS delete_backup_get_child_details_list(json,bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_reassigncase(character varying,uuid,character varying,character varying,character varying,uuid,timestamp without time zone,character varying,integer,uuid,json,character varying);
DROP FUNCTION IF EXISTS delete_backup_get_codes_discription_service_log();
DROP FUNCTION IF EXISTS delete_backup_get_codes_discription_service_log(text);
DROP FUNCTION IF EXISTS delete_backup_get_purchase_auth_fiscal();
DROP FUNCTION IF EXISTS delete_backup_get_payment_header_details(bigint,bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_get_provider_search(integer,character varying,numeric,numeric,integer);
DROP FUNCTION IF EXISTS delete_backup_get_provider_service_log();
DROP FUNCTION IF EXISTS delete_backup_get_provider_service_log(text);
DROP FUNCTION IF EXISTS delete_backup_getpersontransportation(uuid,uuid,character varying,integer,integer,boolean);
DROP FUNCTION IF EXISTS delete_backup_getannualreview(uuid);
DROP FUNCTION IF EXISTS delete_backup_get_receipt_fast_entry(character varying,character varying,bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_get_receipt_fast_entry(character varying,character varying,bigint,bigint,bigint,character varying);
DROP FUNCTION IF EXISTS delete_backup_getactortype(character varying);
DROP FUNCTION IF EXISTS delete_backup_getadoptionpaymenthistory(integer,integer,integer);
DROP FUNCTION IF EXISTS delete_backup_getpersonauditlog(uuid,character varying,bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_getadoptionpaymenthistory(integer,bigint,integer,integer);
DROP FUNCTION IF EXISTS delete_backup_getdatypeconfiglist(integer,integer,character varying);
DROP FUNCTION IF EXISTS delete_backup_getappealdashboard(uuid,integer,integer,character varying);
DROP FUNCTION IF EXISTS delete_backup_getintakeassessment(character varying,uuid);
DROP FUNCTION IF EXISTS delete_backup_getappealdashboard(uuid,integer,integer,character varying,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_getassessmentlist(character varying,character varying,character varying,uuid,uuid);
DROP FUNCTION IF EXISTS delete_backup_getcase_summary(uuid);
DROP FUNCTION IF EXISTS delete_backup_getdatypeconfiglist(integer,integer,text);
DROP FUNCTION IF EXISTS delete_backup_getdocdetails_cnt();
DROP FUNCTION IF EXISTS delete_backup_getfinanceincomebycase(numeric);
DROP FUNCTION IF EXISTS delete_backup_getgapagreementlist(uuid,integer,integer);
DROP FUNCTION IF EXISTS delete_backup_getgroupinglist(character varying,integer,integer,character varying,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_getguardianship(uuid,integer);
DROP FUNCTION IF EXISTS delete_backup_listiveplacement(character varying,text[],character varying,character varying,bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_getintakeassessment(character varying,uuid,boolean);
DROP FUNCTION IF EXISTS delete_backup_listfocuspersoncasestatus(uuid,character varying,uuid,character varying,bigint,bigint,boolean);
DROP FUNCTION IF EXISTS delete_backup_getpaymentdetails(integer,bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_getpaymenthistorybyclientid(integer,bigint,bigint,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_getpaymenthistorybyclientid(integer,bigint,bigint,character varying,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_getpaymentnotice(character varying,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_getpendingreviewda(character varying,integer,integer);
DROP FUNCTION IF EXISTS delete_backup_getservicecaseremovallist(uuid,bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_listiveplacement(character varying,text[],character varying,character varying,bigint,bigint,character varying,character varying,character varying,character varying,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_getpersonalertlist(uuid,bigint,bigint,integer,character varying,boolean);
DROP FUNCTION IF EXISTS delete_backup_getplacementsummary(uuid,bigint,bigint,character varying,character varying,boolean);
DROP FUNCTION IF EXISTS delete_backup_getrestitutionpaymentlist(integer,uuid,bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_listiveplacement(character varying,text[],character varying,character varying,bigint,bigint,character varying,character varying,character varying,character varying,timestamp without time zone,character varying);
DROP FUNCTION IF EXISTS delete_backup_getsameracrossrefda(character varying,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_getsupervisorsbycounty(character varying);
DROP FUNCTION IF EXISTS delete_backup_listiveplacement(character varying,bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_insert_payment_header_details(uuid);
DROP FUNCTION IF EXISTS delete_backup_insert_payment_header_details(uuid,integer);
DROP FUNCTION IF EXISTS delete_backup_jirasupportticketslist();
DROP FUNCTION IF EXISTS delete_backup_jirasupportticketslist(character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_mycasesearch(character varying,integer,integer,character varying,character varying,character varying,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_listauditmodifiedlogs(uuid,character varying,character varying,bigint,bigint,uuid,boolean);
DROP FUNCTION IF EXISTS delete_backup_sp_payment_detail_insert(bigint,bigint,bigint,timestamp without time zone,timestamp without time zone,numeric,integer,character varying,numeric,character,character varying,bigint,bigint,character varying);
DROP FUNCTION IF EXISTS delete_backup_listiveplacement(character varying,text[],bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_listiveplacement(character varying,text[],character varying,bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_listpersonhealthinsurance(uuid,bigint,bigint,character varying,character varying,boolean);
DROP FUNCTION IF EXISTS delete_backup_listpersonphycisianinfo(uuid,bigint,bigint,character varying,character varying,boolean);
DROP FUNCTION IF EXISTS delete_backup_listplacementuserdetails(character varying,character varying,bigint,bigint,character varying,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_listpreintake(character varying,character varying,bigint,bigint,character varying,boolean);
DROP FUNCTION IF EXISTS delete_backup_listprognotesubtypes(uuid);
DROP FUNCTION IF EXISTS delete_backup_listprovideruir(character varying,character varying,integer,integer,character varying,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_placementrevisionupdate(character varying,timestamp without time zone,character varying);
DROP FUNCTION IF EXISTS delete_backup_recording(json,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_restichangeformapprovereject(json,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_placementrevisionupdate(character varying,timestamp without time zone,character varying,character varying,character varying,timestamp without time zone,character varying,character varying,character varying,character varying,integer,character varying);
DROP FUNCTION IF EXISTS delete_backup_placementrevisionupdate(character varying,timestamp without time zone,character varying,character varying,character varying,timestamp without time zone,character varying,character varying,character varying,character varying,integer,character varying,timestamp without time zone,character varying);
DROP FUNCTION IF EXISTS delete_backup_placementrevisionupdate(character varying,timestamp without time zone,character varying,character varying,character varying,timestamp without time zone,character varying,character varying,character varying,character varying,integer,character varying,timestamp without time zone,character varying,boolean,character varying);
DROP FUNCTION IF EXISTS delete_backup_publiccaseplanrouting(character varying,character varying,character varying,numeric,character varying,character varying,character varying,numeric,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_publicserviceplanrouting(character varying,character varying,character varying,integer,character varying,character varying,character varying,integer);
DROP FUNCTION IF EXISTS delete_backup_recording(character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_updatedisposition(uuid);
DROP FUNCTION IF EXISTS delete_backup_recording(json,uuid,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_restitution_pmt_slip(character varying);
DROP FUNCTION IF EXISTS delete_backup_reviewsummary(uuid,bigint,bigint,character varying,boolean);
DROP FUNCTION IF EXISTS delete_backup_saveintake(jsonb,character varying);
DROP FUNCTION IF EXISTS delete_backup_saveintake(jsonb,character varying,integer,character varying);
DROP FUNCTION IF EXISTS delete_backup_searchevaluationsources(character varying,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_sp_get_current_balance(bigint,timestamp without time zone,timestamp without time zone,character varying,timestamp without time zone,bigint);
DROP FUNCTION IF EXISTS delete_backup_servicecaseassignlist(character varying,character varying,integer,integer);
DROP FUNCTION IF EXISTS delete_backup_sp_cares_outbound_interface_gen_data(integer,character varying,character varying,integer,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_acc_trans_rs_insert(character varying,numeric,integer,integer,timestamp without time zone,timestamp without time zone,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_account_transaction_insert(bigint,bigint,character varying,character varying,numeric,character,timestamp without time zone,numeric,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_sp_address(character varying,character varying,integer,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_sp_get_placement_rate(bigint,integer,timestamp without time zone,timestamp without time zone,character);
DROP FUNCTION IF EXISTS delete_backup_sp_address(character varying,character varying,character varying,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_sp_adoption_subsidy_check(bigint,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_cares_outbound_interface_gen_data_50(integer,character varying,character varying,integer,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_county_specific_unov_fss(timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_batch_error_log(character varying,bigint,bigint,character varying,integer,character varying,integer,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_sp_batch_prov_checklist(character,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_updateteamassignment(character varying,character varying,character varying,character varying,character varying,character varying,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_sp_get_totalamount_fiscalcategory(character varying);
DROP FUNCTION IF EXISTS delete_backup_sp_cares_outbound_interface_gen_data_10(integer,character varying,character varying,integer,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_cares_outbound_interface_gen_data_15(integer,character varying,character varying,integer,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_cares_outbound_interface_gen_data_20(integer,character varying,character varying,integer,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_cares_outbound_interface_gen_data_25(integer,character varying,character varying,integer,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_cares_outbound_interface_gen_data_30(integer,character varying,character varying,integer,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_cares_outbound_interface_gen_data_35(integer,character varying,character varying,integer,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_cares_outbound_interface_gen_data_40(integer,character varying,character varying,integer,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_cares_outbound_interface_gen_data_45(integer,character varying,character varying,integer,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_expungement_insert(bigint);
DROP FUNCTION IF EXISTS delete_backup_sp_fc_worksheet_removal_info(bigint);
DROP FUNCTION IF EXISTS delete_backup_sp_fc_worksheet_ssi_ssa_criteria_info(bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_sp_fiscalunitticklers_dashboard(bigint,bigint,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_sp_fiscalunitticklers_dashboard(bigint,bigint,character varying,character varying,character varying,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_sp_fostercare_calculation(character,character,bigint,timestamp without time zone,timestamp without time zone,timestamp without time zone,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_ive_fc_periods(bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_sp_ive_fc_periods(character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_sp_ive_routing();
DROP FUNCTION IF EXISTS delete_backup_sp_ive_routing(character varying);
DROP FUNCTION IF EXISTS delete_backup_sp_ive_spv_approval_status(uuid,character varying,character varying,bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_sp_rs_fiscal_cat_cd(bigint,bigint,character,timestamp without time zone,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_ive_status_approval(bigint,bigint,character varying,text[],character varying,character varying,bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_sp_list_overpayment_audit_log(integer,bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_sp_list_payable_approvels(character varying,character varying,character varying,bigint,bigint);
DROP FUNCTION IF EXISTS delete_backup_sp_over_payment(bigint,bigint,bigint,timestamp without time zone,timestamp without time zone,numeric,character varying);
DROP FUNCTION IF EXISTS delete_backup_sp_payment_exeception(character varying,integer,character varying);
DROP FUNCTION IF EXISTS delete_backup_sp_payment_stamping(timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_receivable_offset_providers(timestamp without time zone,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_rs_acc_trans_calc(character varying,integer,timestamp without time zone,timestamp without time zone,integer);
DROP FUNCTION IF EXISTS delete_backup_sp_save_update_mdm_id(uuid,character varying,character varying);
DROP FUNCTION IF EXISTS delete_backup_sp_stipend_calculation(integer,integer,date,date,date,date);
DROP FUNCTION IF EXISTS delete_backup_sp_stipend_calculation(integer,integer,timestamp without time zone,timestamp without time zone,timestamp without time zone,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_stipend_calculation(bigint,bigint,timestamp without time zone,timestamp without time zone,timestamp without time zone,timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_suspension_calculation(character,bigint,timestamp without time zone,timestamp without time zone,timestamp without time zone,timestamp without time zone,timestamp without time zone,timestamp without time zone,integer);
DROP FUNCTION IF EXISTS delete_backup_sp_under_over_gap(timestamp without time zone);
DROP FUNCTION IF EXISTS delete_backup_sp_void_placement_ar_tickler(timestamp without time zone,bigint);
DROP FUNCTION IF EXISTS delete_backup_updateallegation(uuid);
DROP FUNCTION IF EXISTS delete_backup_usersservicerequest(character varying,integer,integer);
DROP FUNCTION IF EXISTS delete_backup_addupdatecaseevaluation(json,uuid);
DROP FUNCTION IF EXISTS delete_backup_sp_under_over_pvt(timestamp without time zone);