ALTER TABLE tb_ncands_elements ADD COLUMN IF NOT EXISTS HPSCC VARCHAR(1);
ALTER TABLE tb_ncands_elements ADD COLUMN IF NOT EXISTS RTCRC VARCHAR(1);

ALTER TABLE ncands_childrisk ADD COLUMN IF NOT EXISTS HPSCC VARCHAR(1);
ALTER TABLE ncands_childrisk ADD COLUMN IF NOT EXISTS RTCRC VARCHAR(1);