const comprehensivefamilyassessment = 'COMPREHENSIVE FAMILY ASSESSMENT';
const comprehensivecaregiverassessment = 'COMPREHENSIVE CAREGIVER ASSESSMENT';
const comprehensivechildassessment = 'COMPREHENSIVE CHILD ASSESSMENT';
const childassessmentmodules = 'CHILD ASSESSMENT MODULES';
export class CansFConfig {
    public static StrengthAndNeedsList = [
        { key: 'A1', value: 'Parental-Caregiver collaboration', section: comprehensivefamilyassessment },
        { key: 'A2', value: 'Relations among sibling', section: comprehensivefamilyassessment  },
        { key: 'A3', value: 'Extended family relations', section: comprehensivefamilyassessment  },
        { key: 'A4', value: 'Family conflict', section: comprehensivefamilyassessment  },
        { key: 'A5', value: 'Family communication', section: comprehensivefamilyassessment  },
        { key: 'A6', value: 'Family role appropriateness', section: comprehensivefamilyassessment  },
        { key: 'A7', value: 'Safety', section: comprehensivefamilyassessment  },
        { key: 'A8', value: 'Social Resources', section: comprehensivefamilyassessment  },
        { key: 'A_11', value: '' },
        { key: 'A_12', value: '' },
        { key: 'B1', value: 'Financial Resources', section: comprehensivecaregiverassessment },
        { key: 'B2', value: 'Residential stability', section: comprehensivecaregiverassessment },
        { key: 'C1', value: 'Supervision', section: comprehensivecaregiverassessment },
        { key: 'C2', value: 'Involvement with care', section: comprehensivecaregiverassessment },
        { key: 'C3', value: 'Emotional responsiveness', section: comprehensivecaregiverassessment },
        { key: 'C4', value: 'Knowledge', section: comprehensivecaregiverassessment },
        { key: 'C5', value: 'Organization', section: comprehensivecaregiverassessment },
        { key: 'C6', value: 'Boundaries', section: comprehensivecaregiverassessment },
        { key: 'C7', value: 'Discipline', section: comprehensivecaregiverassessment },
        { key: 'C8', value: 'Post-traumatic Reactions', section: comprehensivecaregiverassessment },
        { key: 'C9', value: 'Physical Health', section: comprehensivecaregiverassessment },
        { key: 'C10', value: 'Mental health', section: comprehensivecaregiverassessment },
        { key: 'C11', value: 'Developmental', section: comprehensivecaregiverassessment },
        { key: 'C12', value: 'Substance use', section: comprehensivecaregiverassessment },
        { key: 'C13', value: 'Caregiver Criminal Behavior', section: comprehensivecaregiverassessment },
        { key: 'D1', value: 'Sexual Abuse', section: comprehensivecaregiverassessment },
        { key: 'D2', value: 'Physical Abuse', section: comprehensivecaregiverassessment },
        { key: 'D3', value: 'Emotional Abuse', section: comprehensivecaregiverassessment },
        { key: 'D4', value: 'Neglect', section: comprehensivecaregiverassessment },
        { key: 'D5', value: 'Medical Trauma' , section: comprehensivecaregiverassessment},
        { key: 'D6', value: 'Witness to Family Violence', section: comprehensivecaregiverassessment },
        { key: 'D7', value: 'Community Violence', section: comprehensivecaregiverassessment },
        { key: 'D8', value: 'School Violence', section: comprehensivecaregiverassessment },
        { key: 'D9', value: 'Natural/Man-made Disasters', section: comprehensivecaregiverassessment },
        { key: 'D10', value: 'War-Affected', section: comprehensivecaregiverassessment },
        { key: 'D11', value: 'Terrorism-Affected', section: comprehensivecaregiverassessment },
        { key: 'D12', value: 'Witness/Victim to Criminal Activity', section: comprehensivecaregiverassessment },
        { key: 'D13', value: 'Disruptions in Caregiving', section: comprehensivecaregiverassessment },
        { key: 'E1', value: 'Knowledge of family-child needs', section: comprehensivecaregiverassessment },
        { key: 'E2', value: 'Knowledge of service options', section: comprehensivecaregiverassessment },
        { key: 'E3', value: 'Knowledge of rights & responsibilities', section: comprehensivecaregiverassessment },
        { key: 'E4', value: 'Ability to listen', section: comprehensivecaregiverassessment },
        { key: 'E5', value: 'Ability to communicate', section: comprehensivecaregiverassessment },
        { key: 'E6', value: 'Natural supports', section: comprehensivecaregiverassessment },
        { key: 'F1', value: 'Satisfaction with youth’s living arrangement', section: comprehensivecaregiverassessment },
        { key: 'F2', value: 'Satisfaction with youth’s educational arrangement', section: comprehensivecaregiverassessment },
        { key: 'F3', value: 'Satisfaction with service arrangement', section: comprehensivecaregiverassessment },
        { key: 'G1', value: 'Relationship with biological mother', section: comprehensivechildassessment },
        { key: 'G2', value: 'Relationship with biological father', section: comprehensivechildassessment },
        { key: 'G3', value: 'Relationship with primary caregiver', section: comprehensivechildassessment },
        { key: 'G4', value: 'Relationship with other family adults', section: comprehensivechildassessment },
        { key: 'G5', value: 'Relationship with siblings', section: comprehensivechildassessment },
        { key: 'G6', value: 'Medical/Physical', section: comprehensivechildassessment },
        { key: 'G7', value: 'Intellectual (IQ only)' , section: comprehensivechildassessment},
        { key: 'G8', value: 'Autism Spectrum/PDD', section: comprehensivechildassessment },
        { key: 'G9', value: 'Speech Language Delay', section: comprehensivechildassessment },
        { key: 'G10', value: 'Social Functioning', section: comprehensivechildassessment },
        { key: 'G11', value: 'School Attendance', section: comprehensivechildassessment },
        { key: 'G12', value: 'School Achievement', section: comprehensivechildassessment },
        { key: 'G13', value: 'School Behavior', section: comprehensivechildassessment },
        { key: 'G14', value: 'Mental Health Needs', section: comprehensivechildassessment },
        { key: 'G15', value: 'Risk Behaviors', section: comprehensivechildassessment },
        { key: 'G16', value: 'Adjustment to Trauma', section: comprehensivechildassessment },
        { key: 'H1', value: 'Sexual Abuse', section: comprehensivechildassessment },
        { key: 'H2', value: 'Physical Abuse', section: comprehensivechildassessment },
        { key: 'H3', value: 'Emotional Abuse', section: comprehensivechildassessment },
        { key: 'H4', value: 'Neglect', section: comprehensivechildassessment },
        { key: 'H5', value: 'Medical Trauma', section: comprehensivechildassessment },
        { key: 'H6', value: 'Witness to Family Violence', section: comprehensivechildassessment },
        { key: 'H7', value: 'Community Violence', section: comprehensivechildassessment },
        { key: 'H8', value: 'School Violence', section: comprehensivechildassessment },
        { key: 'H9', value: 'Natural/Man-made Disasters', section: comprehensivechildassessment },
        { key: 'H10', value: 'War-Affected', section: comprehensivechildassessment },
        { key: 'H11', value: 'Terrorism-Affected', section: comprehensivechildassessment },
        { key: 'H12', value: 'Witness/Victim to Criminal Activity', section: comprehensivechildassessment },
        { key: 'H13', value: 'Disruptions in Caregiving', section: comprehensivechildassessment },
        { key: 'I1', value: 'Psychosis', section: childassessmentmodules },
        { key: 'I2', value: 'Attn Deficit / Impulse Control', section: childassessmentmodules },
        { key: 'I3', value: 'Depression / Mood Disorder', section: childassessmentmodules },
        { key: 'I4', value: 'Anxiety', section: childassessmentmodules },
        { key: 'I5', value: 'Oppositional Behavior', section: childassessmentmodules },
        { key: 'I6', value: 'Conduct / Antisocial Behavior', section: childassessmentmodules },
        { key: 'I7', value: 'Substance Abuse', section: childassessmentmodules },
        { key: 'I8', value: 'Eating Disturbance', section: childassessmentmodules },
        { key: 'I9', value: 'Anger Control', section: childassessmentmodules },
        { key: 'I10', value: 'Anger Control', section: childassessmentmodules },
        { key: 'J1', value: 'Suicide Risk', section: childassessmentmodules},
        { key: 'J2', value: 'Self-Injurious Behaviors', section: childassessmentmodules },
        { key: 'J3', value: 'Reckless Behaviors', section: childassessmentmodules },
        { key: 'J4', value: 'Danger to Others', section: childassessmentmodules },
        { key: 'J5', value: 'Sexual Aggression', section: childassessmentmodules },
        { key: 'J6', value: 'Sexually Reactive Behaviors', section: childassessmentmodules },
        { key: 'J7', value: 'Runaway', section: childassessmentmodules },
        { key: 'J8', value: 'Delinquent Behavior', section: childassessmentmodules },
        { key: 'J9', value: 'Fire-Setting', section: childassessmentmodules },
        { key: 'J10', value: 'Intentional Misbehavior', section: childassessmentmodules },
        { key: 'J11', value: 'Bullying', section: childassessmentmodules },
        { key: 'J12', value: 'Exploited', section: childassessmentmodules },
    ];
    public static CansFSectionList = [comprehensivefamilyassessment, comprehensivecaregiverassessment, comprehensivechildassessment,
        childassessmentmodules];
}
