 CREATE OR REPLACE FUNCTION public.bk_original_sp_tb_purchase_authorization(v_authorization_id bigint, v_status bigint, v_securityid character varying, v_costno numeric, v_provider_id integer, v_startdate date, v_enddate date, v_payment_method character varying, v_store_receipt_id character varying, v_type_1099_cd character varying, v_report_1099_sw character, v_client_account_id integer)
  RETURNS text                                                                                                                                                                                                                                                                                                                                                                                         
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                                     
 AS $function$                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                     
         /* One Parameter added decision - intakeserreqstatustypeid  */                                                                                                                                                                                                                                                                                                                              
         DECLARE                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                     
         v_paymentid integer;                                                                                                                                                                                                                                                                                                                                                                        
         v_fromroleid character varying;                                                                                                                                                                                                                                                                                                                                                             
         v_fromloadnumber character varying;                                                                                                                                                                                                                                                                                                                                                         
         v_toroleid character varying;                                                                                                                                                                                                                                                                                                                                                               
         v_securityuserid character varying;                                                                                                                                                                                                                                                                                                                                                         
         vl_pay_header_id BIGINT DEFAULT 0;                                                                                                                                                                                                                                                                                                                                                          
         vl_pay_status_id BIGINT DEFAULT 0;                                                                                                                                                                                                                                                                                                                                                          
         vl_pay_detail_id BIGINT DEFAULT 0;                                                                                                                                                                                                                                                                                                                                                          
         vl_tb_client_account BIGINT DEFAULT 0;                                                                                                                                                                                                                                                                                                                                                      
         v_fiscal_category_cd character varying;                                                                                                                                                                                                                                                                                                                                                     
         --v_client_account_id integer;                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                     
         begin                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                     
                 select fiscal_category_cd into v_fiscal_category_cd from tb_service_purchase_authorization where authorization_id=v_authorization_id;                                                                                                                                                                                                                                               
                 --select client_account_id into v_client_account_id from tb_client_account where account_type_cd='591' and client_id=v_client_id;                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                     
                 if(v_status = 39)                                                                                                                                                                                                                                                                                                                                                                   
         then                                                                                                                                                                                                                                                                                                                                                                                        
                 delete from routing where objectid = v_authorization_id :: character varying and  eventcode='PCAUTH' and  activeflag =0;                                                                                                                                                                                                                                                            
                 delete from routing where objectid = v_authorization_id :: character varying and  eventcode='PCAUTH' and  routingstatustypeid=62;                                                                                                                                                                                                                                                   
                 update routing set activeflag =0 where objectid = v_authorization_id :: character varying and  eventcode='PCAUTH' and routingstatustypeid = 62;                                                                                                                                                                                                                                     
         end if;                                                                                                                                                                                                                                                                                                                                                                                     
         if(v_status = 40)                                                                                                                                                                                                                                                                                                                                                                           
         then                                                                                                                                                                                                                                                                                                                                                                                        
         update TB_SERVICE_PURCHASE_AUTHORIZATION set sprvsr_approval_status_cd= 3047 , sprvsr_approval_dt=now(),ads_approval_status_cd= 3047 , ads_approval_dt=now() where authorization_id = v_authorization_id;                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                     
         if (v_fiscal_category_cd = '7503' or v_fiscal_category_cd = '7502')                                                                                                                                                                                                                                                                                                                         
         then                                                                                                                                                                                                                                                                                                                                                                                        
         --add amount to transation Source as ‘Obligated’ and Transaction type as ‘Ancillary Goods/Services Obligation’                                                                                                                                                                                                                                                                              
         --SELECT al_next_value from  sp_nextid ( 'sq_tb_client_account') into vl_tb_client_account;                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                     
         INSERT INTO public.tb_account_transaction                                                                                                                                                                                                                                                                                                                                                   
         (client_account_id ,transaction_type_cd, transaction_source_cd, benefit_start_dt, benefit_end_dt, transaction_amount_no, transaction_dt, credit_debit_sw,                                                                                                                                                                                                                                   
         notes_tx, create_ts,  create_user_id, update_ts, update_user_id, delete_sw,payment_detail_id, authorization_id)                                                                                                                                                                                                                                                                             
         select v_client_account_id,'5530', '5474', v_startdate, v_enddate , v_costno, now(), 'D','',now(),v_securityid,now(),v_securityid,'N',null,v_authorization_id ;                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                     
         update tb_client_account set available_balance_no=coalesce (available_balance_no ,0)  - v_costno where client_account_id = v_client_account_id;                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                     
         --update tb_service_purchase_authorization set client_account_id=v_client_account_id  where  authorization_id= v_authorization_id;                                                                                                                                                                                                                                                          
         if (v_fiscal_category_cd = '7502')                                                                                                                                                                                                                                                                                                                                                          
         then                                                                                                                                                                                                                                                                                                                                                                                        
                 update tb_client_account set obligated_for_anc=v_costno where client_account_id = v_client_account_id;                                                                                                                                                                                                                                                                              
         end if;                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                     
         end if;                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                     
         else if(v_status = 41)                                                                                                                                                                                                                                                                                                                                                                      
         then                                                                                                                                                                                                                                                                                                                                                                                        
         update TB_SERVICE_PURCHASE_AUTHORIZATION set  funding_approval_status_cd= 3047 , funding_approval_dt=now() where authorization_id=  v_authorization_id;                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                     
         else if(v_status = 42)                                                                                                                                                                                                                                                                                                                                                                      
         then                                                                                                                                                                                                                                                                                                                                                                                        
         update TB_SERVICE_PURCHASE_AUTHORIZATION set sprvsr_approval_status_cd= 3047 , sprvsr_approval_dt=now() where authorization_id= v_authorization_id;                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                     
         if (v_fiscal_category_cd = '7503' or v_fiscal_category_cd = '7502')                                                                                                                                                                                                                                                                                                                         
         then                                                                                                                                                                                                                                                                                                                                                                                        
         --add amount to transation Source as ‘Obligated’ and Transaction type as ‘Ancillary Goods/Services Obligation’                                                                                                                                                                                                                                                                              
         --SELECT al_next_value from  sp_nextid ( 'sq_tb_client_account') into vl_tb_client_account;                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                     
         INSERT INTO public.tb_account_transaction                                                                                                                                                                                                                                                                                                                                                   
         (client_account_id ,transaction_type_cd, transaction_source_cd, benefit_start_dt, benefit_end_dt, transaction_amount_no, transaction_dt, credit_debit_sw,                                                                                                                                                                                                                                   
         notes_tx, create_ts,  create_user_id, update_ts, update_user_id, delete_sw,payment_detail_id, authorization_id)                                                                                                                                                                                                                                                                             
         select v_client_account_id,'5530', '5474', v_startdate, v_enddate , v_costno, now(), 'D','',now(),v_securityid,now(),v_securityid,'N',null,v_authorization_id ;                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                     
         update tb_client_account set available_balance_no=coalesce (available_balance_no ,0)  - v_costno where client_account_id = v_client_account_id;                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                     
         --update tb_service_purchase_authorization set client_account_id=v_client_account_id  where  authorization_id= v_authorization_id;                                                                                                                                                                                                                                                          
         if (v_fiscal_category_cd = '7502')                                                                                                                                                                                                                                                                                                                                                          
         then                                                                                                                                                                                                                                                                                                                                                                                        
                 update tb_client_account set obligated_for_anc=v_costno where client_account_id = v_client_account_id;                                                                                                                                                                                                                                                                              
         end if;                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                     
         end if;                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                     
         else if(v_status = 44)                                                                                                                                                                                                                                                                                                                                                                      
         then                                                                                                                                                                                                                                                                                                                                                                                        
         update TB_SERVICE_PURCHASE_AUTHORIZATION set ads_approval_status_cd= 3047 , ads_approval_dt=now() where authorization_id= v_authorization_id;                                                                                                                                                                                                                                               
         else if(v_status = 43)                                                                                                                                                                                                                                                                                                                                                                      
         then                                                                                                                                                                                                                                                                                                                                                                                        
         update TB_SERVICE_PURCHASE_AUTHORIZATION set payment_approval_status_cd= 3047 , payment_approval_dt=now() where authorization_id= v_authorization_id;                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                     
         end  if;                                                                                                                                                                                                                                                                                                                                                                                    
         end  if;                                                                                                                                                                                                                                                                                                                                                                                    
         end  if;                                                                                                                                                                                                                                                                                                                                                                                    
         end  if;                                                                                                                                                                                                                                                                                                                                                                                    
         end if;                                                                                                                                                                                                                                                                                                                                                                                     
         if( v_status = 00)                                                                                                                                                                                                                                                                                                                                                                          
         then                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                     
         select ph.payment_id into v_paymentid from tb_payment_header ph where ph.authorization_id=v_authorization_id;                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                     
         update tb_payment_header set gross_amount_no = v_costno,payment_end_dt = v_enddate,payment_start_dt = v_startdate,payment_method_cd = v_payment_method                                                                                                                                                                                                                                      
         where payment_id=v_paymentid;                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                     
         --                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                     
         end if;                                                                                                                                                                                                                                                                                                                                                                                     
         if(v_status = 43 )                                                                                                                                                                                                                                                                                                                                                                          
         then                                                                                                                                                                                                                                                                                                                                                                                        
         --select * from tb_payment_header;                                                                                                                                                                                                                                                                                                                                                          
         SELECT al_next_value from  sp_nextid ( 'sq_payment_header') into vl_pay_header_id;                                                                                                                                                                                                                                                                                                          
         SELECT al_next_value from  sp_nextid ( 'sq_payment_detail') into vl_pay_detail_id;                                                                                                                                                                                                                                                                                                          
         SELECT al_next_value from  sp_nextid ( 'sq_payment_status') into vl_pay_status_id;                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                     
         INSERT INTO public.tb_payment_header                                                                                                                                                                                                                                                                                                                                                        
         (payment_id, provider_id, authorization_id, payment_dt, payment_type_cd, check_status_cd, payment_method_cd, gross_amount_no, offset_amount_no, manual_sw, approval_status_cd,                                                                                                                                                                                                              
          create_ts,  create_user_id, update_ts, update_user_id, delete_sw,store_receipt_id)                                                                                                                                                                                                                                                                                                         
         VALUES(vl_pay_header_id, v_provider_id, v_authorization_id , now() , '4', '', v_payment_method, v_costno, 0, '', '3047',now(),v_securityid,now(),v_securityid,'N',v_store_receipt_id )                                                                                                                                                                                                      
         RETURNING payment_id into v_paymentid;                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                     
                 INSERT INTO public.tb_payment_detail                                                                                                                                                                                                                                                                                                                                                
         (payment_detail_id, payment_id, county_cd, payment_amount_no, client_id, final_service_id, final_service_start_dt, final_service_end_dt, final_amount_no, create_ts, create_user_id, update_ts, update_user_id,case_id,type_1099_cd,report_1099_sw,final_fiscal_category_cd)                                                                                                                
         select vl_pay_detail_id,v_paymentid, tp.county_cd,v_costno,  tsl.client_id , tps.service_id, v_startdate, v_enddate, v_costno,now(),v_securityid,now(),v_securityid,tsl.case_id,v_type_1099_cd,v_report_1099_sw,tspa.fiscal_category_cd                                                                                                                                                     
         from tb_service_log tsl                                                                                                                                                                                                                                                                                                                                                                     
         join tb_provider_services tps on tps.provider_service_id=tsl.provider_service_id                                                                                                                                                                                                                                                                                                            
         join tb_provider tp on tps.provider_id=tp.provider_id                                                                                                                                                                                                                                                                                                                                       
         join tb_service_purchase_authorization tspa on tspa.service_log_id=tsl.service_log_id and tspa.delete_sw='N'                                                                                                                                                                                                                                                                                
         where  tspa.authorization_id= v_authorization_id limit 1                                                                                                                                                                                                                                                                                                                                    
         ;                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                     
         INSERT INTO public.tb_payment_status                                                                                                                                                                                                                                                                                                                                                        
         (payment_status_id, payment_status_cd, payment_status_dt, payment_id,  create_ts, create_user_id, update_ts, update_user_id)                                                                                                                                                                                                                                                                
         VALUES(vl_pay_status_id,'1634', now(), v_paymentid,now(),v_securityid,now(),v_securityid);                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                     
         update tb_service_purchase_authorization set final_amount_no=v_costno where authorization_id=v_authorization_id;                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                     
         update routing set remarks='Approved',routingstatustypeid = 43 where objectid=v_authorization_id :: character varying and eventcode='PCAUTH' and fromroleid='FNSFS' and toroleid='FNSFS' and activeflag=1;                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                     
         if (v_fiscal_category_cd = '7503' or v_fiscal_category_cd = '7502')                                                                                                                                                                                                                                                                                                                         
         then                                                                                                                                                                                                                                                                                                                                                                                        
         --credit amount --Source as ‘Obligation Liquidation’ and Transaction type as ‘Ancillary Goods/Services Obligation’                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                     
         --SELECT al_next_value from  sp_nextid ( 'sq_tb_client_account') into vl_tb_client_account;                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                     
         INSERT INTO public.tb_account_transaction                                                                                                                                                                                                                                                                                                                                                   
         (client_account_id, transaction_type_cd, transaction_source_cd, benefit_start_dt, benefit_end_dt, transaction_amount_no, transaction_dt, credit_debit_sw,                                                                                                                                                                                                                                   
         notes_tx, create_ts,  create_user_id, update_ts, update_user_id, delete_sw,payment_detail_id, authorization_id)                                                                                                                                                                                                                                                                             
         select v_client_account_id,'5530', '5475', v_startdate, v_enddate , (select transaction_amount_no from tb_account_transaction where authorization_id=v_authorization_id order by create_ts limit 1), now(), 'C','',now(),v_securityid,now(),v_securityid,'N',vl_pay_detail_id,v_authorization_id ;                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                     
         update tb_client_account set available_balance_no=coalesce (available_balance_no ,0)  + (select transaction_amount_no from tb_account_transaction where authorization_id=v_authorization_id order by create_ts limit 1) where client_account_id = v_client_account_id;                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                     
         --debit amount --Source as ‘Ancillary Payments’ and Transaction type as ‘Ancillary Goods/Services Disbursements’                                                                                                                                                                                                                                                                            
         --SELECT al_next_value from  sp_nextid ( 'sq_tb_client_account') into vl_tb_client_account;                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                     
         INSERT INTO public.tb_account_transaction                                                                                                                                                                                                                                                                                                                                                   
         (client_account_id, transaction_type_cd, transaction_source_cd, benefit_start_dt, benefit_end_dt, transaction_amount_no, transaction_dt, credit_debit_sw,                                                                                                                                                                                                                                   
         notes_tx, create_ts,  create_user_id, update_ts, update_user_id, delete_sw,payment_detail_id, authorization_id)                                                                                                                                                                                                                                                                             
         select v_client_account_id,'5531', '5476', v_startdate, v_enddate , v_costno, now(), 'D','',now(),v_securityid,now(),v_securityid,'N',vl_pay_detail_id,v_authorization_id ;                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                     
         update tb_client_account set  total_balance_no=coalesce (total_balance_no ,0)  - v_costno, available_balance_no=coalesce (available_balance_no ,0)  - v_costno                                                                                                                                                                                                                              
         where client_account_id = v_client_account_id;                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                     
         if (v_fiscal_category_cd = '7502')                                                                                                                                                                                                                                                                                                                                                          
         then                                                                                                                                                                                                                                                                                                                                                                                        
                 update tb_client_account set obligated_for_anc=coalesce (obligated_for_anc ,0) - coalesce((select cost_no from tb_service_purchase_authorization where authorization_id=v_authorization_id),0)                                                                                                                                                                                      
         where client_account_id = v_client_account_id;                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                     
                 update tb_commingled_account set total_balance_no = coalesce(total_balance_no,0) - v_costno where comm_account_id = (select comm_account_id from tb_client_account where client_account_id = v_client_account_id);                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                     
         end if;                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                     
         end if;                                                                                                                                                                                                                                                                                                                                                                                     
         end if;                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                     
         RETURN 'success';                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                     
         END;                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                     
         $function$                                                                                                                                                                                                                                                                                                                                                                                    

