 CREATE OR REPLACE FUNCTION public.medicalsubstanceabusereferal(i_evalutionid uuid)                                                                                                                                                                     
  RETURNS TABLE(youthname character varying, youthid character varying, folderid character varying, dob character varying, complaint_id character varying, guardian_name character varying, guardian_phone character varying, appdate character varying)
  LANGUAGE plpgsql                                                                                                                                                                                                                                      
 AS $function$                                                                                                                                                                                                                                        
    BEGIN                                                                                                                                                                                                                                             
         RETURN QUERY                                                                                                                                                                                                                                 
         (        select distinct                                                                                                                                                                                                                     
              CAST(p.firstname||' '||p.lastname as character varying)  as youthname,                                                                                                                                                                  
              CAST(p.cjamspid as character varying) as youthid,                                                                                                                                                                                       
              INTSR.intakenumber as folderid,                                                                                                                                                                                                         
              cast(to_char(p.dob,'MM/DD/YYYY') as character varying) as DOB,                                                                                                                                                                          
              complaintid as complaint_id,                                                                                                                                                                                                            
              CAST(COALESCE(                                                                                                                                                                                                                          
                         (select person.firstname||' '||person.lastname from person                                                                                                                                                                   
                                 where person.personid IN (select a.actorid                                                                                                                                                                           
                               from actor a join intakeservicerequestactor insa                                                                                                                                                                       
                               on a.actorid=insa.actorid and insa.activeflag=1                                                                                                                                                                        
                               join actorrelationship ar on ar.intakeservicerequestactorid=insa.intakeservicerequestactorid and ar.activeflag=1                                                                                                       
                               where  ar.relationshiptypekey='mother' and a.personid=p.personid)),                                                                                                                                                    
                                 (select person.firstname||' '||person.lastname from person                                                                                                                                                           
                                 where person.personid IN (select a.actorid                                                                                                                                                                           
                               from actor a join intakeservicerequestactor insa                                                                                                                                                                       
                               on a.actorid=insa.actorid and insa.activeflag=1                                                                                                                                                                        
                               join actorrelationship ar on ar.intakeservicerequestactorid=insa.intakeservicerequestactorid and ar.activeflag=1                                                                                                       
                               where  ar.relationshiptypekey='father' and a.personid=p.personid)),                                                                                                                                                    
                                 (select person.firstname||' '||person.lastname from person                                                                                                                                                           
                                 where person.personid IN (select a.actorid                                                                                                                                                                           
                               from actor a join intakeservicerequestactor insa                                                                                                                                                                       
                               on a.actorid=insa.actorid and insa.activeflag=1                                                                                                                                                                        
                               join actorrelationship ar on ar.intakeservicerequestactorid=insa.intakeservicerequestactorid and ar.activeflag=1                                                                                                       
                               where  ar.relationshiptypekey not in ('mother','father') and a.personid=p.personid))) as character varying)                                                                                                            
                         as guardian_name,                                                                                                                                                                                                            
                 CAST(COALESCE(                                                                                                                                                                                                                       
                         (select personphonenumber.phonenumber from personphonenumber                                                                                                                                                                 
                                 where personphonenumber.personid IN (select a.actorid                                                                                                                                                                
                               from actor a join intakeservicerequestactor insa                                                                                                                                                                       
                               on a.actorid=insa.actorid and insa.activeflag=1                                                                                                                                                                        
                               join actorrelationship ar on ar.intakeservicerequestactorid=insa.intakeservicerequestactorid and ar.activeflag=1                                                                                                       
                               where  ar.relationshiptypekey='mother' and a.personid=p.personid)),                                                                                                                                                    
                                 (select personphonenumber.phonenumber from personphonenumber                                                                                                                                                         
                                 where personphonenumber.personid IN (select a.actorid                                                                                                                                                                
                               from actor a join intakeservicerequestactor insa                                                                                                                                                                       
                               on a.actorid=insa.actorid and insa.activeflag=1                                                                                                                                                                        
                               join actorrelationship ar on ar.intakeservicerequestactorid=insa.intakeservicerequestactorid and ar.activeflag=1                                                                                                       
                               where  ar.relationshiptypekey='father' and a.personid=p.personid)),                                                                                                                                                    
                                 (select personphonenumber.phonenumber from personphonenumber                                                                                                                                                         
                                 where personphonenumber.personid IN (select a.actorid                                                                                                                                                                
                               from actor a join intakeservicerequestactor insa                                                                                                                                                                       
                               on a.actorid=insa.actorid and insa.activeflag=1                                                                                                                                                                        
                               join actorrelationship ar on ar.intakeservicerequestactorid=insa.intakeservicerequestactorid and ar.activeflag=1                                                                                                       
                               where  ar.relationshiptypekey not in ('mother','father') and a.personid=p.personid))) as character varying)                                                                                                            
                         as guardian_phone,                                                                                                                                                                                                           
              CAST(to_char(sap.appointmentdate,'MM/DD/YYYY') as character varying) as appdate                                                                                                                                                         
              from intakeservicerequestevaluation inve                                                                                                                                                                                                
              join intakeservicerequest INTSR on INTSR.intakenumber=inve.intakenumber and INTSR.activeflag=1                                                                                                                                          
              join intakeservicerequestactor INSRA on INSRA.intakeserviceid=INTSR.intakeserviceid and INSRA.activeflag=1                                                                                                                              
              join actor ACC on ACC.actorid=INSRA.actorid and ACC.activeflag=1 and ACC.actortype='Youth'                                                                                                                                              
              join person p on ACC.personid=p.personid and p.activeflag=1                                                                                                                                                                             
             left join servicerequestappointment sap on sap.intakeserviceid=INTSR.intakeserviceid and sap.activeflag=1                                                                                                                                
              where  inve.intakeservicerequestevaluationid = i_evalutionid limit 1) ;                                                                                                                                                                 
    end;                                                                                                                                                                                                                                              
   $function$                                                                                                                                                                                                                                           

