export class CaseWorkerUrlConfig {
    public static readonly countyListurl = 'admin/county/countylist';
    public static readonly gettypesurl = 'referencetype/gettypes';
    public static readonly gettypesfilterurl = 'referencetype/gettypes?filter';
    public static readonly getpicklisturl = 'tb_picklist_values/getpicklist';
    
    public static readonly EndPoint = {
        Dashboard: {
            DSDSActionDetailsUrl: 'servicerequestsearches/usersservicerequest',
            SupervisorReviewListUrl: 'servicerequestsearches/pendingreviewdalist',
            SupervisorClosedReviewListUrl: 'servicerequestsearches/closeddalist',
            MyIntakeListUrl: 'Intakedastagings/listintakeda',
            DsdsActionSummaryUrl: 'Intakeservicerequests/getdsdsactionsummarydtls',
            AddAuditLog: 'auditlog/addupdate',
            DsdsCaseStatusUrl: 'Intakeservicerequests/getrestrictedcasestatus',
            GetPrior: 'intakedastagings/getpriors',
            AdoptionActionSummary: 'Intakeservicerequests/getadoptionsummarydtls',
            MyExpungedCaseSearch: 'servicerequestsearches/myexpungedcasesearch?data'
        },
        UserCalendar: {
            CalendarEventsUrl: 'Intakeservicerequests/getcalendarevents',
            AddUpdateHealthPassportUrl: 'calendardetails/addupdate',
            CaseNumberHealthPassportUrl: 'calendardetails/getcasenumberhealthpassport',
            HealthAppointmentListUrl: 'calendardetails/list?filter',
            healthpassportcalendarUrl: 'calendardetails/getcalendareventList',
            HealthPassportCollateralUrl: 'calendardetails/healthpassportcollateral'
        },
        CaseFolders: {
            GetCaseList: 'servicerequestsearches/usersservicerequestfolders?data',
            PersonSeach: 'intakedastagings/personsearchfolders?filter',
            FolderList: 'intakedastagings/servicerequestsearchfolders?filter'
        },
        DSDSAction: {
            ReportSummary: {
                IncidentType: 'manage/Servicerequestincidenttype',
                PossibleCheckList: 'Intakeservicerequestillegalactivitytypes',
                Source: 'Intakeservicerequestinputtypes',
                ReportSummary: 'Intakeservicerequests/reportsummary/list/',
                ExpungedReportSummary: 'Intakeservicerequests/expungedreportsummary/list/',
                UpdateReportSummary: 'Intakeservicerequests/update'
            },
            Assessment: {
                ListAssessment: 'admin/assessment/list',
                InvolvedPersonList: 'People/getinvolvedperson?filter',
                RoutingInfoList: 'routing/getroutingdetails?filter',
                SupervisorList: 'Intakedastagings/getroutingusers',     // List of all supervisor to allow access to other sups
                AssessmentByName: 'admin/assessment/getassessmentdetailsbytitleheadertext',
                DeleteAssessment: 'admin/assessment/deleteassessment',
                Generateintakedocument: 'evaluationdocument/generateintakedocument'
            },
            CrossReference: {
                CrossReferenceUrl: 'Intakeservicerequestcrossreferences/getAllCrossReferencebySerReqid',
                SameRaReporterApUrl: 'Intakeservicerequests/getCrossRefByPersonType',
                CrossRefDaUrl: 'servicerequestsearches/getDetails',
                CrossRefProviderUrl: 'Intakeservicerequests/getCrossRefBySameProvider',
                CrossRefAddUrl: 'Intakeservicerequestcrossreferences',
                CrossReferenceReasonTypesUrl: 'Intakeservicerequestcrossreferencereasontypes/'
            },
            Disposition: {
                StatusUrl: 'Intakeservicerequestdispositioncodes/getstatuslist',
                DispositionUrl: 'daconfig/servicerequesttypeconfigdispositioncode/getdispositionlist',
                DispositionListUrl: 'Intakeservicerequestdispositioncodes/GetDispositon',
                DispositionAddUrl: 'Intakeservicerequestdispositioncodes/Add',
                DispositionValidation: 'Intakeservicerequestdispositioncodes/taskvalidationdisposition',
                ServiceCaseDispositionAddUrl: 'servicecasedisposition/add',
                AdoptionCaseDispositionAddUrl: 'adoptioncasedisposition/add',
                caseClosureDispositionUrl: 'servicecasedisposition/caseclosure',
                getcaseclosureUrl: 'servicecasedisposition/getcaseclosure',
                ebpcaseclosuredetailsUrl: 'Servicecasedisposition/ebpcaseclosuredetails'
            },
            InvestigationPlan: {
                PlanSummaryUrl: 'Investigations/GetTaskSummary',
                ActivityTaskUrl: 'Investigations/GetActivityTask',
                ActivityGoalUrl: 'Investigations/GetActivityGoal',
                AmmappingListUrl: 'admin/ammapping/list',
                GetActivitiesUrl: 'Activities',
                GetActvitiesAddUrl: 'Activities/add',
                GetActivitiesListUrl: 'Activities',
                GetActivityTaskUrl: 'Intake/activitytask',
                ActivityGoalTypeUrl: 'Intake/activitygoaltype',
                ActivityGoalStatusTypeUrl: 'Intake/activitygoalstatustype',
                InvestigationDispositionUrl: 'Intake/activitytasktypestatusdispositionmap/investigationdisposition/list',
                GoalDispositionUrl: 'Intake/amgoalstatus/investigationgoaldisposition/list',
                InvestigationActivitiesUrl: 'Intakeservicerequests/investigationactivities/list',
                ActivityAllTaskUrl: 'admin/activitytasktype',
                GoalUpdateUrl: 'Intake/activitygoal',
                MappingListUrl: 'admin/amactivity/mappinglist',
                ActivitySaveUrl: 'Intake/activitytask/add',
                AddTaskUrl: 'Intake/activitytask/addtask',
                ActivityTaskUpdateUrl: 'Intake/activitytask',
                UserProfilekUrl: 'admin/teammemberassignment/investigationplanassignto/list',
                TaskStatusTypeUrl: 'Intake/activitytaskstatustype'
            },
            InvolvedPerson: {
                InvolvedPersonListUrl: 'Intakeservicerequestactors/GetPersonList',
                InvolvedPersonListCWUrl: 'People/getpersondetailcw',
                InvolvedExpungedPersonListCWUrl: 'People/getexpungedpersondetailcw',
                YouthInvolvedPersonListUrl: 'Intakeservicerequests/prepopasmtprepostdiacharge',
                InvolvedPersonSearchUrl: 'globalpersonsearches/getEnhancedPersonSearchData',
                PriorListUrl: 'Intakeservicerequests/getdsdsactions',
                GenderTypeUrl: 'admin/gendertype',
                EthnicGroupTypeUrl: 'admin/ethnicgrouptype',
                MartialStatusTypeUrl: 'admin/maritalstatustype',
                RaceTypeUrl: 'admin/racetype',
                LanguageTypeUrl: 'admin/languagetype',
                IncomeTypeUrl: 'admin/incometype',
                PersonIdentifierTypeUrl: 'admin/personidentifiertype',
                PersonPhoneTypeUrl: 'admin/Personphonetype',
                PersonAddressUrl: 'admin/personaddresstype',
                StateListUrl: 'States',
                CountyListUrl: 'admin/county/list',
                CountyList: CaseWorkerUrlConfig.countyListurl,
                RelationshipTypesUrl: 'Relationshiptypes/list',
                getcollateral: 'People/getcollateral',
                ActorTypeUrl: 'admin/actortype',
                ZipCodeUrl: 'Regions',
                DeletePerson: 'Intakeservicerequestactors/deletewithintakeserreqnumber',
                Person: 'People/getwholepersondetials',
                Relationship: 'Relationshiptypes',
                ActorType: 'admin/actortype',
                SavePerson: 'People/add',
                UpdatePerson: 'People/personaddupdate',
                CheckPerson: 'People/checkpersonrole',
                UserActorTypeUrl: 'admin/actortype/listActortype',
                PersonAddressesUrl: 'Personaddresses',
                LivingArrangementTypeUrl: 'admin/livingarrangementtype',
                ReligionTypeUrl: 'admin/religiontype',
                EmailTypeUrl: 'admin/personemailtype',
                PhoneTypeUrl: 'admin/personphonetype',
                PersonList: 'People/getpersondetail',
                ZIPSearch: 'city/getstatedetails?filter',
                PersonsInAdoptionCase: 'adoptioncase/adoptioncaselist',
                UnkPersonList: 'Intakedastagings/getintakejsondata',
                updateUnkPersonList: 'Intakedastagings/updateintakejsondata',
                personservicetype: 'personservicetype',
                dentalspecialtytype: 'dentalspecialtytype',
                healthprofessiontype: 'healthprofessiontype',
                healthdomaintype: 'healthdomaintype',
                healthassessmenttype: 'healthassessmenttype',
                medicalconditiontype: 'medicalconditiontype',
                prescriptionreasontype: 'prescriptionreasontype',
                informationsourcetype: 'informationsourcetype',
                medicationtype: 'medicationtype',
                physicianspecialtytype: 'physicianspecialtytype/listphysicianspecialtytypes',
                pickListUrl: CaseWorkerUrlConfig.getpicklisturl,
                PersonHealthList: 'People/listpersonhealth',
                PersonDisability: 'People/getpersondisability',
                CpsIntakeReport: 'Intakedastagings/getsupervisorapprovalinfo',
                getpersonrelationbyintakeservice: 'servicecase/getpersonrelationbyintakeservice',
                HealthPassportAddUpdate: 'personhealthpassport/addupdate',
                HealthPassportList: 'personhealthpassport/list',
                HealthPassportDelete: 'personhealthpassport/delete',
                getpersondetailcw: 'People/getpersondetailcw',
                GetAllRelationshipByPersonURL: 'People/getallpersonrelationbyprovidedpersonid',
                GetPersonProgramArea: 'Personprogramareas/getpersonprogramarea'
            },
            Sdmcaseworker: {
                SdmvaluesUrl: 'Intakeservicerequestsdm/getintakeservicerequestsdm',
                SdmServiceCaseUrl: 'servicecase/getservicecasesdm',
                SdmCountyListUrl: CaseWorkerUrlConfig.countyListurl,
                PathwaySdmListUrl: 'Intakeservicerequestsdm/getintakeservicerequestsdm?filter',
                PathwaySdmCreateUrl: 'Intakeservicerequestsdm/createsdm',
                PathwayAutorizationUrl: 'Intakedastagings/pathwayapprove',
                Sdmtraffickingvalid: 'Intakeservicerequestsdm/getsdmtraffickingvalid',
                UpdateTraffickingUrl: 'Intakeservicerequestsdm/updatetrafficking',
                UpdatechildfatalityUrl: 'Intakeservicerequestsdm/updatechildfatality',
                SdmtraffickingaudittrailUrl: 'Intakeservicerequestsdm/getsdmtrafficking'
            },
            InvolvedEntity: {
                EntityGridUrl: 'Intakeservicerequestagencies/list',
                EntityRoleGridUrl: 'Intakeservicerequests/entityroletypes/list',
                AddEntityRoleUrl: 'Intakeservicerequestagencies/addagency',
                DeleteEntityUrl: 'Intakeservicerequestagencies',
                UpdateEntityRoleUrl: 'Intakeservicerequestagencies/update'
            },
            Allegation: {
                AllegationInvestigationUrl: 'Investigationallegationactors/getinvestigationallegationdetail',
                AllegationListUrl: 'Investigations/getinvestigationallegationlist',
                AllegationStatusDropdownUrl: 'Investigationallegationstatustypes',
                AllegationIndicatorUrl: 'investigationallegations/allegationList',
                AllegationAddUpdateUrl: 'Investigationallegations/',
                AllegationDeleteUrl: 'Investigationallegations/deleteallegation',
                LinkPersonUrl: 'Investigationallegations/actorList/',
                AddLinkPersonUrl: 'Investigationallegations/addActors/',
                IndicatorListUrl: 'admin/allegation/indicatorsList/',
                AllegationEditUrl: 'Investigationallegationactors/getAllegations/',
                AllegationUpdateUrl: 'Investigationallegationactors/updateAllegationActor',
                AllegationURL: 'admin/allegation/list'
            },
            Referrals: {
                IntakeServiceRequestReferralListUrl: 'Intake/Intakeservicerequestreferral',
                IntakeServiceRequestReferralUrl: 'Intake/Intakeservicerequestreferral/add',
                ReferredToTypeUrl: 'admin/referredtotype',
                ReasonListUrl: 'daconfig/servicerequesttypeconfig/reasonlist',
                DispositionListUrl: 'daconfig/servicerequesttypeconfig/dispositionlist'
            },
            Attachment: {
                UploadAttachmentUrl: 'attachments/uploadsFile',
                LargeFileUploadAttachmentUrl: 'attachments/edmsuploadmetadata',
                AttachmentGridUrl: 'Documentproperties/getcaseworkerattachments',
                FailedAttachmentGridUrl: 'Documentproperties/getUploadFailedAttachments?filter',
                GetFileUploadStatusUrl: 'Documentproperties/getFileUploadStatusUpdate?filter',
                PersonAttachmentGridUrl: 'Documentproperties/getpersonattachments',
                PersonAttachmentUpdate: 'Documentproperties/updatepersonattachments',
                AttachmentTypeUrl: 'Intake/attachmenttype/',
                AttachmentClassificationTypeUrl: 'Intake/attachmentclassificationtype/',
                SaveAttachmentUrl: 'Documentproperties/addcaseworkerattachment',
                UpdateFileUploadedUrl: 'attachments/updatefileuploaded',
                UpdateLargeFileUploadedUrl: 'attachments/updatelargefileuploaded',
                DeleteAttachmentUrl: 'Documentproperties/delete',
                DeleteLargeFileAttachmentUrl: 'Documentproperties/deletelargefile',
                Deletebydocumentpropertiesid: 'Documentproperties/deletebydocumentpropertiesid',
                serviceCaseAttachmentGridUrl: 'Documentproperties/getservicecaseattachments',
                CompaintFromCase: 'intakeservicerequestevaluations/getcomplaintlistbycasenumber?filter',
                downloadFileFromECMS: 'attachments/downloadFileFromECMS',
                downloadFileFromEDMS: 'attachments/downloadFileFromEDMS',
                downloadFileViewFromEDMS: 'attachments/downloadFileViewFromEDMS',
                UploadStatusUpdateAttachmentUrl: 'Documentproperties/fileuploadstatusupdate',
                UpdatePresignUrlAttachmentUrl: 'Documentproperties/updatepresignurlstatus',
                getcountygoliveconfig: 'admin/county/getcountygoliveconfig',
                getusercounty: 'admin/county/getusercounty?data='
            },
            Recording: {
                GetAllDaRecordingUrl: 'admin/progressnote/getalldarecording',
                GetCaseClosureRecordings: 'admin/progressnote/getcaseclosurerecordings',
                ListProgressSubTypeUrl: 'admin/progressnotetype/listprognotesubtypes',
                AddRecordingUrl: 'admin/progressnote/addRecordings',
                GetRecordingDetailUrl: 'admin/progressnote/getdarecordingdetails',
                UpdateRecordingUrl: 'admin/progressnote/updateRecordings',
                ListProgressTypeUrl: 'admin/progressnotetype/listprognotetypes',
                AddResourceConsultURL: 'intakeservicerequestconsultreview/addupdate',
                GetResourceConsultURL: 'intakeservicerequestconsultreview/listconsultreview',
                GetSelectTypeURL: 'consultreviewusertype/',
                DeleteResourceURL: 'intakeservicerequestconsultreview/consultreviewdelete',
                DeleteResourceUserURL: 'intakeservicerequestconsultreview/consultreviewconfigdelete',
                ContactNotesList: 'admin/progressnote/getallcontactnoteslist',
                AddUpdateNotes: 'admin/progressnote/addupdatecontactnotes',
                AddComments: 'admin/progressnotedetail',
                AddDetailedAudit: 'admin/progressnote/auditcontactnotes',
                AddQualityCare: 'admin/progressnote/updateQualityCare',
                ValidateContactNotes: 'admin/progressnote/validatecontactnote',
                addsenuntimelycompletionreason: 'Intakeservicerequests/addsenuntimelycompletionreason',
                GetProgressNoteMiOptions:CaseWorkerUrlConfig.gettypesurl,
                GetHolidaysURL: 'admin/progressnote/getholidays'
            },
            Affidavit: {
                AddUpdate: "servicecaseaffidavit/addupdate",
                List: "servicecaseaffidavit/list",
                Delete: "servicecaseaffidavit/delete",
            },
            Intended: {
                AddUpdate: "serviceintendedaction/addupdate",
                List: "serviceintendedaction/list",
                Delete: "serviceintendedaction/delete",
                download: "evaluationdocument/generateintakedocument",
                details: "serviceintendedaction/getlistsupervisordtls"
            },
            Form1080a: {
                AddUpdate: "form1080a/addupdate/",
                List: "form1080a/list",
                Delete: "form1080a/delete",
                GetFormData: 'form1080a/getForm1080a'
            },
            Form1080b: {
                AddUpdate: "form1080b/addupdate",
                List: "form1080b/list",
                Delete: "form1080b/delete",
                GetFormData: 'form1080b/getForm1080b'
            },
            Form1080c: {
                AddUpdate: 'form1080c/addupdate',
                GetFormData: 'form1080c/getForm1080c',
                List: 'form1080c/list',
                Delete: 'form1080c/delete'
            },
            ChildRemoval: {
                GetRemovalReason: 'removalreasontype',
                InvolvedPersonList: 'People/getinvolvedperson',
                getScheduleH: 'People/getScheduleH',
                GetState: 'States',
                GetSentTo: 'admin/agencytype',
                GetFamilyFindingsHistory: 'intakeservreqchildremoval/getfamilyfindingshistory',
                InitFamilyFindings: 'intakeservreqchildremoval/initfamilyfindings',
                GetFamilyFindings: 'intakeservreqchildremoval/getfamilyfindings',
                GetFamilyFindingRelationships: 'intakeservreqchildremoval/getbinticlientrelations',
                SyncFamilyFindingRelationship: 'intakeservreqchildremoval/syncbinticlientrelation',
                GetChildRemovalList: 'intakeservreqchildremoval/getchildremoval',
                GetChildRemovalListForDisorderPopUpCheck: 'intakeservreqchildremoval/getchildremovalDetailsForDisorderCheck',
                ServiceCaseValidate: 'intakeservreqchildremoval/servicecasevalidation',
                CreateCaseUrl: 'servicecase/createservicecase',
                SubmitChildRemoval: 'intakeservreqchildremoval/add',
                Notification: 'intakeservreqchildremoval/removalnotificationmail',
                GetRemovalNotificationRoles: 'intakeservreqchildremoval/removalnotification',
                routingUserUrl: 'routing/getldssusers',
                EmailSchoolNotification: 'Usernotifications/notificationmail',
                FourEChildRemoval: 'Intakeservreqchildremoval/addlegalstatus',
                GetTypes: CaseWorkerUrlConfig.gettypesurl,
                GetAllTypesList: 'referencetype/allvaluesbyreferenceid',
                approveOrReject: 'routing/routingupdate'
            },
            Court: {
                PetitionDetailsSave: 'intakeservicerequestpetition/add',
                PetitionCinaDetailsSave: 'cinapetition/addcinapetition',
                PetitionDetailslist: 'intakeservicerequestpetition',
                PetitionCinaDetailList: 'cinapetition/list?filter',
                PetitionCinaWitnessList: 'petitionwitness/list?filter',
                PetitionApgtDetailsSave: 'apgtpetition/addapgtpetition',
                PetitionApgtDetailList: 'apgtpetition/list?filter',
                PetitionApgtDelete: 'apgtpetition/delete',    
                getFinanceAsset: 'People/getfinanceasset',
                getFinanceIncomeList: 'People/financeincomelist',
                HearingTypeUrl: 'hearingtype',
                CourtActionTypeUrl: 'courtactiontype',
                FindingTypeUrl: 'findingtype',
                ConditionTypeUrl: 'conditiontype',
                CourtOrderTypeUrl: 'courtordertype',
                AdjudicatedDecisionTypeUrl: 'adjudicateddecisiontype',
                OffenceCategoryListUrl: 'OffenceCategoryListUrl',
                CourtActionAddUrl: 'intakeservicerequestcourtaction/add',
                HearingStatusTypeUrl: 'hearingstatustype',
                PetitionTypeUrl: 'petitiontype',
                PetitionListUrl: 'intakeservicerequestpetition/getpetitiondetails',
                OutComeURL: CaseWorkerUrlConfig.gettypesurl,
                HearingAddUrl: 'intakeservicerequestcourthearing/addhearing',
                HearingUpdateUrl: 'intakeservicerequestcourthearing/updatehearing',
                getHearingUrl: 'intakeservicerequestcourthearing/gethearingdetails',
                getCourtActions: 'intakeservicerequestcourtaction/getcourtaction',
                deleteHearing: 'intakeservicerequestcourthearing/deletehearing',
                hearingoutComeUrl: CaseWorkerUrlConfig.gettypesurl,
                GetCourtOrderUrl: 'intakeservreqcourtorder/getcourtorder',
                Gethealthcaredecisionmakerinformation: 'intakeservreqcourtorder/gethealthcaredecisionmakerinformation',
                ChecklistUrl: 'checklist',
                checklistdisplayorder: 'checklist/checklistdisplayorder',
                CourtOrderSaveUrl: 'intakeservreqcourtorder/add',
                Addhealthcaredecisionmakerinformation: 'intakeservreqcourtorder/addhealthcaredecisionmakerinformation',
                AggravatedcircumstancesUrl: CaseWorkerUrlConfig.gettypesurl,
                ChildpermanencyplanUrl: CaseWorkerUrlConfig.gettypesurl,
            },
            MaltreatmentInformation: {
                MaltreatementTypeUrl: 'investigationallegations/allegationList',
                GetMaltreatementTypeUrl: 'admin/allegation/allegationWOIndicatorsList',
                IncidentLocationDropDown: 'incidentlocationtype/',
                MaltreatorUrl: 'admin/allegation/indicatorsList/',
                InjuryTypeUrl: 'injurytype',
                MaltreatmentCharactersticsTypeUrl: 'maltreatmentcharactersticstype',
                injuryCharactersticsTypeUrl: 'injurycharactersticstype',
                JurisdictionListUrl: CaseWorkerUrlConfig.countyListurl,
                HouseHoldTypeUrl: 'householdtype',
                MaltreatmentInformation: 'Investigationallegations/getinvestigationallegation',
                AddMaltreatmentINformationUrl: 'investigationmaltreatment/addupdate',
                providermaltreatmenttypeUrl: 'providermaltreatmenttype/',
                attorneyaddress: 'attorneyaddress/getaddress',
                InvestigationContributingFactor: 'Investigationallegations/getInvestigationContributingFactor',
            },
            ServiceAgreement: { // @TM: --- Service Agreement for In-Home Services
                GetServiceAgreementUrl: 'serviceagreement/list?filter',
                AddServiceAgreementUrl: 'serviceagreement/add',
            },
            ServicePlan: {
                GoalUrl: 'serviceplan/goal',
                AddActivityUrl: 'serviceplan/activity',
                ActivityUrl: 'serviceplan/activity/list',
                AddServicePlanUrl: 'serviceplan/add',
                DelectServicePlanUrl: 'serviceplan/activity',
                InvolvedPersonUrl: 'People/getpersondetail',
                ServiceLog: 'serviceplan/servicelog',
                GetCategoryProgramNames: 'servicepan/serviceslog/getprogramsname',
                ClientprogramServices: 'TbServices/agencyservices',
                ClientProgramName: 'TbAgencyProgramAreas/agencyProvidedServices',
                agencyServiceLog: 'serviceLogs/list',
                servicelogmultipelist: 'serviceLogs/servicelogmultipelist',
                Frequency: 'Picklistvalues/frequencyList',
                DelectServiceLog: 'serviceLogs/deleteVendorService',
                Duration: 'Picklistvalues/durationList',
                VendorServices: 'TbServices/vendorservices',
                AllVendorServices: 'TbServices/allvendorservices',
                VendorServiceSave: 'serviceLogs/vendorSaveServiceLog',
                // AllVendorServices : 'TbServices/allvendorservices',
                vendorServiceLog: 'serviceLogs/getVendorList',
                multivendorServiceLog: 'Intakeservicerequests/getmultiplevendorlist',
                fiscalCodes: 'fiscalCodes/agencyservices',
                VendorServiceSearch: 'providerListSearches/values',
                ServiceEndReason: 'Picklistvalues/serviceEndReason',
                ReasonServiceNotReceived: 'Picklistvalues/reasonServiceNotReceiveds',
                PurchaseAuthorizationSave: 'purchaseAuthorizations/purchaseAuthorize',
                PurchaseAuthorizationGet: 'purchaseAuthorizations/getPurchaseAuthorize',
                ApprovePurchaseAuthorization: 'tb_service_purchase_authorization/updateservicepurchaseauthorization',
                Getservicecaseplan: 'serviceplan/getservicecaseplan',
                ServiceLogApproval: 'purchaseAuthorizations/routingPurchaseAuthorization',
                ServicePlanReviewCase: 'serviceplan/getserviceplandetails',
                PurchaseAuthorizationReject: 'tb_account_transaction/rejectbyAuthId/',
                PurchaseAuthorizationReturn: 'tb_account_transaction/returnbyAuthId/',
                ClientEligibility: 'tb_account_transaction/getClientEligibilityStatus?filter',
                Listbyallrelation: 'serviceplan/listbyallrelation?filter',
                Snapshothist: 'snapshothist?filter'
            },
            AsServicePlan: {
                GoalUrl: 'serviceplan/goal/list',
                AsAddActivityUrl: 'servicetype/list',
                AsAddSubService: CaseWorkerUrlConfig.gettypesurl,
                VendorServiceSearch: 'providerListSearches/values',
                ServiceEndReason: 'Picklistvalues/serviceEndReason',
                ReasonServiceNotReceived: 'Picklistvalues/reasonServiceNotReceiveds',
                PurchaseAuthorizationSave: 'purchaseAuthorizations/purchaseAuthorize',
                PurchaseAuthorizationGet: 'purchaseAuthorizations/getPurchaseAuthorize'
            },
            ArCaseClosure: {
                CaseClosureListUrl: 'caseclosureparticipant/getcaseclosurelist',
                CaseClosureServiceTypeUrl: 'closuretype',
                CaseClosureServiceSubTypeUrl: 'closuresubtype',
                CaseClosureStatusAddUpdateUrl: 'caseclosuresummary/addupdate',
                SummaryValidationUrl: 'caseclosuresummary/validatecaseclosurelist',
                InvolvedPersonListUrl: 'People/getinvolvedperson'
            },
            appointment: {
                intakeWorkerList: 'Intakedastagings/getIntakeUsers',
                addupdateAppointment: 'servicerequestappointment/addupdate',
                getAppointmentHistory: 'servicerequestappointment/appointmentlisthistory',
                getAppointmentList: 'servicerequestappointment/appointmentlisthistory',
                deleteAppointment: 'servicerequestappointment/appointmentdelete'
            },
            Placement: {
                PlacementAddUrl: 'placement/add',
                PlacementListUrl: 'placement/list',
                childcharacteristicUrl: 'childcharacteristictype',
                PlacementSearch: 'placement/search',
                PlacementSearchAdd: 'placement/addjs',
                PlacementSearchAddFromIntake: 'placement/addintakeplacement',
                PlacementUpdate: 'placement/updateplacement',
                PlacementLRAddUpdate: 'placementleavereturn/addupdate',
                PlacementLRList: 'placementleavereturn/list',
                PlacementReleaseAddUpdate: 'placementrelease/addvalues',
                PlacementListByPerson: 'placement/getplacementbyperson',
                PlacementFPrimCountry: 'placement/fprimcountry',
                PermanencyPlan: {
                    PermanencyPlanList: 'permanencyplan/list',
                    PermanencyPlanAdd: 'permanencyplan/add',
                    PermanancyPlanTypeSubType: 'Permanencyplantypes/list'
                },
                Adoption: {
                    TprRecommendationList: 'tprrecommendation/gettprrecommendation',
                    TprRecommendationAdd: 'tprrecommendation/add',
                    LegalCustodyAddUpdate: 'legalcustody/addupdate',
                    LegalCustodyList: 'legalcustody/getlegalcustody',
                    TPRDetail: 'tprdetails/gettprdetails',
                    SingleParentCheckInfo: 'tprdetails/singleparentcheckinfo',
                    AdoptionEffortAdd: 'adoptionplanning/addupdate',
                    AdoptionEffortList: 'adoptionplanning/getadoptionplanning',
                    AdoptionEmotionalTieList: 'adoptionemotional/list',
                    AdoptionEmotionalTieAdd: 'adoptionemotional/addupdate',
                    GetBioClientID: 'adoptionagreement/getbioclientid'
                },
                GetReasonTypes: CaseWorkerUrlConfig.gettypesfilterurl,
                GetPlacementByServiceCase: 'placement/getplacementbyservicecase'

            },
            Gap: {
                AnnualReview: 'gapannualreview/list',
                AddEditReview: 'gapannualreview/addupdate'
            },
            Fim: {
                MeetingTypesUrl: 'Meetingtypes/',
                FamilyMeetingTypesUrl: 'Familymeetingtypes/list',
                ParticipantTypesUrl: 'Participanttypes/list',
                AddParticipantUrl: 'Meetingrecordings/addupdate',
                FimListUrl: 'Meetingrecordings/getfimdetails'
            },
            legalActionHistory: {
                hearingType: 'hearingtype?filter={"nolimit":true}'
            },
            entities: {
                RegionListUrl: 'admin/region/list',
                AgencyCategoryUrl: 'admin/agencycategory',
                EntityRoletypeUrl: 'admin/agencyroletype',
                InvolvedEnititesSearchUrl: 'gloabalagencysearches/getAgencySearchData'
            },
            MedicationPsychotopic: {
                getcountygoliveconfig: 'admin/county/getcountygoliveconfig',
                getusercounty: 'admin/county/getusercounty?data=',
                auditTrailhcdm: 'personmedicalcondition/auditTrailhcdm'
            },
            Transport: {
                TransportationList: 'persontransportation/list?filter',
                FromList: 'locationfromtype?filter',
                ToList: 'locationtotype?filter',
                AddTransport: 'persontransportation/add',
                DeleteTransport: 'persontransportation/deletetransport',
                TransportationById: 'persontransportation/getpersontransportationbyId?filter',
                UpdateTransport: 'persontransportation/updatetransport/'
            },
            kinship: {
                attachmentUrl: 'Documentproperties/getcaseworkerattachments/',
                checklistUrl: 'admin/amtask',
                AddKinshipUrl: 'kinshipcare/addupdate',
                KinshipListUrl: 'kinshipcare/list',
                KinshipContactNote: 'admin/progressnote/kinshipcontactnote',
            },
            as_maltreatment: {
                getintakejsondata: 'Intakedastagings/getintakejsondata',
                AllegationsIndicaorUrl: 'admin/allegation/getallegationsandindicaors'
            },
            courtactions: {
                CourtActionsList: 'intakeservicerequestpetition/listadjdispdetails?filter'
            },
            foster_care: {
                childCharacteristicsUrl: 'tb_picklist_values/getpicklist?filter',
                fcProviderSearchUrl: 'tb_provider/fostercareprovidersearch?filter',
                otherLocalDeptmntTypeUrl: 'tb_picklist_values/getpicklist?filter',
                bundledPlcmntServicesTypeUrl: 'tb_services/getbundledplacementserviceslist?filter',
                placementStrTypeUrl: 'tb_services/getplacementstructureslist?filter',
                comarlisteUrl: 'tb_services/getcomarlist?filter',
                saveReferalUrl: 'tb_placement/fostercarereferaladd',
                fostercarereferallistUrl: 'tb_placement/fostercarereferallist',
                addPlacementRequestUrl: 'tb_placement/addplacement',
                approvePlacementRequestUrl: 'tb_placement/approverejectedplacement',
                rejectPlacementRequestUrl: 'tb_placement/approverejectedplacement',
                removeplacement: 'tb_placement/exitplacement',
                placementexitapproval: 'tb_placement/placementexit',
                approveOrReject: 'routing/routingupdate',
                ExitTypeUrl: CaseWorkerUrlConfig.getpicklisturl,
                PlChildHistoryListUrl: 'tb_placement/placementchildhistorylist',
                ExitReasonTypeUrl: 'tb_picklist_values/getexitreasonlist',
                cpaHomePlacementLHistoryUrl: 'tb_placement/cpahomeplacementlist',
                cpaHomeProviderNameUrl: 'tb_provider/getcpahomeprovidername',
                addcpaHomeplacementUrl: 'tb_placement_cpa_homes/cpahomeplacementadd',
                childPaymentListUrl: 'finance/getAccountsPayableInfo',
                mytaskdashboard: 'titleive/ive/mytaskdashboard'
            },
            ActionLetter: {
                GetProgramType: CaseWorkerUrlConfig.gettypesfilterurl,
                GetActionType: CaseWorkerUrlConfig.gettypesfilterurl,
                GetProgramList: 'actionletterprogramconfig/getprogramheaderconfig?filter',
                SaveCitation: 'oasactionletter/add',
                ListCitation: 'oasactionletter/list?filter'
            },
            AdultScreenTool: {
                listAST: 'intakeservreqadultscreentool/list?filter'
            },
            AdultReferral: {
                ServiceTypeUrl: 'Intakeservicerequestpurposes/list',
                ServiceSubTypeUrl: 'admin/intakeservicerequesttype/',
                AssessmentUrl: 'Intake/intakeservicerequestreferral/getreferalassessmentlist',
                supervisorsListUrl: 'Intake/intakeservicerequestreferral/getsupervisorsbycounty',
                approveIntakeUrl: 'Intake/intakeservicerequestreferral/countybasednewcase'
            },
            Assignment: {
                Reassigncase: 'servicecase/reassigncase'
            },
            IntakeTransfer: {
                AddUpdate: 'intaketransfers/addupdate',
                GetByIntakeNumber: 'intaketransfers/getbyintakenumber',
                GetSupervisorByCountyId: 'intaketransfers/getsupervisorbycountyid'
            },
            AncillaryServices: {
                AddUpdate: 'ancillaryservices/addupdate',
                list: 'ancillaryservices/list'
            },
            PsychotropicPrescriptionReview: {
                Getcase: 'psychotropicmedications/getcasenumberpsychotropic',
                GetList: 'psychotropicmedications/getpsychotropiclist',
                GetOtherMedicalList: 'psychotropicmedications/personmedicallist',
                GetHistory: 'psychotropicmedications/getpsychotropichistory',
                Getcurrentmedications: 'psychotropicmedications/getothercurrentmedication',
                GetPsychotropicnotificationrecord: 'psychotropicmedications/getpsychotropic',
                Getsupervisorviewrecord: 'psychotropicmedicationreport/getpsychotropiclistbyrequestid',
                GetEditUserDetails: 'psychotropicmedications/getUserdetailsById'
            },
               Consent: {
                GetAssignments: 'Caseassignments/getworkload?filter'
            },
            PsychotropicPrescriptionReport: {
                GetList: 'psychotropicmedicationreport/getpsychotropicmedicationreportdetails',
                GetAveragetimeList: 'psychotropicmedicationreport/getpsychotropiccalculateavgtime',
                GetHolidaylist: 'psychotropicmedicationreport/getholidayslist',
                GetCaseworker: 'psychotropicmedicationreport/getPsychotropiccwlistbycounty'
            },
            Beacon: {
                Getbeaconrequestedbylist: '/beacon/getbeaconrequestedbylist?filter',
                Getbeaconrequestdetails: '/beacon/getbeaconrequestdetails?filter',
                Beaconcasesearch: '/beacon/beaconcasesearch?filter',
                Beaconssnsearch: '/beacon/beaconssnsearch?filter',
                Getbeaconrequesthistory: '/beacon/getbeaconrequesthistory?filter',
                Getbeaconrealtimedata: 'beaconrealtimedata/getbeaconrealtimedata?filter',
                Getbeaconaudit: '/beacon/getbeaconaudit'
            },
            AssessmentYouth: {
                Getchilddatqyitasssessment: "admin/assessment/getchilddatqyitasssessment?filter"
            }


        }
    };
}