const countylisturl = 'admin/county/countylist';
const listprognotetypesurl = 'admin/progressnotetype/listprognotetypes';
const listprognotesubtypesurl = 'admin/progressnotetype/listprognotesubtypes';
const addrecordingsurl = 'admin/progressnote/addRecordings';
const getalldarecordingurl = 'admin/progressnote/getalldarecording';
// Referral endpoints
export class ReferralUrlConfig {
    public static EndPoint = {
        Referral: {
            getProviderReferralUrl: 'providerreferral/getproviderreferral',
            getNextReferralNumberUrl: `Nextnumbers/getNextNumber?apptype=providerreferral`,
            listprogramnamesUrl:'providerreferral/listprogramnames',
            StateListUrl: 'States'
        }
    }
}




// To maintain intake functionality
export class NewUrlConfig {
    public static EndPoint = {
        Intake: {
            GetNextNumberUrl: `Nextnumbers/getNextNumber?apptype=IntakeNumber`,
            ServiceRequestIncidentTypeUrl: `manage/Servicerequestincidenttype?filter={"where" :{"activeflag":1}}`,
            IntakeServiceRequestIllegalActivityTypeUrl: `Intakeservicerequestillegalactivitytypes?filter={"where" :{"activeflag":1}}`,
            IntakeServiceRequestInputTypeUrl: `Intakeservicerequestinputtypes/list?filter={"where" :{"activeflag":1},"order" : "description"}`,
            GlobalPersonSearchUrl: 'globalpersonsearches/getPersonSearchData',
            InvolvedEnititesSearchUrl: 'gloabalagencysearches/getAgencySearchData',
            AgencyCategoryUrl: 'admin/agencycategory',
            CountryListUrl: countylisturl,
            StateListUrl: 'States',
            MaritalStatusUrl: 'admin/maritalstatustype',
            ReligionTypeUrl: 'admin/religiontype',
            RegionListUrl: 'admin/region/list',
            NextnumbersUrl: 'Nextnumbers/getNextNumber?apptype=servicerequestauthorizationnumber',
            DADispositionUrl: 'admin/intakeservicerequesttype/listdadisposition',
            DAStatusUrl: 'admin/intakeservicerequesttype/listdastatus',
            AllegationsIndicaorUrl: 'admin/allegation/getallegationsandindicaors',
            DATypeUrl: 'admin/intakeservicerequesttype',
            EthnicGroupTypeUrl: 'admin/ethnicgrouptype',
            GenderTypeUrl: 'admin/gendertype',
            LivingArrangementTypeUrl: 'admin/livingarrangementtype',
            LanguageTypeUrl: 'admin/languagetype',
            RaceTypeUrl: 'admin/racetype',
            RelationshipTypesUrl: 'Relationshiptypes',
            ActorTypeUrl: 'admin/actortype',
            UserActorTypeUrl: 'admin/actortype/listActortype',
            ActorTypeListUrl: 'admin/actortype/listactortype',
            EntitesTypeUrl: 'admin/agencytype',
            EntityRoletypeUrl: 'admin/agencyroletype',
            IntakeserviceRequestCrossReferenceReasonTypesUrl: 'Intakeservicerequestcrossreferencereasontypes',
            ServiceRequestSearchesUrl: 'servicerequestsearches/getDetails',
            SameRACrossRefDAsUrl: 'GetSameRACrossRefDAs/getDetails',
            ProgressNoteURL: listprognotetypesurl,
            ProgressNoteSubTypeUrl: listprognotesubtypesurl,
            IntakeServiceRouteDAUrl: 'Intakeservicerequests/routeda',
            SendtoSupervisorreviewUrl: 'Intakedastagings/reviewIntake',
            PersonRelativeUrl: 'personrelations',
            PersonAddressesUrl: 'personaddresses',
            TemporarySavedIntakeUrl: 'Intakedastagings/listdadetails',
            CompleteIntakeUrl: 'Intakedastagings/completeIntake',
            IntakeServiceRequestsUrl: 'Intakeservicerequests/getdsdsactions',
            MyIntakeListUrl: 'Intakedastagings/listintakeda',
            PersonUrl: 'People/getwholepersondetials',
            GetIntakeAssessmentUrl: 'admin/assessmenttemplate/getlist',
            ValidateAddressUrl: 'People/validateaddress',
            CommunicationUrl: 'Intakeservicerequestinputsources?filter={"order":"description"}',
            SuggestAddressUrl: 'People/suggestaddress',
            IntakePurposes: 'Intakeservicerequestpurposes',
            IntakeAgencies: 'admin/teamtype/list?filter={"order":"description"}',
            Intakeservs: 'Intakeservs',
            ResourceTooltipUrl: 'Resources/resourcelist',
            AttachmentGridUrl: 'Documentproperties/getintakeattachments',
            SaveAttachmentUrl: 'Documentproperties/addintakeattchment',
            DeleteAttachmentUrl: 'Documentproperties/delete',
            PersonInvolvedManageUrl: 'People/intakeperson',
            AddressTypeUrl: 'admin/personaddresstype',
            MDCountryListUrl: countylisturl,
            OffenceCategoryListUrl: 'offensecategories',
            PhoneTypeUrl: 'admin/personphonetype',
            EmailTypeUrl: 'admin/personemailtype', 
            saveIntakeUrl: 'providerreferral/getproviderreferral',
            //saveIntakeUrl: 'Intakedastagings/listdadetails',
            SupervisorApprovalUrl: 'Intakedastagings/approveIntake',
            PriorAuditLogUrl: 'Intakeservicerequests/priors',
            EducationTypeUrl: 'educationtype',
            GradeTypeUrl: 'gradetype',
            TestingTypeUrl: 'testingtype',
            ListProgressTypeUrl: listprognotetypesurl,
            ContactRoleTypeUrl: 'Contactroletypes',
            ContactSubTypeUrl: listprognotesubtypesurl,
            AddContcatTypeUrl: addrecordingsurl,
            GetAllNotesUrl: getalldarecordingurl,
            SdmCountyListUrl : countylisturl,
            allegationsUrl: 'admin/allegation/getallegationsindicators',
            allegationsSubTypes : 'admin/allegation/getcasesubtype',
            EvaluationSourceTypeList : 'evaluationsourcetypes',
            EvaluationAgencyTypeList : 'evaluationsourceagencies',
            EvaluationSourceSearchList : 'evaluationsources/list',
            validateComplaintId: 'Intakeservicerequestevaluations/isComplaintIdExists',
            intakeWorkerList: 'Intakedastagings/getIntakeUsers',
            hearingType: 'hearingtype?filter={"nolimit":true}',
            conditionType: 'conditiontype?filter={"nolimit":true}',
            courtActionType: 'courtactiontype?filter={"nolimit":true}',
            findingType: 'findingtype?filter={"nolimit":true}',
            courtOrderType: 'courtordertype?filter={"nolimit":true}',
            adjuctedDecisions: 'adjudicateddecisiontype?filter={"nolimit":true}',
            addpetition: 'intakeservicerequestpetition/add',
            addcourtdetails: 'intakeservicerequestcourtaction/add',
            saoComplete: 'Intakedastagings/clwClosedIntake',
            contactType: 'admin/progressnotetype/listprognotetypes?filter={"nolimit":true}',
            purposeType: 'progressnotepurposetype?filter={"nolimit":true}',
            typeofLocation: listprognotesubtypesurl,
            personsInvolvedType: 'contactroletypes?filter={"nolimit":true}',
            notesSave: addrecordingsurl,
            notesEdit: 'admin/progressnote/getdarecordingdetails',
            notesList: getalldarecordingurl,
            informationsourcetype: 'informationsourcetype',
            prescriptionreasontype: 'prescriptionreasontype',
            healthprofessiontype: 'healthprofessiontype',
            healthdomaintype: 'healthdomaintype',
            healthassessmenttype: 'healthassessmenttype',
            medicalconditiontype: 'medicalconditiontype',
            physicianspecialtytype: 'physicianspecialtytype',
            dentalspecialtytype: 'dentalspecialtytype',
            personservicetype: 'personservicetype',
            medicationtype: 'medicationtype',
            listprogramnamesUrl:'providerreferral/listprogramnames',
            GenerateDocumentList: 'documenttemplate',
            getAddedPetitions: 'intakeservicerequestpetition/list?filter',
        },
        DSDSAction: {
            Attachment: {
                UploadAttachmentUrl: 'attachments/uploadsFile',
                AttachmentGridUrl: 'Documentproperties/getcaseworkerattachments',
                PersonAttachmentGridUrl: 'Documentproperties/getpersonattachments',
                PersonAttachmentUpdate: 'Documentproperties/updatepersonattachments',
                AttachmentUploadUrl: 'attachments/uploadsFile',
                AttachmentTypeUrl: 'Intake/attachmenttype/',
                AttachmentClassificationTypeUrl: 'Intake/attachmentclassificationtype/',
                SaveAttachmentUrl: 'Documentproperties/addcaseworkerattachment',
                DeleteAttachmentUrl: 'Documentproperties/delete',
                serviceCaseAttachmentGridUrl: 'Documentproperties/getservicecaseattachments',
                CompaintFromCase: 'intakeservicerequestevaluations/getcomplaintlistbycasenumber?filter'
            },
            Recording: {
                GetAllDaRecordingUrl: getalldarecordingurl,
                ListProgressSubTypeUrl: listprognotesubtypesurl,
                AddRecordingUrl: addrecordingsurl,
                GetRecordingDetailUrl: 'admin/progressnote/getdarecordingdetails',
                UpdateRecordingUrl: 'admin/progressnote/updateRecordings',
                ListProgressTypeUrl: listprognotetypesurl,
                AddResourceConsultURL: 'intakeservicerequestconsultreview/addupdate',
                GetResourceConsultURL: 'intakeservicerequestconsultreview/listconsultreview',
                GetSelectTypeURL: 'consultreviewusertype/',
                DeleteResourceURL: 'intakeservicerequestconsultreview/consultreviewdelete',
                DeleteResourceUserURL: 'intakeservicerequestconsultreview/consultreviewconfigdelete',
                ContactNotesList: 'admin/progressnote/getallcontactnoteslist',
                AddUpdateNotes: 'admin/progressnote/addupdatecontactnotes',
                AddComments: 'admin/progressnotedetail'
            },
            Disposition: {
                StatusUrl: 'Intakeservicerequests/statuslist',
                DispositionUrl: 'Intakeservicerequests/dispositionlist',
                DispositionListUrl: 'Intakeservicerequestdispositioncodes/GetDispositon',
                DispositionAddUrl: 'Intakeservicerequestdispositioncodes/Add'
            }
        }
    };
}
