

DELETE from role_resource where resourceid in (
select pgresourceid FROM pgresource WHERE resourceid IN (
	SELECT id FROM resource WHERE (lower(resourceid) LIKE 'cw-%' or 
	lower(resourceid) LIKE 'myintake-%' or lower(resourceid) LIKE 'caseworker-%')
)) and permissiontype = 1;

DELETE FROM pgresource WHERE resourceid IN (
	SELECT id FROM resource WHERE (lower(resourceid) LIKE 'cw-%' or 
	lower(resourceid) LIKE 'myintake-%' or lower(resourceid) LIKE 'caseworker-%')
);

DELETE FROM resource WHERE (lower(resourceid) LIKE 'cw-%' or 
	lower(resourceid) LIKE 'myintake-%' or lower(resourceid) LIKE 'caseworker-%');
	
	
-------------

-- Intake worker main screen

insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-module','Intake - Module', 2, null, 'Intake - Module','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-narrative-screen','Intake Main - Narrative Tab', 3, 'myintake-module', 'Intake Main - Narrative Tab','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved','Intake Main - Persons Involved Tab', 3, 'myintake-module', 'Intake Main - Persons Involved Tab','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-find','Intake - Persons Involved Find', 3, 'myintake-persons-involved', 'Intake - Persons Involved Find','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit','Intake - Persons Involved Edit', 3, 'myintake-persons-involved', 'Intake - Persons Involved Edit','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-find-profile-information','Intake - Persons Involved Find Profile-information', 3, 'myintake-persons-involved-find', 'Intake - Persons Involved Find Profile-information','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-find-search-results','Intake - Persons Involved Find Search-results', 3, 'myintake-persons-involved-find', 'Intake - Persons Involved Find Search-results','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-find-relation','Intake - Persons Involved Find Relation', 3, 'myintake-persons-involved-find', 'Intake - Persons Involved Find Relation','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-find-person-role','Intake - Persons Involved Find Person-role', 3, 'myintake-persons-involved-find', 'Intake - Persons Involved Find Person-role','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-profile','Intake - Persons Involved Edit Profile', 3, 'myintake-persons-involved-edit', 'Intake - Persons Involved Edit Profile','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-health','Intake - Persons Involved Edit Health', 3, 'myintake-persons-involved-edit', 'Intake - Persons Involved Edit Health','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-education','Intake - Persons Involved Edit Education', 3, 'myintake-persons-involved-edit', 'Intake - Persons Involved Edit Education','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-work','Intake - Persons Involved Edit Work', 3, 'myintake-persons-involved-edit', 'Intake - Persons Involved Edit Work','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-contacts','Intake - Persons Involved Edit Contacts', 3, 'myintake-persons-involved-edit', 'Intake - Persons Involved Edit Contacts','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-address','Intake - Persons Involved Edit Address', 3, 'myintake-persons-involved-edit', 'Intake - Persons Involved Edit Address','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-informal-supports','Intake - Persons Involved Edit Informal Supports', 3, 'myintake-persons-involved-edit', 'Intake - Persons Involved Edit Informal Supports','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-person-role','Intake - Persons Involved Edit Person Role', 3, 'myintake-persons-involved-edit', 'Intake - Persons Involved Edit Person Role','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-health-provider-information','Intake - Persons Involved Edit Health Provider Information', 3, 'myintake-persons-involved-edit-health', 'Intake - Persons Involved Edit Health Provider Information','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-health-insurance-information','Intake - Persons Involved Edit Health Insurance Information', 3, 'myintake-persons-involved-edit-health', 'Intake - Persons Involved Edit Health Insurance Information','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-health-medication-including-psychotrophic','Intake - Persons Involved Edit Health Medication Including-psychotrophic', 3, 'myintake-persons-involved-edit-health', 'Intake - Persons Involved Edit Health Medication Including-psychotrophic','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-health-medical-conditions','Intake - Persons Involved Edit Health Medical Conditions', 3, 'myintake-persons-involved-edit-health', 'Intake - Persons Involved Edit Health Medical Conditions','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-health-behavioral-health-info','Intake - Persons Involved Edit Health Behavioral Health-info', 3, 'myintake-persons-involved-edit-health', 'Intake - Persons Involved Edit Health Behavioral Health-info','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-health-substance-abuse','Intake - Persons Involved Edit Health Substance Abuse', 3, 'myintake-persons-involved-edit-health', 'Intake - Persons Involved Edit Health Substance Abuse','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-education-school','Intake - Persons Involved Edit Education School', 3, 'myintake-persons-involved-edit-education', 'Intake - Persons Involved Edit Education School','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-education-accomplishments','Intake - Persons Involved Edit Education Accomplishments', 3, 'myintake-persons-involved-edit-education', 'Intake - Persons Involved Edit Education Accomplishments','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-education-testing-info','Intake - Persons Involved Edit Education Testing-info', 3, 'myintake-persons-involved-edit-education', 'Intake - Persons Involved Edit Education Testing-info','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-persons-involved-edit-education-vocation','Intake - Persons Involved Edit Education Vocation', 3, 'myintake-persons-involved-edit-education', 'Intake - Persons Involved Edit Education Vocation','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-contact','Intake Main - Contacts Tab', 3, 'myintake-module', 'Intake Main - Contacts Tab','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-disposition','Intake Main - Disposition Tab', 3, 'myintake-module', 'Intake Main - Disposition Tab','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-sdm','Intake Main - SDM Tab', 3, 'myintake-module', 'Intake Main - SDM Tab','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-attachement','Intake Main - Attachment Tab', 3, 'myintake-module', 'Intake Main - Attachment Tab','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-sdm-maltreatment-type','Intake - Sdm Maltreatment Type', 3, 'myintake-sdm', 'Intake - Sdm Maltreatment Type','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-sdm-recomendation-overrides','Intake - Sdm Recomendation Overrides', 3, 'myintake-sdm', 'Intake - Sdm Recomendation Overrides','myintake-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('myintake-sdm-cps-response-type','Intake - Sdm CPS Response Type', 3, 'myintake-sdm', 'Intake - Sdm CPS Response Type','myintake-module',1, 'admin', now(), 'admin', now());

-------------

-- Caseworker main screen

insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-module','Caseworker - Module', 2, null, 'Caseworker - Module','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-summary','Caseworker - Summary Tab', 3, 'caseworker-module', 'Caseworker - Summary Tab','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-checklist','Caseworker - Checklist Tab', 3, 'caseworker-module', 'Caseworker - Checklist Tab','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-contacts','Caseworker - Contact Tab', 3, 'caseworker-module', 'Caseworker - Contact Tab','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-contacts-notes','Caseworker - Contact Notes Tab', 3, 'caseworker-module', 'Caseworker - Contact Notes Tab','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-contacts-notes-add-new','Caseworker - Contact Add New Note', 3, 'caseworker-contacts-notes', 'Caseworker - Contact Add New Note','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-contacts-notes-edit','Caseworker - Contact Edit Note', 3, 'caseworker-contacts-notes', 'Caseworker - Contact Edit Note','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-contacts-notes-view','Caseworker - Contact View Note', 3, 'caseworker-contacts-notes', 'Caseworker - Contact View Note','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-contacts-meeting','Caseworker - Contact Meeting', 3, 'caseworker-contacts', 'Caseworker - Contact Meeting','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-contacts-meeting-add-new','Caseworker - Contact Add New Meeting', 3, 'caseworker-contacts-meeting', 'Caseworker - Contact Add New Meeting','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-contacts-meeting-view','Caseworker - Contact View Meeting', 3, 'caseworker-contacts-meeting', 'Caseworker - Contact View Meeting','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-contacts-resource-consult-review','Caseworker - Contact Add Resource Consult Review', 3, 'caseworker-contacts', 'Caseworker - Contact Add Resource Consult Review','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-resource-consult-review-add','Caseworker - Contact Add Resource Consult Review', 3, 'caseworker-contacts-resource-consult-review', 'Caseworker - Contact Add Resource Consult Review','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-resource-consult-review-edit','Caseworker - Contact Edit Resource Consult Review', 3, 'caseworker-contacts-resource-consult-review', 'Caseworker - Contact Edit Resource Consult Review','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-resource-consult-review-view','Caseworker - Contact View Resource Consult Review', 3, 'caseworker-contacts-resource-consult-review', 'Caseworker - Contact View Resource Consult Review','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-resource-consult-review-delete','Caseworker - Contact Delete Resource Consult Review', 3, 'caseworker-contacts-resource-consult-review', 'Caseworker - Contact Delete Resource Consult Review','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-sdm','Caseworker - Sdm Tab', 3, 'caseworker-module', 'Caseworker - Sdm Tab','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-sdm-pathway','Caseworker - Sdm Pathway ', 3, 'caseworker-sdm', 'Caseworker - Sdm Pathway ','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-sdm-maltreatment-type','Caseworker - Sdm Maltreatment', 3, 'caseworker-sdm', 'Caseworker - Sdm Maltreatment','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-sdm-recommandations-overrides','Caseworker - Sdm Recommandations', 3, 'caseworker-sdm', 'Caseworker - Sdm Recommandations','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-sdm-cps-response-type','Caseworker - Sdm Cps Response', 3, 'caseworker-sdm', 'Caseworker - Sdm Cps Response','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-maltreatment-allegation','Caseworker - Maltreatment Allegation', 3, 'caseworker-module', 'Caseworker - Maltreatment Allegation','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-assessment','Caseworker - Assessment Tab', 3, 'caseworker-module', 'Caseworker - Assessment Tab','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-assessment-start','Caseworker - Assessment Start', 3, 'caseworker-assessment', 'Caseworker - Assessment Start','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-assessment-edit','Caseworker - Assessment Edit', 3, 'caseworker-assessment', 'Caseworker - Assessment Edit','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-assessment-view','Caseworker - Assessment View', 3, 'caseworker-assessment', 'Caseworker - Assessment View','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-assessment-print','Caseworker - Assessment Print', 3, 'caseworker-assessment', 'Caseworker - Assessment Print','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-assessment-delete','Caseworker - Assessment Delete', 3, 'caseworker-assessment', 'Caseworker - Assessment Delete','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-child-removal','Caseworker - Child Removal Tab', 3, 'caseworker-module', 'Caseworker - Child Removal Tab','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-child-removal-approval','Caseworker - Child Removal Approval', 3, 'caseworker-child-removal', 'Caseworker - Child Removal Approval','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-placement','Caseworker - Placement Tab', 3, 'caseworker-module', 'Caseworker - Placement Tab','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-placement-foster-care-placement','Caseworker - Placement Foster Care Placement', 3, 'caseworker-placement', 'Caseworker - Placement Foster Care Placement','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-placement-permanancy-plan','Caseworker - Placement Permancy Plan', 3, 'caseworker-placement', 'Caseworker - Placement Permancy Plan','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-kinship','Caseworker - Kinship Tab', 3, 'caseworker-module', 'Caseworker - Kinship Tab','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-kinship-program-assignment','Caseworker - Kinship Program Assignment', 3, 'caseworker-kinship', 'Caseworker - Kinship Program Assignment','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-kinship-program-assignment-save','Caseworker - Kinship Program Assignment Save', 3, 'caseworker-kinship-program-assignment', 'Caseworker - Kinship Program Assignment Save','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-kinship-case-closure','Caseworker - Kinship Case Closure', 3, 'caseworker-kinship', 'Caseworker - Kinship Case Closure','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-kinship-case-closure-add','Caseworker - Kinship Add Case Closure', 3, 'caseworker-kinship-case-closure', 'Caseworker - Kinship Add Case Closure','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-kinship-case-closure-edit','Caseworker - Kinship Edit Case Closure', 3, 'caseworker-kinship-case-closure', 'Caseworker - Kinship Edit Case Closure','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-kinship-case-closure-delete','Caseworker - Kinship Delete Case Closure', 3, 'caseworker-kinship-case-closure', 'Caseworker - Kinship Delete Case Closure','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons','Caseworker - Persons Involved Tab', 3, 'caseworker-module', 'Caseworker - Persons Involved Tab','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-find','Caseworker - Persons Involved Find', 3, 'caseworker-persons', 'Caseworker - Persons Involved Find','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-edit','Caseworker - Persons Involved Edit', 3, 'caseworker-persons', 'Caseworker - Persons Involved Edit','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-delete','Caseworker - Persons Involved Delete', 3, 'caseworker-persons', 'Caseworker - Persons Involved Delete','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-find-profile-info','Caseworker - Persons Involved Find Profile-Information', 3, 'caseworker-persons-find', 'Caseworker - Persons Involved Find Profile-Information','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-find-search-results','Caseworker - Persons Involved Find Search Result', 3, 'caseworker-persons-find', 'Caseworker - Persons Involved Find Search Result','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-find-relation','Caseworker - Persons Involved Find Role Info', 3, 'caseworker-persons-edit', 'Caseworker - Persons Involved Find Role Info','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-edit-profile','Caseworker - Persons Involved Edit Profile Info', 3, 'caseworker-persons-edit', 'Caseworker - Persons Involved Edit Profile Info','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-edit-health','Caseworker - Persons Involved Edit Health', 3, 'caseworker-persons-edit', 'Caseworker - Persons Involved Edit Health','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-edit-education','Caseworker - Persons Involved Edit Education', 3, 'caseworker-persons-edit', 'Caseworker - Persons Involved Edit Education','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-edit-contact','Caseworker - Persons Involved Edit Contact', 3, 'caseworker-persons-edit', 'Caseworker - Persons Involved Edit Contact','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-edit-address','Caseworker - Persons Involved Edit Address', 3, 'caseworker-persons-edit', 'Caseworker - Persons Involved Edit Address','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-edit-roles','Caseworker - Persons Involved Edit Roles', 3, 'caseworker-persons-edit', 'Caseworker - Persons Involved Edit Roles','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-edit-health-provider-info','Caseworker - Persons Involved Edit Health Provider Info ', 3, 'caseworker-persons-edit-health', 'Caseworker - Persons Involved Edit Health Provider Info ','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-edit-health-insurance-info','Caseworker - Persons Involved Edit Health Insurance Info', 3, 'caseworker-persons-edit-health', 'Caseworker - Persons Involved Edit Health Insurance Info','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-edit-health-medical-including ','Caseworker - Persons Involved Edit Health Medical Including', 3, 'caseworker-persons-edit-health', 'Caseworker - Persons Involved Edit Health Medical Including','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-edit-health-medical-conditions','Caseworker - Persons Involved Edit Health Medical Conditions', 3, 'caseworker-persons-edit-health', 'Caseworker - Persons Involved Edit Health Medical Conditions','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-edit-health-behavioral-health-info','Caseworker - Persons Involved Edit Health Behavioral Health Info', 3, 'caseworker-persons-edit-health', 'Caseworker - Persons Involved Edit Health Behavioral Health Info','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-edit-health-substance-abuse','Caseworker - Persons Involved Edit Health Substance Abuse', 3, 'caseworker-persons-edit-health', 'Caseworker - Persons Involved Edit Health Substance Abuse','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-edit-education-school','Caseworker - Persons Involved Edit Education School', 3, 'caseworker-persons-edit-education', 'Caseworker - Persons Involved Edit Education School','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-edit-education-accomplishments','Caseworker - Persons Involved Edit Education Accomplishments', 3, 'caseworker-persons-edit-education', 'Caseworker - Persons Involved Edit Education Accomplishments','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-edit-education-testing-Info','Caseworker - Persons Involved Edit Education Testing Info', 3, 'caseworker-persons-edit-education', 'Caseworker - Persons Involved Edit Education Testing Info','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-persons-edit-education-vocation','Caseworker - Persons Involved Edit Education Vocation', 3, 'caseworker-persons-edit-education', 'Caseworker - Persons Involved Edit Education Vocation','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-court','Caseworker - Court Tab', 3, 'caseworker-module', 'Caseworker - Court Tab','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-court-petition-details','Caseworker - Court Petition Details', 3, 'caseworker-court', 'Caseworker - Court Petition Details','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-court-hearing-details','Caseworker - Court Hearing Details', 3, 'caseworker-court', 'Caseworker - Court Hearing Details','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-court-court-order ','Caseworker - Court Court Order ', 3, 'caseworker-court', 'Caseworker - Court Court Order ','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-court-hearing-details-schedule- hearing','Caseworker - Court Hearing Details Schedule Hearing', 3, 'caseworker-court-hearing-details', 'Caseworker - Court Hearing Details Schedule Hearing','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-attachments','Caseworker - Attachments Tab', 3, 'caseworker-module', 'Caseworker - Attachments Tab','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-attachments-upload','Caseworker - Attachments Upload ', 3, 'caseworker-attachments', 'Caseworker - Attachments Upload ','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-attachments-scan','Caseworker - Attachments Scan', 3, 'caseworker-attachments', 'Caseworker - Attachments Scan','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-attachments-camera','Caseworker - Attachments Camera', 3, 'caseworker-attachments', 'Caseworker - Attachments Camera','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-attachments-video','Caseworker - Attachments Video', 3, 'caseworker-attachments', 'Caseworker - Attachments Video','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-attachments-record','Caseworker - Attachments Record', 3, 'caseworker-attachments', 'Caseworker - Attachments Record','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-attachments-edit','Caseworker - Attachments Edit', 3, 'caseworker-attachments', 'Caseworker - Attachments Edit','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-attachments-delete','Caseworker - Attachments Delete', 3, 'caseworker-attachments', 'Caseworker - Attachments Delete','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-attachments-camera-delete','Caseworker - Attachments Camera Delete', 3, 'caseworker-attachments-camera', 'Caseworker - Attachments Camera Delete','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-investigation-findings','Caseworker - Investigation Findings', 3, 'caseworker-module', 'Caseworker - Investigation Findings','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-investigation-findings-save','Caseworker - Investigation Findings Save', 3, 'caseworker-investigation-findings', 'Caseworker - Investigation Findings Save','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-investigation-findings-complete','Caseworker - Service Plan Complete', 3, 'caseworker-investigation-findings', 'Caseworker - Service Plan Complete','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan','Caseworker - Service Plan Tab', 3, 'caseworker-module', 'Caseworker - Service Plan Tab','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-goals-strategies','Caseworker - Service Plan Goals And Strategies', 3, 'caseworker-service-plan', 'Caseworker - Service Plan Goals And Strategies','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-activities','Caseworker - Service Plan Activities', 3, 'caseworker-service-plan', 'Caseworker - Service Plan Activities','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-service-log','Caseworker - Service Plan Sevice Log', 3, 'caseworker-service-plan', 'Caseworker - Service Plan Sevice Log','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-goals-strategies-add-goals','Caseworker - Service Plan Add Goals And Strategies', 3, 'caseworker-service-plan-goals-strategies', 'Caseworker - Service Plan Add Goals And Strategies','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-goals-strategies-edit-goals','Caseworker - Service Plan Edit Goals And Strategies', 3, 'caseworker-service-plan-goals-strategies', 'Caseworker - Service Plan Edit Goals And Strategies','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-goals-strategies-delete-goals','Caseworker - Service Plan Delete Goals And Strategies', 3, 'caseworker-service-plan-goals-strategies', 'Caseworker - Service Plan Delete Goals And Strategies','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-activities-add-new-activity','Caseworker - Service Plan Add New Activities', 3, 'caseworker-service-plan-activities', 'Caseworker - Service Plan Add New Activities','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-activities-edit-activity','Caseworker - Service Plan Edit Activities', 3, 'caseworker-service-plan-activities', 'Caseworker - Service Plan Edit Activities','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-activities-delete-activity','Caseworker - Service Plan Delete Activities', 3, 'caseworker-service-plan-activities', 'Caseworker - Service Plan Delete Activities','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-activities-view-log','Caseworker - Service Plan View Log', 3, 'caseworker-service-plan-activities', 'Caseworker - Service Plan View Log','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-activities-add-service','Caseworker - Service Plan Add Service', 3, 'caseworker-service-plan-activities', 'Caseworker - Service Plan Add Service','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-activities-add-service-search','Caseworker - Service Plan Add Service Screen', 3, 'caseworker-service-plan-activities-add-service', 'Caseworker - Service Plan Add Service Screen','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-activities-add-service-search-search-result','Caseworker - Service Plan Add Service Search Result', 3, 'caseworker-service-plan-activities-add-service-search', 'Caseworker - Service Plan Add Service Search Result','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-activities-add-service-search-clear','Caseworker - Service Plan Add Service Clear Search Result', 3, 'caseworker-service-plan-activities-add-service-search', 'Caseworker - Service Plan Add Service Clear Search Result','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-activities-add-service-search-view-map','Caseworker - Service Plan Add Service View Map', 3, 'caseworker-service-plan-activities-add-service-search', 'Caseworker - Service Plan Add Service View Map','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-activities-add-service-search-next','Caseworker - Service Plan Add Service Next', 3, 'caseworker-service-plan-activities-add-service-search', 'Caseworker - Service Plan Add Service Next','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-activities-add-service-search-service-date','Caseworker - Service Plan Add Service Date', 3, 'caseworker-service-plan-activities-add-service-search', 'Caseworker - Service Plan Add Service Date','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-service-log-agency-provided-services','Caseworker - Service Plan Sevice Log Agency Provided Services', 3, 'caseworker-service-plan-service-log', 'Caseworker - Service Plan Sevice Log Agency Provided Services','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-service-log-vendor-services','Caseworker - Service Plan Sevice Log Vendor Services', 3, 'caseworker-service-plan-service-log', 'Caseworker - Service Plan Sevice Log Vendor Services','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-service-log-agency-provided-services-view','Caseworker - Service Plan Sevice Log Agency Provided Services View ', 3, 'caseworker-service-plan-service-log-agency-provided-services', 'Caseworker - Service Plan Sevice Log Agency Provided Services View ','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-service-log-agency-provided-services-add','Caseworker - Service Plan Sevice Log Agency Provided Services Add New ', 3, 'caseworker-service-plan-service-log-agency-provided-services', 'Caseworker - Service Plan Sevice Log Agency Provided Services Add New ','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-service-log-agency-provided-services-edit','Caseworker - Service Plan Sevice Log Agency Provided Services Edit ', 3, 'caseworker-service-plan-service-log-agency-provided-services', 'Caseworker - Service Plan Sevice Log Agency Provided Services Edit ','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-service-log-agency-provided-services-delete','Caseworker - Service Plan Sevice Log Agency Provided Services Delete ', 3, 'caseworker-service-plan-service-log-agency-provided-services', 'Caseworker - Service Plan Sevice Log Agency Provided Services Delete ','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-service-log-vendor-services-view','Caseworker - Service Plan Sevice Log Vendor Services View ', 3, 'caseworker-service-plan-service-log-vendor-services', 'Caseworker - Service Plan Sevice Log Vendor Services View ','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-service-log-vendor-services-add','Caseworker - Service Plan Sevice Log Vendor Services Add New ', 3, 'caseworker-service-plan-service-log-vendor-services', 'Caseworker - Service Plan Sevice Log Vendor Services Add New ','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-service-log-vendor-services-edit','Caseworker - Service Plan Sevice Log Vendor Services Edit ', 3, 'caseworker-service-plan-service-log-vendor-services', 'Caseworker - Service Plan Sevice Log Vendor Services Edit ','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-service-plan-service-log-vendor-services-delete','Caseworker - Service Plan Sevice Log Vendor Services Delete ', 3, 'caseworker-service-plan-service-log-vendor-services', 'Caseworker - Service Plan Sevice Log Vendor Services Delete ','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-disposition','Caseworker - Disposition Tab', 3, 'caseworker-module', 'Caseworker - Disposition Tab','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-disposition-investigation-summary','Caseworker - Disposition Investigation Summary', 3, 'caseworker-disposition', 'Caseworker - Disposition Investigation Summary','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-disposition-status-disposition','Caseworker - Disposition Status Disposition', 3, 'caseworker-disposition', 'Caseworker - Disposition Status Disposition','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-disposition-cps-intake-report','Caseworker - Disposition Cps Intake Report', 3, 'caseworker-disposition', 'Caseworker - Disposition Cps Intake Report','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-disposition-investigation-summary-save','Caseworker - Disposition Investigation Summary Save', 3, 'caseworker-disposition-investigation-summary', 'Caseworker - Disposition Investigation Summary Save','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-disposition-status-disposition-save','Caseworker - Disposition Status Save', 3, 'caseworker-disposition-status-disposition', 'Caseworker - Disposition Status Save','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-disposition-cps-intake-report-save','Caseworker - Disposition Cps Intake Report Save', 3, 'caseworker-disposition-cps-intake-report', 'Caseworker - Disposition Cps Intake Report Save','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-case-timeline','Caseworker - Case Timeline Tab', 3, 'caseworker-module', 'Caseworker - Case Timeline Tab','caseworker-module',1, 'admin', now(), 'admin', now());
insert into resource (resourceid, resourcename, resourcetype, parentkey, description, modulekey,activeflag, insertedby, insertedon, updatedby, updatedon) values ('caseworker-kinship-care','Caseworker - Kinship Care Tab', 3, 'caseworker-module', 'Caseworker - Kinship Care Tab','caseworker-module',1, 'admin', now(), 'admin', now());

update resource set activeflag = 0 where resourcename like '%select%';