 CREATE OR REPLACE FUNCTION public.checkstatusandclose(v_intakenumber character varying, v_insertedby uuid)                                                                                                                              
  RETURNS TABLE(closecount bigint)                                                                                                                                                                                                       
  LANGUAGE plpgsql                                                                                                                                                                                                                       
 AS $function$                                                                                                                                                                                                                           
                                                                                                                                                                                                                                         
 declare closecount bigint;                                                                                                                                                                                                              
                                                                                                                                                                                                                                         
 begin                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                         
         select count(1) into closecount from intakeservicerequestevaluation INE where intakenumber= v_intakenumber and complaintstatustypekey !='CHC';                                                                                  
                                                                                                                                                                                                                                         
         if(closecount = 0)                                                                                                                                                                                                              
         then                                                                                                                                                                                                                            
         RAISE NOTICE 'Parsing Item % ', closecount;                                                                                                                                                                                     
         INSERT INTO intakeservicerequestdispositioncode                                                                                                                                                                                 
 (intakeservicerequestdispositioncodeid,intakeserviceid,intakeserreqstatustypeid,servicerequesttypeconfigiddispostionid, statusdate                                                                                                      
 , insertedby, insertedon, updatedby, updatedon,activeflag)                                                                                                                                                                              
 select  gen_random_uuid() ,INSR.intakeserviceid,SRTCDP.intakeserreqstatustypeid,SRTCDP.servicerequesttypeconfigiddispostionid,now(), v_insertedby,now(), v_insertedby,now(),1                                                           
 From intakeservicerequest INSR                                                                                                                                                                                                          
 join serviceRequestTypeConfig SRTC on SRTC.intakeservreqtypeid=INSR.intakeservreqtypeid and  SRTC.intakeServReqTypeId= INSR.intakeservreqtypeid and SRTC.ServiceRequestSubTypeId= INSR.intakeservicerequestclassid and SRTC.activeflag=1
 join ServiceRequestTypeConfigDispositionCode SRTCDP on SRTCDP.servicerequesttypeconfigid=SRTC.serviceRequestTypeConfigid                                                                                                                
 and SRTCDP.intakeserreqstatustypeid=(select intakeserreqstatustypeid from intakeserreqstatustype where  intakeserreqstatustypekey='Review')                                                                                             
 and SRTCDP.activeflag=1                                                                                                                                                                                                                 
 where intakenumber=v_intakenumber and INSR.activeflag=1 and SRTCDP.dispositioncode='DISAPPR'  and NOT EXISTS (select 1 from intakeservicerequestdispositioncode where intakeserviceid=INSR.intakeserviceid and activeflag=1);           
                                                                                                                                                                                                                                         
 update folderassignment set status='Closed',closedate=now(),activeflag=0, updatedon=now(), updatedby=v_insertedby where objectid=v_intakenumber and foldertypekey='LegalAction' and status='Active';                                                                             
                                                                                                                                                                                                                                         
 end if;                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                         
 return query select count(1)  from intakeservicerequestevaluation INE where intakenumber= v_intakenumber and complaintstatustypekey !='CHC';                                                                                            
                                                                                                                                                                                                                                         
 end                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                         
 $function$                                                                                                                                                                                                                              

