 CREATE OR REPLACE FUNCTION public.createvop(i_intakeservicepetitionid uuid, i_currntuser uuid, i_vopviolationdate timestamp without time zone, i_vopviolationoffencetype character varying, i_vopnotes text, vopconditions json, i_initiatedby character varying)
  RETURNS text                                                                                                                                                                                                                                                    
  LANGUAGE plpgsql                                                                                                                                                                                                                                                
 AS $function$                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                  
 declare complaintname character varying;                                                                                                                                                                                                                         
 declare petitionuuid uuid;                                                                                                                                                                                                                                       
 declare complaintuuid uuid;                                                                                                                                                                                                                                      
 declare i json;                                                                                                                                                                                                                                                  
 begin                                                                                                                                                                                                                                                            
            select gen_random_uuid() into petitionuuid;                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                  
            INSERT INTO intakeservicerequestpetition                                                                                                                                                                                                              
 (intakeservicerequestpetitionid, intakeservicerequestid, petitionid, associatedattorneys,                                                                                                                                                                        
 complaintid, transferpetitionid, hearingnotes, activeflag, effectivedate, insertedby, updatedby, insertedon, updatedon, old_id, petitionfocusname, petitiontypekey,                                                                                              
 intakenumber, teamtypekey, petitionfiled, hearingdatetime, hearingtypekey, petitionstatustypekey, courtcasenumber,                                                                                                                                               
 petitiondate,isvop,vopnotes,vopviolationoffencetype,vopviolationdate,voppetitionid,vopinitiatedby)                                                                                                                                                               
  select petitionuuid, intakeservicerequestid, petitionid ||'-VOP-'|| vopversion+1 , associatedattorneys,                                                                                                                                                         
 complaintid, transferpetitionid, hearingnotes, activeflag, effectivedate, insertedby, updatedby, now(),                                                                                                                                                          
 now(), old_id, petitionfocusname, petitiontypekey,                                                                                                                                                                                                               
 intakenumber, teamtypekey, petitionfiled, hearingdatetime, hearingtypekey, 'OP'::character varying, courtcasenumber,                                                                                                                                             
 petitiondate,true,I_vopnotes,I_vopviolationoffencetype,I_vopviolationdate,I_intakeservicepetitionid,i_initiatedby from intakeservicerequestpetition where intakeservicerequestpetitionid = I_intakeservicepetitionid;                                            
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                  
 select gen_random_uuid() into complaintuuid;                                                                                                                                                                                                                     
 select petitionid ||'-VOP-'|| vopversion+1 into complaintname from intakeservicerequestpetition where intakeservicerequestpetitionid = I_intakeservicepetitionid;                                                                                                
                                                                                                                                                                                                                                                                  
 update intakeservicerequestpetition set vopversion=vopversion+1 where intakeservicerequestpetitionid=I_intakeservicepetitionid;                                                                                                                                  
                                                                                                                                                                                                                                                                  
 INSERT INTO intakeservicerequestevaluation                                                                                                                                                                                                                       
 (intakeservicerequestevaluationid, objectid, intakenumber, isdetention, isdrai, ismcasp, countyid, complaintid, evaluationsourcetypeid,                                                                                                                          
 evaluationsourceagencyid, yearsofage, complaintreceiveddate, arrestdate, zipcode, unknownrange, offensedate, begindate,                                                                                                                                          
 enddate, evaluationsourceid, activeflag, updatedby, updatedon, insertedby, insertedon, effectivedate, expirationdate,                                                                                                                                            
 old_id, complaintstatustypekey, offencelocationtypekey)                                                                                                                                                                                                          
   select complaintuuid, objectid, ine.intakenumber, isdetention, isdrai, ismcasp, countyid, complaintname , evaluationsourcetypeid,                                                                                                                              
 evaluationsourceagencyid, yearsofage, complaintreceiveddate, arrestdate, zipcode, unknownrange, offensedate, begindate,                                                                                                                                          
 enddate, evaluationsourceid, ine.activeflag, ine.updatedby, now(), ine.insertedby, now(), now(), ine.expirationdate,                                                                                                                                             
 ine.old_id, 'PS', ine.offencelocationtypekey from intakeservicerequestevaluation ine                                                                                                                                                                             
 join intakeservreqevalpetitionconfig inpc on inpc.intakeservicerequestevaluationid=ine.intakeservicerequestevaluationid and inpc.activeflag=1                                                                                                                    
 where inpc.intakeservicerequestpetitionid=I_intakeservicepetitionid order by ine.insertedon::date desc limit 1;                                                                                                                                                  
                                                                                                                                                                                                                                                                  
 INSERT INTO intakeservicerequestevaluationconfig                                                                                                                                                                                                                 
 (intakeservicerequestevaluationconfigid, intakeservicerequestevaluationid, updatedby, updatedon, insertedby, insertedon,                                                                                                                                         
 activeflag, allegationid,  offenceaddedtype)                                                                                                                                                                                                                     
 select gen_random_uuid(), complaintuuid, I_currntuser, now(), I_currntuser,                                                                                                                                                                                      
 now(),1, allegationid, i_initiatedby from allegation where allegationcode='VOP' ;                                                                                                                                                                                
                                                                                                                                                                                                                                                                  
 INSERT INTO intakeservreqevalpetitionconfig                                                                                                                                                                                                                      
 (intakeservreqevalpetitionconfigid, intakeservicerequestevaluationid, intakeservicerequestpetitionid, intakenumber,                                                                                                                                              
 activeflag, updatedby, updatedon, insertedby, insertedon, effectivedate)                                                                                                                                                                                         
 select gen_random_uuid(), complaintuuid, petitionuuid, intakenumber, 1, I_currntuser, now(), I_currntuser, now(),                                                                                                                                                
 now() from intakeservicerequestpetition where intakeservicerequestpetitionid = I_intakeservicepetitionid;                                                                                                                                                        
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                  
 INSERT INTO intakeservreqevalactorconfig                                                                                                                                                                                                                         
 (intakeservreqevalactorconfigid, intakeservicerequestevaluationid, intakeservicerequestactorid, activeflag, updatedby, updatedon, insertedby, insertedon, effectivedate)                                                                                         
 select gen_random_uuid(), complaintuuid,  intakeservicerequestactorid, 1,I_currntuser, now(), I_currntuser, now(), now()                                                                                                                                         
 from intakeservreqevalactorconfig inec                                                                                                                                                                                                                           
 join intakeservicerequestevaluation ine on  ine.intakeservicerequestevaluationid=inec.intakeservicerequestevaluationid                                                                                                                                           
 join intakeservreqevalpetitionconfig inpc on inpc.intakeservicerequestevaluationid=ine.intakeservicerequestevaluationid and inpc.activeflag=1                                                                                                                    
 where inec.activeflag=1 and inpc.intakeservicerequestpetitionid=I_intakeservicepetitionid order by ine.insertedon::date desc limit 1;                                                                                                                            
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                  
 For  i  in Select * from  json_array_elements(vopconditions)                                                                                                                                                                                                     
 LOOP                                                                                                                                                                                                                                                             
         INSERT INTO intakeservreqpetitionvopconditionconfig                                                                                                                                                                                                      
 (intakeservreqpetitionvopconditionconfigid, intakeservicerequestpetitionid, objectkey,                                                                                                                                                                           
 objecttype, activeflag,  insertedby, updatedby, insertedon, updatedon)                                                                                                                                                                                           
 VALUES( gen_random_uuid(),petitionuuid , i->>'conditiontypekey' , I_vopviolationoffencetype, 1,                                                                                                                                                                  
  I_currntuser, I_currntuser, now(), now());                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                  
 END    LOOP;                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                  
                 return 'SUCCESS';                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                  
                 end;                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                  
 $function$                                                                                                                                                                                                                                                       

