 CREATE OR REPLACE FUNCTION public.interfaces_generate_cses_outbound(in_otherid character varying, in_clientid character varying, in_transactiontypecode character varying)                                                                                                                                                                                                                                                                             
  RETURNS TABLE(totalcount bigint, statuscode character varying, batchruntimestamp character varying, batchsequenceno character varying, transactionsequenceno character varying, transactiontypecode character varying, cisclientid character varying, recordtypecode character varying, transactiontimestamp character varying, recordsequenceno character varying, csesoutcol1 character varying, csesoutcol2 character varying, csesoutcol3 numeric)
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                                                                                      
 AS $function$                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 DECLARE                                                                                                                                                                                                                                                                                                                                                                                                                                                
 v_transactiontypecode character varying;                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 BEGIN                                                                                                                                                                                                                                                                                                                                                                                                                                                  
          --Transaction Type = 40 (Maintenance Payment Update)                                                                                                                                                                                                                                                                                                                                                                                          
         -- IF in_transactiontypecode='40' THEN                                                                                                                                                                                                                                                                                                                                                                                                         
         -- RETURN QUERY                                                                                                                                                                                                                                                                                                                                                                                                                                
         --      select ;                                                                                                                                                                                                                                                                                                                                                                                                                               
         -- END IF;                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
          --Transaction Type = 42 (Existing Parent End-dated)                                                                                                                                                                                                                                                                                                                                                                                           
         -- IF in_transactiontypecode='42' THEN                                                                                                                                                                                                                                                                                                                                                                                                         
         -- RETURN QUERY                                                                                                                                                                                                                                                                                                                                                                                                                                
         --      select ;                                                                                                                                                                                                                                                                                                                                                                                                                               
         -- END IF;                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
          --Transaction Type = 45 (Caseworker Update)                                                                                                                                                                                                                                                                                                                                                                                                   
          IF in_transactiontypecode='45' THEN                                                                                                                                                                                                                                                                                                                                                                                                           
                         IF in_clientid!='' THEN                                                                                                                                                                                                                                                                                                                                                                                                        
                          RETURN QUERY                                                                                                                                                                                                                                                                                                                                                                                                                  
                          SELECT count(1) OVER() as totalcount,incses.statuscode as statuscode ,incses.batchruntimestamp as batchruntimestamp ,incses.batchsequenceno as batchsequenceno,                                                                                                                                                                                                                                                               
                          incses.transactionsequenceno as transactionsequenceno,incses.transactiontypecode as transactiontypecode,incses.cisclientid as cisclientid,                                                                                                                                                                                                                                                                                    
                          incses.recordtypecode as recordtypecode, incses.transactiontimestamp as transactiontimestamp,incses.recordsequenceno as recordsequenceno,                                                                                                                                                                                                                                                                                     
                          incses.csesoutcol1 as csesoutcol1,incses.csesoutcol2 as csesoutcol2,incses.csesoutcol3 as csesoutcol3 FROM public.interfacescsesoutbound as incses;                                                                                                                                                                                                                                                                           
                         END IF;                                                                                                                                                                                                                                                                                                                                                                                                                        
                         IF in_clientid='' THEN                                                                                                                                                                                                                                                                                                                                                                                                         
                         -- RETURN QUERY                                                                                                                                                                                                                                                                                                                                                                                                                
                          --SELECT  ;                                                                                                                                                                                                                                                                                                                                                                                                                   
                         END IF;                                                                                                                                                                                                                                                                                                                                                                                                                        
          END IF;                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
          --Transaction Type = 43 (Hearing Date Update)                                                                                                                                                                                                                                                                                                                                                                                                 
         -- IF in_transactiontypecode='40' THEN                                                                                                                                                                                                                                                                                                                                                                                                         
         -- RETURN QUERY                                                                                                                                                                                                                                                                                                                                                                                                                                
         --      select ;                                                                                                                                                                                                                                                                                                                                                                                                                               
         -- END IF;                                                                                                                                                                                                                                                                                                                                                                                                                                     
  END;                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 $function$                                                                                                                                                                                                                                                                                                                                                                                                                                             

